### ISSUE TITLE
Add usage instructions to README

### ISSUE THREAD

**Issue by Stukongeluk** [stryker-mutator/stryker-net#1]
I cloned this repo and tried to run it. Didn't work.
When is the next release? @richardwerkman

**Comment by simondel** [comment]
Instructions on running Stryker.NET on a project would be great (either from a NuGet package or from source)

**Comment by richardwerkman** [comment]
@Stukongeluk could you try again? I'd like to close this issue.

**Comment by Stukongeluk** [comment]
Well, it works with the steps from the  `contributions.md`, but like @simondel said, some instructions to run it from a NuGet package would be great (and documented in the `readme.md`) ;D. After that is done, I will close the issue.

**Comment by richardwerkman** [comment]
Oke thank you for your feedback. I changed the issue title for better understanding.
