### ISSUE TITLE
Change argument names

### ISSUE THREAD

**Issue by yaelkeemink** [stryker-mutator/stryker-net#100]
Change the argument names to use dashes instead of camel case. For instance: timeoutMS will change to timeout-ms

**Comment by simondel** [comment]
This also applies to the config. Old properties can be removed for now since the project is still in its early stage

**Comment by KonH** [comment]
I can grab this issue & will send PR soon, I hope.

**Comment by simondel** [comment]
Awesome! Be sure to sign up for Hacktoberfest :) If you have any questions, let us know!

**Comment by KonH** [comment]
I have made PR for this issue - #129, please review.
But I have several questions:
- Is dashed syntax related to placeholders in readme? For example: `-cp <relativePathToFile>` (relativePathToFile is placeholder)
- It is strange to LogLevel currently uses ArgumentName = "-logConsole", is that expected? https://github.com/stryker-mutator/stryker-net/blob/c5960ca113e53fbc8f50e940217acae3ad3f8ee1/src/Stryker.CLI/Stryker.CLI/CLIOptions.cs#L22-L29

**Comment by yaelkeemink** [comment]
Awesome, thanks for participating! You do not need to adjust the placeholders. But I agree with you it is a bit strange we use logConsole insteaf of logLevel. @richardwerkman what was the reason you used logConsole over here?
