### ISSUE TITLE
Run fails due to threshold break limit but mutation score is above break limit

### ISSUE THREAD

**Issue by juriekruger** [stryker-mutator/stryker-net#1003]
Running the tool on version 0.17 the CLI build fails with the below message.

The mutation score is lower than the configured break threshold of 80%.
 If you're running in a CI environment, this means your pipeline will now fail.

My mutation score is 100%

[12:23:22 INF] Time Elapsed 00:01:49.1238882
[12:23:22 INF] The final mutation score is 100.00 %
[12:23:22 WRN] Final mutation score is below threshold break. Crashing...

Config file as below

{
  "stryker-config": {
    "log-level": "info",
    "test-runner": "DotnetTest",
    "timeout-ms": 100000,
    "threshold-high": 100,
    "threshold-low": 90,
    "threshold-break": 80,
    "excluded-mutations": [
      "string",
    ],
    "mutate": [
      "!**/Startup.cs",
      "!**/IConfigurationExtensions.cs"
    ],
    "reporters": "['html']"
  }
}

 - OS: Windows
 - Type of project: core
 - Framework Version: netcoreapp2.1
 - Stryker Version: 0.17

**Comment by Mobrockers** [comment]
0.17.1 with a fix for this problem will be released shortly
