### ISSUE TITLE
Compile error for mutated enum member declarations

### ISSUE THREAD

**Issue by Danghor** [stryker-mutator/stryker-net#1016]
**Describe the bug**
When using enums that have calculations in it, Stryker.NET prints a warning message:

`Stryker.NET encountered an compile error in [...] with message: The expression being assigned to 'Fruit.Banana' must be constant (Source code: ((StrykerXGJbRBlHxqRdD9O.MutantControl.IsActive(0)?Apple + 1:Apple - 1)))`

The code used:
 ```csharp
public enum Fruit
{
    Apple = 1,
    Banana = (Apple - 1)
}
```

**Expected behavior**
No warning should be printed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .Net Framework Library
 - Framework Version: 4.7.2
 - Stryker Version: 0.17.1 (beta)

**Additional context**
Enum member declarations must be constants. When doing a substraction from a constant like above, the result is still a constant and can be compiled. However, when the right-hand-side of the declaration is changed to `StrykerXGJbRBlHxqRdD9O.MutantControl.IsActive(0) ? Apple + 1 : Apple - 1`, this is no longer a constant and compilation fails.

A similar problem would occur for all constants. This is currently solved by skipping constant declarations and not mutating them at all. Therefore I fixed it by skipping enum member declarations as well and notmutating them. **I created a unit test and a fix for the bug already and will attach a pull request to this issue in a minute.**

In the long run, I think a concept should be developed to also mutate enum member declarations and constants, since changing a `-` to a `+` here would be a valid mutation that breaks unit tests. It therefore would provide a benefit to the user of Stryker.NET.

**Comment by Mobrockers** [comment]
> I created a unit test and a fix for the bug already and will attach a pull request to this issue in a minute.

Awesome!

Could you create a feature request for the future improvements so we can track it?
