### ISSUE TITLE
Feature request: Mutate object initializer

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1025]
**Is your feature request related to a problem? Please describe.**
This issue comes from #1023. At this time we don't mutate object initializers like:

``` cs
new Dictionary<int, int>
{
    [0] = 1
};
```
or 

``` cs
var person = new Person()
{
    Age = 1
};
```

**Describe the solution you'd like**
We could mutate them into an empty form:

``` cs
new Dictionary<int, int>{};
```
or 

``` cs
var person = new Person(){};
```

**Describe alternatives you've considered**
For the Dictionary this makes a lot of sense as we already mutate all collection types. For regular objects I'm not sure yet.

**Comment by Liam-Rougoor** [comment]
Hey! I would like to work on this.

**Comment by PBonnema** [comment]
Hi, I'm also going to work on this

**Comment by richardwerkman** [comment]
Note that for the object initializer this could result in uninitialized properties. So we have to figure out if this is worth mutating. Especially since the init properties since #C 10 this will happen a lot. Maybe we should focus on the dictionary, array and list first

**Comment by rouke-broersma** [comment]
> Note that for the object initializer this could result in uninitialized properties. So we have to figure out if this is worth mutating. **Especially since the init properties since #C 10 this will happen a lot.** Maybe we should focus on the dictionary, array and list first

Which makes for a compelling argument to test this, right? ;)
