### ISSUE TITLE
Refactor ProjectFileReader and InputFileResolver

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#1034]
> > Since this actually reads the project file, I don't think it can belong anywhere except in the ProjectFileReader unfortunately. I am confused as to why a new ProjectFileReader was created before the change as we have a project file reader already from the constructor. Perhaps the whole ExtractProjectFolders should be moved to the project file reader as well. Maybe rename the method to GetSharedProjectFolders or something.
@Mobrockers 

> Actually it does read the file, only parses it. ProjectFileReader and InputFileResolver are due for refactoring but I have no idea on how to proceed at this stage.
> My initial attempt was to improve the existing design and get rid of the new ProjectFileReader() and reuse the existing instance, but it ends up broking many tests and also lead me to the realisation I had to replicate the ExtractProjectFolders logic for many of those to work.
> @dupdob

_Originally posted by @Mobrockers in https://github.com/stryker-mutator/stryker-net/pull/1028_

**Comment by dupdob** [comment]
Good idea to open this issue. I definitely sadly do not have the time to deal with this refactoring now.
