### ISSUE TITLE
linq mutators for Union, Intersect, Concat & Except

### ISSUE THREAD

**Issue by jnyrup** [stryker-mutator/stryker-net#1038]
I was wondering how to mutate code that involved the following LINQ methods

* `Union()`
* `Intersect()`
* `Concat()`
* `Except()`

One idea was this mapping

Original | Mutated
-- | --
`Union()` | `Intersect()`
`Intersect()` | `Union()`
`Concat()` | `Except()`
`Except()` | `Concat()`

Alternatively would it be within the scope of Stryker or possible at all, to mutate the `IEnumerable<T>` parameter with `Enumerable.Empty<T>()`?

**Comment by richardwerkman** [comment]
I Like these additions to the linq mutator. I'm not sure what your plan is with the `Enumerable.Empty<T>()`. Should it replace the whole linq query?

If you'd like to help us more with our mutators you could check out this issue: https://github.com/stryker-mutator/stryker-handbook/issues/33

**Comment by jnyrup** [comment]
@richardwerkman 
My idea with `Enumerable.Empty<T>()` was to introduce two mutants of e.g. `a.Concat(b)`:
* `Enumerable.Empty<T>().Concat(b)`
* `a.Concat(Enumerable.Empty<T>())`

I had a look at the other issue, but I don't really have any opinions on mutant levels, except that it sounds useful.

**Comment by richardwerkman** [comment]
That could prove hard as these methods are not always directly called on the list itself. They are often called like:

`a.ToList().Concat(b);`

which would become: 

`a.Enumerable.Empty<T>().Concat(b)`

That would not compile of couse. I think swapping the methods with their "opposite" method does the job as well and is a much easier mutation. So I'd rather go for your first suggestion.

And thanks for taking a look at the other issue, good to know it sounds useful.
