### ISSUE TITLE
Use stryker on the stryker build

### ISSUE THREAD

**Issue by yaelkeemink** [stryker-mutator/stryker-net#104]
It would be cool if we use stryker-net on stryker-net itself in the build. That way we can check our own score.

**Comment by richardwerkman** [comment]
This would be extra useful now we have the dashboard reporter. We can show our mutation score badge in the readme and update our report every day: https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker-net/master

I suggest running on master every night is sufficient for now.
