### ISSUE TITLE
Show number of tests found in initial run

### ISSUE THREAD

**Issue by yaelkeemink** [stryker-mutator/stryker-net#105]

**Comment by Szpi** [comment]
Hi, I'm happy to take this issue. Could you write something more about what exactly do you expect ? :) 
This library seems is very interesting. Do you have more issues for beginners? I'd love to write mutator.

**Comment by yaelkeemink** [comment]
Hi, glad to hear you are interested in helping us out! I would like to see the number of tests found in the initial test run shown in the console and the logs. That way I know if the number of tests I run on stryker is the amount of tests I expected it to be.

To answer your othher question, I will define some more issues for beginners (and hacktober) tomorrow :)
