### ISSUE TITLE
Align terminology of Mutator Types

### ISSUE THREAD

**Issue by avassem85** [stryker-mutator/stryker-net#106]
In the [handbook](https://github.com/stryker-mutator/stryker-handbook/blob/setup-handbook/mutator-types.md#supported-mutators) are the mutators described that are being used within the Stryker eco system.  Now there is a mismatch of the terminology being used in [documentation](https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/README.md#boolean-mutator)/code of Stryker.NET.

Binary mutator -> Binary Operators
Boolean mutator -> Boolean Substitutions
PrefixUnaryStatements -> Update operators or Boolean Substitutions
PostfixUnaryStatements -> Update operators

**Comment by joostas** [comment]
I will take his one.
