### ISSUE TITLE
Cannot install without Dotnet Core 3.1 installed with latest version(0.18.0)

### ISSUE THREAD

**Issue by detrek77** [stryker-mutator/stryker-net#1074]
**Describe the bug**
I have docker images I am creating for Stryker runs on different versions of dot net Core(2.1, 2.2, 3.1). Since version 0.18.0 of Stryker.NET was released I am unable to install stryker on any image that doesn't contain Dotnet core 3.1.

**Logs**
Step 14/19 : RUN dotnet tool install -g dotnet-stryker
 ---> Running in b8063bd4273a
error NU1202: Package dotnet-stryker 0.18.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any. Package dotnet-stryker 0.18.0 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any
The tool package could not be restored.

**Expected behavior**
I am able to install Stryker without Dotnet core 3.1 installed

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: Dotnet Core
 - Framework Version Core 2.1, 2.2
 - Stryker Version: beta 0.18.0

**Comment by Mobrockers** [comment]
Dotnet core 3.1 is the latest lts. We have decided to upgrade to it with stryker 0.18.0. Therefor dotnet core 3.1 runtime is required.

**Comment by detrek77** [comment]
I can indeed still test the projects but I'd have to install 3.1 on the other images now. I'll likely just move forward with one image at this point since I no longer can create self-contained versions for each Dotnet core version. I was essentially just trying to keep the docker images smaller and lean. Thank you for the clarification!

**Comment by Mobrockers** [comment]
Awesome! Are these public docker images? :)

**Comment by detrek77** [comment]
They are not, they are internal. I am working on injecting Stryker into our repos PR pipeline. Really been enjoying the features you guys have built into it! Especially the git diff config option.

**Comment by Mobrockers** [comment]
Cool! The git diff option should be getting a lot more awesome in the next two months! We have an internship student working on making sure that you can use the git diff option but also have a full html report available after the testrun.
