### ISSUE TITLE
Stryker .NET throws compile error during initial test run

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-net#1075]
Stryker throws a compile error during the initial test run on vstest.
No special configurations, just specified the path for my *.csproj file on cmd. 
Attached the file with logs on the cmd during test run.
[StrykerLogs.txt](https://github.com/stryker-mutator/stryker/files/4628241/StrykerLogs.txt)
 
Please let me know if you need additional information.

**Comment by nicojs** [comment]
Originally reported: https://github.com/stryker-mutator/stryker/issues/2207 by @kish0

**Comment by richardwerkman** [comment]
@nicojs you can also transfer issues now. In the bottom right of this screen. That way you don't have to create a new issue but just transfer it to another repo :+1:
