### ISSUE TITLE
Deprecate testrunner option

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1077]
The testrunner option will soon not be needed anymore.

We added the option to transit from "dotnet test" to vstest. 

I think it's safe to say now that vstest works correctly and we no longer need "dotnet test" as a fallback.

For now we will mark the testrunner option as deprecated. In version 1.0 we will remove the option.

**Comment by rouke-broersma** [comment]
The option will be gone after #1273 so we can also remove the implementations.
