### ISSUE TITLE
Output folder CLI argument

### ISSUE THREAD

**Issue by Taturevich** [stryker-mutator/stryker-net#1078]
Currently, the default folder for the mutation report is called _StrykerOutput_. I can't find any option or setting to change this folder name or path.

It would be nice to have an option to specify the folder name as one of the CLI arguments. Or, if this is already available, then could you please point out how to use it?

One of the blocked scenarios is the GitlabCI pipeline. We are running several steps of mutation testing via Stryker and collecting reports via artifacts, but because it writes reports into a hardcoded directory only one step ends up being with artifacts in that folder. In order to overcome this, we'd have to rename the output folder after the mutator run.

Thanks!

**Comment by Mobrockers** [comment]
As a workaround, could you not have a publish artifact step for every mutation testrun you perform?

Not familiar with gitlab ci but on jenkins and azure pipelines I know you can 'artifact' a specific folder at a specific time in the pipeline. You would of course end up with an artifact for every single mutation testrun.

Aside that, we are open to making the output folder configurable.

**Comment by rouke-broersma** [comment]
If there are more requests for this option we can consider reopening this issue.

**Comment by candoumbe** [comment]
Hello there !

I would also find it very handy to define, using a CLI argument, where to create the mutation test result files.
Most of the time when doing CI on server build, teams have a custom location in the filesystem where every file created during the build should be stored.

There can be a complex directory tree where serveral mutation tests results could be stored along side one an other and having the test hardcoded is not always easy to manage.

Sure, we can add an additional build step after mutation tests have run to manipulate the file but that seems kind of cumbersome.

I hope this issue get reopened and maybe I could contribute to make this feature available ?
