### ISSUE TITLE
Simplify mutation switching architecture

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#1079]
The current Stryker.net's mutation switching architecture supports two designs:
1) the new logic relying on the custom DataCollector used with VsTest when coverage analysis is activated
2) the original environment variable based logic for other cases

Likewise, the coverage capture logic supports two designs
A) the new logic relying on the custom DataCollector
B) the original design using environment variables and named pipes used when using `dotnet test`

Code could be significantly streamlined if:

- [x] Stryker.net drops support for `dotnet test' as per #1077 
- [x] Stryker.net's DataCollector is always loaded

As of now, using the DataCollector only when coverage analysis is a defensive strategy, allowing a safe mode if the datacollector turned out to be an issue when testing some assembly.
As no issue has ever been reported about this, and there is no identified cause for concerns, I propose to drop this feature as well.

This should result in a more readable code base and some (marginal) performance improvement.

Waiting for feedback before working on this (especially waiting for decision on #1077)

**Comment by Mobrockers** [comment]
@dupdob The descision on #1077 has been made :) It's just a matter of doing it.

**Comment by richardwerkman** [comment]
Nice catch @dupdob! I hadn't thought about removing all this code. Sounds like a good idea :)

**Comment by rouke-broersma** [comment]
@dupdob Is anything left to clean up for this? I think we've got this covered by now?

**Comment by dupdob** [comment]
yes!
