### ISSUE TITLE
Calculate timeout value based on initial testrun

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1080]
**Is your feature request related to a problem? Please describe.**
Stryker can wait for a long time before a mutant is marked as timeout. In most cases this is not needed.

**Describe the solution you'd like**
With coverage analysis we have information at hand as for what mutant is covered by which tests. If we calculate the timeout value for each mutant individually instead of collective we can make more precise decisions on how long we have to wait.

This will have most impact on large projects with many timeouts and some slow tests. I think we can reduce the timeout time from ~15 seconds to ~2 seconds for most mutants.

**Additional context**
@dupdob we have to think about how this should work with running multiple mutants at the same time. I think we have to take the highest timeout value from all mutants. But maybe we can think of a way to shorten the wait?

**Comment by dupdob** [comment]
IIRC, I made a similar comments regarding what could be achieved using VsTest and mutant coverage.
We can establish a per mutant time out as we have the initial run time of each test. It would require some work to track the total test time of each mutant, but it can be done. But there is a blocking issue:
- bear in mind that progress is reported with the list of ended tests and the list of tests in progress
- my testing revealed that test in infinite loop (i.e. timeouts) disrupts notification, and we often don't get any notification about those tests. It looks like being in an infinite loop blocks any notification

 ⇒ This means we are not aware of which tests is triggering the time out, which means we do not know which mutations is being tested.
 ⇒ We do not know which mutant is in timeout.

That being said, we can still compute a more accurate time out value for each test sessions, by cumulating the (initial) run time of each tests as the reference time.

This could probably lead to a factor 2-3 gains for test sessions in time out.

**Comment by richardwerkman** [comment]
@dupdob Lets say we test 3 mutants in one test session and we have calculated the time it should take to test each mutant. The mutants could look like this:

- Mutant 1: runtime 600ms
- Mutant 2: runtime 200ms
- Mutant 3: runtime 700ms

Do you think we should do it like: 600 + 200 + 700 = 1500ms? All mutants should have been tested after 1500ms (plus some margin). This would still mean a significant reduction from the current waiting time.

**Comment by dupdob** [comment]
Yes, that's my idea.
But thinking about it, I have other ideas. I will explain them on Slack

**Comment by dupdob** [comment]
this feature has been implemented in some form for a while now
