### ISSUE TITLE
Detect initial build failures where old msbuild versions are used

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1086]
**Is your feature request related to a problem? Please describe.**

When the initial build fails with a message that the project version is not recognized and the project will be treated as an older version, this generally means we failed to detect the visual studio installation location.

```
Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0".
```

Compilation fails because syntax is used that is not supported by this older compiler version.

**Describe the solution you'd like**
When we detect this, we should log a clear warning with instructions to try and fix to problem or if that doesn't work to come to us for assistance.

**Describe alternatives you've considered**
We should also add to the getting started guide for full framework to enable the feature nuget targets and build tasks in visual studio because since visual studio 2019.xx this isn't installed by default anymore...

**Additional context**
![image](https://user-images.githubusercontent.com/3595932/82297064-6a028580-99b2-11ea-98ad-3d6fccafdb71.png)

#1083

**Comment by dupdob** [comment]
Fixed by #2975
