### ISSUE TITLE
Dashboard reporter

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#109]
Stryker is currently working on a generic [html dashboard](https://github.com/stryker-mutator/mutation-testing-elements) for mutationtest results. To integrate with this dashboard we will have to generate a `*.json` file with the testrun results in a specific structure.

In [this issue](https://github.com/stryker-mutator/mutation-testing-elements/issues/1) the json schema will be defined.

For now Stryker.NET can only generate the needed json. When the complete dashboard is done we can integrate it with the dashboard.

**Comment by Mobrockers** [comment]
@Mobrockers Selfping. I'll try and pick this up tonight

**Comment by Mobrockers** [comment]
Fixed with #352
