### ISSUE TITLE
Correct apparoach for selecting mutant

### ISSUE THREAD

**Issue by maulikhdave9601672767** [stryker-mutator/stryker-net#1090]
For a legacy system consisting thousands of test cases, it is not compatible to run all the type of mutants. What is the industrial approach to select the right mutants.

Current Approach :
"excluded-mutations": ["Boolean","Arithmetic","Logical","Assignment","Unary","Update","Checked","Linq","String","Bitwise"],

How to select which mutants to exclude in a which scenario.

Lets Take example :

1. Legacy system with thousnd of test
2. new devlopment system

**Comment by Mobrockers** [comment]
Hi @maulikhdave9601672767 

For different systems, you would use different configurations. Does that answer your question?

**Comment by maulikhdave9601672767** [comment]
No
How to identify which mutant is best for my system.
so if i have legacy system with 10000 test how i should proceed
and i have new project with new devlopment how should i proceded ?

**Comment by richardwerkman** [comment]
First of all. We advice to turn on ALL mutators to get the best possible test coverage. 

Lets Take example :

- Legacy system with thousands of test
- New development system

> Legacy system with thousands of test

Even if it might take a few hours to run we still advice to use all possible mutations. This gives best insight in where you should improve test coverage. You can store the report so you basically only need to run stryker once. If you still think this takes too long it depends on your code what kind of mutations you can exclude. The number of tests has nothing to do with what mutations should be made.

If you have a lot of log statements that you deem to be unimportant, you could exclude the string mutator or exclude methods with the name `LogInformation` for example. You could also exclude some folders to focus on certain parts of your app first. If you have an app that uses a lot of Entity Framework but choose not to test the queries, you could exclude the linq mutator. But keep in mind this is not recomended.

> New development system

For a new system we advice to run Stryker regulary with all mutations. See [our blog](https://stryker-mutator.io/blog/2020-05-15/azure-pipelines-integration) to see how. You can use our `--diff` feature to shorten the runtime.

**Comment by maulikhdave9601672767** [comment]
But keep in mind this is not recomended. 
so whar recomanded and best practice :)

**Comment by Mobrockers** [comment]
> But keep in mind this is not recomended.
> so whar recomanded and best practice :)

Recommended and best practice is to turn on **all** mutators, and run stryker every build cycle (CI/pull request) by leveraging the git diff feature to only mutations for current changes.

**Comment by Mobrockers** [comment]
I think this question has been sufficiently answered
