### ISSUE TITLE
Thresholds

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#11]
Right now the mutation score color thresholds are fixed at 60 and 80.

It would be nice to let users pass their own preferred thresholds. Also an extra threshold could be added for returning a non zero exit code.

Param suggestion: `--thresholds 60 80 90` for:

- `< 60` return exit code 1
- `> 60` mutation score is red
- `> 80` mutation score is yellow
- `> 90` mutation score is green

**Comment by nicojs** [comment]
To keep it in sync with Stryker js, it should be: 

`--threshold.break 60 --threshold.low 70 --threshold.high 80`

(or maybe: `--threshold-break 60 --threshold-low 70 --threshold-high 80`)

An argument with 3 values like suggested here is very uncommon at best (and might even be impossible with the dotnet cli)

**Comment by richardwerkman** [comment]
Good point, my preference would go to `--threshold-break 60 --threshold-low 70 --threshold-high 80` becouse the other parameters also use a "-" instead of "."

**Comment by Stukongeluk** [comment]
I'm working on this right now, sticking with the preference of @richardwerkman ;) PR will arrive somewhere this week!
