### ISSUE TITLE
Stryker fails with InvalidCastException

### ISSUE THREAD

**Issue by weezlemsneezle** [stryker-mutator/stryker-net#1128]
**Describe the bug**
Stryker fails to execute.
Please see my sample project at [https://github.com/weezlemsneezle/StrykerTest](https://github.com/weezlemsneezle/StrykerTest)
It seems the exception is caused by
`Span<ushort> kindaUnrelated = stackalloc ushort[] { 0 };`
at [Line 9-12](https://github.com/weezlemsneezle/StrykerTest/blob/master/StrykerTest/Foo.cs#L9-L12)

To reproduce:
- clone repository
- execute `dotnet stryker` in repository

**Logs**
[VsTest-log.host.20-07-01_15-45-10_54815_9.txt](https://github.com/stryker-mutator/stryker-net/files/4858250/VsTest-log.host.20-07-01_15-45-10_54815_9.txt)
[VsTest-log.host.20-07-01_15-45-12_53314_9.txt](https://github.com/stryker-mutator/stryker-net/files/4858251/VsTest-log.host.20-07-01_15-45-12_53314_9.txt)
[VsTest-log.txt](https://github.com/stryker-mutator/stryker-net/files/4858252/VsTest-log.txt)
[log-20200701.txt](https://github.com/stryker-mutator/stryker-net/files/4858253/log-20200701.txt)

**Expected behavior**
No crash

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: core
 - Framework Version: core 3.1
 - Stryker Version: beta 0.18.0

**Comment by richardwerkman** [comment]
Thank you for submitting this issue. The bug has been reproduced on my machine and I'm working on a solution :+1:

**Comment by weezlemsneezle** [comment]
Thanks for the quick fix!
