### ISSUE TITLE
Disable string mutation on regexes when regex mutator is enabled

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1132]
**Is your feature request related to a problem? Please describe.**
The string mutation on regex strings is not needed when placing regex mutations. 

**Describe the solution you'd like**
It would be nice to skip the string mutation when the regex mutator is enabled. The string mutation should still be placed on other strings when the regex mutator is enabled.

**Additional context**
We should wait for #1123 before we start working on this.

**Comment by Mobrockers** [comment]
Only for strings that contain regexes right?

**Comment by richardwerkman** [comment]
Ah yes, I will add that to be extra clear...
