### ISSUE TITLE
Diff feature not working when used with a config file 

### ISSUE THREAD

**Issue by raschmitt** [stryker-mutator/stryker-net#1160]
**Describe the bug**

I'm trying to run  mutations with `diff` enabled on a branch that only has alterations in a `.yaml` file when compared to the source branch.

![image](https://user-images.githubusercontent.com/11604696/89465653-da66aa80-d748-11ea-9ad9-81b06d9991c0.png)

With as far as I understand should result in all mutations being ignored.

Yet when I run stryker, 13 mutations are tested.

![image](https://user-images.githubusercontent.com/11604696/89466026-77294800-d749-11ea-8928-492bb1baf4b1.png)

**Logs**
[log-20200805.txt](https://github.com/stryker-mutator/stryker-net/files/5031198/log-20200805.txt)

**Expected behavior**

I expected all mutations to be ignored due to the fact that no code was actually updated.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: Class Library
 - Framework Version: .Net Core 3.1
 - Stryker Version: 0.18.0 (beta)

**Additional context**

The test project which I'm running mutations against references multiple projects.

My `stryker-config.json` file:

```json
{
  "stryker-config": {
    "test-runner": "vstest",
    "reporters": ["progress", "html"],
    "log-level": "info",
    "log-file": false,
    "timeout-ms": 10000,
    "max-concurrent-test-runners": 4,
    "threshold-high": 80,
    "threshold-low": 70,
    "threshold-break": 10,
    "mutate": [
      "!**/Migrations/*.cs",
      "!**/Registers/*.cs",
      "!**/CustomWebHostService.cs",
      "!**/Program.cs",
      "!**/Startup.cs",
      "!**/ApiExtension.cs",
      "!**/Bootstrapper.cs",
      "!**/RabbitMqListener.cs",
      "!**/NativeInjectorBootStrapper.cs",
      "!**/*.Designer.cs",
      "!**/*Context.cs"
    ],
    "excluded-mutations": [],
    "ignore-methods": []
  }
}
```

**Comment by raschmitt** [comment]
My issue seems to be related to the existence of a `stryker-config.json` file.

When I run stryker with `diff` enabled and a mutation config file is present all tests, except for those explicit ignored in my config file, are run.

When I run stryker without a config file being present, the `diff` feature works just fine.

My `stryker-config.json` is as follows:

```json
{
  "stryker-config": {
    "test-runner": "vstest",
    "reporters": ["progress", "html"],
    "log-level": "info",
    "log-file": false,
    "timeout-ms": 10000,
    "max-concurrent-test-runners": 4,
    "threshold-high": 80,
    "threshold-low": 70,
    "threshold-break": 10,
    "mutate": [
      "!**/Migrations/*.cs",
      "!**/Registers/*.cs",
      "!**/CustomWebHostService.cs",
      "!**/Program.cs",
      "!**/Startup.cs",
      "!**/ApiExtension.cs",
      "!**/Bootstrapper.cs",
      "!**/RabbitMqListener.cs",
      "!**/NativeInjectorBootStrapper.cs",
      "!**/*.Designer.cs",
      "!**/*Context.cs"
    ],
    "excluded-mutations": [],
    "ignore-methods": []
  }
}

Am I doing something wrong or missing something in my config file?
````

**Comment by raschmitt** [comment]
My issue seems to be related to the presence/existence of my `stryker-config.json` file, when it is present the `diff` feature does not run, as reported, when the file is not present the `diff` feature runs just fine.

Am I missing or doing something wrong with my configuration file?

**Comment by Mobrockers** [comment]
Hi! It looks like the build.yml is in your test project. The diff feature in 0.18.0 turns on all mutations when a change in the test project has been determined, because we had no good way to validate if a specific test had been changed.

The mutants need to be turned on when a test has been changed because a change in an existing test can mean that a previously killed mutant is suddenly not killed.

It appears we did not add any logging to show this behavior.

See here, if tests have been changed we do not filter out any mutants:

https://github.com/stryker-mutator/stryker-net/blob/6ca7c4b911f52dc249d0125922f1f521c98ac88c/src/Stryker.Core/Stryker.Core/MutantFilters/DiffMutantFilter.cs#L22

We are working to improve this behaviour in #1101

**Comment by raschmitt** [comment]
@Mobrockers Interesting.

The `build.yaml` is not actually part of my test project.

But I was running these mutations on a pipeline where I was getting the `stryker-config.json` from another repository and placing it on the same folder as my test project. 

The "workaround" ended up to be placing this config file on a shallow path.

**Comment by raschmitt** [comment]
Another issue for me at least is that as I have a single test project for all my solution projects and I end up always updating this test project.

So the `diff` feature in this specific case ends not being so efficient in increasing mutation speed for my Pull Requests.

Would there be any solution for a case like this?

**Comment by Mobrockers** [comment]
Awesome 👍
