### ISSUE TITLE
Determine affected mutants by changes in "non source" file

### ISSUE THREAD

**Issue by Stijn-Rutten** [stryker-mutator/stryker-net#1165]
Depends on #1101 

**Is your feature request related to a problem? Please describe.**
When using the dashboard compare feature and a none source file is changed there is no way of knowing which tests are affected by this. Thus all mutants have to be tested.

**Describe the solution you'd like**
I have not looked into any concrete solutions but we should look into ways to determine which parts of the source code or the tests have been affected by these changes. That way we only have to enable the mutants in these parts of the source code.

**Comment by g7ed6e** [comment]
Hi @Stijn-Rutten , I think the "Let's test all mutants because we detect a change in non source files" feature should be opt-in. What do you think ?

**Comment by Mobrockers** [comment]
It should be configurable as in you should be able to exclude files and/or folders with a pattern.
I do not agree that it should be opt-in at all.

Accuracy over speed, unless the user decides that they accept less accuracy for more speed.

**Comment by Stijn-Rutten** [comment]
@g7ed6e I agree with @Mobrockers , I it should be enabled by default. Not keeping track of these types of files can create some unexpected results.

@Mobrockers I'm willing to take a look at pattern exclusion for this.

**Comment by Stijn-Rutten** [comment]
Started on a draft: #1206

**Comment by Stijn-Rutten** [comment]
@Mobrockers Can we close this?

**Comment by Mobrockers** [comment]
@Stijn-Rutten not really. We've given people the option to ignore certain files but it's not automatic. I'd like to keep this open in case we can figure something out.
