### ISSUE TITLE
Stryker generates duplicate mutations

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#1170]
**Describe the bug**
The 'NegateConditionMutator' and the `BinaryExpressionMutator' often result in duplicate mutation,e.g:
original code:
```csharp
if (x == 0)
```
NegateConditionMutator gives
```csharp
if (!(x == 0))
```
BinaryExpressionMutator gives
```chsarp
if (x!=0)
```
Both mutations are equivalent and mutant outcomes are the same. This result is biased statistics and supplemental test time.

**Expected behavior**
Stryker should not create equivalent mutations.
One possible solutions would be to:
- modify 'NegateConditionMutator' so it properly negates binary expression
- add duplicate detection logic so that Stryker no longer injects (obvious) duplicate.

This approach is implemented in PR #1166

**Comment by Mobrockers** [comment]
Did you mean PR #1166  ?

**Comment by Mobrockers** [comment]
Are both approaches implemented in #1166 or just the first?

For the second approach I was thinking we could write a very crude mutation filter that goes over all mutations and finds mutations within the same file/span and checks them against known equivalent mutations.

**Comment by dupdob** [comment]
> Did you mean PR #1166 ?
Yes, I have no idea I ended up using the other PR's id instead. Thanks

**Comment by dupdob** [comment]
I implemented both in PR #1166. What you suggest is exactly what I have done: MutationOrchestration node apply this crude filter when generating mutation (and logs when discarding a duplicate).
And I modified `NegateConditionMutator` so that mutations could match the outcome of `BinaryExpressionMutator`

**Comment by dupdob** [comment]
z

**Comment by Mobrockers** [comment]
> I implemented both in PR #1166. What you suggest is exactly what I have done: MutationOrchestration node apply this crude filter when generating mutation (and logs when discarding a duplicate).
> And I modified `NegateConditionMutator` so that mutations could match the outcome of `BinaryExpressionMutator`

Ah cool! I wonder if that's the best place for this filtering but we can always move it if we notice we can identify a lot of different equivalent mutations later on 👍

**Comment by dupdob** [comment]
As per discussion on PR #1166, if we cannot change the outcome of mutators, two solutions are still possible:
1) prevent known duplicates to happen in the first place. For example, limit the NegateConditionMutator so that it does not mutate binary expressions
2) improve the mutant detection logic so it can recognise (some) known duplicates, such as a != b vs !(a==b).

The problem with (1) is that it will reduce the number of mutants when the BinaryExpressionMutator is disabled. Which is not good, and detection of potential mutant is a bit harder as it looks

The problem with (2) is that will be difficult to implement

**Comment by dupdob** [comment]
as a reminder, original solution was to modify mutators so they end generating similar syntax constructs

**Comment by richardwerkman** [comment]
I'd like to give my view on the `NegateConditionMutator`. It was introduced to mutate if statements like:
```cs
if (person.IsAdult()) ...
```
to
```cs
if (!(person.IsAdult())) ...
```
as it's the only mutation possible for these type of if statements.

However, it did introduce a lot of duplicate mutations indeed. As you said it overlaps with the binary mutator and probably a lot more. So we would like to fix this. 

In addition to the solutions you provided we could do this by making sure the `NegateConditionMutator` does only mutate code that contains no other mutations. @dupdob maybe your new architecture did make this possible? It would be nice to be able to do that. And much more easy than excluding all types of nodes like binary expressions. 

I hope this makes the context of the `NegateConditionMutator` a bit clearer. We want to keep it as simple as possible.

**Comment by dupdob** [comment]
I am afraid the new design does not provide any additional information to mutators. It could be done, but then there would be the question of ensuring that the NegateMutator happens last.
Also, the NegateMutator still add new mutations on top of existing ones, such as:
```csharp
if ((a==b) && (c==d))
```
The binary expression mutator will generate
```csharp
if ((a!=b) && (c==d)) // (1)
if ((a==b) && (c!=d)) // (2)
if ((a==b) || (c==d)) // (3)
```
And the negate condition mutator will generate
```csharp
if (!((a==b) || (c==d))) // (4)
```
which is yet another mutation.

So the negate condition mutator must not mutate conditions with are single binary expression, but still mutate chain of more than one binary expression
