### ISSUE TITLE
Stryker does not mark expression bodied static constructor for coverage capture

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#1171]
**Describe the bug**
Stryker injects marking logic in static constructors (and properties) to identify mutant coverage. Indeed, so called 'static mutants' need to be tested against all tests as one cannot identify dependences through coverage data.
But as of V0.18 (and previous), Stryker does not mark expression bodied properties. This results in potentially incorrect coverage data hence incorrect test results. 

**Expected behavior**
Stryker should be able to mark every static constructors/properties, disregarding its form. Note this implies converting expression bodied construct to full body variant.

**Comment by Mobrockers** [comment]
You say as of v0.18. Is this because we introduced a breaking change there or because the feature didn't exist before v0.18?

**Comment by dupdob** [comment]
No regression here. I updated my comment. Sorry for the ambiguity.
