### ISSUE TITLE
String mutator

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#118]
A mutator should be added that mutates strings into other strings.

Original | Mutated
| - | - |
`"foo"` (non-empty string) | `""` (empty string)
`""` (empty string) | `"Stryker was here!"`
`$"foo {bar}"` (string interpolation) | `$""` 

The mutator should look for StringLiteralExpression nodes

**Comment by dutts** [comment]
I'm happy to take a look

**Comment by simondel** [comment]
Awesome! If you need any help, let us know :)

It may be useful to install the [.NET Compiler Platform SDK for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK). It allows you to visually view the syntax tree of a file. This can help you figure out what kind of node(s) you need to mutate and the properties that they have. More info can be found [here](https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis).

**Comment by Mobrockers** [comment]
@Valdas3 Seeing as I can't find a fork from @dutts we can assume they did not yet have time to start on this. Feel free to pick this one up 👍

**Comment by Mobrockers** [comment]
@eTomate Feel free to pick up any work that you find interesting!

**Comment by Valdas3** [comment]
@Mobrockers actually, I was planning to do this, sorry for the late reply. @eTomate, have you already started working on this?
