### ISSUE TITLE
methods containing const string compile error

### ISSUE THREAD

**Issue by MentallyYours** [stryker-mutator/stryker-net#1181]
Methods containing const string variables gets compile exception. The error detail shown below.

The stryker version is  "**version": "0.18.0**".
.net core version =  **2.2**

**Actual code is:**

public void TestMethod(SomeClass instance)
{
            const string query = "SELECT COL1, COL2 FROM TABLE (NOLOCK)" +
                "WHERE COL1 = @COL_NAME";
}

[15:27:16 WRN] Stryker.NET encountered an compile error in C:\Git\someCode.cs (at 31:33) with message: The expression being assigned to 'query' must be constant (Source code: (Strykerl9bPlZSUPUE24og.MutantControl.IsActive(209)?"":"XXXX " )+
(Strykerl9bPlZSUPUE24og.MutantControl.IsActive(210)?"":                "YYYYYY" )+
(Strykerl9bPlZSUPUE24og.MutantControl.IsActive(211)?"":                "ZZZZ" )+
(Strykerl9bPlZSUPUE24og.MutantControl.IsActive(212)?"":                "AAAAA"))
[15:27:16 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.

**Comment by Mobrockers** [comment]
Hi, thank you for the bug report! I believe this pr should fix this issue: #1176

**Comment by dupdob** [comment]
@MentallyYours : could please share a bit of the related code? or a way to reproduce this? it may be something new

**Comment by MentallyYours** [comment]
@dupdob  it's the production code so i added only the compilation error part. Actually it's a const sql command query (edited above). Is it enough?

**Comment by dupdob** [comment]
Thanks, that's perfect.By the way, this should not be a blocking problem for you, so you can either ignore the message or remove the '+' from the string declaration and use single string instead of a concatenation (nothing left to mutate).
Meanwhile, we will fix this for a future version.

**Comment by MentallyYours** [comment]
@dupdob Thanks. It's not a blocking problem for me. The warning says "please report" so i followed the command :)

**Comment by dupdob** [comment]
Thanks for reporting. This is an issue because we expect Stryker to generate _legal_ mutants or being able to cleanly remove them when they are the cause of build errors.
To cut it short, it makes sense for Stryker to skip mutating const variables as they would result in build errors.
