### ISSUE TITLE
Some mutation spans are wrong in latest master

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#1186]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3595932/92248050-6135b100-eec8-11ea-8cd0-b5267ef1cd09.png)

The spans should be located here:

```csharp
private async Task<IList<T>> ListAsync<T>(string arrayProperty, string apiFormat, params object[] formatters)
{
    var list = new List<T>();
    var response = await SendAsync(HttpMethod.Get, apiFormat, formatters);

    using var json = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
    var listJson = json.RootElement.GetProperty(arrayProperty);
    for (int i = 0; i < listJson.GetArrayLength(); i++)
    {
        var item = JsonConvert.DeserializeObject<T>(listJson[i].GetRawText());
        list.Add(item);
    }
    return list;
}
```

In the past this issue has been caused by re-using a mutated syntax tree for further mutation instead of applying the mutation on a copy and using the original to continue mutation.

**Comment by richardwerkman** [comment]
I'll take a look!

**Comment by dupdob** [comment]
It is probably related to the mutation orchestration re design.

**Comment by richardwerkman** [comment]
Yes I already located it! It's indeed in the `ForStatementOrchestrator`. I'll push the fix in a minute.
