### ISSUE TITLE
Current branch name is not correctly identified in pull request scenarios

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#1189]
**Describe the bug**
Branch is not correctly identified, resulting in a complete mutation testrun instead of fallback being used

**Logs**
We could not locate a baseline for branch , now trying fallback version master

**Expected behavior**
Current or target branch name should be used

**Comment by g7ed6e** [comment]
Hi @Mobrockers.
I think that in pull request scenario, this code https://github.com/stryker-mutator/stryker-net/blob/d76229dfe7f95fd42649e9d636f070e842cb7e73/src/Stryker.Core/Stryker.Core/DiffProviders/GitDiffProvider.cs#L42 should be replaced by a comparison between the current merged branch of the pull request and the target branch.
this way we can also prevent change detection of build generated files (client side compiled code, stryker output files..).

**Comment by Mobrockers** [comment]
Here is where we determine what to compare with:

https://github.com/stryker-mutator/stryker-net/blob/d76229dfe7f95fd42649e9d636f070e842cb7e73/src/Stryker.Core/Stryker.Core/DashboardCompare/GitInfoProvider.cs#L114

This takes the GitSource argument as the branch to use to compare to (perhaps this could be renamed to TargetBranch or something to make it more clear). So we are already doing what you're suggesting. The only difference is that we also take the current working directory (for when a user is doing this on their own system to test new local changes).

We have no good way to determine that we are in a pull request scenario and I would rather not program detection for this scenario. 

Instead client side compiled code should be excluded through other means (we detect generated code and you can exclude files with a filter as well). Stryker output files should be excluded by the gitignore we place.

This should be sufficient, without having to build ways to detect pull request scenarios.
