### ISSUE TITLE
Mutators for Math

### ISSUE THREAD

**Issue by Myoxocephalus** [stryker-mutator/stryker-net#1194]
I am thinking about adding mutations for System Math.
For exemple i would like to add mutations like:
| Before | After |
|--------|-------|
| Min    | Max   |
| Max    | Min   |

If you think it´s ok i am happy to send a PR.

**Comment by Mobrockers** [comment]
Hi! 

I would appreciate an as complete proposal as possible. Could you list all the possible and useful mutations you would like to add in the table so we can judge it as a whole?

I would rather not piecemeal together a mutator as it will be hard to keep track of progress on the completeness of the mutator if we don't at least try to identify the possibilities from the start.

That said, I think this could be useful for sure :)

**Comment by Myoxocephalus** [comment]
Yes good comment, i could have provided some more information 😃 
Some more mutations could be:
| Before | After |
|--------|-------|
| Min    | Max   |
| Max    | Min   |
| Ceiling    | Floor   |
| Floor    | Ceiling   |
| MinMagnitude    | MaxMagnitude   |
| MaxMagnitude    | MinMagnitude   |
| Cos, Sin and Tan    | Sin, Cos or Tan   |
| BitDecrement    | BitIncrement   |
| BitIncrement    | BitDecrement   |
| Log    | Exp   |
| Exp    | Log   |

**Comment by richardwerkman** [comment]
We could also mutate other kinds like:
```cs
Math.Abs(10);
// to
-Math.Abs(10);
```
or
```cs
Math.Sqrt(10);
// to
10 * 10;
```

But this would make the mutator a lot more difficult. So I'd say we just start with the suggested swapping of method names :+1:

**Comment by richardwerkman** [comment]
About the Cos, Sin and Tan mutations. I think we have a risk they are equivalent mutations. For example a rectangle with 2 exactly the same angles. If we swap the Cos and Tan with equal angles, the outcome will be the same too right? (I'm not a math expert so this might be a wrong assumption.) If the outcome is the same we have created an unkillable mutant.

**Comment by richardwerkman** [comment]
I've been thinking some more about the Cos, Sin and Tan mutation. It could indeed be possible that the outcome of the methods it exactly the same. But only in the case of a perfect equal triangle. So if that happens to someone they should change their tests to use some other values. 

So I agree with the proposed mutations. @Myoxocephalus will you start working on the implementation?

**Comment by Myoxocephalus** [comment]
Yes, i expect to show some WIP PR in 2-3 weeks.

**Comment by jnyrup** [comment]
@richardwerkman `sin x = cos x` for `(4 pi n + pi)/4` (45 degrees and 225 degrees). 

https://www.wolframalpha.com/input/?i=Cos+x+%3D+sin+x

That concern seems no different that min/max and floor/ceiling giving same result for two identical values. 
As you've pointed out, it "just" needs a test case with other input.
