### ISSUE TITLE
Stryker treats .Net 5 as full framework.

### ISSUE THREAD

**Issue by Myoxocephalus** [stryker-mutator/stryker-net#1203]
**Describe the bug**
When running stryker agains a test project targeting .Net 5 i will be treated as full framework mening for example require a solution file.

**Expected behavior**
Should be treated the same as .net core.

**Thoughts about solution**
One solution would be to just map .Net 5 and later versions of .Net to the same value in the `Framework` enum as core but we should probably add a new value as the core name will not be the way forward and threat it the same way as core today.

**Comment by Mobrockers** [comment]
Nice catch :) I agree we should not call it core, however I'm not sure if a new enum value is the way to go either as for the purposes of the enum there is no difference between core and .net 5+

**Comment by Myoxocephalus** [comment]
Yes thats true. Do you have any suggestion on a new name to the value?
I can send a PR.

**Comment by Mobrockers** [comment]
```csharp
public enum Framework
{
    NetClassic,      # => DotNetClassic
    NetCore,         # => DotNet
    NetStandard,     # => DotNetStandard
    Unknown
}
```

@richardwerkman what do you think

**Comment by richardwerkman** [comment]
I agree. As I read in a Microsoft blog `.NET 5 = .NET Core vNext`. So I guess it's best to treat .net core as `DotNet` from now on.
