### ISSUE TITLE
Source branch name is not correctly identified in pull request or branch build scenarios in azure devops

### ISSUE THREAD

**Issue by g7ed6e** [stryker-mutator/stryker-net#1205]
**Describe the bug**
In azure devops yaml pipeline, specifying
`dotnet stryker --diff --git-source "coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranch'])"` as described in https://stryker-mutator.io/blog/2020-05-15/azure-pipelines-integration does not work. the branch is not found.

**Logs**
```
Stryker.NET failed to mutate your project. For more information see the logs below:

No Branch or commit found with given source refs/heads/develop. Please provide a different --git-source or remove this option.

```
**Expected behavior**
refs/heads/develop should be detected as a valid branch name.

**Additional context**
- using this yaml expression in pipeline fix the issue
`replace(coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranch']), 'refs/heads/', '')`
- i think this line is causing the issue
https://github.com/stryker-mutator/stryker-net/blob/d76229dfe7f95fd42649e9d636f070e842cb7e73/src/Stryker.Core/Stryker.Core/DashboardCompare/GitInfoProvider.cs#L74

**Comment by Mobrockers** [comment]
Nice catch! That could definitely be an issue :)

**Comment by g7ed6e** [comment]
@Mobrockers  Any idea of why we try to create and checkout branches ? This is really very dangerous from my point of view.

**Comment by Mobrockers** [comment]
We need to know the source branch name to know where to pull and push the dashboard report to (version), the merge checkout in a pr scenario does not have the name as its a very shallow detached checkout. We considered whether this would cause any issues but couldn't think of any. What dangers do you see?

**Comment by Mobrockers** [comment]
@Stijn-Rutten

**Comment by Stijn-Rutten** [comment]
@g7ed6e When we implemented this we thought considered if this could cause issues. But because we only check out the `GitSource` branch to make sure we have a reference to it, and immediatly after that check out your source branch we could not find an issue with this. But I am very interested to hear if you can find an issue with this, so we can tackle it :)

**Comment by g7ed6e** [comment]
@Stijn-Rutten i agree. i no longer see issue with this :).
