### ISSUE TITLE
RepositoryPath is not correct when specifying test projects using cmd line args

### ISSUE THREAD

**Issue by g7ed6e** [stryker-mutator/stryker-net#1209]
**Describe the bug**
When specifying `--test-projects` the `GitInfoProvider` without specifying BasePath, the path of stryker executable is used to determine the git repo.

**Expected behavior**
When using `--test-projects` the `GitInfoProvider` should use this path as starting point of git repo discovery.

**Comment by Mobrockers** [comment]
Mhm that's not good 🤨

**Comment by richardwerkman** [comment]
We have reworked the lookup of test projects a few times now. I think this should be fixed. Closing the issue
