### ISSUE TITLE
Return an exit code from Stryker CLI 

### ISSUE THREAD

**Issue by shadow-cs** [stryker-mutator/stryker-net#121]
It would be helpful if we could set a threshold for the Mutation score that if not reached would result in the process returning non-zero exit code.

Also failures (like the one described in #120) causes the process to exit with `0`.

For CI purposes it is fundamental to return a proper exit code.

**Comment by shadow-cs** [comment]
Partial duplicate of #11

**Comment by simondel** [comment]
This can be done using the thresholds that can be set by the user.

**Comment by Stukongeluk** [comment]
I'll try to take a shot at this one too!
