### ISSUE TITLE
Add Azure DevOps extension to the documentation

### ISSUE THREAD

**Issue by raschmitt** [stryker-mutator/stryker-net#1214]
I just created this Azure DevOps Extension, which enables people to easily integrate stryker into their pipelines:

https://marketplace.visualstudio.com/items?itemName=raschmitt.run-stryker-net-task

It makes life easier as you can select with a project to mutate using wildcards, and by solving, issues related to the installation of global dotnet tools on Azure Pipelines (https://github.com/dotnet/sdk/issues/8999)

What do you guys think about adding this to the documentation?

**Comment by Mobrockers** [comment]
I'm not opposed as long as we make it clear that we are not affiliated at all.

Also I see your task is written in powershell. I would personally prefer if it was a javascript based task as the powershell library is deprecated and not receiving any more updates (not even security updates).

Also powershell works only on windows, you should probably add that somewhere in the description.

**Comment by raschmitt** [comment]
> I'm not opposed as long as we make it clear that we are not affiliated at all.

I have the following disclaimer both on my Github repository as on the extension page on Azure DevOps marketplace:

`This is not an official Stryker Mutator extension.`

We could also add a note enforcing it in the documentation section.

> Also powershell works only on windows, you should probably add that somewhere in the description.

Just made an update regarding it.

> Also I see your task is written in powershell. I would personally prefer if it was a javascript based task as the powershell library is deprecated and not receiving any more updates (not even security updates).

As it was my first experience developing an Azure DevOps extension I decided to go with Powershell as I had this code almost ready on a template of mine. I plan on upgrading this task to Typescript just not in the near future as I'm focusing on other projects.

**Comment by Mobrockers** [comment]
If you run into any issues with the typescript version let me know. I also have some experience with that.

**Comment by raschmitt** [comment]
I'm planning to have a hit on that next week, If I need anything I will let you know, thanks.

**Comment by rajbos** [comment]
Just found this issue, awesome to see :-).

Since the change has been made and merged, can this issue be closed?

**Comment by Mobrockers** [comment]
I was waiting on @raschmitt to report back on the typescript conversion but sure the documentation has been added so this can be closed.

**Comment by raschmitt** [comment]
Hey guys, thanks for adding it to the docs. Yet I haven't made time yet to upgrade it to typescript :(

I will try to give a try at it again.
