### ISSUE TITLE
Mutation that removes out-parameter assignment within collection initializer triggers safe mode

### ISSUE THREAD

**Issue by oliwennell** [stryker-mutator/stryker-net#1215]
**Describe the bug**

Hi, I seem to have found an issue when Stryker goes into safe mode when trying to mutate some of my code.
```
Stryker.NET encountered an compile error in /Users/oliwennell/Projects/temp/example/example/ExampleClass.cs (at 8:4) with message: The out parameter 'isStringNullOrEmpty' must be assigned to before control leaves the current method (Source code: return (StrykerO1CPJwN1HjOxfxa.MutantControl.IsActive(0)?new List<int>
{}:new List<int>
    {
        PrivateStringToIntegerList(s, out isStringNullOrEmpty)
    });)
[16:13:50 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
```

**Logs**
See attached:
[log-20200918.txt](https://github.com/stryker-mutator/stryker-net/files/5246397/log-20200918.txt)

**Expected behavior**
Not sure. Perhaps Stryker would mutate the list initialization and still assign the out parameter somehow, although it might not always know what to assign it to. Or perhaps it should avoid mutating this certain scenario.

**Desktop (please complete the following information):**
 - OS: Mac
 - Type of project: core
 - Framework Version: core 3.1
 - Stryker Version: beta 0.19.0

**Additional context**

After doing some investigation I was able to create a minimal example, which I've used to generate the log and bug description.

If a method uses the collection initializer syntax to insert items into a collection, and code within that initializer assigns an `out` parameter, then the mutated code cannot compile.

For example:
```
public static List<int> StringToIntegerList(string s, out bool isStringNullOrEmpty)
{
    return new List<int>
    {
        PrivateStringToIntegerList(s, out isStringNullOrEmpty)
    };
}
```
mutates to:
```
public static List<int> StringToIntegerList(string s, out bool isStringNullOrEmpty)
{
    return new List<int> {};
}
```
...which doesn't compile because the `out` parameter is never assigned.

Full example class:
```
using System.Collections.Generic;

namespace example
{
    public static class ExampleClass
    {
        public static List<int> StringToIntegerList(string s, out bool isStringNullOrEmpty)
        {
            return new List<int>
            {
                PrivateStringToIntegerList(s, out isStringNullOrEmpty)
            };
        }

        private static int PrivateStringToIntegerList(string s, out bool isStringNullOrEmpty)
        {
            isStringNullOrEmpty = string.IsNullOrEmpty(s);
            return s.Length;
        }
    }
}
```

**Comment by Mobrockers** [comment]
Hi @oliwennell 👋 

Thank you for the report :) 

What we do in return scenarios is 'return default'. That would probably also work in this scenario except we have to assign default to the out param. Not looking to closely into this that seems like a reasonable and workable solation, what do you think @richardwerkman

**Comment by dupdob** [comment]
It should do the trick. 
Obviously those need to be initialized at the beginning and not the end of the function.

**Comment by dupdob** [comment]
I have a working fix.

**Comment by dupdob** [comment]
This issue can be closed: the fix is in the latest version
