### ISSUE TITLE
Implementation of IReporter interface for use (more or less directly) with git bisect run command

### ISSUE THREAD

**Issue by egoughnour** [stryker-mutator/stryker-net#1217]
**Context**
Applying a unit test suite over the history of a codebase is desirable in many cases. For instance, obviously this can be useful during maintenance development. Then again I find the acceptance test suite (or even source during initial development!) at times is unavailable to me as the unit test suite designer/developer.  Even more desirable would be an assessment of the unit test suite reliability/robustness at a point in time.

**Closer integration with git bisect makes these and other problems more tractable.**  
 
Ideally this could be addressed by creation of a type, say _GitBisectRunReporter_, and accompanying changes to the CLI handling.   Given a reasonably simple failure condition it should be possible to evaluate and thus to exit with the correct integer value.  

The alternative would be iterated manual re-execution of the test run in the course of the logarithmic search, including reassessment of the failure condition/threshold.

**Comment by Mobrockers** [comment]
Hi @egoughnour 

Are you suggesting Stryker performs the bisect operation instead of stryker being run in a bisect stage manually?
Or are there some changes in the stryker output you think would make the bisect operation easier to execute?

**Comment by egoughnour** [comment]
Right. The second case is what I had in mind.  Suppose there were a way to specify a threshold for the number of killed mutations--or maybe the combination of an operator, mutation and a span (or, e.g., containing method body?) in the source.  Then once the threshold is met or the specific mutation is caught (or missed) at the specified location then the result switches from 0 to 1 or vice versa. If an exception is thrown then it would return 125.  That way `git bisect run` can handle the output without any intervention.

Still maybe it makes more sense to have Stryker run the bisect--since in that case it's more of a white box and would be more flexible in terms of the ability to batch various operations with less manual preparation.
In some shells it might be necessary for the user to call bisect using a batch script--depending on the eval or magic back tick support.
If stryker runs the bisect then that's almost certainly unnecessary.

**Comment by Mobrockers** [comment]
Stryker already changes the exit code based on the threshold-break parameter. It that not sufficient?

**Comment by egoughnour** [comment]
Works for me.
