### ISSUE TITLE
No diff between branches - still mutates entire project

### ISSUE THREAD

**Issue by eranrodrig-tipalti** [stryker-mutator/stryker-net#1218]
**Describe the bug**
Branch out of master, run dotnet stryker --diff and still all files in the project are mutated.
![image](https://user-images.githubusercontent.com/70146096/94107236-b6b90a00-fe45-11ea-9cff-078b4abf7d22.png)

**Logs**
[log-20200924.txt](https://github.com/stryker-mutator/stryker-net/files/5273828/log-20200924.txt)

**Expected behavior**
I'd expect it not to mutate anything at all.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project:  dotnet core.
 - Framework Version 3.1.
 - Stryker Version: 0.19.

**Comment by Mobrockers** [comment]
Hi!

I cannot find any explanation for this behavior in the provided logs, we will investigate this issue.

**Comment by eranrodrig-tipalti** [comment]
@Mobrockers Any news?

**Comment by Mobrockers** [comment]
We're working on multiple improvements to the diff functionality that I think will fix this behavior as well.

**Comment by Mobrockers** [comment]
Hi @eranrodrig-tipalti 

I think I have found the issue. I'm implementing a fix.
