### ISSUE TITLE
The parameter GitSource is confusing, it should be renamed

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#1230]
**Is your feature request related to a problem? Please describe.**
It is unclear from the name whether GitSource contains the name of the current branch/commit or the target.

**Describe the solution you'd like**
The parameter should be renamed to something like GitDiffTarget

**Comment by g7ed6e** [comment]
It should also be possible to get diff only using git history and not considering local changed files.

**Comment by Mobrockers** [comment]
@richardwerkman do you agree

**Comment by richardwerkman** [comment]
Yeah I think `--GitDiffTarget` is better than `--GitSource`. So I agree.

@g7ed6e I think not using local changes deserves a seperate issue. Its not related to this one
