### ISSUE TITLE
Enhance cleartext reporter with table report

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#1238]
**Is your feature request related to a problem? Please describe.**
A lot of times you might not be interested in the exact locations of the mutations in the console. A reporter that simply shows the numbers in a table might be useful:

```
-----------|---------|----------|-----------|------------|----------|---------|
File       | % score | # killed | # timeout | # survived | # no cov | # error |
-----------|---------|----------|-----------|------------|----------|---------|
All files  |   69.57 |       16 |         0 |          3 |        4 |       0 |
Add.js     |   82.35 |       14 |         0 |          1 |        2 |       0 |
Circle.js  |   33.33 |        2 |         0 |          2 |        2 |       0 |
-----------|---------|----------|-----------|------------|----------|---------|
```

We also need to come up with a good name for this reporter

**Comment by richardwerkman** [comment]
> We also need to come up with a good name for this reporter

Why not just reporter `table`? In stryker.js the clear-text reporter is the table format. So we can't keep it in sync. But I'd say the name `table` covers this reporter completely right?

And would this reporter be on by default? And would it then replace the clear-text reporter as a default or be default together? 

My preference would be to print the table under the clear-text reporter by default, that way you see an overview when stryker is done. If you want to see some details you just scroll up.

**Comment by Mobrockers** [comment]
That does keep it more in-line with strykerjs so I can agree with that. It can be merged with the clear text reporter.

**Comment by eNeRGy164** [comment]
I was looking at this, but combining the code for the tree and the table in the same report will be very hard to do nicely.
To keep the naming aligned with Stryker, I would then suggest to add the table as `clear-text` and rename the current one to `clear-text-tree`?

**Comment by Mobrockers** [comment]
I don't mind, @richardwerkman what do you think

**Comment by richardwerkman** [comment]
Also good to me 😄

**Comment by eNeRGy164** [comment]
I'll pick this one up if nobody objects
