### ISSUE TITLE
WPF: Program does not contain a static 'Main' method suitable for an entry point

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#1251]
I have created a simple Windows WPF Application project (calculator.csproj) in .Net Framework 4.7.2. Also I have created a unit test project (testCalculator.csproj) for the same which is of type Class Library.

When I tried to mutate the calculator project using Stryker command, I am getting the below error :- CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [..\Desktop\calculator\calculator\calculator\calculator.csproj]

The command used is :- ..\Desktop\calculator\calculator\testCalculator>dotnet stryker -s "../calculator.sln"

Does Stryker support WPF application? If so, is there any solution to resolve this error?

_Originally posted by @jidheshr in https://github.com/stryker-mutator/stryker-net/discussions/1234#discussioncomment-95784_

**Comment by Mobrockers** [comment]
See https://github.com/stryker-mutator/stryker-net/pull/1028 for how this was solved for dotnet core mvc projects

**Comment by dupdob** [comment]
looking into this

**Comment by dupdob** [comment]
Could not reproduce with current HEAD. This was a dummy project with no useful tests: got 4 mutants, none of them killed. No pb except error messages for project ressources.
