### ISSUE TITLE
Add GitHub Actions so maintainers know the system is buildable and tests pass

### ISSUE THREAD

**Issue by mosoftwareenterprises** [stryker-mutator/stryker-net#1252]
**Is your feature request related to a problem? Please describe.**
With GitHub Actions support now being available, it makes contributors jobs easier if they know the current source builds and tests pass, BEFORE they contribute.
Therefore we should add Actions.

**Describe the solution you'd like**
We should add a simple Action to build and test stryker-net on push using linux, windows and macos, to ensure it is always compatible

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Mobrockers** [comment]
I would've preferred you contact us before contributing github actions. We have very thorough azure pipelines jobs for testing code changes.

**Comment by mosoftwareenterprises** [comment]
Fair point, I should have looked harder, I see these on the home page now. 
I started it, as when I ran the tests myself, they failed due to line endings being different.

**Comment by Mobrockers** [comment]
@mosoftwareenterprises sounds like this was a genuine contribution. Sorry for being so quick on the trigger.

Tests failing due to line endings should not happen, could you open a bug for that?
