### ISSUE TITLE
Move reporting on before-testing mutant statuses to reporter

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#1261]
**Is your feature request related to a problem? Please describe.**
We have some reporting as log statements here: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs#L288-L315

This doesn't really fit as log statements, perhaps it should be in a reporter like the clear text reporter.

**Describe the solution you'd like**
We should probably implement this reporter hook to build this reporting: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Reporters/IReporter.cs#L12

**Comment by Mobrockers** [comment]
Default reporters: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs#L336

Lifecycle hook: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Reporters/IReporter.cs#L10

Enum: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Reporters/Reporter.cs

Register new reporter: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Reporters/ReporterFactory.cs#L18

**Comment by luciaconde** [comment]
Currently working on it.
