### ISSUE TITLE
Create Editorconfig

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#1270]
**Is your feature request related to a problem? Please describe.**
We currently don't have an editorconfig. This creates problems for contributors.

**Describe the solution you'd like**
Create an editorconfig for stryker.net so contributors can easily follow our coding guidelines

**Comment by AlexNDRmac** [comment]
I can help with this

**Comment by Mobrockers** [comment]
Awesome! We are currently having a hacktoberfest event with about 10 people (today and tomorrow) so we'll be available for questions on voice chat at https://discord.gg/vFSp6gf or on our slack!

**Comment by AlexNDRmac** [comment]
@Mobrockers pls check rules inside editorconfig, maybe some options you would like to change, maybe - not :) In general - all options respects Microsoft coding styles and recommendation.
