### ISSUE TITLE
nuget contentfiles mutations causes issues

### ISSUE THREAD

**Issue by csMACnz** [stryker-mutator/stryker-net#128]
With nuget packages, you can include compilable source files: https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

These files end up compiled into the `obj\Debug\netcoreapp2.1\NuGet\F3F32FCC102FAF927C28583AC554AF5CC6C67A63\MyLibrary\0.1.2` folder of the project that consumes them. They are effectively linked-in source files.

When Stryker mutates these files, it fails to mutate them back again (presumably because nuget automatically resets them?)

```
[12:26:48 ERR] Unable to rollback mutation for node EmptyQuery with diagnosticmessage The name 'EmptyQuery' does not exist in the current context
[12:26:48 ERR] An error occurred during the mutationtest run
System.ArgumentException: Node to track is not a descendant of the root.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.TrackNodes[TRoot](TRoot root, IEnumerable`1 nodes) in /_/src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions_Tracking.cs:line 43
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, ICollection`1 diagnosticInfo)
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics)
   at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms)
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)
```

In the above message, `EmptyQuery` refers to a method defined in a base class inside the imported source contentFile from the nuget package.

It would be great if either compiled contentFiles from `obj` were ignored from mutation, and/or the ability to ignore files was added. The error looks similar to the error in #125

**Comment by richardwerkman** [comment]
Files in the `obj` folder are already ignored from mutation. Are you sure the problem lies with this file? Have you run using `--logConsole trace` to get more detailed information about the problem? 

Since the error looks similar to #125 it might be the same issue.

**Comment by csMACnz** [comment]
Good to know, might require a bit more investigation then.  All of the failures to "rollback mutation" is on code related to this generated code file. As you say, may be a symptom of the same root cause as the ternary with tuples.

**Comment by csMACnz** [comment]
This looks more like it:

```
[13:48:51 DBG] Compilation failed
[13:48:51 DBG] The type or namespace name 'MyBaseClass<>' could not be found (are you missing a using directive or an assembly reference?), C:\path\redacted\to\file.cs
[13:48:51 DBG] Rollbacking mutations from C:\dev\Accounts\Accounts.Service\Authorisation\XeroRoleAuthorisationHandler.cs
```

(some other errors not provided)

`MyBaseClass<>` is the base class compilation file from the nuget package.
It looks like the actual problem is that the nuget `contentfiles` are not getting included during the recompilation steps after mutation.

**Comment by richardwerkman** [comment]
So if I understand correctly the type `MyBaseClass<>` is from a nuget package? It could indeed be the problem that these `contentfiles` are not included during compilation. Do you know where the file can be found? 

A sollution might be to read the files, create AST's for each contentfile and give these AST's to Roslyn. Then the compiler will know the type `MyBaseClass<>`.

**Comment by richardwerkman** [comment]
Okay so Stryker should scan each referenced nuget package for `*.cs` or `*.cs.pp` files and include the AST's before compiling.

This could be a tricky issue since we don't have a list available of referenced nuget packages. Do you have any suggestions on how to get the locations of these files?

**Comment by csMACnz** [comment]
It might be enough to also scan `obj\<Configuration>\<TargetFramework>\NuGet\**\*.cs` files for inclusion. However I suspect that similar issues would happen with linked files, or other external to the project folder class files.

Since this (and the linking) case are not overly common, it may be enough to allow configuring extra source folders to scan files from during compile?

Otherwise, it may be some deep digging to better emulate what MSBuild is doing when it locates `<Compile>` source files and use that rather than a manual disk scan...

I don't know if Roslyn gives you any MSBuild information, but it might be possible to extract the real "Content" list somehow?

**Comment by richardwerkman** [comment]
Sadly Roslyn doesn't support any MSBuild implementation for .NET Core. This is why I gathered references and *.cs files in the first place. 

I like your sollution as to give a list of folders/files to also include for Stryker. This might be useful for solving other compilation problems in the future as well. 

I would be even more happy if we find a way for Stryker to find the locations itself but this is a issue for the future.

**Comment by Mobrockers** [comment]
Would be fixed with #131

**Comment by Mobrockers** [comment]
@csMACnz Do your nuget content files get included in the compilation using <Compile Include= Link=> style msbuild config? If so #562 will probably implement this feature.

**Comment by Mobrockers** [comment]
If this feature is still wanted feel free to place a comment and/or provide a PR. For now I'm closing this feature request.
