### ISSUE TITLE
Configue extra files and folders to compile

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#131]
Stryker has some problems with compiling a few projects as shown in #128. 

If users could pass a list/array of files and folders to compile, Stryker would also be able to compile these projects. 

``` json
{
    "stryker-config":
    {
        "files-to-compile": [
            "C:/some/location",
            "C:/another/location/specific-file.cs",
         ],
    }
}
```

We will have to test these values to be files of the right extension and scan the given folders for `*.cs` files. The content of the found files should be parsed to AST's and be fed to Roslyn before the first compilation. 

@nicojs what do you think about this solution and the configuration name?

**Comment by richardwerkman** [comment]
I was thinking we could have multiple ways of knowing what files to mutate.

- Default: all files (scan directory for *.cs without bin, obj, node_modules)
  - No configuration so easy. Might miss some files.
- Exclude: configure files to exclude from default files
  - Can be useful when stryker crashes on a file or when the file won't have to be tested.
- Include: configure files to mutate together with default files 
  - Can be useful when a file is not inside the main directory but still part of the project.
- Only: configure files to mutate only 
  - To speed up a mutation test run during developing.

All cases are valid usecases in my eyes. Can this be one single item or should this all be different issues? @Mobrockers @yaelkeemink @nicojs @simondel

**Comment by Mobrockers** [comment]
Since file excludes has already been picked up in #34 and Default: no configuration already exists I think we could suffice with one issue to design and implement the configuration modes and settings, and one extra to implement the include and only modes since they are very similar.
