### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by bcollamore** [stryker-mutator/stryker-net#1347]
Styker run fails
```
[08:11:38 VRB] RollBacking mutations from ...
[08:11:38 VRB] source

		public Grid()
		{
if(StrykeraHOhiZBY3C1UCaN.MutantControl.IsActive(1240)){			float[] pattern = {};
}else{			float[] pattern = { 1.0f, 2.0f };
}			minorGridPen_.DashPattern = pattern;
			horizontalGridType_ = GridType.Coarse;
			verticalGridType_ = GridType.Coarse;
		}


[08:11:38 WRN] Stryker.NET encountered an compile error in ... (at 70:32) with message: The name 'pattern' does not exist in the current context (Source code: pattern)
[08:11:38 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[08:11:38 VRB] RolledBack to

		public Grid()
		{
if(StrykeraHOhiZBY3C1UCaN.MutantControl.IsActive(1240)){			float[] pattern = {};
}else{			float[] pattern = { 1.0f, 2.0f };
}			minorGridPen_.DashPattern = pattern;
			horizontalGridType_ = GridType.Coarse;
			verticalGridType_ = GridType.Coarse;
		}
```

Desktop:
 - OS: Windows
 - Type of project: Framework
 - Framework Version 4.8
 - Stryker Version 0.20.0

**Comment by Mobrockers** [comment]
Hi @bcollamore !

This is a warning and is not blocking for the testrun, do you also have an error for us?

**Comment by richardwerkman** [comment]
@Mobrockers the rolled back code does still contain a mutation. That should not happen and could be blocking

**Comment by Mobrockers** [comment]
> @Mobrockers the rolled back code does still contain a mutation. That should not happen and could be blocking

Mhm I missed that before the formatting fix. That is an issue yes.

**Comment by dupdob** [comment]
I think my PR should fix this, as it improves the situation in two ways: 
1) array initialiser mutations are controlled at the block level (no longer at the statement level)
2) rollback logic has been refactored and will be more reliable

**Comment by dupdob** [comment]
correction: the fixes I mentioned above have already been merged and are part of `master` now.

**Comment by Mobrockers** [comment]
@bcollamore the fix has just been released
