### ISSUE TITLE
Styker v.0.21.0 not excluding files from being mutated in .Net 5.0

### ISSUE THREAD

**Issue by raschmitt** [stryker-mutator/stryker-net#1377]
**Describe the bug**

I'm trying to exclude some files from being mutated with the following `stryker.-config.json`:

```json
{
  "stryker-config": {
    "test-runner": "vstest",
    "reporters": ["progress", "html"],
    "log-level": "info",
    "log-file": false,
    "timeout-ms": 10000,
    "max-concurrent-test-runners": 4,
    "threshold-high": 80,
    "threshold-low": 70,
    "threshold-break": 0,
    "mutate": [
      "!**/Migrations/*.cs",
      "!**/Registers/*.cs",
      "!**/CustomWebHostService.cs",
      "!**/Program.cs",
      "!**/Startup.cs",
      "!**/ApiExtension.cs",
      "!**/Bootstrapper.cs",
      "!**/RabbitMqListener.cs",
      "!**/NativeInjectorBootStrapper.cs",
      "!**/*.Designer.cs",
      "!**/*Context.cs",
      "!**/Mappings/*Mapping.cs",
      "!**/*Data/**/*Mapping.cs"
    ],
    "excluded-mutations": [],
    "ignore-methods": [
      "LogDebug",
      "LogTrace",
      "LogInformation",
      "LogWarning",
      "LogError",
      "LogCritical",
      "Log",
      "Dispose",
      "ToString",
      "WriteLine"
    ]
  }
}
```

Yet when I run stryker all project files get mutated.

**Logs**

[log-20210121.txt](https://github.com/stryker-mutator/stryker-net/files/5851436/log-20210121.txt)

**Expected behavior**

I expected stryker to not mutate files that are excluded in my `mutate` directive.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: .Net
 - Framework Version: 5.0
 - Stryker Version: beta 0.21.0

**Additional context**

I've been using this exact config file for a while and it had been working just fine with .Net Core 3.1 and stryker v.0.20.0.

**Comment by raschmitt** [comment]
Interestingly even if I remove my `stryker-config.json` file and try to ignore files suing properties like: `-m "['!**/Startup.cs']"`, all files still get mutated.

**Comment by Mobrockers** [comment]
It would make sense that you get the same result whether from config file or commandline as they resolve to the same config object. 

I have a feeling this might have something to do with the introduction of the multi project feature @richardwerkman. I think the filters are no longer matching with the file paths. We'll have to investigate.

**Comment by raschmitt** [comment]
> It would make sense that you get the same result whether from config file or commandline as they resolve to the same config object.
> 

Indeed.

> I have a feeling this might have something to do with the introduction of the multi project feature @richardwerkman. I think the filters are no longer matching with the file paths. We'll have to investigate.

Interesting, I've been away from the community for a while, but that is a feature I've been long waiting for, most of my solutions are a multi-project business domain with a single test project. I've searched the docs and found nothing about it, how does it work?

**Comment by richardwerkman** [comment]
@raschmitt We released the solution file run feature only a few weeks ago. We haven't documented it yet because it's still unstable and has some known issues. If you want to test it here is how to use it:

Run stryker from the solution directory
Pass the solution file name using the -s flag

**Comment by richardwerkman** [comment]
> I have a feeling this might have something to do with the introduction of the multi project feature @richardwerkman. I think the filters are no longer matching with the file paths. We'll have to investigate.

@Mobrockers I don't think so. The issue said the problem occured on version 0.20.0. That was before multi project ;) 

We could check if the issue still persists on 0.21.0

**Comment by raschmitt** [comment]
@richardwerkman great feature.

I've been using it since yesterday. So far so good, except for this issue that I'm reporting here.

**Comment by Mobrockers** [comment]
@raschmitt a fix is being released right now

**Comment by raschmitt** [comment]
@Mobrockers just tried with `v.0.21.1`, working fine.

Thank`s a lot guys.
