### ISSUE TITLE
Html reporter doesn't work for multi project runs

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1380]
**Describe the bug**
The html reporter seems to just put all files from all projects under the same directory. Possibly even overwriting duplicate file names. 

Also the cache used by the incremental compare feature is overwritten.

**Expected behavior**
I want every project to have it's own directory in the html report so I can inspect each project.

**Comment by wiciok** [comment]
I'm working on this issue now. It is not related directly to HTML reporter - affects JsonReporter as well.
In general, there are two related issues here.
First is improper handling of files located in project root - it affects also project runs.
Second is general topic of handling separate directories for projects in solution runs.

**Comment by Mobrockers** [comment]
That's awesome! If it is a quick fix please create the change from the master branch. If it requires significant effort please create the change to the v1.0 branch.
