### ISSUE TITLE
Auto open html report with -o or --open

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1404]
**Is your feature request related to a problem? Please describe.**
I don't want to click the html report to open it. That means I have to wait for stryker to finish and then click myself.

**Describe the solution you'd like**
I would like to pass the `-o` or `--open` option so the html report opens when stryker is done. This will also notify me when stryker is done!

**Additional context**
The `-o` option should verify that the html reporter is enabled. With no html report the option will not work and log a warning.

**Comment by Mobrockers** [comment]
This option should be command line only in the new options structure
