### ISSUE TITLE
Stryker cannot handle C# 9 Source Generators

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1413]
**Describe the bug**
In our project, we rely on [source generators](https://docs.microsoft.com/en-us/dotnet/core/dotnet-five#source-generators), one of the latest and greatest C# 9 features. Looks like their presence in code breaks Stryker's efforts.

**Logs**
[log-20210216.txt](https://github.com/stryker-mutator/stryker-net/files/5990683/log-20210216.txt)

**Expected behavior**
I don't know if Stryker can theoretically handle all the magic behind source generators. If not, it would be probably enough to just not touch generated stuff at all.

**Environment**
 - OS: Windows
 - Type of project: core
 - Framework Version: .net 5
 - Stryker Version: 0.21.1
 
**Additional context**
I also attach the code to reproduce the issue.
[SourceGeneratorExample.zip](https://github.com/stryker-mutator/stryker-net/files/5990726/SourceGeneratorExample.zip)

I just run `dotnet stryker` from the test folder. If I comment generated code (`//LogGenerator.Generated.Logger.Log();`), everything works.

**Comment by Mobrockers** [comment]
Could you perhaps complain how a 'source generation' is executed? We compile sources manually using Roslyn so any processes built into msbuild instead of Roslyn will have to be recreated by us.

**Comment by psfinaki** [comment]
Well regretfully I don't know how this works in depth, but our usage is only a bit more complex than in the example I posted (we also have some parameters for the logs). [Here](https://www.youtube.com/watch?v=3YwwdoRg2F4) the guys explain the magic a little bit.

But if you have some specific questions, I can ask around in the company, I have contacts to some gurus here :)

**Comment by psfinaki** [comment]
Also, we actually have our logging strategy open sourced [here](https://github.com/geeknoid/LoggingGenerator), that's what eventually we want to get working :)

**Comment by JohnMcGlynnMSFT** [comment]
I've created a [Pull Request](https://github.com/stryker-mutator/stryker-net/pull/1617) that demonstrates how to integrate source generators.

**Comment by rouke-broersma** [comment]
That's amazing thank you!
