### ISSUE TITLE
Better Solution-wide Mutation Testing

### ISSUE THREAD

**Issue by hannahchan** [stryker-mutator/stryker-net#1448]
I currently have a solution and project structure like the following. Each Project has a TestProject where `ProjectX` is tested by `TestProjectX`.

```
SolutionRoot
├─ Source
│  ├─ SubFolder
│  │  └─ Project1
│  ├─ Project2
│  └─ Project3
├─ Test
│  ├─ SubFolder
│  │  └─ TestProject1
│  │     └─ stryker-config.json
│  ├─ TestProject2
│  │  └─ stryker-config.json
│  └─ TestProject3
│     └─ stryker-config.json
└─ SolutionRoot.sln
```

Each Test Project has been configured with a `stryker-config.json` file which tells Stryker which project to mutate. For example `TestProject1` has a config file with the contents;

```json
{
  "stryker-config": {
    "project-file": "Project1.csproj"
  }
}

```

To mutation test my whole solution, I currently have to change into each of the Test Project directories and run `dotnet stryker`. Instead of doing that, I would like to run `dotnet stryker` in the root of my solution once and have it recursively find and run mutation tests for all of my Test Projects and have it respect the config of individual Test Projects. Ideally this will also output a combine report in the project root. I'm ok if it doesn't do this and it stores a mutation report for each Test Project.

I've tried running `dotnet stryker --solution-path <Solution.sln>` however this produces terrible results compared to running `dotnet stryker` individually in each Test Project. I'm also developing in .NET Core, not .NET Framework.

**Comment by Mobrockers** [comment]
`dotnet stryker --solution-path <Solution.sln>` actually should already do what you are asking for. It is experimental and for sure not production ready (very inconsistent) but it uses the solution file to detect all test projects and projects under test and automatically figures out which are related to which based on project references.

We plan to improve this significantly and build it out to a first class supported feature after the 1.0 release.
