### ISSUE TITLE
Some statements break Stryker.NET

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#145]
### The issue
The following statement breaks Stryker:

``` csharp
string someQuery = "test";
new Uri(new Uri(""), "/API?" + someQuery);
```

The reason is that changing the `+` to an `-` will not cause one but two compile errors.

1. `cannot convert from 'System.Uri' to 'string'`
2. `Operator '-' cannot be applied to operands of type 'string' and 'string'`

During the rollback stage Stryker will try to rollback both errors. It will find the mutation that causes this twice and will try to remove that node twice. The first time is succesful, the second time the node is already removed and will throw a null reference exception. This crashes Stryker.

### Fix
https://github.com/stryker-mutator/stryker-net/blob/f5395ae6bdeb38b4aadc84dbaac9caee23a4e699/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs#L91
The mutation made in the causing statement exists twice in the `brokenMutations` Collection. Somehow we have to make sure the list cannot contain a mutation twice. 

This will fix the bug.

**Comment by B1tF8er** [comment]
Can I do this?

**Comment by B1tF8er** [comment]
let me clone the repo, see the code and if I have any doubts I will let you know

**Comment by drSte** [comment]
can I contribute on this?

**Comment by richardwerkman** [comment]
@drSte if you think you can fix this right away I would say go ahead. Unless @B1tF8er is already on his way to create his pull request. Maybe he can let you know?

**Comment by simondel** [comment]
I think @B1tF8er is already working on this, sorry!

**Comment by B1tF8er** [comment]
I am working on this

**Comment by Mobrockers** [comment]
@drSte The previous contributor no longer has time to continue working on this issue. Are you still interested in fixing this? If so, you could continue on their work as seen in #190.
