### ISSUE TITLE
Fix the order of reporter events

### ISSUE THREAD

**Issue by Valdas3** [stryker-mutator/stryker-net#146]
When executing tests in multi-threaded environment test progress gets reported out of order when compared to the final mutation test scores.  An example:
![Example](https://user-images.githubusercontent.com/9084046/46435736-b8bcc680-c75f-11e8-85f4-850f304c1151.png)

Here, when tests was running, the progress was reported as `SS...S`, which would mean that first two mutants and the last one survived. Looking at the final score, we see that surviving mutants were in positions 3, 4 and 6, so the expected output report should have been  `..SS.S`.

The issue is caused by Parallel.ForEach in MutationTestProcess, so that would be a good place to start
https://github.com/stryker-mutator/stryker-net/blob/00b6f4cd89a6a5d6d5871d7f503fdfc03dda26f6/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs#L112

**Comment by richardwerkman** [comment]
For me this has a very low priority. The [ConsoleDotProgressReporter](https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Reporters/ConsoleDotProgressReporter.cs) main goal is to inform the user about the status of the mutationtestrun. It gives the user the idea that the program is still running and has not crashed, and at the same time gives a **preview** about your results. For me it's way more important that the actual end report works right.

Also this issue would be hard to fix as the order of testing cannot be predicted during paralel testing. Some mutants take longer to test and we can only print the result after it is tested. Thanks to this differences in duration the order changes.

**Comment by kevinlyles** [comment]
One option might be to output a placeholder character for mutants that haven't finished yet.  You'd have to go back and update the existing line of text one it finished to make that work without scrolling a bunch, but I think that's possible with \r.

**Comment by richardwerkman** [comment]
This seems obsolete now. The progress reporter is now the main reporter.
