### ISSUE TITLE
Integrate libgit2sharp added/deleted line information in the diff filter

### ISSUE THREAD

**Issue by Stijn-Rutten** [stryker-mutator/stryker-net#1461]
**Is your feature request related to a problem? Please describe.**
Diff filter

**Describe the solution you'd like**
The new release for libgit2sharp allows to inspect the added and deleted lines in the diff information. We can now determine which mutants in a changed file have been deleted, or have been inserted. Allowing for a more precize exclusion.

**Comment by rouke-broersma** [comment]
We should instead just do a source code compare. Git information is not needed.
