### ISSUE TITLE
Stryker hangs with multi-targeted test project

### ISSUE THREAD

**Issue by ggreig** [stryker-mutator/stryker-net#1475]
**Describe the bug**
When run against a multi-targeted test project, Stryker hangs indefinitely when attempting to initialise test runners.

**Log**
[log-20210317.txt](https://github.com/stryker-mutator/stryker-net/files/6159585/log-20210317.txt)

**Expected behavior**
I expected the tests to be run for each version of the .NET framework targeted by the test assembly, and results grouped by framework. As a graceful fallback, I would expect the tests to be run for at least one of the targeted frameworks (identifying which one), with supported options to control which framework should be used.

**Desktop (please complete the following information):**
 - **OS:** Windows 10
 - **Type of project:** multi-targeted test project (net461;net462;net47;net471;net472;net48;netcoreapp2.1;netcoreapp3.1;net5.0) testing multi-targeted assembly (net5.0;netstandard2.0) - to ensure that the project being tested works as expected for all supported framework versions (that is, the versions the test project is multi-targeted to).
 - **Stryker Version:** 0.22.0 (beta)

**Additional context**
Stryker was successful in analysing these assemblies before multi-targeting was added.

**Comment by Mobrockers** [comment]
Could you try switching the order of the targets in the test project to `netstandard2.0;net5.0`?

**Comment by ggreig** [comment]
I've now tried that; it didn't change the behaviour.

**Comment by Mobrockers** [comment]
I will reopen the feature request we used to have for this. #137
