### ISSUE TITLE
Refactor tests integration (coverage & testing phase)

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#1476]
**Is your feature request related to a problem? Please describe.**
As of V0.22, the integration of tests (test cases, test results, test lists..) is sub par. The current design does not support NUnit's TestCases and xUnit Theories, which lead to issues with coverage capture and mutant testing. 
Timing informations as well as initial test results could be captured to improve the overall behaviour of Stryker.
Finally, the overall design is still naive and there is excessive object creations overall. 
 
Related issues:
#1434, #949, #843, #772

**Describe the solution you'd like**
A better design based on the accumulated experience and findings that could provide:
- increase performances (early efforts show we can hope for significant benefits, like 10-20% total)
- improved support for test cases providing multiple results (as of now, only the first test result is used)
- compute timeout according to the list of tests to be run
- been able to use Stryker even when initial test is not successful, by discarding related tests. There probably still should be some minimal bar to avoid useless run

**Describe alternatives you've considered**
NA

**Additional context**
I have already started working on this when working on issue #1434. This issue is here to capture the initiative and provide space to discuss options

**Comment by dupdob** [comment]
## Update
1. Performance: memory usage as dropped significantly by reusing VsTest raw data as much as possible. It will impact performance for large projects (large as in _tests_ * _mutations_)
1. Implemented proper support for test cases with multiple results. Current design could lead to false positive (i.e. undue survivor) but only in rare situations so it should not have visible impact.
1. Nothing done on timeout front yet
1. Initial test results are now kept (for multiple result supports). Instead of discarding them, I propose the test still to be run, but ignoring their results 
___
## On runtime/dynamic test theories/cases
I have been exploring VsTest's behavior with multiple test cases. Here is a summary of my findings (so far):
1. xUnit and NUnit generate test cases names following this pattern: 
  `"testname(param1.ToString(), param2.ToString(),...)"`
1. static test cases' names are generated at test discovery time
1. dynamic (`[TestCaseSource(...)]`) names are generated at **discovery** time for xUnit, but at **run** time for NUnit. As such
1. you can have **duplicate test cases** if names conflict. With xUnit, those are reported at discovery time, with NUnit are reported at run time.
1. you can only run a test either by **specifying its correct name** of by **running all tests** (in the assembly).
1. mutation can alter a test name if they impact a `ToString()` method. It will result in a new testcase being reported at runtime.

**Comment by rouke-broersma** [comment]
Nice findings! (Or annoying findings 😂)
