### ISSUE TITLE
--ignore-methods doesn't work

### ISSUE THREAD

**Issue by kreghek** [stryker-mutator/stryker-net#1477]
**Describe the bug**

I use Stryker to test my project. And I want to exclude some "auto-generated" methods like ToString and GetHashCode.

The command to run Stryker looks like:
dotnet stryker --project-file=[path-to-project]/Zilon.Core.csproj --ignore-methods "['ToString', 'ConfigureAwait', '*Exception.ctor', 'Equals', 'GetHashCode']" --excluded-mutations "['string']"

But I has no effect:
![image](https://user-images.githubusercontent.com/2405499/111724980-c5cec100-8898-11eb-847b-ab3d6ffe1f5b.png)

You can see full workflow on Github Actions:
https://github.com/kreghek/Zilon_Roguelike/blob/8df8e59f1432ab1966193a49a8b4e7e41ef56384/.github/workflows/mutation-test-stryker.yml

Direct link to the mutation report:
https://github.com/kreghek/Zilon_Roguelike/suites/2293373841/artifacts/48053828

**Logs**

You can get logs from Report archive

https://github.com/kreghek/Zilon_Roguelike/suites/2293373841/artifacts/48053828

**Expected behavior**
The methods are ignored and don't appears in report.

**Desktop (please complete the following information):**
 - OS: ubuntu-latest
 - Type of project: .NET Standart
 - Framework Version 2.0
 - Stryker Version 0.22.0

**Comment by Mobrockers** [comment]
Hi @kreghek

The ignore methods option only ignores methods **calls**, not method bodies. For method bodies you'll want to use the ignore code coverage attribute.
