### ISSUE TITLE
An option to specify target framework for build

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1487]
**Is your feature request related to a problem? Please describe.**
I have found that Stryker runs are inconsistent for projects with multiple targets. For example, for a project targeting both .NET Core and .NET Framework, Stryker sometimes builds against .NET Core and sometimes against .NET Framework. This leads to inconsistent results due to platform-specific code, also such executions may require different parameters (e.g. `--solution-path` is needed for runs against .NET Framework). I want to build only against .NET Core and I am left only with retries and hope to get lucky.

**Describe the solution you'd like**
Yet another Stryker option to specify the target framework. `BuildAnalyzer` actually supports getting framework as a parameter so it looks like we only need to pass it to `ProjectFileReader` which would further pass it to `AnalyzerManager` via `var analyzerResult = manager.GetProject(projectFilePath).Build(targetFramework).First();`

**Comment by richardwerkman** [comment]
Yes we can add a new option for this. We have been struggling with multiple target frameworks. This seems like a good solution.

However I'd like to wait with writing this feature until we have finished working on #1273 as this is a complete rework on the options. If we add a new option now this will result in a huge merge confict.

**Comment by psfinaki** [comment]
@richardwerkman thanks for the quick response! Do you have any idea when that PR is expected to get merged? And is there any way to help there?

**Comment by Mobrockers** [comment]
Hi 🙋‍♀️

I have modified #137 for this feature request.

We are mostly done with the design of #1273, we just need to fix/create all unit tests for all the new options. It should be merged relatively soon.

**Comment by psfinaki** [comment]
@Mobrockers, great. Alright, I will create a PR in the upcoming days :)

**Comment by Mobrockers** [comment]
Closing in favor of #137
