### ISSUE TITLE
Add option to not mutate certain methods (not only parameters passed to method)

### ISSUE THREAD

**Issue by DaveSenn** [stryker-mutator/stryker-net#1496]
**Is your feature request related to a problem? Please describe.**
If we have to do string operations to log some data, we first check if the log level is enabled. Only if the level is enabled, we perform the string operations. 
I don’t really care about log being written or not during (unit) testing. I would like to have an option to exclude the log level checks from mutation.

Code example:
```
if ( _logger.IsInfoEnabled ) // do not mutate IsInfoEnabled 
    _logger.Info( $"Some expensive log {data.AsJson()} );
```
**Describe the solution you'd like**
I would like to have a config option to specify certain methods and or properties to exclude from mutation.
If `IsInfoEnabled` is specified in the new config option it’s return value should never be changed.

**Describe alternatives you've considered**
I did not find any alternatives.

**Additional context**

**Comment by Mobrockers** [comment]
You can use the [Mutate](https://github.com/stryker-mutator/stryker-net/blob/master/docs/Configuration.md#mutate) argument to ignore specific filespans from mutation.

You can also use `[ExcludeFromCodeCoverageAttribute]` to ignore from mutation.

Are those not sufficient?

**Comment by DaveSenn** [comment]
Hi Mobrockers

Thank you for your answer. 
I am not sure if I misunderstand the documentation but as I understand it is not possible to make sure the return value of ` IsInfoEnabled` does not get changed.
-	_logger is of type ILogger defined in another (3rd party) assembly.
-	IsInfoEnabled is property and I would need to make sure the value returned by the getter will never be changed
-	I would like to test all other lines of code in my method therefore a ExcludeFromCodeCoverageAttribute sounds like the wrong approach to me?
I tried to add -	IsInfoEnabled to the method-ignore list but this did not work for me, the return value of IsInfoEnabled was still changed

   ```
 "ignore-methods": [
        "IsTraceEnabled",
        "Trace",
        "IsDebugEnabled",
        "Debug",
        "IsInfoEnabled",
        "Info",
        "IsWarnEnabled",
        "Warn",
        "IsErrorEnabled",
        "Error",
        "IsFatalEnabled",
        "Fatal"
    ],

```

![Capture](https://user-images.githubusercontent.com/7510324/113457237-94650200-940f-11eb-9243-9f8ca13ed265.PNG)

**Comment by Mobrockers** [comment]
I'm not 100 percent sure but I think you can put the ignore coverage attribute on the smallest scope near the mutation (possibly even inside the if) to ignore just that smallest scope.

**Comment by DaveSenn** [comment]
The smallest scope I could add the attribute to would be the method.
Trying to add the attribute to the if will result in `CS7014 C# Attributes are not valid in this context.`

```
namespace System
{
    //
    // Summary:
    //     Specifies the application elements on which it is valid to apply an attribute.
    [Flags]
    public enum AttributeTargets
    {
        //
        // Summary:
        //     Attribute can be applied to an assembly.
        Assembly = 1,
        //
        // Summary:
        //     Attribute can be applied to a module. Module refers to a portable executable
        //     file (.dll or.exe) and not a Visual Basic standard module.
        Module = 2,
        //
        // Summary:
        //     Attribute can be applied to a class.
        Class = 4,
        //
        // Summary:
        //     Attribute can be applied to a structure; that is, a value type.
        Struct = 8,
        //
        // Summary:
        //     Attribute can be applied to an enumeration.
        Enum = 16,
        //
        // Summary:
        //     Attribute can be applied to a constructor.
        Constructor = 32,
        //
        // Summary:
        //     Attribute can be applied to a method.
        Method = 64,
        //
        // Summary:
        //     Attribute can be applied to a property.
        Property = 128,
        //
        // Summary:
        //     Attribute can be applied to a field.
        Field = 256,
        //
        // Summary:
        //     Attribute can be applied to an event.
        Event = 512,
        //
        // Summary:
        //     Attribute can be applied to an interface.
        Interface = 1024,
        //
        // Summary:
        //     Attribute can be applied to a parameter.
        Parameter = 2048,
        //
        // Summary:
        //     Attribute can be applied to a delegate.
        Delegate = 4096,
        //
        // Summary:
        //     Attribute can be applied to a return value.
        ReturnValue = 8192,
        //
        // Summary:
        //     Attribute can be applied to a generic parameter. Currently, this attribute can
        //     be applied only in C#, Microsoft intermediate language (MSIL), and emitted code.
        GenericParameter = 16384,
        //
        // Summary:
        //     Attribute can be applied to any application element.
        All = 32767
    }
}
```

**Comment by Mobrockers** [comment]
I see, that is unfortunate. Then currently we have no good way to ignore this specific mutation.

**Comment by rouke-broersma** [comment]
A feature has been merged to our v1 branch that will help you with this issue. You will be able to use it once we are ready to release v1. See: https://github.com/stryker-mutator/stryker-net/issues/1570
