### ISSUE TITLE
Add option to not mutate exception messages

### ISSUE THREAD

**Issue by DaveSenn** [stryker-mutator/stryker-net#1497]
**Is your feature request related to a problem? Please describe.**
Often exception messages are not used to change the behavior of any code (usually the exception type or additional properties on the exception type will be used for this). 
Changing a exception message does not fail our tests since we use the message only as meta information for the dev taking a look at a log.
I would like to have an option to not change exception messages.

**Describe the solution you'd like**
Add a new configuration option to not mutate exception messages. Maybe it could be an array of exception type not to mutate the messages of?

**Describe alternatives you've considered**
I have not found any alternatives.

**Additional context**

**Comment by Mobrockers** [comment]
Let's say someone removes all exception messages from your code base, would your team be happy about that? Would you be able to troubleshoot properly without the messages in the logs? If the answer is yes, why do you have the messages in the first place? It's still code you have to maintain, if it's not important it's better to cut it. 
If the answer is no, why would you not at least want to test that they have a message? They could have the completely wrong message leading a dev into troubleshooting the wrong problem. If you don't test for this, you cannot guard against this happening.

Exception messages are not used to change behavior of the code true, but they are in most cases an invaluable tool in debugging.

If we were to support this feature (and the other feature you requested) I would prefer a design that is universal and does not require a new option for every type of code to ignore. Could you perhaps give us a suggestion for a user friendly way we could provide this option if we decide to support this?

**Comment by DaveSenn** [comment]
Hi @Mobrockers 

Thank you for your answer. I see your point and I partially agree. 
But I think there are different scenarios. There are exception messages which are important because they are: visible to a user, the only information available to a dev to understand a bug, are being thrown in a library used by other devs… but there are also some exceptions for which the error message is not important. For example, the whole suit of Argument* exception. In most cases I never care about the message. I just look at the stack trace to see where it is coming from and the code will tell me the rest.

For the cases where we should have meaningful exception message, I prefer to trust the dev and reviewer to choose a good message. Having a test for these exception messages would be ideal. But in reality, we have limited resources and time, so we have to concentrate on the “really” important cases.

Here is an example very similar to something I found in productive code leading me to create this feature suggestion.

Code:
```
using System;

namespace MyNamespace
{
    public sealed class Example
    {
        public Int32 ConvertToNonUsStandard( DayOfWeek day ) =>
            day switch
            {
                DayOfWeek.Monday => 1,
                DayOfWeek.Tuesday => 2,
                DayOfWeek.Wednesday => 3,
                DayOfWeek.Thursday => 4,
                DayOfWeek.Friday => 5,
                DayOfWeek.Saturday => 6,
                DayOfWeek.Sunday => 7,
                _ => throw new ArgumentOutOfRangeException( nameof(day), day, $"Day '{day}' is not supported." )
            };
    }
}
```

Test:
```
using System;
using Xunit;

namespace MyNamespace.Test
{
    public sealed class ExampleTest
    {
        [Fact]
        public void ConvertToNonUsStandard()
        {
            var target = new Example();
            Assert.Equal( 1, target.ConvertToNonUsStandard( DayOfWeek.Monday ) );
            Assert.Equal( 2, target.ConvertToNonUsStandard( DayOfWeek.Tuesday ) );
            Assert.Equal( 3, target.ConvertToNonUsStandard( DayOfWeek.Wednesday ) );
            Assert.Equal( 4, target.ConvertToNonUsStandard( DayOfWeek.Thursday ) );
            Assert.Equal( 5, target.ConvertToNonUsStandard( DayOfWeek.Friday ) );
            Assert.Equal( 6, target.ConvertToNonUsStandard( DayOfWeek.Saturday ) );
            Assert.Equal( 7, target.ConvertToNonUsStandard( DayOfWeek.Sunday ) );
            Assert.Throws<ArgumentOutOfRangeException>( () => target.ConvertToNonUsStandard( (DayOfWeek) ( -1 ) ) );
        }
    }
}
```

I know there are better ways to do this conversion (Sunday or Monday as first day of week) but it is a very simple and convenient example. 
The message of the `ArgumentOutOfRangeException` is more or less meaningless. This might sound strange but even if I don’t care about the message, I like to specify a message instead of null just to make it clear to other devs (or future me) that I did not forget to specify a message.

I totally agree with you about a “generic” configuration for all cases being a better option. Since I don’t know much about this project (yet) or about mutation testing in general (I just found out that this is a thing – thanks reddit^^) I didn’t want to make a specific suggestion for a solution. 
But I could imagen something like a configuration per type where you could disable some mutations for this type could be an option.:

```
{
    "typeConfig": [
        {
            "type": "ArgumentOutOfRangeException",
            "ignore": [ "parameters" ]
        },
        {
            "type": "LoggingLib.Logger",
            "ignore": [ "returnValue" ]
        }
    ]
}

{
    "typeConfig": [
        {
            "type": "ArgumentOutOfRangeException",
            "methods": {
                "ctor": {
                    "ignore": [ "parameters" ]
                }
            }
        },
        {
            "type": "LoggingLib.Logger",
            "methods": {
                "Is*Enabled": {
                    "ignore": [ "returnValue" ]
                }
            }
        }
    ]
}
```

This is just some idea and a lot would have to be clarified and specified. 
-	Is it possible to ignore certain “parts” like input parameters or return values instead of the whole type/method
-	What can be ingored/excluded from mutation
-	Configuration per type only or per method of type
-	What about properties … treat get and set as method or invent something different?
-	Namesapce for types required
-	Should it be possible to configure overloads differently

**Comment by rouke-broersma** [comment]
We now have stryker comments to ignore specific code from mutation. We are not planning to introduce another config based ignore feature and feel that stryker comments should be sufficient. If you disagree please let us know.
