### ISSUE TITLE
Mutated assembly conflicts with code coverage analysis 

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#15]
After a mutationtestrun the mutated assembly stays in place. It is located in the test project `bin` folder. When code coverage is analysed with the mutated assembly in place this influcences the code coverage result.

This is due to the added if statements inside the mutated assembly. They are not hit (of course) during the code coverage analysis.

This could be resolved by removing the mutated assembly after Stryker is done. Stryker could replace it with the original assembly file to leave all files as they were before the run.

**Comment by Mobrockers** [comment]
We should define our own output directory for the mutated assemblies so that there can never be any unfortunate conflicts (such as if stryker crashes during run and cannot roll back the old file).

**Comment by Mobrockers** [comment]
We could fix this by simply running a compile and clean after the stryker testrun.

**Comment by Mobrockers** [comment]
We're not planning to spend time on this because the impact is so minimal.
