### ISSUE TITLE
Test-Run fails with "Internal error due to compile error" on generated code

### ISSUE THREAD

**Issue by pscheicher** [stryker-mutator/stryker-net#1504]
The generated code for a dto by an OpenApi-generator ("csharp-netcore") contains the following method:

```
/// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
```

This results in the following message for every dto in the project when running stryker.net:
```
Stryker.NET encountered an compile error in <file> with message: Cannot return a value from an iterator. Use the yield return statement to return a value, or yield break to end the iteration. (Source code: return default(
        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult>);)
[06:52:14 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
```
Stopping with
```
[08:58:44 FTL] Stryker.NET could not compile the project after mutation. This is probably an error for Stryker.NET and not your project. Please report this issue on github with the previous error message.
08:58:44 ERR] An error occurred during the mutation test run 


Internal error due to compile error.
```

**Comment by psfinaki** [comment]
#1413 - related?

**Comment by dupdob** [comment]
I don't think this is related to generated code. There is two issues here:
1) Stryker injects a `return default(type)` or `yield return default(type)` at the end of methods. It should have inject a `yield return` here. The decision is based on the (pre)existence of a `yield return` in the code. We did not think about having only `yield break`.
2) The rollback mechanism should have removed the injected `return default(type)` but it clearly failed to do so.

Both should be fixable and will be fixed. Until a fix is available, the best course of action is to ignore this file with Stryker options.

**Comment by dupdob** [comment]
opened a PR which contains (only) fixes for those 2 problem

**Comment by rouke-broersma** [comment]
The fix for this issue is being released shortly. Could you let us know if the fix works for your case?

**Comment by pscheicher** [comment]
This fix solves my problem.
Thank you
