### ISSUE TITLE
Subfolders are not created on AzureStorageFile

### ISSUE THREAD

**Issue by cmenzi** [stryker-mutator/stryker-net#1525]
**Describe the bug**
When specifying a subfolder in the azure-storage-url (https://storageaccountname.file.core.windows.net/azurefilesharename/my-project-key-01), then it results in an error creating the directories on storage.

I'm not sure if it a bug or a feature. Let me describe the use case we looking for.

We have several projects, which should upload their mutation test reports. As they are microservices or individual libraries, they are usually independent artifacts and have their own release cycle and also their own baselines.

**Azure Storage / Azure Files**
Azure File Storage Immutable Url: https://storageaccountname.file.core.windows.net
Azure File Share Name: azurefilesharename
Resulting URL: https://storageaccountname.file.core.windows.net/azurefilesharename

So, resulting URL is the base for all projects.

Every Project have a key like: `my-project-key-01`, ...

Resulting URL: https://storageaccountname.file.core.windows.net/azurefilesharename/my-project-key-01, ...

**Predefined  `_outputPath` directories from Stryker.NET**

OutputPath: `StrykerOutput/Baselines/<version>`
Parameter Version: 2.0.0-beta0001 

Resulting URL: https://storageaccountname.file.core.windows.net/azurefilesharename/my-project-key-01/StrykerOutput/Baselines/2.0.0-beta0001

I'm happy to contribute with PR again on this, if this is expected behavior.

**Logs**
```
[16:25:43 DBG] Could not locate the current branch name, using project version instead: 2.0.0-beta0270
[16:25:44 DBG] No baseline was found at https://xxx.file.core.windows.net/yyy/the-sub-folder/StrykerOutput/Baselines/dashboard-compare/2.0.0-beta0270/stryker-report.json
[16:25:44 DBG] Creating directories for file https://xxx.file.core.windows.net/yyy/the-sub-folder/StrykerOutput/Baselines/dashboard-compare/2.0.0-beta0270/stryker-report.json
[16:25:44 DBG] Creating directory https://xxx.file.core.windows.net/yyy/the-sub-folder/StrykerOutput/
[16:25:44 ERR] Creating directory failed with status Forbidden and message <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:ff76b1ea-401a-0066-0495-3300f5000000
Time:2021-04-17T14:25:44.3194645Z</Message><AuthenticationErrorDetail>sr is mandatory. Cannot be empty</AuthenticationErrorDetail></Error>
[16:25:44 INF] Time Elapsed 00:14:19.0889376
[16:25:44 INF] The final mutation score is 57.59 %
```

**Expected behavior**
1. All subfolders are created, if they not exists. 
2. Job should fail on unsuccessful upload

**Desktop (please complete the following information):**
 - OS: Windows / Linux
 - Type of project: Core
 - Framework Version: .NET SDK 5.0.202
 - Stryker Version: 0.22.3 (latest)

**Comment by rouke-broersma** [comment]
I suppose the docs are unclear. The subfolder must already exist, Stryker does not create it. Stryker only creates its own folders within the subfolder.

**Comment by cmenzi** [comment]
Ok, then the question is, if this have to stay like this? This is very cumbersome to create a Azure File Share upfront per project instead of creating just one.

We may can add the `IStrykerOptions.ProjectName` to the uri, so that it either results in:

Possible Azure File Storage URI:
- https://storageaccountname.file.core.windows.net/azurefilesharename (Must exists, as is)
- https://storageaccountname.file.core.windows.net/azurefilesharename/custom-sub-folder (Must exists upfront, as is)

And include the `IStrykerOptions.ProjectName`:
- Option a) `/{ProjectName}/StrykerOutput/Baselines/2.0.0-beta0001`
- Option b) `/StrykerOutput/{ProjectName}/Baselines/2.0.0-beta0001`
- Option c) `/StrykerOutput/Baselines/{ProjectName}/2.0.0-beta0001`

To retain backward functionality we could say, if `ProjectName` is null or empty, we skip this url part.

**Comment by rouke-broersma** [comment]
You won't have to create a whole new fileshare sorry it that wasn't clear. Only the subfolder needs to be created inside the fileshare.

I am fine with allowing the projectname to be used in the fileshare path. I think option a fits best as it would be comparable to the stryker dashboard reporter and baseline provider. I would say if the projectname does not exist use StrykerOutput, if it does exist leave out that part of the path.

`/{ProjectName|StrykerOutput}/Baselines/2.0.0-beta0001`

**Comment by cmenzi** [comment]
Ok, I will submit a PR.
