### ISSUE TITLE
Cannot inject mutation '{}' in '_collection' because we cannot find the original code.

### ISSUE THREAD

**Issue by marcin-golebiowski** [stryker-mutator/stryker-net#1527]
**Describe the bug**

Stryker.NET has a problem with mutating following code:

```
using System;
using System.Collections.Generic;
using System.Text;

namespace TestApp
{
    public static class ExampleExtension
    {
        private static string[] tabs = { "tab1", "tab2"};

        private List<string> _collection;

        public List<string> Collection
        {
            get => _collection;

            set
            {
                _collection = value;
            }
        }
    }
}
```

Message: 
    System.InvalidOperationException : Cannot inject mutation '{}' in '_collection' because we cannot find the original code.
  Stack Trace: 
    RoslynHelper.InjectMutation[T](T original, Mutation mutation) line 52
    <>c__DisplayClass1_0.<InjectMutations>b__0(Mutation toConvert) line 37
    <>c__DisplayClass1_0.<InjectMutations>b__2(Mutant m) line 44
    SelectEnumerableIterator`2.MoveNext()
    Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
    MutantPlacer.PlaceStatementControlledMutations(StatementSyntax original, IEnumerable`1 mutations) line 85
    AccessorSyntaxOrchestrator.InjectMutations(AccessorDeclarationSyntax sourceNode, SyntaxNode targetNode, MutationContext context) line 41
    NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) line 117
    CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) line 108
    <>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) line 93
    Replacer`1.Visit(SyntaxNode node)
    CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
    CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
    CSharpSyntaxRewriter.VisitAccessorList(AccessorListSyntax node)
    AccessorListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
    CSharpSyntaxRewriter.Visit(SyntaxNode node)
    Replacer`1.Visit(SyntaxNode node)
    SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
    NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) line 92
    NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) line 117
    CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) line 108
    <>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) line 93
    Replacer`1.Visit(SyntaxNode node)
    CSharpSyntaxRewriter.VisitPropertyDeclaration(PropertyDeclarationSyntax node)
    PropertyDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
    CSharpSyntaxRewriter.Visit(SyntaxNode node)
    Replacer`1.Visit(SyntaxNode node)
    SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
    NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) line 92
    NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) line 117
    CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) line 108
    <>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) line 93
    Replacer`1.Visit(SyntaxNode node)
    CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
    CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
    CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node)
    ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
    CSharpSyntaxRewriter.Visit(SyntaxNode node)
    Replacer`1.Visit(SyntaxNode node)
    SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
    NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) line 92
    NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) line 117
    CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) line 108
    <>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) line 93
    Replacer`1.Visit(SyntaxNode node)
    CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
    CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
    CSharpSyntaxRewriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
    NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
    CSharpSyntaxRewriter.Visit(SyntaxNode node)
    Replacer`1.Visit(SyntaxNode node)
    SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
    NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) line 92
    NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) line 117
    CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) line 108
    <>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) line 93
    Replacer`1.Visit(SyntaxNode node)
    CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
    CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
    CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
    CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
    CSharpSyntaxRewriter.Visit(SyntaxNode node)
    Replacer`1.Visit(SyntaxNode node)
    SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
    SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
    NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) line 92
    NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) line 117
    CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) line 108
    CsharpMutantOrchestrator.Mutate(SyntaxNode input) line 82
    MutantOrchestratorTests.MutationFails() line 49

**Expected behavior**
No exception.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Type of project: Stryker.Code.UnitTest
 - Framework Version .NET 5.0
 - Stryker Version:  v.1.0  branch

**Comment by dupdob** [comment]
I can reproduce the issue on master too. I am analyzing this.

**Comment by dupdob** [comment]
This is again an issue of mutation 'spillage', i.e Stryker generates an array initializer mutation (that need to be controlled by an `If` statement) that ends up in the next method/accessor. And then it fails since the mutation can no longer be injected.
