### ISSUE TITLE
Stryker Does Not Honour Static Analysis

### ISSUE THREAD

**Issue by MelbourneDeveloper** [stryker-mutator/stryker-net#1534]
**Describe the bug**
Static analysis disallows the mutation, but Stryker ignores this.

**Expected behavior**
Stryker should not add mutations that don't compile due to static analysis via Roslyn code rules

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project .NET Core
 - Framework Version 5
 - Stryker Version  0.22.3 (beta)

**Additional context**

Here is the mutation:
![image](https://user-images.githubusercontent.com/16697547/115982847-5eb3d300-a5e1-11eb-9027-28652d8a3fae.png)

But, I cannot compile this because of Roslyn's code rules. Roslyn should have squashed the mutation. But, it seems as though Stryker is not honouring the rules.

![image](https://user-images.githubusercontent.com/16697547/115982881-85720980-a5e1-11eb-9760-f05d854eac2d.png)

You can recreate the issue with this repo:
https://github.com/MelbourneDeveloper/RestClient.Net/tree/5/develop

Commit: 4c14356e80906b8017e06c422db814109635dd6d

You can run the batch files in src\RestClient.Net.UnitTests\

**Comment by rouke-broersma** [comment]
To implement analysers we need to figure out how msbuild passes them to roslyn and recreate this. Seeing as analysers are simple csharp classes or dlls I think we can just pass them straight into the compilation either as syntax yree or as assembly reference. Hopefully the analysers are exposed as msbuild properties in which case buildalyzer can probably pass them to us.

**Comment by MelbourneDeveloper** [comment]
@rouke-broersma it seems odd that you would need to do anything at all. If you depend on Roslyn for compilation, it should fail when code rules are violated. The important thing is the analysers Nuget package.

**Comment by MelbourneDeveloper** [comment]
Philosophical point: 

What is the point of mutation testing? 

It's to eliminate the possibility of  potential code entering the system that would destroy the fundamental correctness of the system. 

Static analysis has the same end goal but achieves it through a different means. It reduces possible code paths where it is clear that the system will behave incorrectly. 

For example, static analysis can determine if there is code without a null check. If static analysis catches this, there is no need for mutations because static analysis already prevents them.

**Comment by rouke-broersma** [comment]
I agree that so long as the rule is active and causes compilation errors that mutation testing does not need to point out the possible mutations as well.

**Comment by rouke-broersma** [comment]
> @rouke-broersma it seems odd that you would need to do anything at all. If you depend on Roslyn for compilation, it should fail when code rules are violated. The important thing is the analysers Nuget package.

It's not so much that we depend on Roslyn, but we use the Roslyn SDK directly from code. This means we replace MSBuild as project manager and that also means that any transformations MSBuild performs before handoff to Roslyn need to be performed in stryker as well. 
Since MSBuild is proprietary and MSBuild internal logic is mostly trial-by-error and information in old thick books that my generation is no longer forced to read we have to reverse-engineer a lot of MSBuild logic 😅

**Comment by dupdob** [comment]
By the way, looking into this issue, I just ran into this: MSBuildWorkspace
https://gist.github.com/DustinCampbell/32cd69d04ea1c08a16ae5c4cd21dd3a3

The text hints it should be easy to achieve (but still no clue on how), but at works, `MSBuildWorkSpace` could be an interesting options to increase Stryker compatibility with project with custom build steps.

**Comment by rouke-broersma** [comment]
Last time we looked into msbuild workspace it did not work on dotnet core which is why we don't use it. Perhaps these days it works on core.

**Comment by dupdob** [comment]
Just did a quick repro: it turns out that Buildalyzer lists analyzers separately, i.e. they are not in the 'AssemblyReferences' list.

**Comment by rouke-broersma** [comment]
> Just did a quick repro: it turns out that Buildalyzer lists analyzers separately, i.e. they are not in the 'AssemblyReferences' list. 

I expected as much

**Comment by MelbourneDeveloper** [comment]
Here is another scenario:

![image](https://user-images.githubusercontent.com/16697547/116759640-2899a780-aa56-11eb-8ce5-9878b5b13465.png)

FirstOrDefault is not valid because it could return null and nullable reference types are turned on.

![image](https://user-images.githubusercontent.com/16697547/116759687-47983980-aa56-11eb-83ed-125c4c183193.png)

**Comment by MelbourneDeveloper** [comment]
The whole nullable reference types ecosystem depends on static analysis to work. If you take away static analysis, you are left with buggy code.

**Comment by rouke-broersma** [comment]
> The whole nullable reference types ecosystem depends on static analysis to work. If you take away static analysis, you are left with buggy code.

Nullable reference types are not roslyn analyzer rules, they're their own compiler feature. They also don't generate errors by default. We already enable Nullable reference types during the compilation but it could be we need to extract your warnings as errors rules to be able to use them during mutation testing.

**Comment by GrahamTheCoder** [comment]
> Last time we looked into msbuild workspace it did not work on dotnet core which is why we don't use it. Perhaps these days it works on core.

It does work for both, but iirc you can't build a framework assembly from a core process. I ended up with two exes, the core one delegates to the framework one when needed. Then there's a bit of assembly binding faff too. This might be a good starter:
https://github.com/icsharpcode/CodeConverter/blob/1817d3a504dbd04c0bb63b225d1aa3dbb1c2bb96/CommandLine/CodeConv.Shared/MSBuildWorkspaceConverter.cs#L115

Here's the PR where I implemented using MSBuildWorkspace for a similar shape project
https://github.com/icsharpcode/CodeConverter/pull/556

**Comment by dupdob** [comment]
@MelbourneDeveloper : could you check with the latest version please ? we have improved support for analyzers and this issue may be resolved.

**Comment by dupdob** [comment]
The needed feature (analyzer support) has been implemented. I close this issue for now. Feel free to reopen it if this is still a problem with latest versions (>1.5)
