### ISSUE TITLE
Options to include or exclude LinqExpressions on LinqMutator

### ISSUE THREAD

**Issue by leonardosimoura** [stryker-mutator/stryker-net#1546]
**Is your feature request related to a problem? Please describe.**
Options to include or exclude LinqExpressions on LinqMutator. Ex. Not run FirstOrDefault mutations

**Describe the solution you'd like**
A additional parameter to configure

**Describe alternatives you've considered**
I tried the mutate example !MyFolder/MyService.cs{10..100} but it ignore logic inside some linq methods ( example ( First(f => f.Amount > 10)  where f.Amount > 10 is ignored to

**Additional context**
I trying to run stryker againt a big project and if we can choose when to enabled some of linq mutations will help us to focus on the core logic.

**Comment by richardwerkman** [comment]
I'm curious why you want to exclude FirstOrDefault mutations. If you think the mutation is irrelevant we could make this issue about that. It is a very hard mutation to kill so I do understand your issue with it.

I was thinking about moving that mutation to a higher mutation level. So that some linq mutations will be turned on by default and some only if you increase the mutation level.

**Comment by leonardosimoura** [comment]
The ideia is just disable them temporarily so is possible to focus on other mutations first.
Think in a project with half of its mutations as Linq mutations, but for the bussiness team  the most impotant mutations are others mutations and only a few linq mutations.

Sorry but i made the PR #1660  before read this,
I like the ideia to filter the expressions based on mutation level.
I created a ExcludeLinqExpressionFilter is possible to use it to apply some rules
What you think about something like:
**Basic:** Any, Count,
**Standard:**  Min, Max, Sum, Average,
**Advanced:**  OrderBy, OrderByDescending, FirstOrDefault, First, SingleOrDefault, Single, Last, All, Skip, Take, SkipWhile, TakeWhile, ThenBy, ThenByDescending,
**Complete:** All Expressions

**Comment by richardwerkman** [comment]
What about?
Basic: Any, Count, All
Standard: Min, Max, Sum, Average, OrderBy, OrderByDescending, First, Single, Last,
Advanced: Skip, Take, SkipWhile, TakeWhile, ThenBy, ThenByDescending,
Complete: All Expressions

I think order of items is very important to test. So it should be enabled standard. This means OrderBy but also First and Last as they are ordering as well. But they won't be mutated to FirstOrDefault. We can do that in complete.

**Comment by rouke-broersma** [comment]
Perhaps this should be a separate issue

**Comment by leonardosimoura** [comment]
I agree,  i will create a new one soo we can focus only in the expressions filter here
