### ISSUE TITLE
Mutant Survives Even When Tests Fail

### ISSUE THREAD

**Issue by MelbourneDeveloper** [stryker-mutator/stryker-net#1548]
**Describe the bug**
Stryker is saying that a mutant is surviving but when I use the mutant locally, the test fails

**Expected behavior**
Mutant does not survive

**Desktop (please complete the following information):**
 - OS: Windows
 - Framework Version: 5
 - Stryker Version : 22.3 (Beta)

**Additional context**
Stryker picks up this mutation in complete mode:

![image](https://user-images.githubusercontent.com/16697547/116761857-115db880-aa5c-11eb-9583-d77047b34b33.png)

But, this test should squash the mutant:

![image](https://user-images.githubusercontent.com/16697547/116761906-305c4a80-aa5c-11eb-89eb-dc377f5f1e4d.png)

And does so when I manually set the mutant locally:

![image](https://user-images.githubusercontent.com/16697547/116761944-4a962880-aa5c-11eb-9759-0facc7a22e6c.png)

![image](https://user-images.githubusercontent.com/16697547/116762032-8e892d80-aa5c-11eb-8ec4-ea0e17d06f03.png)

You can see the code here and reproduce the issue with this commit:

https://github.com/MelbourneDeveloper/Urls/blob/31b239f8a8535fc6cc323b3088ce3a4265a997cb/src/Uris/UserInfo.cs#L11

**Comment by dupdob** [comment]
Thanks for this report. This is a problem linked to `static` values and coverage. Code coverage cannot identify relevant tests for those, that's why Stryker marks related mutants as to be tested against all tests.
We forgot to cover for static properties' default initializer.

**Comment by dupdob** [comment]
updated my PR (#1539) to implement a fix for this

**Comment by MelbourneDeveloper** [comment]
@dupdob awesome. I think that Urls will be able to score 100% on Complete after this fix.

**Comment by dupdob** [comment]
A couple of remarks:
1. As a workaround, you can turn `Empty` into a static [readonly] field, it will work as expected
1. In general, static values can lead to false positive (i.e. undue survivors) as they may introduce coupling across tests. Cache typically can be problematic.

**Comment by MelbourneDeveloper** [comment]
All the Empty properties are read only static variables from what I can tell

**Comment by MelbourneDeveloper** [comment]
@rouke-broersma did this get fixed?

**Comment by rouke-broersma** [comment]
Yes, however the fix has not yet been released. I'll try to do that soon (but not tonight).

**Comment by MelbourneDeveloper** [comment]
Awesome! Will keep an eye out for the release
