### ISSUE TITLE
release 0.2.0 breaks on writing the mutated assembly to disk

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#155]
Stryker breaks on writing the mutated assemby to disk.

https://github.com/stryker-mutator/stryker-net/blob/a1bbda45673caad85295ada4a7699e22e2712f5f/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs#L76

This line was added just before the 0.2.0 release. It creates the folder the `.dll` file should be written to. To fix this, first should be checked if the folder doesn't exist first. Or we could skip the creation of the folder completely since it should always exist. I'm not sure yet, but this should be fixed quickly.

**Comment by simondel** [comment]
Thanks for opening the issue @richardwerkman and thanks for fixing it @KonH! I expect a folder creation to not fail if it already exists and I expect the creation to also not fail if I pass a path to a file, since it can simply take the directory path from that file and use it.

**Comment by nicojs** [comment]
Awesome it got fixed so quickly! Can we add an integration test for this?

**Comment by simondel** [comment]
Yes (there are no integration tests right now)

**Comment by nicojs** [comment]
Nevermind, I see there is #156 for that.
