### ISSUE TITLE
Enable reproducible builds

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1556]
> I guess we'll have to enable sourcelink for Stryker 😝

Yeah, it's basically as simple as adding this package reference:
```xml
<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="all" />
```

_Originally posted by @0xced in https://github.com/stryker-mutator/stryker-net/issues/1532#issuecomment-834815548_

**Comment by 0xced** [comment]
Even better, use [DotNet.ReproducibleBuilds](https://www.nuget.org/packages/DotNet.ReproducibleBuilds/)
```xml
<PackageReference Include="DotNet.ReproducibleBuilds" Version="0.1.26" PrivateAssets="all" />
```

> This package sets the following properties:
> - `PublishRepositoryUrl` = `true`
> - `EmbedUntrackedSources` = `true`
> - `DebugType` = `embedded`. You can specify `portable` in your project if you prefer, but you'll need to upload that `.snupkg` file too.
> - `IncludePackageReferencesDuringMarkupCompilation` = `true` (enables a fix for WPF)
> - `ContinuousIntegrationBuild` = `true` on CI systems

> It also adds SourceLink dependencies for all repo types (the right one will be used automatically).

**Comment by rouke-broersma** [comment]
Hi @0xced I was looking to implement this in stryker and found the package [DotNet.ReproducibleBuilds.Isolated](https://github.com/dotnet/reproducible-builds#dotnetreproduciblebuildsisolated-documentation-and-nuget-package).

The documentation is kinda sparce so I was wondering if you had any more insights into if this would be useful to us on top of `DotNet.ReproducibleBuilds`
