### ISSUE TITLE
Generate filled stryker config file with cli command

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1558]
**Is your feature request related to a problem? Please describe.**
I would be nice if stryker can generate a complete stryker config file with all defaults filled in.

**Describe the solution you'd like**
`dotnet stryker init` generates a config file with all defaults. No stryker run is started.
If a stryker config already exists, it is overwritten.

**Comment by richardwerkman** [comment]
I'd like to debate the overwriting of a config file. Maybe with a confirmation?

Also I'd like to add that any options that are passed trough the CLI could also be filled in the config file already. This is however less trivial than it seems as we don't have a direct mapping in code between the CLI and JSON config names

**Comment by ysbakker** [comment]
> I'd like to debate the overwriting of a config file. Maybe with a confirmation?

There could be a `--force` option that overwrites the existing config file, if it exists in that location?
I'd suggest that by default, the existing config file is not overwritten. 

> Also I'd like to add that any options that are passed trough the CLI could also be filled in the config file already. This is however less trivial than it seems as we don't have a direct mapping in code between the CLI and JSON config names

Seems very user-friendly, if you already have a working stryker command. Maybe I can implement a basic version of the `init` command first, and iterate on this so it allows this?
