### ISSUE TITLE
Happy flow tests

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#156]
We should add a integration test project that checks the happy flow of Stryker. This will prevent broken releases like 0.2.0. 

For instance it could create an instance of `StrykerCLI` and run it on a small example project. The exit code of stryker should be correct. Maybe we could also test more, like expected output or mutationscore. 

Anyone with experience writing these kind of tests that can give some advise on how to set this up?

**Comment by simondel** [comment]
@richardwerkman @Mobrockers The integration test takes 30 minutes. Running the project itself in a regular scenario is a lot faster:
https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=415&_a=summary&view=logs
