### ISSUE TITLE
Support for mutating calls to `System.Linq.Expressions.Expression`

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [stryker-mutator/stryker-net#1561]
**Is your feature request related to a problem? Please describe.**

I have this use case in which a string containing a logical expression is parsed and a lambda expression created and compiled. This enables running arbitrary DSLs with little overhead (comparing to modeling the whole syntax tree in handcrafted objects).

For instance: The string `1 = 1` would be created using

```
var expression = Expression.Equal(
  Expression.Constant(1),
  Expression.Constant(1)
)
```

So I want to create mutations to test my test suite, but since I'm not using the equality operator directly, an opportunity for a mutation is missed. In this scenario I would expect `Expression.Equal` to be mutated to `Expression.NotEqual`.

**Describe the solution you'd like**

I'd like the mutations currently in place to also be available for `System.Linq.Expressions.Expression` calls. For instance:

`Expression.Equal` can be replaced with `Expression.NotEqual`
`Expression.GreaterThan` can be replaced with `Expression.GreaterThanOrEqual` and `Expression.LesserThan`

The number of possibilities is endless.
https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression?view=net-5.0

**Describe alternatives you've considered**

- Changing the code to not use Linq expressions would solve some my testing problems, but would introduce an additional overhead I'm not comfortable with.
- Eventually if you think this feature is too niche maybe having a plugin system so that one can create custom Murators would be nice.

**Additional context**

I'm willing to lend a hand if you think this feature brings enough value.

**Comment by richardwerkman** [comment]
For most projects this would not do much as most projects won't use Expression. So I'd say we would not want this is Stryker. 

But I like your idea about custom mutators. Would you be able to create a seperate issue for that? Than we can discuss how that would work there.

In general we could just look at a specific assembly and look for classes that implement the `IMutator` interface. The difficult part would be how to know where to look for the assembly. As you would probably not want the mutator assembly as a part of your project.

**Comment by TiagoOliveiraMarques** [comment]
Opened a new issue for custom mutators feature. Closing this issue.
