### ISSUE TITLE
Stryker doesn't ignore methods if they are not called on an object

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1576]
**Describe the bug**
Practically, that means that `Dispose` cannot be ignored, and this is how I discovered the problem. 
But then I started to play around with this and it looks like whatever method a class has, it won't be ignored if needed.

That is, in case I have `DoSomething` among ignored methods:
`someObject.DoSomething()` will be ignored
`DoSomething()` won't be ignored

**Expected behavior**
These methods are ignored, just like others are.

**Desktop (please complete the following information):**
 - OS: Windows
 - Stryker Version: beta 0.22.4

**Additional context**
This probably used to work as `Dispose` is mentioned in [this issue](https://github.com/stryker-mutator/stryker-net/issues/1377) which is resolved. Although it's there among many other things, I don't know if `Dispose` in particular was verified.

**Comment by richardwerkman** [comment]
Hmm thats weird. Those statements are both of type `InvocationExpression`. So I'd expect it to work on both. I'll look into this.

**Comment by richardwerkman** [comment]
I found the issue! Should be fixed in our next release 👍

**Comment by psfinaki** [comment]
Amazing, thanks!

**Comment by psfinaki** [comment]
That's still not released, right?

**Comment by rouke-broersma** [comment]
Not yet. When it's released we will remove the fixed in master label.

**Comment by psfinaki** [comment]
Aaaand so when can we expect the release? :) 
I thought releases happened after every reasonable merge so just want to clarify this or maybe help with something.

**Comment by richardwerkman** [comment]
Usually we wait a few weeks to save up some features/bugs to all release at once. To prevent having releases every week. But at the moment we have two bug fixes on master so it's indeed a good idea to do a release. We will do one today!

**Comment by psfinaki** [comment]
Amazing, thanks!

**Comment by psfinaki** [comment]
Don't want to be "that guy" but... any ideas when this can actually happen?

**Comment by rouke-broersma** [comment]
@richardwerkman keep your promises man ;)

**Comment by richardwerkman** [comment]
@psfinaki Please be "that guy" since I apparently need that... Sorry I forgot! I've just done the release, a new version should appear within minutes on nuget 👍

**Comment by psfinaki** [comment]
Oh thanks! I saw failing builds and thought it's very hard to release right now so I was too shy to remind last week :D

**Comment by rouke-broersma** [comment]
@psfinaki The failing builds are due to our CI infra being flaky unfortunately. Nothing serious to worry about.
