### ISSUE TITLE
Describe release procedure

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-net#158]
So far, I have been the only one doing releases using Azure Pipelines and GitHub releases/tags.

I have to describe this process to ensure others can do it as well. This procedure may change in the future as we automate the process further.

**Comment by richardwerkman** [comment]
Will we start working with a release branch? Or still from master?

**Comment by simondel** [comment]
I don't see the benefit of using a release branch for this right now. For strykerJS we use it to signal that we want a release.
