### ISSUE TITLE
Mutator idea: string.IsNullOrEmpty

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1581]
**Is your feature request related to a problem? Please describe.**
When using string.IsNullOrEmpty most of the times only null is tested. 

**Describe the solution you'd like**
If we mutate `string.IsNullOrEmpty(x)` into `(x != null)` and `(x != string.Empty)` it's clear both are tested.

**Comment by peterpim** [comment]
Testcomment
