### ISSUE TITLE
Coverage analysis filter overwrites Ignored mutant statuses while it should ignore them

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1586]
**Describe the bug**
Let's say I have a project with two identical classes (attached to this ticket). 
Initially (_initial commit, hash d242de36_) I have poor test coverage:

`dotnet stryker`
![image](https://user-images.githubusercontent.com/5451366/121179575-31a14400-c860-11eb-9759-64d15d56b1c2.png)

This makes me sad, so I do some refactoring and add a bunch of tests for the first class (_added some tests, hash b71bedf0_). Now I have better score:

`dotnet stryker`
![image](https://user-images.githubusercontent.com/5451366/121181025-db350500-c861-11eb-8d1f-f34168ad012a.png)

Numbers make sense. But when I run Stryker in diff mode against _initial commit_ (in reality, that's in PRs), the stats are odd:

` dotnet stryker -diff -gdt d242de36580bc0e13f8ba3bd00065fb8e2ef0ca6`
![image](https://user-images.githubusercontent.com/5451366/121180389-18e55e00-c861-11eb-8529-bd8868ebd55b.png)

**Expected behavior**
There are a few things wrong:
1) Ideally, I wouldn't want to see `Class2.cs` here at all, because it was not touched since diff target and Stryker apparently somehow takes this into account, _ignoring_ some mutants in that class (and therefore making 0 score there). 
2) Even if that must be there, where does the number 66.67 come from? AFAIU it should be 100% there, but I would understand 50% (incorrect but at least clearly 4/8 = 50%).

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .NET Core
 - Framework Version: 5
 - Stryker Version: beta 0.22.4

**Additional context**
The code: [StrykerDiff.zip](https://github.com/stryker-mutator/stryker-net/files/6616253/StrykerDiff.zip)

**Comment by psfinaki** [comment]
Knock-knock :)

**Comment by rouke-broersma** [comment]
Hi @psfinaki 

2 Mutants were ignored so they are not taken into account for the mutation score calculation. So your score is 4/6 not 4/8. I can see how this is confusing seeing the number 6 (total tested mutants) is not mentioned anywhere.

**Comment by psfinaki** [comment]
Alright, thanks for reaching back. Okay, so I understood the theory correctly :)

**Comment by mcastror-prft** [comment]
Hello Guys, Is there any update on this one?. I have added stryker as a step in a project's pipeline so I have to use the file diff feature due to step execution time limit restrictions. It looks like I'm experiencing the same issue, the score is messed up. I think it calculated correctly when I turned off coverage analysis but then it took longer so didn't work for me.

**Comment by dupdob** [comment]
I have opened a PR with a probable fix for this, but it made us that it may need a bit of redesign to ensure correct results.

**Comment by psfinaki** [comment]
A bit late to the party, but just wanted to confirm that this all works for me as I would imagine. Thanks!
