### ISSUE TITLE
Errorhandling

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#16]
Right now there are 2 kinds of custom exceptions, both inherrit from StrykerException. I initially thought there would be much more kinds of exceptions, but it turned out this is not the case.

I would like to see one kind of custom exception, for example `UserException` or `InputException`. It should contain a message that clearly explains to the user what they did wrong and how they can invoke Stryker.NET right next time. Everything that the user can fix themselves should be shown to them using this kind of exception.

- Initital testrun failed
- Initial build failed
- Arguments wrong
- 2 project references found

I would like to see that the user sees no stacktrace in this case, only a clear message about what they did wrong and how they can improve. A stacktrace could give wrong impressions to users, as they think Stryker.NET is broken.

I suggest the following:

- The Core project will handle all exceptions by logging them (except the custom exceptions)
- The CLI project will handle the custom exceptions without a stacktrace

**Comment by joostas** [comment]
I will try on this.
