### ISSUE TITLE
Stryker Output Is Difficult to Read Due to Color Choices

### ISSUE THREAD

**Issue by JasonBock** [stryker-mutator/stryker-net#1602]
**Is your feature request related to a problem? Please describe.**
It's not a big problem per-se, just something to hopefully make it easier to read output.

**Describe the solution you'd like**
When I run Stryker from the command line, this is what I see:
![image](https://user-images.githubusercontent.com/904213/122815701-6cad6980-d29b-11eb-9700-f204af8f43c3.png)
The output is really hard for me to read for the `INF` messages.

**Comment by richardwerkman** [comment]
We use serilog for those messages. I don't know if we have any influence over the colour it's printed in... To fix this a change in serilog sourcecode might be needed. You could try to create an issue there too? Maybe link to this repo as an example of how we use it.

**Comment by JasonBock** [comment]
Interesting, my original screen shot came from VS2022 Preview 1. In 2019 it looks much better:
![image](https://user-images.githubusercontent.com/904213/122971007-29fb9800-d354-11eb-9f63-018babec3730.png)

**Comment by jafin** [comment]
Seems more of an issue with VS2022  https://developercommunity.visualstudio.com/t/terminal-colors-are-wrong/1454753

**Comment by rouke-broersma** [comment]
@JasonBock would appreciate if you could let us know if this is fixed when vs2022 releases. For now I would like to close this as vs2022 is in preview and a bug report has been filed with their team. If this ends up being a permanent problem we should reopen.
