### ISSUE TITLE
Add Summary Value in the Report

### ISSUE THREAD

**Issue by JasonBock** [stryker-mutator/stryker-net#1603]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a feature request

**Describe the solution you'd like**
When Stryker is done, I see this in the report:
![image](https://user-images.githubusercontent.com/904213/122815961-c0b84e00-d29b-11eb-8afe-f8bad79697c6.png)
It would be nice to see a summary percentage/row somewhere in the report. That way I can quickly see if the changes I made have any effect from a previous run.

**Comment by rouke-broersma** [comment]
Hi @JasonBock 

The 'All files' row has the total mutation score in the next column. Is your suggestion different from that summary?

**Comment by JasonBock** [comment]
Ah, got it. I didn't realize that's what the row is for :)
