### ISSUE TITLE
CompilerError Mutates Code Incorrectly for Reverse() Call

### ISSUE THREAD

**Issue by JasonBock** [stryker-mutator/stryker-net#1604]
**Describe the bug**
When I run Stryker against my project with a method called `Reverse()`, I get a compiler error. The code can be found [here](https://github.com/JasonBock/SpackleNet/blob/main/Spackle/Extensions/RangeExtensions.cs#L136). This is not the LINQ `Reverse()` method, so this shouldn't be changed.

**Expected behavior**
Stryker runs without causing a Compiler Error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .NET 5.0
 - Stryker Version: 0.22.4

**Comment by rouke-broersma** [comment]
Hi @JasonBock

Does this crash Stryker or are we able to recover safely and remove the faulty mutation?

**Comment by JasonBock** [comment]
Sorry, I should've been clearer with this one (and the other issue I reported on a compiler error). Stryker recovers safely so that's good.

**Comment by rouke-broersma** [comment]
In that case unfortunately there's not a lot we can do about this at the moment. We should probably not log a warning for this specific mutation since we are aware of it.

#1400
