### ISSUE TITLE
Clean up sonarqube issues

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1607]
**Describe the bug**
We've let our code quality slip

**Logs**
https://github.com/stryker-mutator/stryker-net/runs/2882596005

**Expected behavior**
Clean it all up

**Comment by dupdob** [comment]
I had a quicklook, and at least one bug refers to code that is no longer in V1. Should not we focus on the V1 branch and disregard `master` from no on?

**Comment by rouke-broersma** [comment]
We should probably pick this up after merging V1 for sure, I just noticed it now and made an issue to not forget. I don't think we need to pick this up right this second.

**Comment by dupdob** [comment]
I had a look because I was worried it was linked to my last two PRs. 😄

**Comment by rouke-broersma** [comment]
Nah :)

**Comment by Christian-Oleson** [comment]
These issues, are there any order y'all want to prioritize these? Do you want to fix them one by one? All in the same PR? Separate PRs for issue type?

**Comment by rouke-broersma** [comment]
If you see any quick-wins feel free to contribute them in one PR. If they are larger fixes or if the fixes could have unintended side effects I would leave them for us to take a look at before you try to solve them so that you're not wasting your time if we decide we do not want to touch it at this time. This issue is not really meant to be picked up by outside contributors but nevertheless I welcome the help!
