### ISSUE TITLE
Class-level exclusions and mutation options 

### ISSUE THREAD

**Issue by pinkfloydx33** [stryker-mutator/stryker-net#1647]
**Is your feature request related to a problem? Please describe.**
We have a set of helper functions in an library we reference related to argument validation, each which takes an optional message that will eventually become the exception message. It's quite frustrating that Stryker marks the strings as survived mutants as we don't check the messages in our tests (and it would be an undertaking to do so) 

```csharp
Requires.NotNull(arg1, nameof(arg1), "optional message");
Requires.Argument(arg2 > 0, nameof(arg2), "optional message");
Requires.Range(arg3, 0, 5, nameof(arg3), inclusive: true, "optional msg");
```

These methods exist in pretty much all of our public (and some internal) API so it's lot of noise to have to deal with. 

**Describe the solution you'd like**
Ideally I'd like a way to exclude an entire class (rather than just the  method names) since in this case the majority of checks are null tests. 

Another option would be a way to tweak mutations at the class/method level (ie. don't apply string mutations). As you can see in the examples above, I don't really care about the string mutations but If I could, I'd probably want to keep the `<` mutation on the `Argument` method and the `false` mutation on the `Range` method... but really I'd settle (sigh) for excluding the entire class altogether if only to remove the noise of the string mutants. 

**Describe alternatives you've considered**
The class in question only has a handful of methods, so I could just list them out in the config file, but I'd have to do so for every project. If I add new methods I'd have to make sure to update everything. The names are fairly generic in some cases (we have an `IsDefined` for enums) so there's still some chance of some conflicts using method name only. 

Another option would be to disable string mutations altogether. We've not explored that option yet, but based on what we've been seeing so far this *may* be a viable alternative.

**Comment by psfinaki** [comment]
Well from what I understand that's pretty much what I raised [here](https://github.com/stryker-mutator/stryker-net/issues/1630) and what was then addressed and merged [here](https://github.com/stryker-mutator/stryker-net/pull/1635).

We just need to get this released and then you should be able to specify "Requires.*" in the ignored methods list!

@rouke-broersma can we expect 0.22.9 anytime soon? :)

**Comment by rouke-broersma** [comment]
I'll trigger the release

**Comment by rouke-broersma** [comment]
@pinkfloydx33 Do you think the solution from #1635 is sufficient to solve your problem?

**Comment by pinkfloydx33** [comment]
Yes it does. And my apologies I looked through all the open/closed issues prior to posting. I'm not sure how I missed that.

**Comment by rouke-broersma** [comment]
Not a problem. The update has been released.

**Comment by psfinaki** [comment]
@rouke-broersma just saying that I didn't want to sound annoying with that, it was just a question :) Thanks for release though!

**Comment by rouke-broersma** [comment]
@psfinaki I don't mind when you ask for a release and it's not a lot of effort. It's more that historically we haven't released every commit unless it had been some time in between or there is a specific need such as in this case. So I often forget to release 🤷‍♂️. I'm happy you remind us to release stuff no worries.

**Comment by psfinaki** [comment]
Alright, thanks for calming me down :)

**Comment by pinkfloydx33** [comment]
Should a filter like `*Something.*` work? I can't tell based on looking at the tests. 

I have multiple classes called `AbcSomething`, `DefSomething` and `XyzSomething` of which I want to exclude all methods. I added a `*Something.*` method exclusion but it doesn't seem to be taking hold. 

Of note is that they all inherit from an abstract class `SomethingBase` (which doesn't match that pattern) and the members invoked are either virtual/abstract or defined on the base class only. Sometimes my reference is of the base type, others of the concrete type. I tried `*Something*.*` and that didn't seem to work either. 

If it's not covered that's fine as I can just exclude them individually, but I wanted to make sure I wasn't missing something.

**Comment by rouke-broersma** [comment]
I tested your regex and I think the issue is that you need to escape your *. 

See: https://regex101.com/r/MxUDN7/1

I am not sure if it's intentional that you should have to escape your * with `\\` but as you can see once you do that the `\\*` gets replaced with `[^.]*` and there will be a match. @grbell-ms or @psfinaki can you confirm that this is intentional? Perhaps we should document this behavior. Note: I am not very familiar with Regex.

**Comment by pinkfloydx33** [comment]
Are these values supposed to be *actual* regexes though? The source code does a `Regex.Escape` on the value and then does some tinkering to ensure  `*` is interpreted as `[^.]*` (anything except a period any number of times). My leading asterisk should already be covered since Regex.Escape turns an asterisk into `\*` (the double slash is just escaping the slash itself within the c# string, it doesn't actually exist that way... though you'd need the same in json). `Regex.Escape` would turn `\*` into `\\\*` the last two characters of which would get replaced and then you'd have a regex expecting a literal slash in it (and a bug) 

Currently, my leading `*` becomes something like this:

`^(?:[^.]*\.)*[^.]*`

I'm _pretty sure_ that it's going to get consumed greedily depending on the other parts of the method name and prevent matches depending on what those names look like.

The transform on user input should likely have the nongreedy `*?` quantifier, depending on what the actual rules are here (since asterisk can never represent a period you obviously have some rules to how all this should work, so the actual semantics aren't for me to decide). Maybe even on the overall non-capturing group, which should at the very least use a `+` and not a `*` on the *inner* value (since you can't have two dots in a row) which would also be more performant. 

Maybe:
`^(?:[^.]+\.)*[^.]*?`
Or
`^(?:[^.]+\.)*?[^.]*?`

But I don't understand how or why escaping the asterisk as you demonstrate even works, based on the existing code.

**Comment by rouke-broersma** [comment]
Oh I completely skipped over the regex escape.. Like I said I'm not very used to working with regex. If you feel this is a bug or you think this is something we should support please open a new bug or feature request with the improvements you would like!

**Comment by pinkfloydx33** [comment]
I think whatever rules are in place are OK, no sense making it overly complicated. I just don't know what those rules are supposed to technically be and I'm still confused as to why my leading star doesn't work. If it's not meant to, that's fine. But if it _is_ then I'd say it's a bug which is why I asked for clarification about it.

**Comment by psfinaki** [comment]
Ha I wonder if there is anyone good at RegEx apart from people who actually create RegEx engines :D In this case I guess only @grbell-ms and @thegod can help. 

I was testing only things like Something* (not *Something), because that was the usecase. However looking at the tests *Something should kind of work as well I think... In either case we should adjust either the code or the regex comment + tests.

**Comment by pinkfloydx33** [comment]
@rouke-broersma @grbell-ms 

So I found myself circled back to this issue and I'm hoping to get a bit of help. Can ya'll tell me what the proper value to include in my config file is to ignore all methods from the `Requires` class (from OP)? I currently have the following in my configuration:

```json
{
  "stryker-config": {
     "ignore-methods": [
          "Requires.*"
      ]
   }
}
```

However, method calls to methods on the `Requires` class are getting mutated. What's the appropriate value that I should have in there? I thought #1635  had corrected this. I actually haven't been paying attention to the mutations lately (and had one or two projects disabled), but now that I've upgrade to 1.x I'm seeing these methods included again. 

Of note, it seems that the mutation is actually the "statement" mutation. So what I end up with is the method calls completely removed. I am not sure if perhaps it's a bug with the statement mutation (in which case I can open a new issue) or if I just don't understand the rules for the exclusion.

**Comment by rouke-broersma** [comment]
@pinkfloydx33 that is a problem with the new statement mutator. I think we have a fix for that waiting to be released. Let me check.

**Comment by pinkfloydx33** [comment]
Ok... sorry I should've looked first. Can you verify that my exclusion looks correct otherwise? I know there was a bit of back and forth originally over the way things were getting escaped. Looking at the changes on #1635 it appears as if I _should_ be good with what I have (outside of the statement mutator bug)

**Comment by rouke-broersma** [comment]
Config looks good to me
