### ISSUE TITLE
Stryker Randomly Reports NoCoverage for all mutants

### ISSUE THREAD

**Issue by pinkfloydx33** [stryker-mutator/stryker-net#1648]
**Describe the bug**
Stryker randomly reports `NoCoverage` for **all** non-excluded mutants. 

When running against multiple projects (individually) I can almost always reproduce the problem in at least one of them by specifying `max-concurrent-test-runners` with a value _other_ than the default. I was originally going to say that was necessary to reproduce the issue, but I am still getting random (though less frequent) runs reporting `NoCoverage` without it so concurrency may be a red herring. 

These runs then break my automated builds--I have a script that collects the output from each project and combines them into a single report which fails due to missing result files.

**Logs**
I have logs but I'd prefer not attaching them publicly as they look to contain our source code. Can I provide these directly to someone? If not, I'll see what I can do about redacting them.

**Expected behavior**
Stryker should detect the same coverage/no-coverage status every run.

**Desktop (please complete the following information):**
 - OS: Windows 10 and Ubuntu 18.04
 - Type of project: Core
 - Framework Version: 3.1/5.0 (see below)
 - Stryker Version: 0.22.9

**Additional context**
I have a solution with five projects in it. The projects-under-test are multi-targeted .NET5.0 and .NETStandard2.1 (and in one instance, .NETCOREAPP3.1 in lieu of .NETStandard). The Test projects themselves are multi-targeted 3.1/5.0. Each project has a configuration file that looks like this:

```json
{
	"stryker-config": {
		"reporters": [ "progress", "html", "json" ],
		"max-concurrent-test-runners": 4,
		"coverage-analysis": "perTest",
		"project-file": "The.Project.Name.csproj",
		"language-version": "CSharp9",
		"mutation-level": "Advanced",
		"ignore-methods": [ "ToString", "ConfigureAwait", "*Exception.ctor", "Log*" ],
		"excluded-mutations": [	"string" ],
		"mutate": [ "!**/Some.Exclusions.cs" ]
	}
}
```
For two of the test projects, specifying `project-file` is necessary as there are a handful of tests that validate some interactions between two of the libraries (unavoidable). For consistency I specify the `project-file` in all configuration files.

I run Stryker for all of the test projects, individually of course. With the above configuration I am pretty much guaranteed that at least one of the test projects will report that all tests are `NoCoverage`. It's not always the same project(s). When running in my build pipeline it might be the first, it might be the third. Because the pipeline fails at the first missing result file it's hard to say what the remaining projects would do.

If I remove `max-concurrent-test-runners` and rely on the default, I get a smooth run more often then not--but not always. Re-running the "failed" executions with the very same configuration will _usually_ produce a completed run. 

This is all happening in my build pipelines. I *sometimes* experience the same behavior locally but only when overriding the default concurrency (I have not yet experienced it locally using the defaults). 

Some other notes:
- My PC is Windows 10 with .NET Core 3.1, .NET 5.0 and 6.0 Preview installed. 
- My Build agents are Ubuntu 18.04 and have 3.1/5.0
  - For some reason Stryker always goes single-threaded on the Linux VMs, despite having 8 cores, which is why I was specifying the concurrency value
- Every run of Stryker (locally and on VMs) also produces Warnings/FileNotFoundExceptions for
  -  Microsoft.CodeAnalysis.NetAnalyzers, Version=5.0.4.22903
  - Microsoft.CodeAnalysis.Workspaces, Version=3.3.0.0

My solution structure looks like the following:
```yaml
\Solution.sln
\src
    \ProjectA
    \ProjectB
\test
    \ProjectA.Tests
    \ProejctB.Tests
```

**Comment by rouke-broersma** [comment]
Do you know if this happens with any other version of stryker? For example in 0.22.6?

Also could you list the testframework you use?

On your other notes:
Could you create a new bug for the incorrect core-count issue?

As for Microsoft.CodeAnalysis.*, do you use any of these packages in your project? If not, could you create a new issue and could you provide the part of the logging around where the exception occurs? Let me know if this includes sensitive information, in that case I will provide you with an alternative method of supplying the logs.

**Comment by pinkfloydx33** [comment]
> Also could you list the testframework you use?

Sure. I use Xunit as my test framework. Looking at the various logged output files (Stryker and vstest) it appears that *maybe* test fixtures are breaking things but I'm not sure.

Re: logs, do you want the ones I've collected on this specific issue? I have them zipped up but I'd prefer providing them via alternative means. 

> As for Microsoft.CodeAnalysis.*, do you use any of these packages in your project?

I am not using Microsoft.CodeAnalysis in any project (at least directly). I get the same errors in any project of mine that I run against, though admittedly all our projects reference the nuget packages generated from these specific projects. I don't get the `NoCoverage` issue in those other solutions (at least not so far). I can open an issue for that. 

> Do you know if this happens with any other version of stryker? For example in 0.22.6?

I do not know if a different version of Stryker exhibits the issue  described above. I will install an older version and try it. It will take me a bit because locally I have to run it a few times before it happens.

> Could you create a new bug for the incorrect core-count issue?

I am wondering if this might be an Azure VM thing. I'm going to log into a machine on my scaleset and check how dotnet reports Environment Processor Count and if it's accurate then I'll open a new issue.

**Comment by pinkfloydx33** [comment]
> As for Microsoft.CodeAnalysis.*, do you use any of these packages in your project?

It looks like .NET5.0 automatically includes some analyzers and they come from `Microsoft.CodeAnalysis.CSharp.Analyzers` and `Microsoft.CodeAnalysis.NetAnalyzers`. These are where the errors are generating out of.  Interestingly, I don't get the errors on Stryker 0.22.6. I opened #1650

**Comment by rouke-broersma** [comment]
> > Also could you list the testframework you use?
> 
> Sure. I use Xunit as my test framework. Looking at the various logged output files (Stryker and vstest) it appears that *maybe* test fixtures are breaking things but I'm not sure.
> 
> Re: logs, do you want the ones I've collected on this specific issue? I have them zipped up but I'd prefer providing them via alternative means. 
> 

Let's see if we can figure this out without you having to share privileged information first. A small repro would probably be more useful if that's possible. 

> > As for Microsoft.CodeAnalysis.*, do you use any of these packages in your project?
> 
> ~~I am not using Microsoft.CodeAnalysis in any project (at least directly). I get the same errors in any project of mine that I run against, though admittedly all our projects reference the nuget packages generated from these specific projects. I don't get the `NoCoverage` issue in those other solutions (at least not so far). I can open an issue for that.~~
> 
> It looks like .NET5.0 automatically includes some analyzers and they come from Microsoft.CodeAnalysis.CSharp.Analyzers and Microsoft.CodeAnalysis.NetAnalyzers. These are where the errors are generating out of.  Interestingly, I don't get the errors on Stryker 0.22.6. Should I open a new issue?
> 

Yes please. 

> > Do you know if this happens with any other version of stryker? For example in 0.22.6?
> 
> ~~I do not know if a different version of Stryker exhibits the issue  described above. I will install an older version and try it. It will take me a bit because locally I have to run it a few times before it happens.~~
> 
> I just ran against 0.22.6 locally. The very first run exhibited the issue in 3/5 projects.
> 
> > Could you create a new bug for the incorrect core-count issue?
> 
> I am wondering if this might be an Azure VM thing. I'm going to log into a machine on my scaleset and check how dotnet reports Environment Processor Count and if it's accurate then I'll open a new issue. 
> 

Thank you!

**Comment by pinkfloydx33** [comment]
It looks like the core count is something Azure related as .NET (via Powershell) is only reporting 2 which would give Stryker the correct default value of 1.

I am not sure how to create a small repro of the reported issue as I have no idea what's causing it. The only thing I can think of is perhaps the cross-targeting as I cannot reproduce in one of my other solutions which is .net5.0 only.

What I *can* tell you, is that there are **tons** of these at the end of each of the log files, next to each test:

> System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. (293dddea)

Looks to be between `System.Runtime` (the majority) and `System.Collections`. These don't exist in the logs when working normally

**Comment by rouke-broersma** [comment]
Mhm I think we have another issue about the missing System.Runtime, let me look.

**Comment by dupdob** [comment]
@pinkfloydx33 : if you still have this problem, can you please try again with the latest release? Several bug fixes have been implemented and the situation should have improved

**Comment by pinkfloydx33** [comment]
Haven't seen it happen; I'm on Stryker 1.x now and .NET 6 on that specific project which I'm sure makes some sort of difference
