### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1649]
Hey I want to fix some docs but the link to fix the docs is broken :)

The link "edit this page" here
![image](https://user-images.githubusercontent.com/5451366/128387554-64609dad-0646-4500-b194-b2f5ce4a649e.png)

leads here
![image](https://user-images.githubusercontent.com/5451366/128387453-85f6d35a-b7a4-4b45-9ed6-aebbbe79f1c8.png)

**Comment by rouke-broersma** [comment]
Looks like the edit link points to master while the page content comes from the v1 branch 🙃.. This will be fixed when we finally merge v1 to master..

Remind me to never again mess with long living branches... So many problems..

Thanks for reporting this! 😣

**Comment by psfinaki** [comment]
> Looks like the edit link points to master while the page content comes from the v1 branch 

Yeah I didn't want to disappoint with that information yet :D

**Comment by psfinaki** [comment]
Can I actually help here in any way? Docs are important :)

**Comment by rouke-broersma** [comment]
We have our open source day tomorrow. We will go through what's left for v1 and decide what to do. Perhaps we'll be ready to merge to master in which case we won't have to fix anything for this.

**Comment by psfinaki** [comment]
Alright, feel free to ping me here if you need to have some "consistency checks" and so on, I'm good at that :D

**Comment by richardwerkman** [comment]
We set master as our default branch again. That should fix the website on the next update

**Comment by psfinaki** [comment]
Amazing, thanks!

**Comment by psfinaki** [comment]
@rouke-broersma is this supposed to be in? The web seems to show the same thing unless I'm missing something.
(not urgent as I have a secret link to docs in code but just wondering)

**Comment by rouke-broersma** [comment]
We use static site generation for the docs and turned out there was a build issue on master (which we didn't detect because we didn't use master). I have fixed the issue and tonight the fixed site should deploy. I will check tomorrow that it worked.
