### ISSUE TITLE
Expand ignore method to allow wildcards in the class name


### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1651]
> Should a filter like `*Something.*` work? I can't tell based on looking at the tests.
> Should a filter like `*Something.*` work? I can't tell based on looking at the tests. 

> I have multiple classes called `AbcSomething`, `DefSomething` and `XyzSomething` of which I want to exclude all methods. I added a `*Something.*` method exclusion but it doesn't seem to be taking hold. 

> Of note is that they all inherit from an abstract class `SomethingBase` (which doesn't match that pattern) and the members invoked are either virtual/abstract or defined on the base class only. Sometimes my reference is of the base type, others of the concrete type. I tried `*Something*.*` and that didn't seem to work either. 

> If it's not covered that's fine as I can just exclude them individually, but I wanted to make sure I wasn't missing something.

_Originally posted by @pinkfloydx33 in https://github.com/stryker-mutator/stryker-net/issues/1647#issuecomment-893344042_

**Comment by richardwerkman** [comment]
Seems to work for me already. Closing for now, feel free to open again is someone runs into this issue
