### ISSUE TITLE
Configuration Documentation for C# in website and this Repo is out of sync with actual commands in v0.22.9

### ISSUE THREAD

**Issue by JPTouron** [stryker-mutator/stryker-net#1655]
**Describe the bug**
The [documentation for the configuration for the C# version](https://stryker-mutator.io/docs/stryker-net/configuration) does not correspond with the actual commands listed with the --help option

**Example**
`dotnet Stryker.CLI.dll --help`

_Outputs_

`Options:
  -cp|--config-file-path <path>                             Sets the config-file-path relative to current workingDirect`

[_Web site states_](https://stryker-mutator.io/docs/stryker-net/configuration#config-file-path)

config-file <path>
Command line: [-f|--config-file] "appsettings.dev.json"

**Expected behavior**
Doc should be in sync

**Comment by richardwerkman** [comment]
The website gets the content directly from github. We just completed a complete rework for the options. But now that we merged the website updated as well... This is indeed unfortunate as we are not ready to release the new version yet.

We'll try to fix the website by targeting the master branch. But for now you can see the (current) documentation on our [master branch under /docs](https://github.com/stryker-mutator/stryker-net/blob/master/docs/Configuration.md). Sorry for the inconvenience.

**Comment by rouke-broersma** [comment]
Should be fixed by next website update (should be tonight)
