### ISSUE TITLE
Cannot distinguish some errors by exit code

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1672]
**Describe the bug**

Given that Stryker is still not entirely stable, our mutation testing script reruns the execution in case of errors (I should actually publish our script one day here, it is now quite elaborate and can be useful for others). But we actually want to rerun it differently depending on what exactly happened and I haven't found a better way to make a decision rather than looking at the error code.

In particular, I have now two things I want to distinguish:
1) Stryker tries to run against a wrong framework ([this thing](https://github.com/stryker-mutator/stryker-net/issues/1487)). In that case I just retry 8 times (lucky number in China), it helps in 99% cases :D
2) Stryker fails because mutation score is lower than the break threshold (in that case I don't want to rerun or maybe max 1 time haha)

However in both cases the exit code is 1. AFAIU Stryker doesn't control the code in the first case, but explicitly set 1 in the second case. Is there a reason for that particular code? If no, can it be set to something else, e.g. 42?

**Comment by rouke-broersma** [comment]
There is no specific reason for exit 1. We could actually change that to something meaningful. Good idea!

**Comment by psfinaki** [comment]
I can think of a way to make this more "meaningful" although maybe we could start documenting the codes somewhere?
