### ISSUE TITLE
Reporters should report in a mutant-free world

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1676]
**Is your feature request related to a problem? Please describe.**

We run Stryker against a bunch of projects and then merge the reports using a custom script. This works but in the full report we basically miss the projects without mutants which sort of hinders the general visibility of the situation.

**Describe the solution you'd like**

I wonder could there be an alternative approach? For statistics, we count the mutation score of such projects as 100% anyway because there is basically nothing we can improve from the mutation testing perspective. But I guess N/A would do as well. What do you think?

**Comment by rouke-broersma** [comment]
This sounds similar to this: https://github.com/stryker-mutator/stryker-net/issues/1621

**Comment by psfinaki** [comment]
I checked that before yeah, and well the heading is similar but the scenario is actually somewhat different:
> When you have no mutants to test due to your mutants not being covered by tests

Here I mean that there are just no mutants generated whatsoever. We have a bunch of projects like this, quite primitive but important ones.

**Comment by rouke-broersma** [comment]
> I checked that before yeah, and well the heading is similar but the scenario is actually somewhat different:
> > When you have no mutants to test due to your mutants not being covered by tests
> 
> Here I mean that there are just no mutants generated whatsoever. We have a bunch of projects like this, quite primitive but important ones.

Should be the same implementation, it was not my intention with that feature request to limit it to only when you have mutants but no tests. I'll close that one in favor of yours.

**Comment by psfinaki** [comment]
Oh alright! Well so at least you are for it :) Do you have an idea on how hard this can be to implement and where to start?

**Comment by rouke-broersma** [comment]
Fixed by https://github.com/stryker-mutator/stryker-net/commit/982c30d7d28d7d0081cba66ca5fc37f34c49cc07

**Comment by psfinaki** [comment]
> hope to get on this next week

Damn :D Thanks, @rouke-broersma!
