### ISSUE TITLE
Stryket.NET crashes on .NET6, reported here as log instructing

### ISSUE THREAD

**Issue by veikkoeeva** [stryker-mutator/stryker-net#1677]
**Describe the bug**
Stryker.NET crashes. The error message instructors to report it here. The following is a quote of the message:

> [19:51:40 WRN] Stryker.NET encountered an compile error in /home/runner/work/Verifiable/Verifiable/src/Verifiable.Tpm/obj/Debug/net6.0/Verifiable.Tpm.ImplicitNamespaceImports.cs (at 7:0) with message: The feature 'global using directive' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. (Source code: global using global::System.Threading.Tasks;)
[19:51:40 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[19:51:40 FTL] Stryker.NET could not compile the project after mutation. This is probably an error for Stryker.NET and not your project. Please report this issue on github with the previous error message.
[19:51:40 ERR] An error occurred during the mutation test run 

**Logs**
The log line can be seen at https://github.com/lumoin/Verifiable/runs/3425939046?check_suite_focus=true#step:14:777.

**Expected behavior**
Stryker.NET does not crash.

**Desktop (please complete the following information):**
 - OS: **Linux, Windows, MacOS**
 - Type of project: **NET6**
 - Framework Version: **6.0.100-preview.7.21379.14**
 - Stryker Version: **0.22.10**

**Additional context**
This is likely due to .NET6 builds. I opened this as I did not see a mention of this yet. The test run is at https://github.com/lumoin/Verifiable/actions/runs/1167885420. I just added Stryker.NET to the project for later use (thank you for the library!).

If you look at the logs, there are warnings about plenty of other things too. Some of the warnings may be cured by improving the setup (as noted, I haven't delved into yet really).

I take the liberty (do tell and I removed if needed) to cross-link https://github.com/stryker-mutator/stryker-net/issues/1677 as it looks like to be related.

**Comment by rouke-broersma** [comment]
Let's revisit this next week when .NET 6 is released so we can confirm if the issue persists after updating the Roslyn SDK with the stable .NET 6 platform SDK.

**Comment by veikkoeeva** [comment]
@rouke-broersma I've tested a bit already. It won't crash, but some other issues cropped in the aforementioned codebase (some getters won't compile after mutation). I get back sometime next week, almost no sleep due to a few hackathons. :D

**Comment by rouke-broersma** [comment]
Awesome, thanks for getting back to me so soon :)

**Comment by richardwerkman** [comment]
I think this issue can be closed? If the warning about the compile error persists please create a new issue for that :)
