### ISSUE TITLE
Dashboard api key option not working 

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1687]
**Logs**
```
[08:52:16 ERR] Dashboard upload failed with statuscode Unauthorized and message: Provide an "X-Api-Key" header
[08:52:16 ERR] Uploading to stryker dashboard failed...
```

https://stryker-mutator.slack.com/team/UUQ9T0LQN

**Comment by philrowan-mtb** [comment]
Hello, I also hit this issue in the RC. The input validation [requires a baseline input ](https://github.com/stryker-mutator/stryker-net/blob/v1.0/src/Stryker.Core/Stryker.Core/Options/StrykerInputs.cs#L137) else it just skips setting the dashboard api key. I believe this check should instead ensure that at least one of the reporters is the dashboard reporter.

**Comment by rouke-broersma** [comment]
Yes thank you for looking into it, that is the problem. It should check 2 things; 1: Is the dashboard reporter enabled, 2: Is the dasboard storage location enabled for the with-baseline feature AND is the with-baseline feature enabled.

**Comment by philrowan-mtb** [comment]
Maybe I am missing some other changes happening in the 1.0 or just misunderstanding this feature release but shouldn't I be able to report to the dashboard _without_ a baseline to push a full report in order to establish the baseline? Either way, I could start work on this.

**Comment by rouke-broersma** [comment]
Dashboard reporter and baseline (with dashboard as storage location) are two separate features that both use the dashboard.
