### ISSUE TITLE
Ignored methods are not ignored in V1

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1690]
**Describe the bug**
The mutations in ignored methods are not ignored anymore.

**Expected behavior**
Mutations are ignored, as they used to be.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: core
 - Framework Version: net5.0
 - Stryker Version: 1.0.0-rc2
 
**Additional context**
Demo: [IgnoreMethodsDemo.zip](https://github.com/stryker-mutator/stryker-net/files/7172040/IgnoreMethodsDemo.zip)

**Comment by rouke-broersma** [comment]
I think this has not yet been merged from master to V1 🙈

**Comment by psfinaki** [comment]
Oh no! Alright then, good that I checked that before migrating all our code to the new version :D Alright then, hope it gets there soon

**Comment by rouke-broersma** [comment]
I started on the merge but it was trickier than I had the effort for so I released the rc instead 😁 I'll probably do it on Friday and release a new rc.

**Comment by psfinaki** [comment]
Sure, thanks!

**Comment by rouke-broersma** [comment]
The merge was trickier than I thought so it wasn't fixed on Friday but as soon as it's done I'll release a new rc.

**Comment by psfinaki** [comment]
Sure, thanks for headsup!

**Comment by rouke-broersma** [comment]
I just released rc3. It should include the ignore methods feature and it should have the so far reported v1 issues resolved.

**Comment by psfinaki** [comment]
Thanks! I will be on vacation for a few weeks so won't be able to check so just silently hope everything is working :)
