### ISSUE TITLE
Stryker 1.0.0-rc2 fails with error about missing log-level property

### ISSUE THREAD

**Issue by mapspiral** [stryker-mutator/stryker-net#1694]
**Describe the bug**
Running `dotnet stryker` on my machine fails with the following error after upgrading from 0.22.7 to 1.0.0-rc2:

```
There was a problem with one of the json properties in your stryker config. Path "stryker-config.log-level", message: "Could not find member 'log-level' on object of type 'FileBasedInput'. Path 'stryker-config.log-level', line 8, position 20."
```
The stryker-config.json looks like this:

```
{
    "stryker-config":
    {
        "reporters": [
            "progress",
            "html"
        ],
        "log-level": "info",
        "log-file":true,
        "timeout-ms": 10000,
        "project-file": "DataServices.Worker.JoinData.UBL.csproj",
        "max-concurrent-test-runners": 2,
        "threshold-high": 80,
        "threshold-low": 70,
        "threshold-break": 60,
        "mutation-level": "Standard",
        "mutate": [
        ],
        "excluded-mutations": [
            "string",
            "Logical operators"
        ],
        "ignore-methods": [
            "*Log*",
            "ToString",
            "*HashCode*"
        ]
    }
}
```
It looks as if the log-level is present in the file.

**Logs**
No logs are generated using the '--log-to-file' option.

**Expected behavior**
I expect Stryker to run and complete as it did in my original version (0.22.7).

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project Core
 - Framework Version core 5.0.401
 - Stryker Version 1.0.0-rc2

**Additional context**
Nothing additional to add.

**Comment by rouke-broersma** [comment]
Hi @mapspiral 

log-level has been renamed to verbosity in v1. We will publish a migration guide for v0 to v1 when we release a final version for v1. You can downgrade to v0.22.10 until v1 is released to get back the old configuration options.

I will fix the upgrade notice today, it should not suggest to install preview versions, sorry about that!
