### ISSUE TITLE
Compilation error when using file scoped namespaces

### ISSUE THREAD

**Issue by jaspervhaastert** [stryker-mutator/stryker-net#1711]
**Describe the bug**
Stryker.NET cannot compile the project when using C# 10 file scoped namespaces, even with `--language-version preview`.

**Logs**
[log-20211004.txt](https://github.com/stryker-mutator/stryker-net/files/7276758/log-20211004.txt)

**Expected behavior**
I expect it to be able to compile the project.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .NET Core
 - Framework Version: 6.0.0-rc.1
 - Stryker Version: 0.22.11 and 1.0.0-rc3

**Additional context**
`--language-version preview` _does_ solve compilation errors for other C# 10 features such as global usings.

**Comment by dupdob** [comment]
This is a limitation of Stryker architecture: `Preview` is a placeholder for the preview version from the Net framework used to build Stryker (5.0 as of today). As such, it does not support C#10 features.

This will be fixed when a Net 6.0 Stryker version is available.

**Comment by rouke-broersma** [comment]
To be clear, we do not claim to nor can we provide full compatibility with preview versions of dotnet or csharp as this would require shipping preview versions of the compiler sdk. Using preview versions of dotnet/csharp is on a best effort basis. If this issue persists after the full release of csharp 10 and a stryker update (to update the compiler sdk) we would love to know. For now I'll close this issue.
