### ISSUE TITLE
Stryker.NET install can fail when nuget config contains private nuget registries

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-net#1723]
**Is your feature request related to a problem? Please describe.**

Stryker.NET installation can fail when your nuget config contains private nuget registries. 

![image](https://user-images.githubusercontent.com/1828233/138843335-4e27effa-73ac-4067-bff4-72ca25d6ec64.png)

```xml
<packageSources>
    <add key="azure" value="https://pkg.azure.com/cdwrt06/cdwrt06_10_2021/_packaging/Universal/nuget/v3/index.json"/>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
</packageSources>
```

**Describe the solution you'd like**

Improve the getting-started.md to describe the best solution. We simply removed all package sources except `nuget.org`, which worked. But I hope there is a better solution.

**Describe alternatives you've considered**

Maybe change the docs to force nuget to use `nuget.org`?

**Additional context**

Users of Nuget often don't know exactly which package sources they configured, because Visual Studio manages them as well.

**Comment by rouke-broersma** [comment]
Since there hasn't been any traction on this issue and since dotnet tools distributed through nuget are more and more common I assume modern dotnet developers are aware of this concept and documentation around this concept is not neccesary.
