### ISSUE TITLE
`ignore-methods` not working for constructors of generic types

### ISSUE THREAD

**Issue by loop54-christoffer** [stryker-mutator/stryker-net#1757]
**Describe the bug**
When I instantiate a type such as `new InputArgument<int>(true)` while simultaneously having specified in my config

```json
        "ignore-methods": [
            "*InputArgument*.ctor"
        ],
```

Stryker will still attempt to mutate the boolean given to the constructor. With this configuration, I would expect it not to.

**Logs**
I think the problem is clear enough even without logs. For easy reproduction, [one could add a test case with a constructor for a generic type to the relevant test](https://github.com/stryker-mutator/stryker-net/blob/89d63792f4984c9ede7635a42cdb8bf0720c12d6/src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs#L252-L311).

**Expected behavior**
As stated above, when I have ignored the constructor of `InputArgument` I would expect stryker not to mutate the argument given to that constructor.

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project: .NET 5
 - Framework Version: .NET 5
 - Stryker Version: 1.0.0-rc3

**What can I do?**
If I can find the time, I might try my hand at fixing this because it would be very helpful to me.

That said, I haven't worked with Roslyn before so it would be a significant investment for me. Therefore, I would first like to hear from someone that I just haven't misunderstood something silly!

**Comment by psfinaki** [comment]
Hi there, I think this was already reported [here](https://github.com/stryker-mutator/stryker-net/issues/1690) and [here](https://github.com/stryker-mutator/stryker-net/issues/1721) and the reason for the behavior was that Stryker RC versions didn't have all the features merged yet.

But it's claimed that V1.0.0 has this working. I can't test this myself right now - maybe you have a chance to verify?

**Comment by loop54-christoffer** [comment]
Ah! I must have missed that. The reason I'm still on 1.0.0-rc3 is that I'm running into something similar to #1387 when I try to run the stable 1.0.0, which makes it impossible for me to verify that it's working in 1.0.0 now.

(I haven't chimed in on that issue (or created a new one myself) yet because I want to do some additional troubleshooting of why 1.0.0 fails before I do so.)

**Comment by rouke-broersma** [comment]
1.0.0-rc3 should already include the ignore mutants changes and should work if you're using the config file instead of cli. I think it's very possible that we simply never tested this feature with generic constructors and that the feature does not currently work when generics are in play.

I am curious what issues you have with v1 because there shouldn't be that many changes since rc3.

**Comment by loop54-christoffer** [comment]
I think there was a bugfix/optimisation in 1.0 that wasn't in rc3, which made my setup accidentally work, when it "shouldn't" have. One of the test projects does not directly reference the mutated project, but is able to call it indirectly through a reference to the other test project, which does reference the mutated project.

This worked in rc3 because it, apparently, allowed me to specify as the mutated project anything in the union of direct references from any of the test projects. In 1.0, I must specify something in the intersection of direct references from the test projects.

Of course, the C# compiler allows calling projects that are referenced only transitively, so others could run into this problem too – but I don't know if it's a bug report or a feature request.

**Comment by loop54-christoffer** [comment]
However, now that I figured out the above, I've been able to test 1.0 on my project and it does indeed ignore constructors of generic types. However, if I try to add a unit test for it, the test fails. Do you want me to close this because it's fixed for me in practise, or keep it open because you want to try adding the test yourself?

**Comment by rouke-broersma** [comment]
If you're sure your problem is solved in v1 you can go ahead and close the issue. If you're not sure and want us to take a look keep it open.

**Comment by loop54-christoffer** [comment]
I'm absolutely sure it's fixed for me – the problematic mutations are marked as "ignored" in the HTML report and the overall mutation score reflects this too.

**Comment by loop54-christoffer** [comment]
Thank you for an amazing tool, by the way! I first stumbled over mutation testing back in 2012, but at that point I did *not* expect I would be able to apply it in practise with a cross-platform, user-friendly interface within ten years. I'm ecstatic about it!

**Comment by rouke-broersma** [comment]
That's great to hear 😄

**Comment by psfinaki** [comment]
Just a small update - ignore-methods option work for me as well :)
