### ISSUE TITLE
When using --since:<commitish> filtered mutants in changed files are run anyway

### ISSUE THREAD

**Issue by Deneas** [stryker-mutator/stryker-net#1760]
**Describe the bug**
In my project I disabled LINQ mutations for one location with `// Stryker disable once Linq`, because the mutant there is unkillable.
When now running `dotnet stryker` while in the corresponding test project, the mutant correctly gets ignored.
If I run `dotnet stryker --since:c76f6c8f53ba30efb3ff081c95867977548d2e2f` instead, the mutant is not ignored because the file has changed.

**Logs**
[WithoutSince.txt](https://github.com/stryker-mutator/stryker-net/files/7449019/WithoutSince.txt)
[WithSince.txt](https://github.com/stryker-mutator/stryker-net/files/7449021/WithSince.txt)

**Expected behavior**
I would expect that filtered mutants are ignored, even when they are in an changed file.

**Desktop (please complete the following information):**
 - OS: Windows
 - Core
 - Framework Version net5.0
 - Stryker Version 1.0.0

**Additional context**
All code is available in the repository https://github.com/Deneas/MutationTestingExample, although be aware that he commands in the Readme are from before 1.0.0 :)

**Comment by rouke-broersma** [comment]
Thank you for letting us know! Sounds like we have a problem with the order in which the different filters are executed.
