### ISSUE TITLE
Statement mutation cannot be ignored entirely

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1762]
**Describe the bug**
I want to migrate to Stryker 1.0.0 and I also need to keep the scores (as we lock them in), so I need to temporarily ignore the statement mutation for now. However this works weirdly.

Here's my code missing some tests:
![image](https://user-images.githubusercontent.com/5451366/139673917-3b4290af-27ae-4b43-a517-351c22d008b5.png)

Here's the report when nothing is ignored:
![image](https://user-images.githubusercontent.com/5451366/139673980-dee4c546-2269-44df-8c52-e7eb3d83b2df.png)

And here's what happens when I ignore the statement mutation:
![image](https://user-images.githubusercontent.com/5451366/139674063-3b2c524c-cdd6-4eab-8ad8-cabb64ac4de4.png)

So only one of the two statement mutations is ignored. This is unacceptable for me :(

**Expected behavior**
Ignore all the statement mutations, essentially give the same score as it was Stryker beta.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: Core
 - Framework Version: 5.0
 - Stryker Version: 1.0.0

**Additional context**
Repro is here: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/7453333/Repro.zip)

**Comment by richardwerkman** [comment]
How exactly did you ignore the statement mutations? Did you add the following to your config file?
```json
"ignore-mutations": ["statement"]
```

**Comment by richardwerkman** [comment]
Oh I now see your repro... You did. So I would expect it to work indeed. I'll take a look at this

**Comment by psfinaki** [comment]
Yes, all is in the repro. Thanks :)

**Comment by richardwerkman** [comment]
I found the issue. When passing "statement" as ignored mutation it was interpreted as "block". This was because the full name for "block" is "block statements" which contains "statements". This bug should be fixed in our next release!

**Comment by psfinaki** [comment]
Amazing, thanks for quick fix! I can verify I get the same numbers now. When can we expect the release?

**Comment by richardwerkman** [comment]
I was hoping to squeeze some more PRs in one release. But it seems they are not done soon so I will release these fixes tonight!

**Comment by psfinaki** [comment]
Amazing, looking forward :)

**Comment by richardwerkman** [comment]
Released :) Should be available in a few minutes
