### ISSUE TITLE
Project not found when using / instead of \.

### ISSUE THREAD

**Issue by Kuinox** [stryker-mutator/stryker-net#1769]
**Describe the bug**
In my config, when I use `"project": "CK.MQTT.Client/CK.MQTT.Client.csproj"`, stryker doesn't find the project. Using a backslash solve the issue.

**Expected behavior**
I can use both slash or backslash in the config.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: Library
 - Framework Version: .NET 5
 - Stryker Version: 1.0.0

**Additional context**
Looks like a regression because it was working before 1.0.0.

**Comment by richardwerkman** [comment]
Are you sure this worked before? I don't think we made any changes concerning project filtering. But I'll fix this
