### ISSUE TITLE
Vs Extension

### ISSUE THREAD

**Issue by Szpi** [stryker-mutator/stryker-net#177]
It would be really cool if developer could install stryker extension to visual studio, right click on class maybe test? and press Run mutation tests and then automatically run stryker with proper includes /excludes. Maybe some visualization window?

Making such extension would take much effort, but just imagine it 🥇

**Comment by nicojs** [comment]
I agree that this is something that we eventually want. First we need to make sure we have test runner integration (#183) and .NET framework support (#28). Once we have that, we can already have basic plugin IMHO
