### ISSUE TITLE
Ignore block mutation of ignored method.

### ISSUE THREAD

**Issue by Kuinox** [stryker-mutator/stryker-net#1778]
**Describe the bug**
![image](https://user-images.githubusercontent.com/18743295/140000125-9f349e01-75cf-4e6c-a53a-11c5d5b6d17f.png)
Here , we can see Warn is ignored (string mutation of warn is ignored).

**Expected behavior**
Replacing this method call by an empty statement should also be ignored

**Desktop (please complete the following information):**
 - OS: Windows: 11
 - Type of project: Library
 - Framework Version: .NET 5
 - Stryker Version: 1.0.0

**Comment by richardwerkman** [comment]
This would be a bit tricky to implement. I would rather take a different approach that's a bit broader than this. Block mutations are unwanted when another mutation is already present in the block. So I would like a way to skip placing the block mutation if another mutation is present in it. That would also solve your issue as it would contain a (ignored) mutation. 

The same would also work for statement mutations, they are unwanted if another mutation is present inside of them.
