### ISSUE TITLE
Allow the break threshold to be higher than others

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1779]
**Is your feature request related to a problem? Please describe.**
Here's my "customer case" :)

Currently we execute Stryker in different ways:
1) We have nightly executions for all the projects (about 200 of them right now) to have the "big picture"
2) We execute it in PRs for changed projects to see if the changes don't lower the current mutation score (we have an original mechanism of keeping track of it :D) 

We also have some "quality standards", something like mutation score above 85 is good, 50 to 85 is disturbing (and someone should jump on addressing this), below 50 is very very bad - our systems won't allow the package to be normally released basically.

Now we've been getting by with one `stryker-config.json` so far, where we have reporters, ignored methods and so on but where we don't set any thresholds whatsoever. And then:
1) For nightly executions, we would set the scores in the CLI like `--threshold-high 85 --threshold-high 50 --threshold-break 0` - to have the nice picture
2) For PR executions, we would set them as `--threshold-high 100 --threshold-low 100 --threshold-break <current mutation score>` - just to prevent PRs from being merged if not sufficiently tested
---
Now, Stryker 1.0 removes the high and low thresholds from the CLI and makes us have them in the config. This leaves us with too options:
1. Set `high: 100, low: 100` in the current config - and lose in clarity of the big picture after nightly runs (the numbers will be basically only green or red there)
2. Have two configs, one for nightly with `high: 85, low: 50` and one for PRs without thresholds at all - and have all the other settings duplicated

**Describe the solution you'd like**
The above options are not the end of the world but I thought - why does Stryker even break when the break threshold is higher than the high one? It makes sense that "low" must be lower than or equal to "high", but "break" has a bit different objective so probably doesn't need to an obstacle here - for those who know what they're doing.

We can maybe write a warning instead.

**Additional context**
I can do that :D

**Comment by rouke-broersma** [comment]
They way I see it is, you have two sets of metrics. One for overall/nightly builds and one for 'new code' (new code period in sonarqube if you're familiar). This means two configs with different allowed values.

I can see that allowing the break threshold higher than the low threshold would fix your specific use case but I don't think this is semantically correct. A score can't both be 'good enough (yellow)' yet not be good enough (break). This would mean that your build would be red, but when you look at the report the report is actually yellow. Confusing.

To me your requests suggests that you want some kind of global config, and then have per-project or even per-run specific settings. In essence this is exactly the case for why we decided that the CLI options have a higher precedence than the config file, but perhaps it would be good to also allow some kind of config-merge where we would allow multiple config files with one being the main config and others overwriting or appending to.

**Comment by richardwerkman** [comment]
@rouke-broersma I think adding threshold-high and threshold-low back to the CLI is more efficient than adding multiple config support. Especially since we don't know it multiple config support is needed for any other scenario.

**Comment by psfinaki** [comment]
@rouke-broersma Your logic is correct, nevertheless I believe it partly depends on devs' interpretations of all those colors. I think universally "red" is something "bad" and "green" is something "not bad" and everything else depends :D But yeah that's why I suggested a warning in case the developers agreed on the color interpretation and now know what they are doing. 

That said, bringing back the CLI options would definitely suffice as well. Although it's probably a bit bigger effort?

**Comment by psfinaki** [comment]
Well blocked is a strong word... It's not blocking our migration per se and I think we will go for two configs for now. Rather it's a "regression" in some sense. So it probably should be mentioned in the migration guide and addressed sooner than later :)
