### ISSUE TITLE
Disabling all mutations is not working

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1781]
**Describe the bug**
This:
![image](https://user-images.githubusercontent.com/5451366/140519340-c3d42e30-2707-42e6-989a-c95f5ddb1060.png)

Leads to this:
![image](https://user-images.githubusercontent.com/5451366/140519443-037a9239-790a-4c16-8ccd-123f015caf27.png)

And as a result to this:
![image](https://user-images.githubusercontent.com/5451366/140519552-dce3ff71-60f5-44f9-8570-6ab964cce8f4.png)

**Expected behavior**
All the mutations are ignored.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project core
 - Framework Version: 5.0
 - Stryker Version: 1.01

**Additional context**
Disabling `once` also doesn't work. **__Disabling a list of specific mutations works - so things are not too bad ;)__** 

Here's the repro: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/7486439/Repro.zip)

**Comment by psfinaki** [comment]
The `restore all` is also **working**.

**Comment by dupdob** [comment]
thanks for reporting.
I reproduces this problem and I think I have identified the issue.
Could you please try without any trailing whitespaces after `all` ? Like this: `// Stryker disable all: testing`

I think it should work; in any case, trailing whitespaces prevent identification of `all`

**Comment by psfinaki** [comment]
Mhm this actually throws:
![image](https://user-images.githubusercontent.com/5451366/140604253-4ff24f2c-43c6-4410-b5e1-5696e2580688.png)

So no this didn't help :)

Regardless, I took this from the example in the [migration guide](https://stryker-mutator.io/blog/2021-30-10-announcing-stryker-net-1.md#ignore-mutations) so that one might need to be addressed:
![image](https://user-images.githubusercontent.com/5451366/140604287-7f7ec600-29a1-46e4-a858-aacb07d876d6.png)

However, ignoring individual migrations works regardless of spacing there.

**Comment by dupdob** [comment]
Thanks for the update. This is another issue actually, but I have got a repro thanks to you. This exception happens because every mutation is ignored.
I fixed and added a test for that.

**Comment by dupdob** [comment]
see #1776

**Comment by psfinaki** [comment]
Great, thanks for prompt response @dupdob, looking forward to the fix :)
