### ISSUE TITLE
Some inline-disabled mutations look strange in the reports

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1782]
**Describe the bug**
So as you can guess, we've updated to Stryker 1.0 and are now making use of the new opportunities so I'm reporting whatever I discover :D That said, the update went quite smoothly, the logs are much cleaner and things work faster for us.

Here's a minor thing. Consider this code:
```csharp
// Stryker disable once assignment: testing
a += 4;

// Stryker disable once arithmetic: testing
b = a + b;

a += 4;
```

Stryker respects the directives but for some reason in the first case the report shows the mutation weirdly:
![image](https://user-images.githubusercontent.com/5451366/140536786-28fe455d-440f-408a-a0a4-b7aa2cd56e8b.png)

So it's this particular interference of `assignment` mutation and `disable` syntax.

**Expected behavior**
The first mutation shows in the same way as the third.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: core
 - Framework Version: net5.0
 - Stryker Version: 1.0.1

**Additional context**
Repro: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/7487182/Repro.zip)

**Comment by rouke-broersma** [comment]
That is weird 😄

**Comment by rouke-broersma** [comment]
The whole mutation report is getting an overhaul soon. Let's look into this after we have upgraded to the fancier report.

**Comment by psfinaki** [comment]
Sure!

**Comment by rouke-broersma** [comment]
@psfinaki The updated report is getting released right now! Please let us know what you think and if it's a better experience :)

**Comment by psfinaki** [comment]
Well the report generally looks more beautiful of course but regarding the original issue - it's still there, in a different form now :D
<img width="501" alt="image" src="https://user-images.githubusercontent.com/5451366/145816221-7ecc07bf-eb9b-4f09-a4ae-790fc278c61d.png">

**Comment by richardwerkman** [comment]
![image](https://github.com/stryker-mutator/stryker-net/assets/14224500/5d5af242-afff-4550-9391-f50bb393db28)
It looks like we no longer include the comment into the mutation. Closing the issue
