### ISSUE TITLE
Ability to disable mutation for lines of code based on pattern / method

### ISSUE THREAD

**Issue by ewancoder** [stryker-mutator/stryker-net#1791]
It would be a nice feature to have an abitily to disable mutation of specific lines of code based on pattern. For example, I don't want this

```csharp
_logger.LogDebug("App started");
```

mutated into this

```csharp
;
```

(deleted line)

There are a lot of lines of code related to logging and we don't have any tests that test that we log precise strings. I would like to have an ability to have something similar to "exclude-methods" so that I can disable the mutation of the whole line.

Discussion:
https://github.com/stryker-mutator/stryker-net/discussions/1790

**Comment by GaetBaka** [comment]
Agree, mutants should not be created when inside an ignored method.
Adding to ignore-methods should be enough to ignore the method, seems legit
