### ISSUE TITLE
Disk baseline not being saved unless baseline reporter is manually enabled

### ISSUE THREAD

**Issue by sbergen** [stryker-mutator/stryker-net#1797]
**Describe the bug**

When using
```
"baseline": {
  "enabled": true,
  "provider": "Disk"
}
```

a baseline report is never saved, unless the `baseline` reporter is manually enabled.

`DiskBaselineProvider.Save` is only called from `GitBaselineReporter.OnAllMutantsTested`, so the reporter should probably be implicitly enabled if the baseline feature is in use?

**Logs**
I can provide logs if necessary, but I feel the issue is pretty clear.

**Expected behavior**
A baseline report should get saved to the disk when using the Disk provider.

**Desktop:**
 - OS: MacOS
 - Type of project: class library
 - Framework Version: core 2.0
 - Stryker Version 1.0.1, master

**Comment by rouke-broersma** [comment]
Yep! The reporter should be enabled, thank you for reporting!
