### ISSUE TITLE
Fallback Disk baseline report is not looked for in the correct location

### ISSUE THREAD

**Issue by sbergen** [stryker-mutator/stryker-net#1798]
**Describe the bug**

When using
```
"reporters": [
    "progress",
    "html",
    "baseline"
],
"baseline": {
    "enabled": true,
    "provider": "Disk",
    "fallback-version": "main"
},
"since": {
    "enabled": true,
    "target": "main"
}
```

(see #1797 for details on why the baseline reporter has to be manually enabled)

1. Generate a baseline report on the `main` branch
2. Run Stryker on a branch that is not `main`
3. The baseline report can't be found, because it is looked for in the wrong directory:

`GitBaselineReporter.OnAllMutantsTested` and `DashboardMutantFilter.GetBaselineAsync` use `dashboard-compare/{projectVersion}`, but `DashboardMutantFilter.GetFallbackBaselineAsync` uses the version name directly. 

I'm not sure how this interacts with other baseline providers, so I wasn't comfortable suggesting a direct fix in a pull request.

**Logs**
I can provide logs if necessary, but I feel the issue is pretty clear.

**Expected behavior**
An existing fallback baseline report on disk should be found when it's present.

**Desktop:**
 - OS: MacOS
 - Type of project: class library
 - Framework Version: core 2.0
 - Stryker Version 1.0.1, master

**Comment by rouke-broersma** [comment]
Thank you for reporting these issues! I'll take a look soon.
