### ISSUE TITLE
Large projects

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#18]
On large projects, it might occur that not all compile errors are returned by Roslyn after the first compile try. If this happens, not all "broken" mutations will be rollbacked.

For now this problem has not occurred yet. Stryker should be tested on a large project to discover if this is an existing bug or not.

**Comment by Mobrockers** [comment]
@richardwerkman Do you feel like we have sufficiently fixed this now, or should we try this on even larger projects?

**Comment by richardwerkman** [comment]
I think this will work for extremely large projects, if not people can open new issues for their case.
