### ISSUE TITLE
dotnet stryker baseline recreate command

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1805]
We could add a `create-baseline` command that stores the baseline in the desired storage provider after doing a complete run.

_Originally posted by @richardwerkman in https://github.com/stryker-mutator/stryker-net/issues/1803#issuecomment-969165641_

Users can use this option to generate a completely fresh baseline even if a baseline already exists. This is useful when you baseline is very old or if the baseline becomes corrupt (bad merge of baseline with new results).

**Comment by Liam-Rougoor** [comment]
This issue will be covered by #1560 , so closing this one.
