### ISSUE TITLE
Json report formatting error

### ISSUE THREAD

**Issue by gmdunlop** [stryker-mutator/stryker-net#1807]
**Describe the bug**
Getting a parsing error trying to read json report. Looks like the formatting on the json is off.

**Logs**
     | Conversion from JSON failed with error: Invalid character
     | after parsing property name. Expected ':' but got: ,. Path
     | 'projectRoot', line 8, position 9.

![stryker-logs](https://user-images.githubusercontent.com/82120675/142073681-16902182-de33-4879-8f79-c3ecf4edeb4e.PNG)

**Expected behavior**
Should be able to convert json report into Powershell object.

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project: netcore
 - Framework Version: netcoreapp3.1
 - Stryker Version: 1.1.0

**Additional context**
This is the command used to convert the report to a Powershell object:
$strykerData = (Get-Content $jsonReport -Raw | Out-String | ConvertFrom-Json )

**Comment by richardwerkman** [comment]
Hmm that's odd... We just use the default JSON serializer from .net core. Wouldn't expect something like this to happen. However, we did change JSON serializer not long ago. Do you know since when this behaviour occurs?

**Comment by rouke-broersma** [comment]
Was the json report already pretty-printed or did you use some tool to accomplish this? I don't think we should be pretty-printing the report. Perhaps this was changed when we switched to system.text.json.

**Comment by gmdunlop** [comment]
My bad! We have a bug in our code where we are handling the json before our print statement. This issue can be closed now.
