### ISSUE TITLE
Stryker.NET encountered a compile error

### ISSUE THREAD

**Issue by gmdunlop** [stryker-mutator/stryker-net#1811]
**Describe the bug**
Multiple messages reporting compile errors and an unhandled System.InvalidOperationException.

**Logs**
![stryker-issue-1](https://user-images.githubusercontent.com/82120675/142891009-4114278c-4d15-4c02-9ba0-2fb55315ae7c.PNG)
![stryker-issue-2](https://user-images.githubusercontent.com/82120675/142891040-ada95e56-0f76-4288-97b2-aaf7e6b252eb.PNG)
![stryker-issue-3](https://user-images.githubusercontent.com/82120675/142891065-30f75df7-dd02-40b7-aed7-45e9b9a799ef.PNG)
![stryker-issue-4](https://user-images.githubusercontent.com/82120675/142891080-052be9d0-5c58-459c-92c5-e34d35ea3a68.PNG)

**Expected behavior**
Stryker successfully calculates the mutation score.

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project: netstandard
 - Framework Version: 2.0
 - Stryker Version 1.1.0

**Additional context**
Was working fine on version 0.22.11.
Version 1.0.1 had similar messages, but no exception was thrown.
All other builds and test runs are succeeding.

**Comment by richardwerkman** [comment]
This is gonna be hard for us to pick up without a reproduction scenario. Could you maybe find out what method is causing the compile errors and post that method here? 

Btw this could be related to #1745

**Comment by gmdunlop** [comment]
It looks like all of the compiler errors are coming from property declarations with get/set methods. It's saying that there were paths that didn't return a method, but it's just a plain get method.
![compile_error](https://user-images.githubusercontent.com/82120675/146566193-d018690f-026a-437d-8215-feb4c632ecf1.PNG)
 Also, are the compile errors related to the exception thrown at the end?

**Comment by gmdunlop** [comment]
Also #1839 seems to be reporting the same problem.

**Comment by rouke-broersma** [comment]
Sounds similar to #1839 yes

The errors at the end are related. When we find a compiler error we try to remove the bad mutation. In the case of the block mutator we can't find the location of the mutation so we have to rollback everything.
