### ISSUE TITLE
Linq mutator

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#182]
We would like to add a new mutator that mutates Linq queries. It should look for specific methods and replace them with their counterpart or remove them. The following methods should be mutated:

| Original | Mutated | 
| ------------- | ------------- | 
| `Distinct()` |  |
| `Reverse()` |  |
| `OrderBy()` |  |
| `OrderByDescending()` |  |
| `SingleOrDefault()` | `FirstOrDefault()` |
| `FirstOrDefault()` | `SingleOrDefault()` |
| `First()` | `Last()` |
| `Last()` | `First()` |
| `All()`  |  `Any()`  |
| `Any()`  | `All()`  |
| `Skip()`  |  `Take()`  |
| `Take()`  |  `Skip()`  |
| `SkipWhile()`  |  `TakeWhile()`  |
| `TakeWhile()`  |  `SkipWhile()`  |
| `Min()`  | `Max()`  |
| `Max()`  | `Min()`  |
| `Sum()`  | `Count()`  |
| `Count()`  | `Sum()`  |

**Comment by eTomate** [comment]
I'd love to give it a shot. Already looked into it a little and might have a lot of questions :)

**Comment by richardwerkman** [comment]
@etomate cool! Please let us know if you need help or have questions :+1:

**Comment by eTomate** [comment]
Hey @richardwerkman - I'm not entirely sure, how we could detect the syntax of a Linq Query, since there is no explicit SytanxKind nor ExpressionSyntax for it.
I've boiled it down to an InvocationExpressionSyntax and added an Enumerable for the different LinqExpression - but I'm not very confident, that this is the matching type. Do you have any ideas?

It feels very hacky to be honest.

Thank you ;)

**Comment by richardwerkman** [comment]
Well, I don't think we can detect Linq Syntax, since it's not an actual C# kind. We can only detect the name of methods. In this case I think it's oke to assume that every method with the `IdentifierName` "All" is an Linq all method. The only way to know that for sure is by reading the semantic model. 

We chose not to create an semantic model for each file since this is an expensive operation. We chose to mutate everything we can, while trusting the RollBack mechanism to resolve our "broken mutations". 

So if your mutator wrongly mutates an "All()" invocation, we can trust Stryker to handle this. 

I hope this helps!

**Comment by eTomate** [comment]
Thanks for the hints @richardwerkman. Can you assign this issue to me (since I can't :D).
Looks fine as of right now - but I'm not fully understanding the rollback for now. I'll have a look into it today over the weekend.

**Comment by simondel** [comment]
Unfortunately we can only assign issues to people who have permissions on this GitHub repo :/

Richard did add an "in progress" label though :)

**Comment by Mobrockers** [comment]
Implemented by #185
