### ISSUE TITLE
Remove configuration file restrictions

### ISSUE THREAD

**Issue by pinkfloydx33** [stryker-mutator/stryker-net#1822]
**Is your feature request related to a problem? Please describe.**

Stryker CLI 1.x throws an exception if the configuration file contains any properties not defined in the schema. Particularly it throws if there's anything more than a root `stryker-config` object. This is overly restrictive and does not match the behavior of 0.x.

We run Stryker as part of our pipelines using a few generic build scripts. All of the existing pipelines are using version 0.x and it's configuration file format. I can't update existing projects enmasse (yet) so I had planned to include a new root `stryker-version` property in the config file for new projects/those I *can* update. My script would then know which version of Stryker to install/run (lack of the property would indicate version zero) and which variation of the config file CLI argument to use. 

Unfortunately this doesn't work as the CLI throws an error because the config file is only allowed to have a single, root `stryker-config` property. 

This is way too restrictive. Any good json parser should be able to ignore properties not defined in the deserialized model. What's more, this does not jive with the suggestion in the [CLI documentation](https://stryker-mutator.io/docs/stryker-net/configuration/#config-file-path) for the config file path argument where it mentions storing your configuration in an AppSettings.json file. 

https://github.com/stryker-mutator/stryker-net/blob/75cbec233ef24d326db04c66eade384851964118/docs/configuration.md#L34

For Stryker v0, I also had some "commented" settings left in the config file that I was trying out but didn't want to remove completely. For example putting an "x" in front of the property name for concurrency which I don't want set during CI but that the Dev could "uncomment" locally. We can't do this any more either as the CLI validates all levels of the config. 

**Describe the solution you'd like**
Please allow arbitrary json properties at any level of the configuration file. System.Text.Json can ignore properties not in the model (or load them into a dictionary of left over values) 

**Describe alternatives you've considered**
I ended up leaving the added properties in the configuration file. On the fly, my script creates a new configuration file with the added properties removed and passes *that* to the CLI instead. This works, but it's a lot of jumping through hoops. And now I've broken local development... The dev will need to remove it if they want to run locally **and** make sure they don't accidentally check it back in.

**Comment by rouke-broersma** [comment]
Just to clarify, you're saying we're validating properties outside of the stryker-config object?

**Comment by pinkfloydx33** [comment]
Pretty much, yes.

You're also validating the presence of additional properties within the Stryker config object. That's not so bad and I can understand doing that (it just differs from v0 so was also a surprise)

**Comment by rouke-broersma** [comment]
That's no good :) 

For your other use case with disabling config but not removing I think we could simply support comments in the json. You can then comment out the unused config. Would that be acceptable?

**Comment by pinkfloydx33** [comment]
Yeah. It's possible your parser actually supports that, I never tried. I typically assume that comments are unsupported as it's bit me before. I can give it a whirl tomorrow and see if it works or not

**Comment by rouke-broersma** [comment]
We use system text json. It's probably an option to turn on and won't work out of the box.

**Comment by pinkfloydx33** [comment]
@rouke-broersma thanks for fixing!! Any ETA on when it will be released? 

Should I open another issue for supporting comments? It should be pretty simple:

https://github.com/stryker-mutator/stryker-net/blob/81b28a6eb2c451754467ca6f4ad7cf8f49944ea7/src/Stryker.CLI/Stryker.CLI/JsonConfigHandler.cs#L71

Could be:
```csharp 
var opts = new JsonSerializerOptions { ReadCommentHandling = JsonCommentHandling.Skip };
var root = JsonSerializer.Deserialize<FileBasedInputOuter>(json, opts);
```

[ReadCommentHandling](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.readcommenthandling?view=net-5.0)
[JsonCommentHandling](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsoncommenthandling?view=net-5.0)

**Comment by rouke-broersma** [comment]
@pinkfloydx33 if you could open a new feature request that would be great

**Comment by pinkfloydx33** [comment]
Thanks! Opened #1831
