### ISSUE TITLE
Weird handling of platform-related preprocessor directives 

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1824]
**Describe the bug**
We heavily use framework symbols in code, e.g. `NET5_0_OR_GREATER`, the full list is [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#conditional-compilation). This allows us to leverage the latest .NET capabilities whenever possible, given that we usually target multiple platforms in the code.

Recently we've noticed strange things going on here. Consider a project for .NET 6 and this code:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/5451366/143911560-26192f04-1115-4666-b7bb-184a71a92de3.png">

Here's the Stryker execution result:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/5451366/143911698-d596cef9-0792-4535-9f69-86606dc5c96c.png">

Two things are wrong here:
1. For the code compiled conditionally, there are no mutants created although they should be - everything targets .NET 6 here.
2. For the code compiled unconditionally, the mutants are marked as "no coverage" although things are covered there. If I remove conditionally compiled code (and related tests), I get 100% mutation score.

**An odd semi-workaround**
If I remove conditionally compiled **tests**, I get a bit happier situation:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/5451366/143913212-2ea29fc7-8557-4006-b1f9-0fa0b6799ab9.png">

Mutants in the conditionally compiled code are still not created (and this is still wrong) but at least the other part works normally. This is not really acceptable because the ordinary code coverage starts crying, so to satisfy that part as well here's what can be done:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/5451366/143913485-fea1039e-e258-4492-bfd7-d89a67baed09.png">

This produces the same result as above (when conditionally compiled tests are deleted). Code coverage is okay. But the expected mutants are still not created so this is not good.

**Expected behavior**
Stryker correctly produces mutants in the conditionally compiled code.

**Desktop:**
 - OS: Windows
 - Type of project: Core
 - Framework Version: .NET 6
 - Stryker Version: 1.1.0

**Additional context**
At least some preprocessor directives are handled correctly:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/5451366/143914056-ebc9407c-e672-43c6-bf9a-b687d38e18ee.png">

Here's the repro: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/7619973/Repro.zip)

**Comment by rouke-broersma** [comment]
That is very strange, I don't think we do anything special with preprocessor directives. Almost as if Roslyn skips reading those syntaxes automatically.

**Comment by psfinaki** [comment]
Well, we only know for now that ordinary code coverage doesn't seem to have issues here... E.g. if project targets frameworks A and B and half of the code (and tests) targets only B, there will be just more tests executed for B.

**Comment by dupdob** [comment]
Here is why (probably) happens:
1) the predefined symbols are properly defined for the building of the tests assembly
2) the predefined symbols are NOT DEFINED for Roslyn analysis
 ⇒ the `SomeClass.Substract(...)` method definition is not parsed, hence not mutated.
 
 Note idea why the first run ends with `NoCoverage` status, but you could check my theory by manually defining the symbol in the project configuration. You should get the expected mutants.

**Comment by psfinaki** [comment]
Hmm alright, I'll update you on this.

**Comment by psfinaki** [comment]
@dupdob yes, tried that, your theory seems to be correct. I'm now trying to understand why everything else manages to work then.

**Comment by richardwerkman** [comment]
Closing as this is being handled in @dupdob's issue
