### ISSUE TITLE
Stryker reports NaN instead of 0% for code without real tests

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1825]
**Describe the bug**
Accidentally noticed this when playing with another bug :D 

The simplest repro is to just have an empty test:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/5451366/143924362-599c37a3-5c8f-47ac-9455-d9e68363efe4.png">

Then Stryker logs this:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/5451366/143924005-82905d4f-c8a1-4576-a8ed-dcf3d30f3d06.png">

The report itself correctly shows 0 though:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/5451366/143924116-f33873c6-018f-4247-a48e-16d04483f04c.png">

Also, apparently if I "cover" this test (with shit :D), Stryker does report 0%:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/5451366/143924307-7382e44c-3a97-4954-a3d0-fc6e03b8d37d.png">

<img width="840" alt="image" src="https://user-images.githubusercontent.com/5451366/143924436-e8ae3b0f-4746-4317-a2cb-526a567c09dc.png">

**Expected behavior**
0% in Stryker logs.

**Desktop:**
 - OS: Windows
 - Type of project: Core
 - Framework Version: .NET 6
 - Stryker Version: 1.1.0

**Additional context**
Repro: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/7620429/Repro.zip)

**Comment by rouke-broersma** [comment]
This is defined behavior 👍 
If there is nothing to calculate because there was nothing to test, the defined behavior is to report the mutation score as NaN.

You could argue that we should not expose this to the user and should simply omit the mutation score completely.

**Comment by psfinaki** [comment]
Okay, this argument makes sense. On the other hand:
1. The score is different in the report and in the console
2. With code coverage this case would likely bring 0 score, so why not have similar logic here

From a customer perspective, 0 would be more useful to me - that said I'll die if you leave things as they are, at least this is not a bug then.

**Comment by rouke-broersma** [comment]
The report should actually display NaN afaik.. Not sure what's up with that. @nicojs @hugo-vrijswijk is Stryker.NET wrong here or is the html report?

**Comment by hugo-vrijswijk** [comment]
From what I can see, there are 2 mutants generated, both with the status `NoCoverage`. In the [metrics](https://stryker-mutator.io/docs/mutation-testing-elements/mutant-states-and-metrics/#metrics) the score is calculated as `detected / valid * 100`. `NoCoverage` falls under the `valid` category (`detected + undetected`, `undetected = survived + noCoverage`), so the score should be `0 / 2 * 100 = 0%`. So I'd say this is wrong in Stryker.NET
