### ISSUE TITLE
Declare standard predefined symbols when building mutated assemblies

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#1828]
**Is your feature request related to a problem? Please describe.**
See issue #1824 

**Describe the solution you'd like**
Stryker needs to declare predefined symbols when building the mutated assembly.

**Describe alternatives you've considered**
Those symbols can be explicitly declared in the (VS/VC) project settings, but this defeats the purpose of predefined symbols.

**Additional context**
It appears Roslyn does not add them automatically. So the code may have to declare them according the target framework version. Any official method would obviously be preferable.

**Comment by psfinaki** [comment]
So I still don't completely understand it. Why symbols like `NET6_0` are understood whereas symbols like `NET6_0_OR_GREATER` are not? [This](https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries#how-to-multitarget) basically says that all these `_OR_GREATER` symbols were added with .NET5.

**Comment by dupdob** [comment]
We need to test this, but are you certain that some symbols are automatically defined ? my understanding is that those are defined by MsBuild targets and Stryker does not use those (until we find a way to cleanly inject mutated source code during MsBuild builds).

**Comment by psfinaki** [comment]
Yes, actually Stryker currently works _ideally_ for platform monikers other than _OR_GREATER_, and `target-framework` option in the config also performs correctly with that.

Look: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/7669842/Repro.zip)

For this class:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/5451366/145065854-a0f1ec13-d336-4303-b840-d88e1e0ddc8a.png">

This is what Stryker does:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/5451366/145065931-fb87da89-8a74-46b8-afce-b5dc3ce2d420.png">

100% behavior that we need.

**Comment by psfinaki** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/5451366/145066266-36e0b76a-a691-4d37-8294-8ef589f8d662.png">

It looks like internally _something somewhere_ doesn't use the .NET5+ SDK.

**Comment by rouke-broersma** [comment]
@psfinaki the build _system_ is msbuild. We don't use msbuild so we don't have those symbols by default is what my guess would be. Why we do have some of the symbols I do not know.

**Comment by richardwerkman** [comment]
I was able to reproduce this issue and could not see a workaround. So I created an issue with buildalyzer.

**Comment by psfinaki** [comment]
Thanks for that, @richardwerkman
