### ISSUE TITLE
Support JSON comments in configuration file

### ISSUE THREAD

**Issue by pinkfloydx33** [stryker-mutator/stryker-net#1831]
**Is your feature request related to a problem? Please describe.**
There are configuration options we like to set locally (ex. concurrency) but not on CI. There's also times when we try out new settings but are in a sort of limbo state as to whether we want to keep them. 

In Stryker 0.x we could keep these settings in the config file but prefix them with some value so that they didn't get read in. When we wanted to use them we'd just remove the prefix. This is useful for local testing but also when trying out new settings. We could also add dummy properties that included comments explaining why certain settings were a particular way. 

With Stryker 1.x this is no longer possible since it validates the configuration object, so we need to remove them entirely. 

See #1822 for more information

**Describe the solution you'd like**
Support comments in JSON. This way we can leave the settings in the configuration file, commented out... or even add comments about why certain options are configured the way they are.

System.Text.Json supports comments, however it is disabled by default. So this request is simply to enable json comments via `JsonSerializerOptions.ReadCommentHandling`

**Describe alternatives you've considered**
Not leaving temporary items in configuration and keeping a separate config or a Readme file documenting why we've selected certain configuration options. 

**Additional context**
https://github.com/stryker-mutator/stryker-net/blob/81b28a6eb2c451754467ca6f4ad7cf8f49944ea7/src/Stryker.CLI/Stryker.CLI/JsonConfigHandler.cs#L71

Could be:
```csharp 
var opts = new JsonSerializerOptions { ReadCommentHandling = JsonCommentHandling.Skip };
var root = JsonSerializer.Deserialize<FileBasedInputOuter>(json, opts);
```

[ReadCommentHandling](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.readcommenthandling?view=net-5.0)
[JsonCommentHandling](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsoncommenthandling?view=net-5.0)

**Comment by pinkfloydx33** [comment]
@richardwerkman @rouke-broersma Thanks folks!

**Comment by richardwerkman** [comment]
You're welcome! This should be released shortly :)
