### ISSUE TITLE
Handle multiple project files in one folder

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1883]
**Is your feature request related to a problem? Please describe.**

So main motivation with this for us is the future of source generation. Currently we have the following project structure:
- src
   - Generators
   - ProjectA (uses Generators)
   - ProjectB (uses Generators)
   - ...
- test
  - Generators.Tests
  - ProjectA.Tests
  - ProjectB.Tests
  - ...

Note that the fact that we can mutation test source generation is very important for us :)

Now I have a script that (simplified) relies on this structure, creates source-test project pairs (including Generators x Generators.Tests), then from each test folder runs `dotnet stryker -p ProjectX`, then merges the mutation reports.

This works as of now, but - long story short - such a project structure leads to problems with dependencies around source generation. .NET 6 made things worse because it has another version of Roslyn which has another version of source generation. 

To makes things work in that field, we'll go the way that .NET itself goes. Take [System.Text.Json](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Text.Json) for example. Notice it has "gen" folder with 2 project files for each version of Roslyn:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/5451366/151565975-db7d0a82-109c-4ff8-b813-0341ef240e2b.png">

Some goes for tests:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/5451366/151566177-c6825cb5-0675-4851-a195-7b488b0d077c.png">

So the structure will be:
- src
    - ProjectA
      - gen
         - Generators.Roslyn3.11.csproj
         - Generators.Roslyn4.0.csproj
      - src
         - ProjectA.csproj 
    - ProjectB
      - gen
         - Generators.Roslyn3.11.csproj
         - Generators.Roslyn4.0.csproj
      - src
         - ProjectB.csproj 
- tests
    - ProjectA
      - gen.Tests
         - Generators.Roslyn3.11.Tests.csproj
         - Generators.Roslyn4.0.Tests.csproj
      - ProjectA.Tests
         - ProjectA.Tests.csproj 
    - ProjectB
      - gen.Tests
         - Generators.Roslyn3.11.Tests.csproj
         - Generators.Roslyn4.0.Tests.csproj
      - ProjectB.Tests
         - ProjectB.Tests.csproj 

Now this will create a problem for Stryker in the mode we currently use. For source generation, we won't be able to run Stryker neither from the test folder nor from the source folder because both contain two project files. Configuration file doesn't help as well.

**Describe the solution you'd like**
This all sounds complicated as "I'm making a case" :D But basically we just need here simple and explicit command line options which would mean "run this test project against this source project". Probably same stuff in config file for consistency.

**Describe alternatives you've considered**
Nothing better than generating extra folders on the fly and moving project files there at the same time rewriting the files themselves (basically adding extra "..\\" for every project reference).

**Comment by rouke-broersma** [comment]
So your biggest problem is that you cannot select the test project to run from the command line 0 options?

**Comment by psfinaki** [comment]
Yes. Probably? What do you mean by "command line 0 options"? :)

But yeah basically I get `Specify which project file to use because this <folder> contains more than one project file.`, in both cases - when I try to run Stryker from the tests folder and when I try to run in from the source folder. Both folders contains multiple project files.

**Comment by psfinaki** [comment]
So what do you think? Will this be alright? I can probably jump on that soon. I believe we have all the stuff for implementing this, just some reshuffling in CLI?

**Comment by rouke-broersma** [comment]
Currently we have two ways to get the project contents. First we use buildalyzer, if that fails we scan the disk. Scanning the disk for files will not work properly in this scenario since we don't use the project file to determine what is included. We have wanted to deprecate and remove this method for a while. I think we need to do this before we support multiple project files in the same folder. @richardwerkman what do you think?

**Comment by psfinaki** [comment]
Take your time and enjoy the vacation. It can wait until next week :)

**Comment by richardwerkman** [comment]
We still have a bug in solution runs that get the wrong project files from buildalyzer. For now it is non blocking as solution runs are broken anyways (thanks to vstest). But once the vstest issue is resolved we will have to look into how we locate, filter and read project files. So @psfinaki if you could start this that would help us! I think we need to rework how stryker runs as a whole (from test project folder or not) once solution runs are a thing. We should simplify and remove any unwanted ways of running stryker IMO. I haven't thought about what way would be the best and how it would work.

**Comment by psfinaki** [comment]
Alright. So I will start with this and try to bring something working without much intervention. And then, once solution runs are there, the whole thing probably can be reworked :)
