### ISSUE TITLE
Breaks when using reproducible builds

### ISSUE THREAD

**Issue by AshleighAdams** [stryker-mutator/stryker-net#1899]
When attempting to mutation test something built with deterministic/continuous integration set in versions equal to or greater than 1.3.0, the test *usually (but not always)* fails with a varying error:

```
Unhandled exception.

no valid language detected || no valid csproj or fsproj was given
```

**Expected behavior**
Mutation test to complete.

**Desktop (please complete the following information):**
 - OS: Windows & Linux, likely others
 - Type of project: core
 - Framework Version: net 5.0
 - Stryker Version: >= 1.3.0

**Additional context**
Can be reproduced by cloning [Verlite](https://github.com/AshleighAdams/Verlite), setting the `GITHUB_ACTIONS` env var to `true` and launching the mutation test:

```bash
Ashleigh@Ashleigh-PC MINGW64 /c/Git/Verlite/tests/UnitTests (lock-stryker-version)
$ GITHUB_ACTIONS="true" dotnet stryker --reporter html --reporter progress --log-to-file

   _____ _              _               _   _ ______ _______  
  / ____| |            | |             | \ | |  ____|__   __| 
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |    
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |    
  ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |    
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|    
                   __/ |                                      
                  |___/                                       


Version: 1.3.1

[19:21:08 INF] Identifying project to mutate.
[19:21:10 INF] The project C:\Git\Verlite\src\Verlite.Core\Verlite.Core.csproj will be mutated.
[19:21:12 WRN] Buildalyzer could not find sourcefiles. This should not happen. Will fallback to filesystem scan. Please report an issue at github.
[19:21:13 INF] Analysis complete.
[19:21:13 INF] Building test project C:\Git\Verlite\tests\UnitTests\UnitTests.csproj (1/1)
[19:21:24 INF] Time Elapsed 00:00:16.4759913
Unhandled exception.

no valid language detected || no valid csproj or fsproj was given
```

[log-20220210.txt](https://github.com/stryker-mutator/stryker-net/files/8043674/log-20220210.txt)
[VsTest-log.host.22-02-10_19-12-32_80171_9.txt](https://github.com/stryker-mutator/stryker-net/files/8043675/VsTest-log.host.22-02-10_19-12-32_80171_9.txt)
[VsTest-log.txt](https://github.com/stryker-mutator/stryker-net/files/8043676/VsTest-log.txt)

**Comment by rouke-broersma** [comment]
This is actually way more concerning to me, as this fallback method is basically deprecated and we are intending to remove it: 

``` 
[19:21:12 WRN] Buildalyzer could not find sourcefiles. This should not happen. Will fallback to filesystem scan. Please report an issue at github.
``` 

We will want to fix this for users using reproducible builds, fixing this will also fix the other errors. It seems like Buildalyzer cannot deal with projects using reproducible builds in CI (so in CI mode which as you said before makes things deterministic including normalizing source paths). The fix might be to simply delete the CI msbuild property from the buildalyzer analysis. We should discuss with upstream if this is something that should be done in general or if this is something that should be done on a case-by-case basis.

**Comment by 0xced** [comment]
I'm currently trying to reproduce this issue on a local checkout of the repository and what's baffling is the non reproducible nature of this bug. Performing the following commands on a local checkout _sometimes_ works and _sometimes_ fails with the `Buildalyzer could not find sourcefiles` warning.

```
git clean -fdx
cd tests/UnitTests
GITHUB_ACTIONS="true" dotnet stryker --reporter html --reporter progress --log-to-file
```

And that's really _sometimes_, I can't reproduce this problem 100% of the time!

**Comment by 0xced** [comment]
OK, so I found something very interesting: when [selecting the `IAnalyzerResult`](https://github.com/stryker-mutator/stryker-net/blob/stryker%401.3.1/src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs#L107) in ProjectFileReader.cs, the `First()` method is used.

```csharp
if (targetFramework == null)
{
    return analyzerResults.First();
}
```

But the `analyzerResults` collection actually contains 2 elements, that's probably what explains the non reproducible nature of this bug.

One of them is the expected (valid) analyzer result and the other one is a broken analyzer result containing no references nor source files. I noticed that for the broken result, the `TargetFramework` property is `null`. That's probably an issue to report to the [Buildalyzer](https://github.com/daveaglick/Buildalyzer/issues) repository.

As a workaround, using `analyzerResults.First(e => e.TargetFramework != null)` instead of `analyzerResults.First()` seems to solve this issue.

**Comment by 0xced** [comment]
Further investigating into Buildalyzer, I figured it will probably difficult to fix this issue in Buildalyzer because a null target framework is [expected for C++ projects][1].

```csharp
// use an empty string if no target framework was found, for example in case of C++ projects with VS >= 2022
```

So filtering out analyzer results that don't have a target framework as hinted in my previous comment is probably the way to go.

[1]: https://github.com/daveaglick/Buildalyzer/blob/v3.2.8/src/Buildalyzer/Logging/EventProcessor.cs#L101-L106

**Comment by 0xced** [comment]
I just opened #1900 to address this issue.

**Comment by 0xced** [comment]
I opened https://github.com/daveaglick/Buildalyzer/pull/198 on the Buildalyzer repository.

**Comment by patanric** [comment]
I have similar problem:

```
Version: 1.5.0

[17:13:47 INF] Identifying project to mutate.
[17:13:54 INF] The project /home/vsts/work/1/s/Natzka.WebAPI.Web/Natzka.WebAPI.Web.csproj will be mutated.
[17:14:29 WRN] Buildalyzer could not find sourcefiles. This should not happen. Will fallback to filesystem scan. Please report an issue at github.
[17:14:29 INF] Analysis complete.
[17:14:29 INF] Building test project /home/vsts/work/1/s/Natzka.WebAPI.Web.Tests.Unit/Natzka.WebAPI.Web.Tests.Unit.csproj (1/1)
[17:14:53 INF] Time Elapsed 00:01:06.8390154

```

I run the same task 3 times. Once for each project in the solution: Core, Infrastructure, Web.

<img src="https://user-images.githubusercontent.com/3979760/161440113-fdfbfd4d-4f10-4638-b6b6-4e7717b06fbe.png" width="400">

```
  - task: Powershell@2
    displayName: 'Run Stryker: Core'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/Natzka.WebAPI.Core.Tests.Unit'
      targetType: 'inline'
      pwsh: true
      script: '$(Agent.BuildDirectory)/tools/dotnet-stryker -p Natzka.WebAPI.Core.csproj'
```

And the only one that works is Core. Web and Infrastructure fail with the same error show above. Even If I change the sequence of the Stryker jobs, Infrastructure and Web fail.

Any Idea on why that could be?

Core just works. From the same pipeline run as above:
```
Version: 1.5.0

[17:09:26 INF] Identifying project to mutate.
[17:09:30 INF] The project /home/vsts/work/1/s/Natzka.WebAPI.Core/Natzka.WebAPI.Core.csproj will be mutated.
[17:09:32 INF] Analysis complete.
[17:09:32 INF] Building test project /home/vsts/work/1/s/Natzka.WebAPI.Core.Tests.Unit/Natzka.WebAPI.Core.Tests.Unit.csproj (1/1)
[17:09:54 INF] Total number of tests found: 175.
[17:09:54 INF] Initial testrun started.

```
