### ISSUE TITLE
Azure pipeline triggers result in sometimes 4 builds triggered for the same commit

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#191]
It seems like due to some github integrations in combination with pull request triggers and master build triggers that sometimes up to 4 builds are triggered at the same time for one commit.

**Comment by richardwerkman** [comment]
Interesting find! This could also explain the long duration of the builds? Maybe @simondel knows more about this?

**Comment by simondel** [comment]
I'll take a look at this tomorrow 👍

**Comment by simondel** [comment]
@richardwerkman what do you mean with long build times?

**Comment by richardwerkman** [comment]
@simondel sorry, I was talking about the duration of the integration test build. This takes up to 36 minutes. But this could be due to the fact that indeed 3 builds are triggered by only one commit.

![screenshot_3](https://user-images.githubusercontent.com/14224500/47110570-8035e600-d251-11e8-8f7e-561943c49ecc.png)

I guess this takes it's toll on the azure pipelines resources.

**Comment by Mobrockers** [comment]
We can run up to 10 parallel jobs and every job is run on a new agent so that should not be the case.

**Comment by simondel** [comment]
Each build has two environments so keep in mind that each build will take up two parallel jobs.

**Comment by Mobrockers** [comment]
Every single build takes about the same 35 minutes to complete though, I would expect the timings to be off if one build was blocked because we ran out of parallel instances.

**Comment by simondel** [comment]
I have removed some duplicate webhooks. Let's see if this fixes the issue.

**Comment by Mobrockers** [comment]
Seems to have been azure/github integration bug and not something on our side. Seems to no longer occur.

**Comment by abhijeetdhoke** [comment]
I am facing same issues 

<img width="698" alt="image" src="https://github.com/stryker-mutator/stryker-net/assets/7963809/20522f10-5a29-481c-a78e-d67297ccc8ba">
