### ISSUE TITLE
Use of unassigned local variable

### ISSUE THREAD

**Issue by nheath99** [stryker-mutator/stryker-net#1923]
**Describe the bug**
I receive the warning "Stryker.NET encountered an compile error...with message: Use of unassigned local variable 'result'", and I'm asked to report this to GitHub. Please see the following repo for a minimum reproduction of the issue: https://github.com/nheath99/StrykerDemo
It seems to occur whenever a variable is declared but not initialised, and then used later in the method.

**Logs**
[log-20220221.txt](https://github.com/stryker-mutator/stryker-net/files/8112318/log-20220221.txt)

**Expected behavior**
I would not expect this exception to be thrown.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Type of project core
 - Framework Version 6.0
 - Stryker Version 1.3.1

**Additional context**

**Comment by Steve-P-Allen** [comment]
I've seen code like 

int x;
if(a) {
  x = 1;
}
else {
  x = 2
}
return x;

fail, but if x is explicitly initialized it does not fail i.e. int x = 0;

**Comment by andrepm06** [comment]
I'm also dealing with a project that generates many errors like the one described above. There are so many, that even 50 compilation retries are not enough to compile it successfully.

**Comment by dupdob** [comment]
Note that you will get rid of this errors if you disable Block mutators!.

**Comment by richardwerkman** [comment]
I can't seem to reproduce this issue anymore. Please reopen if another reproduction is found.
