### ISSUE TITLE
ConcurrencyInput should not default to 0 if Environment.ProcessorCount reports 0

### ISSUE THREAD

**Issue by maximal096** [stryker-mutator/stryker-net#1927]
**Is your feature request related to a problem? Please describe.**
When a system does return a processor count of 0 (for example gitlabs shared runners) the default value will be set to 0. This will result in a crash unless the user overrides the concurrency setting. [This issue has existed before](https://github.com/stryker-mutator/stryker-net/issues/122) and was fixed with ```Math.Max(Environment.ProcessorCount / 2, 1)```, but now exists again.

**Describe the solution you'd like**
If the Default is 0 a warning should be logged that the ProcessorCount is not reported by the system and 1 should be used to still work without overriding the value.

Something like this

```c#
if (SuppliedInput == null)
{
    if (Default.Value == 0)
    {
        logger.LogWarning("Logical processor count is not reported by the system, using concurrency of 1. "
            + "The recommended concurrency is processorCount / 2.");
        return 1;
    }
        
    return Default.Value;
}
```

Currently the code looks like this [ConcurrencyInput.cs](https://github.com/stryker-mutator/stryker-net/blob/285afbed4116cdda8c35dd68fc4d7dc4fa8b393b/src/Stryker.Core/Stryker.Core/Options/Inputs/ConcurrencyInput.cs).

**Describe alternatives you've considered**
- Settings the default to ```Math.Max(Environment.ProcessorCount / 2, 1)``` and not logging a warning.
- Logging a warning that ProcessorCount is 0 regardless of what happens. In case the value is set by the user the message that the the concurrency you set is bigger than 0 also does not make a whole lot of sence / is not a very good suggestion, so it could be skipped. But also might be overthinking this at this point. I mostly care about it not crashing by default.

**Comment by eNeRGy164** [comment]
@rouke-broersma I like to pick this one up if you don't mind
