### ISSUE TITLE
Mutants are not ingored if ExcludeFromCodeCoverage attribute has jusitification

### ISSUE THREAD

**Issue by marcoatribeiro** [stryker-mutator/stryker-net#1963]
When Justification is added to ExcludeFromCodeCoverageAttribute, the attributed code's mutants are not marked as ignored.

With Justification:
[10:33:32 INF] 11    mutants got status CompileError. Reason: Mutant caused compile errors
**[10:33:32 INF] 60    mutants got status NoCoverage.   Reason: Mutant has no test coverage**
**[10:33:32 INF] 29    mutants got status Ignored.      Reason: Removed by exclude from code coverage filter**

Without Justification:
[10:42:26 INF] 11    mutants got status CompileError. Reason: Mutant caused compile errors
**[10:42:26 INF] 39    mutants got status NoCoverage.   Reason: Mutant has no test coverage**
**[10:42:26 INF] 50    mutants got status Ignored.      Reason: Removed by exclude from code coverage filter**

**Comment by rouke-broersma** [comment]
Could you add a code example so we can see exactly how you place the justification?

**Comment by dupdob** [comment]
I am looking into this. This issue can be reproduced with a unit test.

**Comment by dupdob** [comment]
PR #1964 fixes this problem

**Comment by marcoatribeiro** [comment]
> Could you add a code example so we can see exactly how you place the justification?

Hi, @rouke-broersma!

Here's an example

```csharp
[ExcludeFromCodeCoverage(Justification = "(Reason why class is not covered in unit tests)")]
```

**Comment by rouke-broersma** [comment]
@marcoatribeiro thank you! We have fixed this and the fix has been released :)
