### ISSUE TITLE
Solution runs fail to start with error no csproj file found

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1976]
Is there any documentation on how to make this work? I added a `stryker-config.json` to my root (where my .sln-file is) and one to each project that contains which test projects to run. When I then run `dotnet stryker` or `dotnet stryker --solution MySolution.sln` in the root it says:
```
No .csproj file found, please check your project directory at C:\...
```

_Originally posted by @OskarKlintrot in https://github.com/stryker-mutator/stryker-net/issues/459#issuecomment-1076378109_

**Comment by Christian-Oleson** [comment]
Does this run for an individual csproj file if you move to the directory where the csproj file exists and run stryker from there?

**Comment by rouke-broersma** [comment]
@Christian-Oleson apologies I seem to have not been notified of your question. I assume your question is directed towards @oskarklintrot?
