### ISSUE TITLE
Ignore Mutation missing info in the docs

### ISSUE THREAD

**Issue by jkingdon-ms** [stryker-mutator/stryker-net#1991]
**Is your feature request related to a problem? Please describe.**
The documentation is unclear on what all types of mutations can be ignored via comment.

**Describe the solution you'd like**
A clear list of all the types of mutations that can be ignored, or at least a reference with clear instructions added to the `docs/ignore-mutations.md` file

**Describe alternatives you've considered**
Some kind of helper via an IDE plugin would be nice too but that's out of scope. For now just simply documenting these will help a lot.

**Comment by rouke-broersma** [comment]
Awesome, thanks!
