### ISSUE TITLE
Excluded "Regex" is not working with .Net 

### ISSUE THREAD

**Issue by lyjidapa** [stryker-mutator/stryker-net#2001]
**Describe the bug**
Getting an error when excluding "Regex" in stryger-config
> Invalid excluded mutation (Regex). The excluded mutations options are [Statement, Arithmetic, Block, Equality, Boolean, Logical, Assignment, Unary, Update, Checked, Linq, String, 
> Bitwise, Initializer, Regex]

Here is my stryker-config file
```
{
  "stryker-config": {
    "reporters": [
      "progress",
      "html"
    ],
    "project": "Agoda.Ycs.Gateway.Service.csproj",
    "mutation-level": "Basic",
    "thresholds": { "high": 60, "low": 50, "break": 30},
    "ignore-mutations": [
      "String",
      "Block",
      "Statement",
      "Checked",
      "Bitwise", 
      "Initializer",
      "Checked",
      "Linq",
      "Regex"
    ],
    "ignore-methods": [
      "*Log", 
      "*Exception" 
    ]
  }
}

```

**Logs**
Unable to get log file

**Expected behavior**
Should be able to exclude "Regex" successfully.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Type of project: .Net framework & CSharp
 - Framework Version .Net core 5.0
 - Stryker Version 1.5.0"

**Additional context**

**Comment by dupdob** [comment]
Thanks for reporting this. There is indeed an error in the parsing of this parameter. I opened a PR for this; until the fix is released, you can use `regular` (short for regular expressions) instead of Regex as workaround.
This value (`regular`) will still be supported when the fix is released
