### ISSUE TITLE
Hide excluded and N/A files from reporters

### ISSUE THREAD

**Issue by AdisonCavani** [stryker-mutator/stryker-net#2023]
It would be nice, if there was a option to hide all ``Excluded`` and ``N/A`` files from reporters.
I'm only testing my Controllers, so it doesn't make sense to show all files.
This would make the reporters cleaner.

**Comment by rouke-broersma** [comment]
Would you want this for all Reporters or only for the html report?: https://github.com/stryker-mutator/mutation-testing-elements/issues/2042
