### ISSUE TITLE
Inconsistency between log level names

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#2024]
**Describe the bug**
Basically Stryker writes
`[18:24:32 INF] Logging enabled at level Info`

for `
{
  "stryker-config": {
	"verbosity": "debug"
  }
}
`
and `
{
  "stryker-config": {
	"verbosity": "trace"
  }
}
`

**Expected behavior**
Should write respective level there.

**Desktop**
Stryker Version: 1.5.2

**Additional context**
Repro: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/8584612/Repro.zip)

**Comment by rouke-broersma** [comment]
Neither did I...
