### ISSUE TITLE
Clean up CLI OptionsBuilder GetOption

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#203]
Stryker.CLI/Stryker.CLI/OptionsBuilder.GetOption<T> was extended with non-generic threshold-options and soon with files-to-exclude logic. This is not the right place for loading config sections and should be moved

**Comment by Mobrockers** [comment]
See https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.CLI/Stryker.CLI/OptionsBuilder.cs#L53-L67

**Comment by michielpeeters** [comment]
When my PR has been accepted (after some few retries ;-) ...) I'll start with this one right away.

**Comment by richardwerkman** [comment]
@michielpeeters Good to hear! I've done some work for this too in another branch. Maybe you can find some inspiration here:
https://github.com/stryker-mutator/stryker-net/blob/excluded-mutations/src/Stryker.CLI/Stryker.CLI/OptionsBuilder.cs
