### ISSUE TITLE
Target .NET 6 within the Stryker Projects

### ISSUE THREAD

**Issue by Christian-Oleson** [stryker-mutator/stryker-net#2031]
**Is your feature request related to a problem? Please describe.**
This is not related to any problems I have with Stryker.

**Describe the solution you'd like**
.NET 5 is currently the target framework within the solution. .NET 5 will go EOL very soon. We should move to .NET 6. There are performance benefits as well as supportability benefits.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by rouke-broersma** [comment]
Agreed. The reason we did not yet switch is because this is technically a breaking change (requires newer dotnet runtime) and we had recently gone out of beta and to V1 already. We should do this before .NET 5 is EOL.

**Comment by Christian-Oleson** [comment]
> Agreed. The reason we did not yet switch is because this is technically a breaking change (requires newer dotnet runtime) and we had recently gone out of beta and to V1 already. We should do this before .NET 5 is EOL.

That's 5 days away:
[May 10, 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

**Comment by Christian-Oleson** [comment]
I've added [a PR to move to .NET 6](https://github.com/stryker-mutator/stryker-net/pull/2032).
