### ISSUE TITLE
Continue on warning/error within a single file/mutant/test

### ISSUE THREAD

**Issue by GrahamTheCoder** [stryker-mutator/stryker-net#2073]
**Is your feature request related to a problem? Please describe.**

Primary aim: As a user, I want to see a mutation report for my project.
Secondary aim: I'd also like to do whatever I can to help improve the project over time,

I was about to leave it running overnight since it predicted 5 hours for the full run, and just happened to check it first and see it had stopped on one of the first few tests with absolutely no output for the tests it had done.

The first couple of times I tried this tool over the years with similar results (though not the same bug), I didn't have time to do anything about it, so having gained nothing from an hour put in to trying the tool, it went back to the bottom of my pile. I'd love the user base (and contributor base) of this tool to grow, so I think it's important to show a new user some value (in my case, providing a mutation report).

**Describe the solution you'd like**

Mutation test run continues as best it can (could have some cutoff percentage like I think it does when more than 50% of the initial test run fails).
If an individual test is causing issues, it is skipped.
The report at the end shows what percentage of tests had issues and what percentage of files could not be mutated for some reason, and invites me to report issues to improve future accuracy.

I'm suggesting this on the understanding that this tool has bugs, *and will always have bugs* that affect some tests, or some source files.

In order to discourage people from ignoring issues, you could have the "cutoff percentage" mentioned be version high by default, but allow it to be lowered by configuration if needed

**Describe alternatives you've considered**
Could stop at first error, provide the mutation report up to that point, and the syntax required to skip that test or source file. Again: Some percentages should be reported so it's clear the mutation report isn't "complete".

**Additional context**

See a few comments on the issue that brought this idea to mind: https://github.com/stryker-mutator/stryker-net/issues/2069#issuecomment-1139451810

**Comment by GrahamTheCoder** [comment]
One example is the issue I linked in additional context. But this isn't about specific issues, it's about being fault tolerant.

It relates to files since the behaviour I want for general issues already seems to happen with files that confuse stryker (e.g. Use of unassigned variable). Though I'd suggest the output report should make these issues clear and easy to report, rather than just being in the log.

On the other linked issue, a command line override was suggested. Rather than on/off, a percentage might allow errors to be noticed initially, but then users to get on with achieving their primary aim

**Comment by rouke-broersma** [comment]
Okay so if I understand you correctly you want a certain class of errors that might happen during testing a mutation (you say file but I think you mean mutation) to be a non-fatal error that gets reported on after the fact.

As far as I know the only runtime error that might happen to specific mutations instead of all mutations is the specific one you're hitting.

**Comment by GrahamTheCoder** [comment]
### Classes of isse

* In the general mutation testing algorithm, I see a few major categories of things being looped over.
* I would describe those things as **Source files**, **mutants** and **tests**.
* Each one has a class of errors where only some of that category are affected.

For each source project file, there are potentially many mutants each covered by potentially many of the tests in the test project.

To help explain what I mean by those terms, glancing at the [first page of bugs](https://github.com/stryker-mutator/stryker-net/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9B+Bug%22):

**Source file** (from the source project)
https://github.com/stryker-mutator/stryker-net/issues/1506 Stryker tries various mutations on this file, then fails. But if it mutated other files, it could continue.

**Mutant**
https://github.com/stryker-mutator/stryker-net/issues/1445 only affects a subset of mutants (e.g. Changing `-=` to `+=` probably can't cause it). If it tried other mutations on the same file it could proceed. 

**Test** (from the test project)
https://github.com/stryker-mutator/stryker-net/issues/2069 only affects a subset of tests (e.g, ones that were fast in the initial run). From the discussion, it sounds like other very similar issues may have existed in the past around parallelism and an xunit quirk around time measurement. Stryker is at the mercy of changes to the test framework really.

### This issue's suggestion re-stated

My suggestion is to add a consistent approach to continue in each of those classes of error. And potentially a way to control that behaviour from config (how *far* to try to continue in the face of errors).

### Is it worthwhile?

I explained in the original why I thought it might be valuable to users like me. But if any given class of errors is rare enough to not be worth the complexity of code in handling the error, then obviously leave that one out. If all of them are left out on that basis, then close the issue.

If you still have no idea what I'm talking about, then perhaps @dupdob can interpret for me a little.

**Comment by GrahamTheCoder** [comment]
> we report on this at the end

Ah OK, I guess that's what the "compile error" bit of the report means. My colleague and I did wonder over that! If I see a way to make it clearer and easier to report such issues, I'll raise it separately.

Overall it sounds like you're in agreement for general direction but that "bugs that can be continued from" in files and tests are very rare.

I'll close this and continue discussion on those specific issues, and perhaps later open another more specific issue for continuing from one of them.
