### ISSUE TITLE
Stryker fails to build a project

### ISSUE THREAD

**Issue by ankitadeore19** [stryker-mutator/stryker-net#2093]
I have configured stryker in the azure build release pipeline as below:
- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-stryker'
  inputs:
      command: custom
      custom: tool
      arguments: install dotnet-stryker --tool-path $(Agent.BuildDirectory)/tools

- task: Powershell@2
  displayName: 'Run dotnet-stryker'
  inputs:
      workingDirectory: '<test-project-path>'
      targetType: 'inline'
      pwsh: true
      script: $(Agent.BuildDirectory)/tools/dotnet-stryker

The Error I got is below -

2022-06-21T11:12:13.3312954Z [11:12:13 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
2022-06-21T11:12:13.3315132Z [11:12:13 FTL] Stryker.NET could not compile the project after mutation. This is probably an error for Stryker.NET and not your project. Please report this issue on github with the previous error message.

It was suggested to report this on github . Any help will be appreciated 
Thanks.

- [ ]

**Comment by rouke-broersma** [comment]
Hi @ankitadeore19 

The error you've shown does not show what is actually going wrong. Do you have any further errors, warning or stack traces available?

**Comment by ankitadeore19** [comment]
@[rouke-broersma](https://github.com/rouke-broersma) Attaching the error log here.
[ErrorLog.txt](https://github.com/stryker-mutator/stryker-net/files/8973408/ErrorLog.txt)

**Comment by dupdob** [comment]
Thanks. Judging by the provided log file, it appears that some referenced assemblies are not being resolved properly, hence the build fails. As this is a very rare occurence, Stryker does not report the error properly. This has nothing to do with Safe Mode. I will open an issue to see if we can improve that.
Back to your issue!
`Stryker.NET encountered an compile error in ...\JDAT.SABD.JDQuoteIntegration\DataSync\AnnotationDataSync.cs (at 5:16) with message: The type or namespace name 'Utility' does not exist in the namespace 'JDAT.SABD' (are you missing an assembly reference?) (Source code: Utility)`

if this 'Utility` assembly referenced in some specific way ? or maybe it is distributed via a private Nuget source?

Could you add the _log to file option_ (either -L or --log-to-file) and provide the resulting file so we get all details about the build ?

**Comment by rouke-broersma** [comment]
Since we have not heard back from you with necessary information I am going to go ahead and close this issue. Feel free to comment with a reproducible result at your convenience so we can reopen and take a looko.
