### ISSUE TITLE
Changelog strategy

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-net#21]
How will we create the changelog for new releases? 

For Stryker itself, we use [conventional commit messages](https://conventionalcommits.org/). With those we can generate beautiful changelogs. It also helps to clean up our commit messages. A win-win situation.

An example would be: `feat(parser): add ability to parse arrays.`. This translates to:

""
## Features
 
 **Parser:** add ability to parse arrays.
""

For C# i would suggest taking a look at clog: https://github.com/clog-tool

@richardwerkman if you agree: i would suggest starting squashing PR into single commits while using these commit messages.

**Comment by richardwerkman** [comment]
Closed by #205
