### ISSUE TITLE
Stryker 2.1.0 Incorrect Survived Mutations

### ISSUE THREAD

**Issue by wessonben** [stryker-mutator/stryker-net#2118]
**Describe the bug**
Upgrading from v2.0.0 to v2.1.0 produces different results.  Tests that cover string mutations are not analyzed correctly in v2.1.0 and therefore it reports that the mutations survived despite the tests failing.

**Logs**
See attached file where I ran v2.0.0, then updated to v2.1.0 and ran stryker again.

**Expected behavior**
Expect failing tests to be detected and for the mutations to be killed.

**Desktop (please complete the following information):**
 - OS: Windows 10 (and also GitLab pipeline on Linux)
 - Type of project: .NET 6
 - Framework Version: .NET 6
 - Stryker Version: 2.1.0

**Additional context**

**Comment by wessonben** [comment]
[stryker log.txt](https://github.com/stryker-mutator/stryker-net/files/9243760/stryker.log.txt)

**Comment by wessonben** [comment]
Source code to replicate the problem.
[MutationDemo.zip](https://github.com/stryker-mutator/stryker-net/files/9243775/MutationDemo.zip)

**Comment by dupdob** [comment]
thanks for reporting this with special mention for the reproduction project. it helped a lot.
There has been a regression indeed with static mutations. I have been able to fix the problem on my machine; I will open a PR probably tomorrow with the fix. I need to check why this problem got through and ensure there is an automated regression test to cover this.

**Comment by dupdob** [comment]
just pushed PR #2121 with the fix

**Comment by wessonben** [comment]
Thanks for the quick response @dupdob. I will try the new release when available.

**Comment by rouke-broersma** [comment]
The fix has been released
