### ISSUE TITLE
Detect test projects not supported by VsTest

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#2126]
**Is your feature request related to a problem? Please describe.**
At least one user had troubles with Stryker because its test project was missing key references for proper VsTest support.

**Describe the solution you'd like**
Stryker should properly detect such scenario and guide users toward resolution. Arguably, Stryker could automatically inject needed dependencies.

**Describe alternatives you've considered**
This problem may be rare and may not warrant development effort.

**Additional context**
This issue is open to discuss implementation strategy

**Comment by dupdob** [comment]
My original intent was to perform a dependency analysis when no test was detected at initialization; Stryker could then output a guidance message, such as `Add NUnit3TestAdapter package to project 'TestProject.csproj'`.
Alternatively, Stryker could fail when needed dependencies were not detected like it does for MsTest V1 projects.

**Comment by rouke-broersma** [comment]
Imo we don't need to get too fancy here. 

If we don't find any of mstest testadapter, xunit adapter or nunit adapter (whatever the name is for each) we can fail with a recommendation to add the correct adapter for their used testframework(s). 

As far as I'm concerned we don't even have to check which test framework they use nor if test discovery is failing. We simply fail if there is not at least one test adapter. We can fine tune later and add checks for other test adapters that might be used if that ever happens. 

We could also add something to the getting started about requiring the test project be executable with dotnet test (though I'm not sure if that should only be for dotnet (core), I think dotnet framework tests can't be executed with dotnet test).

**Comment by dupdob** [comment]
> if we don't find any of mstest testadapter, xunit adapter or nunit adapter (whatever the name is for each) we can fail with a recommendation to add the correct adapter for their used testframework(s).
I am not confortable with this, I think this is too restrictive. There are many test frameworks and several test adapters for the most popular ones ([see here](https://www.nuget.org/packages?q=testadapter)). So this logic would result in Stryker supporting only xUnit,NUnit or MSTest for no valid reason.
And if a popular framework updates the name of its adapter, we need to upgrade Stryker and impacted people must upgrade.

Hence my intent to do it only when there is an issue.

Alternatively, we could raise a warning message, such as: _"no known test adapter detected, please add the proper one if no test is detected"_.

My intent with being specific for NUnit, XUnit and MSTest was to provide automatic assistance to those concerned as an attempt to prevent them to open issues about this.

**Comment by rouke-broersma** [comment]
Looking at that list I'm not as worried as you, those testadapters are near unused.

**Comment by dupdob** [comment]
Maybe, but:
1. There are popular alternative runner (eg: `TeamCity.VSTest.TestAdapter`)  ⇒ we need to support those
1. you may have noticed that xUnit is not part of the list. It is because its runner is called `xunit.runner.visualstudio`  ⇒ how to we identify them.
My fear is that this rule will lead to issues that simply do not exist today. I feel that doing nothing would be better.

**Comment by rouke-broersma** [comment]
We can start with warning and if we feel comfortable at some point, if ever, we can change our to error. I would prefer to log this warning even if we can detect the tests, perhaps ask them to let us know which testadapter they use, because then we could try to validate against that testadapter and add it to the list of known working testadapters. 

As for teamcity, I'm not convinced that would work with Stryker anyway, that testadapter seems to be purely so you can run tests from teamcity pipelines.
