### ISSUE TITLE
Feature Request: Markdown Reporter

### ISSUE THREAD

**Issue by guypritchard** [stryker-mutator/stryker-net#2133]
**Is your feature request related to a problem? Please describe.**
Yes.  We've been using Striker within our CI pipeline.  Something we'd like to do is to easily add the simple console output to the PR as a PR comment.  PR comments can be Markdown and given the simple results are in table format a Markdown table would be really useful.  We've been doing this with standard Covlet coverage values and it works really well.
Open to other ideas to achieve this BTW.

**Describe the solution you'd like**
I'd love to have another reporter which can create a fairly simple Markdown table within a file which is created after the Mutators have run.

**Describe alternatives you've considered**
I'd considered using the ClearText output and somehow transforming that into markdown.  Is anyone doing that? 

**Additional context**
I'm happy to do this - I've been working on something locally - but I want to follow the process and ensure this is something which the project is happy to take on.

**Comment by rouke-broersma** [comment]
I don't have any objections

**Comment by guypritchard** [comment]
I've got a proposal for this functionality here:  https://github.com/guypritchard/stryker-net/pull/1 

Happy to change anything about it.  I'd love to help out in any way I can with this project, honestly.  This is a terrific project!

**Comment by rouke-broersma** [comment]
I would actually prefer if you would open the pr against our repo because otherwise we might have to review multiple times. We don't mind if it's not completely finished, we appreciate the effort.

**Comment by guypritchard** [comment]
Ah - yes, will do. I didn't want to pollute your repo :D

I'll change that shortly.

**Comment by guypritchard** [comment]
I've added the PR for you - happy to make any changes.  I'm still 'living with it' so early feedback extremely welcome.

**Comment by guypritchard** [comment]
@rouke-broersma - thanks so much for merging that, and thank you for your patience and assistance getting it over the line.  If there's anything I can do to help the project now or in the future, please reach out.

(I'm not sure what the process is for closing feature requests - happy for you to close this one off whenever you're ready.)

**Comment by rouke-broersma** [comment]
I forgot to link the issue to the pr, I'll close the issue now. Help is always welcome! We have a mountain of open issues you could take a look at ;) Feature suggestions are of course also welcome and if you implement them yourself even better. If you plan to it is best to discuss with us first as you did here.
