### ISSUE TITLE
AzureFileShareBaseline SAS Token Generation in Azure Devops

### ISSUE THREAD

**Issue by StormMaster12** [stryker-mutator/stryker-net#2148]
**Describe the bug**
AzureFileShareBaseline does not seem to be compatible with the SAS token generated by Azure CLI in Azure Devops

Example Azure CLI Task
```
    task: AzureCLI@2
    displayName: Create SAS Token for Stryker
    inputs:
      azureSubscription: ""
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $end = date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'

        $storageAccountKey = az storage account keys list -g ${{parameters.resourceGroup}} -n ${{parameters.storageName}} --query [0].value -o tsv
        $sasToken = az storage fs directory generate-sas --name stryker/ --file-system ${{parameters.storageName}} --account-name ${{parameters.storageName}} --account-key $storageAccountKey --expiry $end --https-only --permissions rwld -o tsv

        Write-Host "##vso[task.setvariable variable=ContainerSasToken]$sasToken"
        Write-Host "##vso[task.setvariable variable=ContainerSasToken;isOutput=true]$sasToken"
```

The above task generates the sas token sucesfully.
`se=2022-08-25T14%3A27Z&sp=rwdl&spr=https&sv=2021-06-08&sr=d&sdd=1&sig=XXXXXXXXXXXXX`

However when passing the token to Stryker, the token is not valid.
```
[13:57:58 ERR] Creating directory failed with status Forbidden and message 
<?xml version="1.0" encoding="utf-8"?>
   <Error>
      <Code>AuthenticationFailed</Code>
     <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Time:2022-08-25T13:57:58.5748519Z
      </Message>
     <AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail>
   </Error>
```

Believe the issue to either be with the token generation. If it is then how to generate the token correctly is not easy to find. Or an issue within AzureFileShareBaseline, specifically where the sas token is appended to the fileshare url. Appending the sas token to  `sv=`  is leading to an incorrect token.
```
var fileUrl = $"{_options.AzureFileStorageUrl}/{_outputPath}/{version}/stryker-report.json";
            var url = new Uri($"{fileUrl}?sv={_options.AzureFileStorageSas}");

            using var requestMessage = new HttpRequestMessage(HttpMethod.Get, url);
```

**Logs**
For us to best assist you in diagnosing the problem we would ask you to run stryker with the option `--log-to-file` or `-L` and to attach the resulting logs to the issue.

**Expected behavior**
Expect an Azure CLI SAS token to be valid when using AzureFileShareBaseline in Azure Devops

**Desktop (please complete the following information):**
 - OS: Linux, Azure Devops
 - Type of project: Core
 - Framework Version: .Net 6
 - Stryker Version: 2.2.0

**Additional context**

**Comment by rouke-broersma** [comment]
Is `se` a new token format or something? Tbh we're not that familiar with azure storage sas so we implemented this in a best effort based on the process when generating a sas, at the time, through the azure portal. If other token types exist, which need to be supplied through a different query parameter, then I guess we just need to start supporting that format.

**Comment by StormMaster12** [comment]
Yeah sorry, was experimenting with different commands. Have tried with `az storage account generate-sas` as well to no avail. So was clutching at straws.

It was previously working before v2.2.0. Generating the sas tokens in the 2019 format.

```
   - task: AzurePowerShell@5
     displayName: Create SAS Token for Stryker
     inputs:
       azureSubscription: ""
       ScriptType: InlineScript
       Inline: |
         $storageAccountKey = ((Get-AzStorageAccountKey -ResourceGroupName ${{parameters.resourceGroup}} -Name "${{parameters.storageName}}")| Where-Object {$_.KeyName -eq "key1"}).Value
         $storageContext = New-AzStorageContext -StorageAccountName ${{parameters.storageName}} -StorageAccountKey $storageAccountKey
         $sasToken = New-AzStorageShareSASToken -ShareName "stryker" -Permission "rwld" -Context $storageContext -ExpiryTime (Get-Date).AddHours(1)       

         Write-Host "##vso[task.setvariable variable=ContainerSasToken]$sasToken"
         Write-Host "##vso[task.setvariable variable=ContainerSasToken;isOutput=true]$sasToken"
       azurePowerShellVersion: LatestVersion
       pwsh: true
       condition: eq(${{ parameters.useBaseline }}, true)
```

**Comment by tidusjar** [comment]
Here's an idea.

For some reason we are modifying the incoming SAS token:
https://github.com/stryker-mutator/stryker-net/blob/ddb01a8de512d4b9adc8af5a388f16eacd86bb87/src/Stryker.Core/Stryker.Core/Options/Inputs/AzureFileStorageSasInput.cs#L22

and then putting it back in the URL
https://github.com/stryker-mutator/stryker-net/blob/ddb01a8de512d4b9adc8af5a388f16eacd86bb87/src/Stryker.Core/Stryker.Core/Baseline/Providers/AzureFileShareBaselineProvider.cs#L57

The solution might just be that we need to not do this and use the URI builder to generate the URI?

**Comment by rouke-broersma** [comment]
Please do :)

**Comment by tidusjar** [comment]
So when using `az storage share generate-sas` it doesn't generate the token with the `?` prefix. I suggest we add validation around the token and rely on .net to generate the query parameters.
