### ISSUE TITLE
Stryker.NET throws Unhandled exception. System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Lutti1988** [stryker-mutator/stryker-net#2157]
**Describe the bug**
Stryker runs into problem, whenever I try to run it in an azure devops build pipeline. The following output is produced with the command `dotnet stryker --project "MyProject" --solution "MySolution.sln" --reporter "progress" --reporter "json"` within the unit test project folder.
Weird is, that the DLLs are searched in project/**bin**/debug/net6.0/**ref**/ instead of project/**obj**/debug/net6.0/**ref**/ , because there is no "ref" folder in bin/debug/x

**Logs**
Output:
![image](https://user-images.githubusercontent.com/61962587/187937661-361d1e0d-d717-495c-9e67-f4921c86f538.png)

**Expected behavior**
The DLLs should be searched in the correct folder.

**Desktop (please complete the following information):**
Azure DevOps Server 2020 Update 1.1 - .NET 6.0 - dotnet-stryker 2.2.0

**Additional context**
On my local machine (Windows 10 - .NET 6.0 - dotnet-stryker 2.2.0) everything works fine.

**Comment by rouke-broersma** [comment]
As far as I can tell that is your unit test failing to resolve it's dependency. What happens if you run dotnet test and dotnet vstest on that testproject?

**Comment by Lutti1988** [comment]
Removing the solution file parameter does not change anything. Same result. 
`dotnet test` result:
![image](https://user-images.githubusercontent.com/61962587/188062021-24ebb74d-3846-485c-8de5-5552d8f1d7c7.png)

`dotnet vstest` result:
![image](https://user-images.githubusercontent.com/61962587/188063639-16061e9f-085a-4953-b768-7c176c585532.png)


Is there maybe a problem with projects referencing other projects? I have a Project-A, a Project-A-UnitTest and a Project-B. Project-A has Project-B as a reference.

**Comment by rouke-broersma** [comment]
Other projects as references are not a problem, especially not when you specify which project to test explicitly.

**Comment by richardwerkman** [comment]
@Lutti1988 is this still an issue in the latest version?

**Comment by dupdob** [comment]
assumed issue is fixed
