### ISSUE TITLE
"No project reference matched the given project filter" on MacOS

### ISSUE THREAD

**Issue by dannyyy** [stryker-mutator/stryker-net#2194]
**Describe the bug**
Running Stryker on MacOS 12.6 fails always with the error message `No project reference matched the given project filter '<path> Choose one of the following'`. Using the same config or CLI arguments on Windows works as expected. Also tried full paths, relative path (with `./` and without)

```
dotnet stryker --solution ZombieSurvivalGame.sln --project ZombieSurvivalGame/ZombieSurvivalGame.csproj --test-project ZombieSurvivalGame.Test/ZombieSurvivalGame.Test.csproj --log-to-file

   _____ _              _               _   _ ______ _______  
  / ____| |            | |             | \ | |  ____|__   __| 
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |    
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |    
  ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |    
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|    
                   __/ |                                      
                  |___/                                       


Version: 3.0.1

[09:08:04 INF] Identifying project to mutate.
[09:08:05 INF] Time Elapsed 00:00:00.9238072
Stryker.NET failed to mutate your project. For more information see the logs below:


No project reference matched the given project filter 'ZombieSurvivalGame/ZombieSurvivalGame.csproj'Choose one of the following references:

  /Users/dannyyy/Development/temp/ZombieSurvivalGame/ZombieSurvivalGame/ZombieSurvivalGame/ZombieSurvivalGame.csproj
```

**Logs**
For us to best assist you in diagnosing the problem we would ask you to run stryker with the option `--log-to-file` or `-L` and to attach the resulting logs to the issue.
[log-20220930.txt](https://github.com/stryker-mutator/stryker-net/files/9681619/log-20220930.txt)

**Expected behavior**
Recognizing the appropriate projects under MacOS

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Type of project: Microsoft .NET
 - Framework Version 6.0.400
 - Stryker Version 3.0.1

**Additional context**

**Comment by richardwerkman** [comment]
I'll take a look at this. However I can't test this locally since I'm running windows.

**Comment by dannyyy** [comment]
Let me know if I can test a pre-release to give feedback.

**Comment by richardwerkman** [comment]
I have created a PR that could fix this. Can you test if this works now on MacOs?

**Comment by richardwerkman** [comment]
See https://github.com/stryker-mutator/stryker-net/blob/master/CONTRIBUTING.md on how to setup your local environment
