### ISSUE TITLE
Mutation algorithm optimalisation

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#22]
Right now _all_ code is checked by every mutator. Some code is not fit for mutating so will always return 0 mutations. Therefore it is not necessary to check this code. Example:

```
using Stryker.Core.Initialisation.ProjectComponent;
using Stryker.Core.Mutants;
using Stryker.Core.Testing;
using System;
using System.Globalization;
using System.IO;
using System.Linq;

namespace Stryker.Core.Reporters
{
    /// <summary>
    /// The default reporter, prints a simple progress and end result.
    /// </summary>
    public class ConsoleRapportReporter : IReporter
    {
``` 
Cannot be mutated by any mutator. So why call the mutators onto these nodes?

Suggestion: only mutate method bodies.

**Comment by nicojs** [comment]
What is the problem you're trying to solve? I wouldn't fix this issue unless you have a problem.

**Comment by richardwerkman** [comment]
Closing the issue because of low priority.
