### ISSUE TITLE
Does not work with Rider / .NET Core 2.1?

### ISSUE THREAD

**Issue by ehouarn-perret** [stryker-mutator/stryker-net#222]
I followed the tutorial given https://stryker-mutator.io/stryker-net/quickstart applied to Rider and turns out that the CLI part cannot be installed:

```
NU1202: Package StrykerMutator.DotNetCoreCli 0.4.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package StrykerMutator.DotNetCoreCli 0.4.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
NU1212: Invalid project-package combination for StrykerMutator.DotNetCoreCli 0.4.0. DotnetToolReference project style can only contain references of the DotnetTool type 
Package restore failed. Rolling back package changes for [...]
```

Which leads me to think that it's issue regarding the version (2.1) of .NET Core I am using for that (xUnit) Test Project.

Any idea?

**Comment by Mobrockers** [comment]
Yes, apologies. We tried to add dotnet global tool support in the previous release, but we did not notice that this broke the dotnet CLI extension tool support. We have reverted this change but need to release a new package for it. In the mean time you could use version 0.3.0 or install stryker as a global dotnet tool instead of a package reference in your project.

**Comment by Mobrockers** [comment]
@ehouarn-perret  Version 0.5.0 of Stryker has been published and includes the fix for this issue. It should be available on nuget.org within the next 15 minutes - half hour.

**Comment by ehouarn-perret** [comment]
> @ehouarn-perret Version 0.5.0 of Stryker has been published and includes the fix for this issue. It should be available on nuget.org within the next 15 minutes - half hour.

Wosh, you're really awesome!

**Comment by simondel** [comment]
@Mobrockers for some reason the changelog for 0.5.0 was not properly generated :confused:

**Comment by ehouarn-perret** [comment]
> With mutation testing we make changes to your source code and test the outcome using your test project.
> 
> It looks like your test project contains no reference to another project that may contain your source code. Because of that, Stryker.NET cannot find any code to mutate.

I know it's sort of dirty (playing without an external project) but say I have a test project, so Stryker can't mutate the entities in that same project? 
Necessarily need to have another one?
