### ISSUE TITLE
Stryker entering safe mode due to compilation error

### ISSUE THREAD

**Issue by Vespion** [stryker-mutator/stryker-net#2253]
**Describe the bug**
While running stryker, the console output indicated a problem had occurred during compilation and that this should be reported as a GitHub issue.
`
[02:09:13 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
`

**Logs**
For us to best assist you in diagnosing the problem we would ask you to run stryker with the option `--log-to-file` or `-L` and to attach the resulting logs to the issue.
[log-20221025.txt](https://github.com/stryker-mutator/stryker-net/files/9856379/log-20221025.txt)

**Expected behavior**
I would expect this message to not appear during regular use of stryker

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Framework Version: .Net 6
 - Stryker Version: 3.0.1
 - IDE: JetBrains Rider

**Additional context**
No other errors have occurred, and the output reports do not show any changes between when this error message was not printed and now.

The reported location of the compiler errors is in the MathsExpressions file in my project. I have attached this file in case this is helpful...if you can read spaghetti code anyway.

`
[02:13:03 WRN] Stryker.NET encountered an compile error in icws94.compilation\Parsers\MathsExpressions.cs (at 147:7) with message: Use of unassigned local variable 'on' (Source code: on)
`

`
[02:13:03 WRN] Stryker.NET encountered an compile error in icws94.compilation\Parsers\MathsExpressions.cs (at 131:7) with message: Use of unassigned local variable 'on' (Source code: on)
`

[MathsExpressions.txt](https://github.com/stryker-mutator/stryker-net/files/9856381/MathsExpressions.txt)

**Comment by kant2002** [comment]
Isn't this is the same as https://github.com/stryker-mutator/stryker-net/issues/1923

**Comment by Vespion** [comment]
Possibly but for the lines where the errors occur, I am using pattern matching in an if statement, which should initialise the variable unless the statement fails, I think.
Come to think of it, I am (ab)using the type system a fair amount which probably isn't helping stryker not trip up.

**Comment by richardwerkman** [comment]
The releated issue #1923 seems to be fixed by now. @Vespion Please reopen this issue if you still encounter this.
