### ISSUE TITLE
Support multiple mutator types

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#2261]
**Is your feature request related to a problem? Please describe.**
The [mutator types](https://github.com/stryker-mutator/stryker-net/blob/4efadc2c5874efb2f5f712e777b825e47ef26da5/src/Stryker.Core/Stryker.Core/Mutators/Mutator.cs) support only one description at the moment. If we want to rename a type we have to deprecate the old name and introduce a new name. This requires support for multiple description attributes.

**Describe the solution you'd like**
I'd like to be able to set two or more descriptions for each mutator type like:
```cs
        [Description("Arithmetic operators")]
        [Description("Math operators")]
        Arithmetic,
```

Both names should work to exclude them in the options.

**Describe alternatives you've considered**
We don't want to mark descriptions as deprecated but will announce this using the changelog and blogposts.

**Comment by ysbakker** [comment]
Microsoft uses comma separation on their `[Authorize]` attribute to allow multiple users: https://learn.microsoft.com/en-us/aspnet/core/security/authorization/roles?source=recommendations&view=aspnetcore-6.0#adding-role-checks

**Comment by Liam-Rougoor** [comment]
Just checked, code with duplicate attributes like this issue description suggests won't compile.

**Comment by Liam-Rougoor** [comment]
By default, the Description attribute from System.ComponentModel does not allow duplicates. I will add a custom attribute to override this behavior to allow duplicates.
