### ISSUE TITLE
AssignmentOperator mutator removes the trailing space

### ISSUE THREAD

**Issue by PBonnema** [stryker-mutator/stryker-net#2271]
**Describe the bug**
The mutator for assignment operators removes the whitespace just after it in its output.
![image](https://user-images.githubusercontent.com/3737630/198705513-18ef487d-dc1c-4731-8f35-92d29c81d32a.png) 

**Logs**
[logs.txt](https://github.com/stryker-mutator/stryker-net/files/9890899/logs.txt)

**Expected behavior**
For the space to remain in the mutator output.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project core
 - Framework Version 6.0
 - Stryker Version 3.0.1

**Additional context**

**Comment by ysbakker** [comment]
Wasn't this fixed in #2276?

**Comment by rouke-broersma** [comment]
It was fixed between operands, but not at the start of expressions.

**Comment by ysbakker** [comment]
I think that's #2270

**Comment by rouke-broersma** [comment]
You're right, closing.
