### ISSUE TITLE
Mutants on some pre-increment/decrement operators don't compile

### ISSUE THREAD

**Issue by PBonnema** [stryker-mutator/stryker-net#2272]
**Describe the bug**
Mutants for pre-increment/decrement operators at the start of a statement don't compile:
![image](https://user-images.githubusercontent.com/3737630/198706748-75cb0d9f-dfc5-4405-9d8e-8ab5203c9657.png)

**Logs**
[logs.txt](https://github.com/stryker-mutator/stryker-net/files/9890932/logs.txt)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project core
 - Framework Version 6.0
 - Stryker Version 3.0.1

**Additional context**
@rouke-broersma  believes this might have to do with the fact these statements are always placed with the tertiary operator instead of using the ifs even though this doesn't work in the above case.

**Comment by dupdob** [comment]
I will have a look, but first and foremost: it makes no sens mutating those, as they will systematically result in un-killable mutant. Probably a good thing they do not compile for now.

**Comment by richardwerkman** [comment]
How will they be un-killable? The value of a changes from 4 to 2 after this mutation right? How is that un-killable?

**Comment by dupdob** [comment]
Wow. I was not thinking clearly this morning. Was imagining some post to pre mutator, I guess.

**Comment by richardwerkman** [comment]
No worries! Thanks for taking a look :)

**Comment by dupdob** [comment]
This is fixed. Stryker was lacking a specific Orchestrator for PrefixUnaryOperator (like there is a Postfix one).
