### ISSUE TITLE
Document all possible ways to run stryker

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#2281]
We're missing documentation on how to run stryker.

We should add 3 chapters explaining how to:
- Run from testproject context
- Run from targetproject context (with --test-projects)
- Run from solution context

**Comment by richardwerkman** [comment]
This should be added to https://github.com/stryker-mutator/stryker-net/blob/master/docs/getting-started.md#prepare

**Comment by richardwerkman** [comment]
Note that the solution context feature is still being worked on. But current implementation requires running stryker from the solution file directory AND passing the --solution option. In that case stryker will automatially detect all projects in the solution and run agains all projects

**Comment by rouke-broersma** [comment]
> This should be added to https://github.com/stryker-mutator/stryker-net/blob/master/docs/getting-started.md#prepare

I don't think we should put advanced configuration in the getting started.

**Comment by ysbakker** [comment]
> > This should be added to https://github.com/stryker-mutator/stryker-net/blob/master/docs/getting-started.md#prepare
> 
> I don't think we should put advanced configuration in the getting started.

Should there be a new "Running stryker" page?

**Comment by rouke-broersma** [comment]
I was thinking something like 'operating modes'
