### ISSUE TITLE
GitDiffProvider should skip stryker config file

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#2292]
**Describe the bug**
https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/DiffProviders/GitDiffProvider.cs#L58
Currently we skip any file called stryker-config.json but we also allow users to supply their own config file. We should add the config file, if used, to the https://stryker-mutator.io/docs/stryker-net/configuration/#sinceignore-changes-in-string option

**Comment by Liam-Rougoor** [comment]
@rouke-broersma instead of forcing Stryker to ignore config files (which users can't opt out of), we could just let users opt-in by adding the config files to the ignore option themselves. I'll remove the automatic ignore of stryker-json.config.
