### ISSUE TITLE
Stryker lacks support for shared projects

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#230]
My first attempts with Stryker on NFluent resulted in no mutants being generated.
After ruling out configuration error and looking at the codebase, I understood this was a limitation due to us relying on shared projects to list source files (see [this project file](https://github.com/tpierrain/NFluent/blob/master/src/NFluent.Standard.20/NFluent.Standard.20.csproj)).
I have worked on a first implementation for this feature, and I am ironing out tests before sendin a PR

**Comment by richardwerkman** [comment]
We have not seen the use of shared projects before, so this is the first time we hear of this issue. Good to hear you are already working on a feature for this. I'll add this to our backlog and I'm looking forward to your PR :)
