### ISSUE TITLE
Stryker cannot recover when unable to rollback a mutant

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#236]
When Stryker fails to rollback a compilation error, the mutated assembly cannot be built and all tests result in survivors. This is obviously not a desirable behaviour.

Having a failsafe fallback strategy would prevent this for happening. For example, restoring the source file to its non mutated state would ensure the file can be compiled successfully.

**Comment by richardwerkman** [comment]
This would be nice to have! But I don't think that we should enable this by default. We want Stryker to be able to rollback all mutations it makes. Skipping a whole file of mutating because of one failed rollback is not desirable. We could however add a "safe mode" that implements this feature. This gives people a way to handle when a "bug" introduces itself in stryker.

This could look like `--safe-mode`. 

@dupdob what do you think about this?

**Comment by dupdob** [comment]
Could you clarify this?
> Skipping a whole file of mutating because of one failed rollback is not desirable.

I think of only one good reason: ensuring that no bug is silently ignored due to this. There is the risk that people will permanently add the _--safe_mode_ toggle, but I understand the intent.

Note that there is also another alternative strategy, which would be significantly slower:
Add mutant to the file one by one than running the compilation until you find the culprit.
It could be a _--diagnose_mode_ for example.

By the description of my issue is wrong, and I am sorry for that. What actually happens is that Stryker crashes with an unrelated exception due to this bit:
https://github.com/stryker-mutator/stryker-net/blob/f6ab6015f95ddeef0bf0dc0f4855f61c47fba7fd/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs#L95-L98

The algorithm will fail at the next loop due to the null id:
https://github.com/stryker-mutator/stryker-net/blob/f6ab6015f95ddeef0bf0dc0f4855f61c47fba7fd/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs#L107-L114

With a strange exception regarding the syntax tree.

**Comment by richardwerkman** [comment]
> Skipping a whole file of mutating because of one failed rollback is not desirable.

Well, if we restore the whole file to its original contents all made (correct) mutations are deleted. So we obviously don't want this to happen too often. 

A `--diagnose_mode` would not be needed if you ask me. This could help to find out what mutations cannot be rollbacked. But we strive to be able to rollback all mutations Stryker makes. We can just repoduce the issue locally to find out what mutation could not be rollbacked.

If you found a case where a mutation couldn't be rollbacked you probably found a bug. We should fix it. But we would still implement a `--safe-mode` to give people a way to still use Stryker even though they found a bug, while we fix it.

> There is the risk that people will permanently add the --safe_mode toggle, but I understand the intent.

I don't think this is a bad thing. By default the --safe-mode should do exactly the same as a normal run. But if they find a bug, their run will still succeed. We could even decide to enable this "safe mode" by default and choose to add a `--dev-mode` setting to use in our integration test. That way our integration test will fail when a mutation cannot be rollbacked, but users will not have to use a special command to fix a bug.

**Comment by chris579** [comment]
Is it worth reporting any failed rollbacks or should I wait until there is some diagnostics mode that actually puts out some useful error data?

**Comment by dupdob** [comment]
I suggest you report it. There is no identified plan to implement a diagnose feature: this requires a significant effort for implementation, will add significant delay at run time, for dubious value.
