### ISSUE TITLE
prevent operating system from sleeping mid run

### ISSUE THREAD

**Issue by brah-mcdude** [stryker-mutator/stryker-net#2365]
my laptop is set to sleep after 1 minute of no input. running stryker on my project takes about 16 minutes. while running stryker i cannot work on my code / laptop. so i need to leave my laptop. but if i leave, then it sleeps and the run stops. i wish for stryker to at least have the option to block my laptop from sleeping. can this be done? and also, after stryker run is done, it should revert to normal sleeping scheme.

**Comment by rouke-broersma** [comment]
This seems like a can of worms I don't really want to get in to to be honest. Can't you just disable sleep for a bit?

**Comment by brah-mcdude** [comment]
that's what i started doing. so it is not an urgent feature.

**Comment by brah-mcdude** [comment]
i am closing this issue.
