### ISSUE TITLE
Handling of inline methods

### ISSUE THREAD

**Issue by fabianeichfeldt** [stryker-mutator/stryker-net#237]
Hi,

I am using stryker since a few weeks and be really happy with it. 
My latest changes of my project includes an inline method which results in a crash of Stryker :-(

> System.ArgumentException: Node to track is not a descendant of the root.
>    at Microsoft.CodeAnalysis.SyntaxNodeExtensions.TrackNodes[TRoot](TRoot root, IEnumerable`1 nodes) in /_/src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions_Tracking.cs:line 43
>    at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, ICollection`1 diagnosticInfo)
>    at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics)
>    at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms)
>    at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
>    at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)

Avoiding the inline method is a proper workaround for me right now. But of course it would be nice to be able to use inline methods in a later version :-)

**Comment by fabianeichfeldt** [comment]
Oh, maybe this is a duplicate to #236

**Comment by richardwerkman** [comment]
My guess is that this is a duplicate of: #134 and will be fixed by #207

**Comment by richardwerkman** [comment]
Hi @fabianeichfeldt, it looks like this specifically happens when an out parameter is named Any. The Linq mutator mutates this into All. 

```csharp
if (System.Environment.GetEnvironmentVariable("ActiveMutation") == "0")
{
    All = retVal.Any;
}
else
{
    Any = retVal.Any;
}
return retVal.TopicNamespaceLocation;
```

This results in the error: The out parameter 'Any' must be assigned to before control leaves the current method. 

I guess we should take a look at the Linq mutator. It should only mutate method names and not variable names. This would resolve this issue.

**Comment by richardwerkman** [comment]
I've created an issue for this bug #250

**Comment by fabianeichfeldt** [comment]
@richardwerkman: I've tested it, both issues are fixed right now! :-)
Thanks a lot

**Comment by richardwerkman** [comment]
@fabianeichfeldt You're welcome! Have fun using Stryker :)
