### ISSUE TITLE
Specify which project file to use because contains more than one project file.

### ISSUE THREAD

**Issue by codmw44** [stryker-mutator/stryker-net#2371]
**Describe the bug**
During run 'dotnet stryker' output is 
> Specify which project file to use because this '/Users/andrewv/Desktop/DummyProject' contains more than one project file.
Even with specify project at stryker-config.json and by command line

**Logs**
[stryker Specify which project file to use.log](https://github.com/stryker-mutator/stryker-net/files/10327326/stryker.Specify.which.project.file.to.use.log)

**Expected behavior**
Find exist project 

**Desktop (please complete the following information):**
 - OS: MacOS (M1)
 - Type of project: framework
 - Framework Version: v4.7.1
 - Stryker Version: 3.4.0

**Comment by rouke-broersma** [comment]
You should run from the folder where either your sln or your source project is located. You're currently running from your desktop.

**Comment by codmw44** [comment]
Please take a look on the last two commands
```
andrewv@m-andreyv-23T5 DummyProject % dotnet stryker --verbosity trace --log-to-file -f "./stryker-config.json" 
Specify which project file to use because this '/Users/andrewv/Desktop/DummyProject' contains more than one project file.
```

**Comment by Liam-Rougoor** [comment]
What does your stryker-config look like? Did you specify the project there?
