### ISSUE TITLE
Have `highest-available` option for `target-framework`

### ISSUE THREAD

**Issue by Marvin-Brouwer** [stryker-mutator/stryker-net#2372]
Hi, 

I noticed that the documentation states the following:
![image](https://user-images.githubusercontent.com/5499778/210403321-f4932ddd-fff0-4c10-b5a9-3da3263661c6.png)

This makes sense to be random, however, I don't like that I have to update that setting in the config now every time I want to add a new runtime.
I have a multi-targeted project with a `net7` test-suite so I want `net7` stryker only.

I'd like to suggest some additional settings for the [`target-framework` setting](https://stryker-mutator.io/docs/stryker-net/configuration/#target-framework-string):
Consider projects with these targets:
```xml
<TargetFrameworks>net6.0;net7.0;netstandard2.1</TargetFrameworks>
```

- `highest-available` => This would look at the options and select the newest: `net7.0`
- `project-default` => This would mean the project visual studio would default to when you first open the sln: `net6.0`

The names are just a suggestion, at the end I'm just looking for a way to automatically select the highest framework available.

Alternatively, auto detecting the test-suite only has `net7` support would also help me out.
However, that just sounds more difficult.

**Comment by rouke-broersma** [comment]
`This would mean the project visual studio would default to when you first open the sln`, don't really know what this means, there is no default target framework as far as I know. Highest available could work, just non-trivial to implement.

**Comment by Marvin-Brouwer** [comment]
To clarify the `This would mean the project visual studio would default to when you first open the sln`.
If you've never opened a solution, so you don't have a `.vs` folder (I think it's actually about the `.suo` but that's in there)
Visual studio needs to select a version here:
![image](https://user-images.githubusercontent.com/5499778/210411826-bc64324a-4e18-4d67-9d3b-ad8eaf735c68.png)
I don't think it's documented anywhere, but it appears that it just looks at the `<TargetFrameworks>` node, splits it by `;` and selects the first it finds:
![image](https://user-images.githubusercontent.com/5499778/210411996-8c92e291-fedb-40a1-b229-34796414efb4.png)
I may be mistaken, but that's what it looks like to me.

I'd say that's a lot less trivial to implement than figuring out what the newest available version is.

**Comment by rouke-broersma** [comment]
There's no guarantee we have that information in that order because we don't read the csproj itself. The csproj gets read by msbuild and we take the result from msbuild (through a 3rd party library) . If both msbuild and this library maintain the ordering that might work. That's a big if and undocumented behavior basically.

**Comment by Marvin-Brouwer** [comment]
That makes sense to me. 
So I guess the only viable option would be to haven an option that would figure out the newest framework.
I would really like that, however, since I have a workaround I can imagine that this will be put low in the backlog.

**Comment by psfinaki** [comment]
By the way the docs are incorrect, we don't select randomly anymore, we [pick the first one](https://github.com/stryker-mutator/stryker-net/blob/fa6d7e54a80414fc0656604debf3f1a3c8ca1722/src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs#L127).

**Comment by psfinaki** [comment]
And yeah the frameworks can be all kinds of [weird crap](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks), imagine you have `netmf`, `wpa81` and `netstandard1.4` - I'd struggle to understand what is the "highest". 

But probably it would make sense to make some basic string comparison for a whitelist of prefixes like `net` or `wp`. Still not trivial though.

**Comment by Marvin-Brouwer** [comment]
So what does "the first one" mean in this context?
Because it looks like it's preferring `net6.0` above `net7.0` and `netcoreapp3.1`.
So I'd say that's alphabetical.

Perhaps have a custom sorter that sorts by `net`>`netcoreapp`>`netstandard`>`netframework` etc.
You cant determine the difference between `netmf` and `wpa81` etc but I highly doubt you'll ever multi-target for those.
And then you can just sort by the number that's split off.

This is just a suggestion though.

**Comment by Marvin-Brouwer** [comment]
I'd say the easiest way out would still be to use the CSPROJ file.
I had a quick peek in the analyzer used: https://github.com/daveaglick/Buildalyzer/blob/7ce6355de5737bcb9b6150faebd2310f3c1b6a1d/src/Buildalyzer/IAnalyzerResult.cs#L28
It seems that you have access to the path. So it's possible to open the project file and read the xml node.
Or maybe it's better to just file a bug with Buildalyzer to make the order of framework mirror the CSPROJ instead of alphabet?

**Comment by dupdob** [comment]
PR #2400 and PR #2928 have significantly improved the situation
