### ISSUE TITLE
Reduce number of times "ActiveMutation" envionment variable is called

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#238]
The current logic used to activate the mutant to be tested is slow, as it relies on accessing environment variables.
I prototyped a version using a cached value, thanks to a constant, and it provides significant performance improvements:
Stryker generates around 1600 mutants for NFluent projects, and a test session is around 10 seconds.

Total run time using environment variable: ~4 hours (4:07)
Total run time using a constant: 3 hours (3:09)

Your mileage may vary, but 25% time decrease is interesting.

**Comment by simondel** [comment]
Awesome! Are you able to share some code?

**Comment by simondel** [comment]
Or would this be something that you would like to fix/propose in a PR?

**Comment by dupdob** [comment]
I have a PR ready. it's just that I wait for my previous PR (#235) to be merged: having support for shared project is required to test NFluent, and I don't the courage to create a branch just with the perf improvements!
