### ISSUE TITLE
Cannot convert from 'System.Range?' to 'int'

### ISSUE THREAD

**Issue by BenjaminMichaelis** [stryker-mutator/stryker-net#2384]
**Describe the bug**
CLI asked to report the issue so here I am :)

**Logs**
Argument 1: cannot convert from 'System.Range?' to 'int' (Source code: ((StrykerqX7ixsUARtOqL6i.MutantControl.IsActive(169)?newLineBeforeExculdeStart?.Index :(StrykerqX7ixsUARtOqL6i.MutantControl.IsActive(168)?excludeRegionMatch.Index:newLineBeforeExculdeStart?.Index ?? excludeRegionMatch.Index)))..)

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .Net
 - Framework Version: .Net 6.0
 - Stryker Version: 3.4.0

**Comment by richardwerkman** [comment]
Could you maybe share a bit of the original code? So we can reproduce this locally?

**Comment by BenjaminMichaelis** [comment]
Reading stryker's console output, I believe it is looking at this line where both the index's are int
```csharp
string resultText = "Some Text";
string normalizedIndentation = resultText[(newBeforeContent?.Index ?? beginningOfContent.Index)..].ReplaceLineEndings(// do more stuff here....
```

So looks like it's just failing with the System.Range struct: https://learn.microsoft.com/dotnet/api/system.range

**Comment by dupdob** [comment]
I had a looked at it, and I now I understand why the syntax error: the mutations alter the type of expression from `int` to `int?`, which triggers the error. I think this specific situation, range definition, can be detected and avoided, but it looks harder in the general case.

Could please specify what was the issue ? was it about 'trigger safe mode'? or is it something else, like Stryker stopping on an exception?

**Comment by BenjaminMichaelis** [comment]
Sorry not sure I fully understand your question about safe mode or an exception in this case in what you are asking.

**Comment by dupdob** [comment]
no problem.
Why did you report this issue ? 
1. is it because you got the following message :
`Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.`
2. is it because Stryker crashed ?
3. other?

I think this is cause by (1), but could you please confirm 😄 ?

**Comment by BenjaminMichaelis** [comment]
Ah, I understand now. It was because of safe mode.

**Comment by dupdob** [comment]
thanks

**Comment by dupdob** [comment]
it means we should either improve error handling (in order not to remove all mutations in the method) or not mutate it in the first place.
