### ISSUE TITLE
Many undue timeout results

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#240]
Running Stryker against NFluent gives a variable number of timeouts between 12 and 15. The first three timeouts could not be explained by the mutant: running them in isolation took the usual test time (~10 seconds).
Plus, successive runs of Stryker give timeouts for different mutants.
Everything hints there is something fishy with those timeouts. I am currently doing further testing to try and understand the actual cause for those.

**Comment by dupdob** [comment]
Doing my testing, I figure that some timeouts happen each time the computer goes to sleep.
This event can happen when doing a multi-hours run on a laptop.
I have a work around available. Still testing.

**Comment by dupdob** [comment]
Further testing revealed that other timeouts are due to test runs crashing, which add delay due to windows error reporting

**Comment by richardwerkman** [comment]
Interesting, on our smaller projects we have not yet encountered this issue! Can you give an example test output of when a test run crashes? And what kind of mutation caused this crash?

I'm also curious for your workaround for the computer going to sleep.

**Comment by dupdob** [comment]
Just to be clear: the test run crashes were due to a timing issue in the test code: an event was disposed before another thread set it, triggering an ObjectDisposedException. I introduced a safeguard to catch the exception. The test no longer crashed and those timeouts were no longer reported, confirming the diagnostic.
I will revert the fix and do a stryker run, but I suspect the logs won't say much.
Anyway, I intend to keep on working on what happen when test crashes, so we could have an explicit reporting of crashes, because they require a specific analysis.

The fix for _sleep_ is pretty straightforward: you need to split the timeout in multiple steps. I redesigned the ProcessExecutor class because I initially suspected a problem with the output redirections. It looks like a wrong lead, but I think the redesign is worth a look.

**Comment by dupdob** [comment]
To be more specific on the 'sleep' issue:
- the problem is that if the computer goes to sleep for a significant period of time, the timeout will trigger instantly once the computer wakes up (at least on windows) due to the time limit being reached, while the test process made no progress. This amounts to 'wasting' the timeout period due to sleep.
- the idea is to split the timeout in several wait period. For example, instead of using a timeout of 1 seconds, I perform 10 timeouts of 100 ms. Therefore, if the computers goes to sleep during one of those wait, it simply waits 100ms(statistically 50ms) and not the full second; this translates to having a timeout of ~950ms instead of 1000ms. Unless of course the computers goes to sleep several time during the run, in which cas you loose ~50ms per sleep period

This no absolute safeguard, but in practice, this brings a significant improvements:
doing manual tests, I add two timeouts (4 Cores) each time I close and reopen the laptop with the current Stryker version. With my fix, the same test triggers NO timeouts at all.

**Comment by richardwerkman** [comment]
I doubt how many people will experience this issue, but if you create a pull request this fix would be good! Maybe it would be better to split the timeout into seconds. So 30 seconds will check 30 times, but a timeout of 10 seconds will check 10 times.
