### ISSUE TITLE
Incorrect code coverage detection in some projects with resources

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#2403]
**Repro steps**
So. Finally. 2 days of digging.

1. Download and open this solution: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/10710114/Repro.zip)
2. Run Stryker. The results in the `RandomClass` are correct:
![image](https://user-images.githubusercontent.com/5451366/218167180-622eede8-aa9e-406d-9bfd-ee33c37a97e7.png)
3. Now go to Directory.Build.props and uncomment the line. Rebuild the solution. The resources file will be regenerated, also the compiler will force you add a `using` statement in a file. 
4. Rerun Stryker and see incorrect results.
![image](https://user-images.githubusercontent.com/5451366/218167852-125f97ac-9d2b-4417-87e3-e4e01400b577.png)

In the `SomeClass`, the mutant is shown as "not covered" although it's easy to see that it is.

This is a **regression**. Version 3.4.0 handles this correctly.

**Comment by rouke-broersma** [comment]
@psfinaki could you test https://github.com/stryker-mutator/stryker-net/pull/2414 and see if this fixes the actual problem in your real project?

I hate Resource files so much 🥴

**Comment by psfinaki** [comment]
@rouke-broersma yeppp that worked. At least for the original project in question :) I will run this version against the whole repo over the weekend just in case but I guess it will be alright.

Thanks! I guess once you cool down from resources, we can add some integration tests using the repros above :D
