### ISSUE TITLE
Static Guid

### ISSUE THREAD

**Issue by Iceeman76** [stryker-mutator/stryker-net#2418]
Consider the following code;
```
public static class StaticKeys
{
	public static Guid StaticPersonKey = new("C8901F9D-4227-4BAC-903F-46E899D863F4");
}
```

Using Stryker would result in:
```
public static class StaticKeys
{
	public static Guid StaticPersonKey = new("");
}
```

This will always throw because an empty string can not be parsed as a Guid.
It would be great if Stryker in this case mutated to Guid.Empty or some random Guid. Maybe configurable?

**Comment by Liam-Rougoor** [comment]
@Iceeman76 Thank you for creating the issue. I understand the problem, but I don't think fixing this is feasible. Stryker operates on syntax trees and syntax nodes _without_ additional type info. Basically, Stryker cannot tell whether a certain string is supposed to be a Guid or not, so it won't be able to know whether to insert an empty string or a Guid.Empty.

**Comment by richardwerkman** [comment]
@Liam-Rougoor well yes and no. We already do this for regex as well. If we find a string in a constructor called "Regex" we assume the string is a regex and we mutate regex specifically.

We could do the same with Guid. It's not foolproof as with the above anonymous constructor we can't find the name. Or someone could have their own class called Guid (but why would they...).

So basically, yes we can do this. But only if the syntax `new Guid("C8901F9D-4227-4BAC-903F-46E899D863F4")` is used.

**Comment by Iceeman76** [comment]
So there is a possibility that this will be implemented in the near future?

**Comment by richardwerkman** [comment]
Well for me this is a low priority feature request. If somebody wants to pick this up that's fine but I'm not gonna spend time on this any time soon. @Iceeman76 maybe you could give it a go yourself?
