### ISSUE TITLE
New empty string mutations break in negated expressions

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#2446]
**Describe the bug**
They work for
```if (string.IsNullOrEmpty(s)) {...}```
producing ```if (s!="") {...}```

but they don't work for
```!string.IsNullOrEmpty(s) {...}```
which produces ```(!s!="") {...}```
which causes compile errors and unkilled mutants.

**Expected behavior**
This mutation should be wrapped in extra parens hence producing valid mutants.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: Core
 - Framework Version: .NET7
 - Stryker Version: 3.7.0

**Comment by richardwerkman** [comment]
Thanks for creating the issue! I'll quickly create a fix

**Comment by psfinaki** [comment]
Well I already created the PR, see above :)

**Comment by richardwerkman** [comment]
Oops, I read over that 🙈

**Comment by richardwerkman** [comment]
Looks like we did exactly the same :) But you forgot to update the docs. 

If you don't mind I'll merge mine, unless you feel like updating the docs too and I'll gladly merge yours in that case

**Comment by psfinaki** [comment]
Oh well I could have updated the docs but this all happened so quick :D 

Anyway, thanks - and would be grateful for a release soon, I'm actually looking forward to see all these new mutants in action :)

**Comment by rouke-broersma** [comment]
Releasing now

**Comment by psfinaki** [comment]
Thanks! Will let you know how it goes on our side. :)
