### ISSUE TITLE
Realtime integration in the HTML reporter in Stryker.NET

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-net#2461]
This issue depends on stryker-mutator/mutation-testing-elements#2434

---

# Realtime Reporting

Add support for realtime reporting in the HTML reporter in Stryker.NET.

## Implementation

1. When all mutants have been created, open the file in the browser with its initial state.
2. After opening the HTML file, use a `HttpListener` to listen to a certain endpoint with the `text/event-stream` header.
3. When a mutant is tested, send an event to the browser. This event should at least contain a mutant `id` and the new `status`.
   a. It might also be nice to put these mutants in a list, and output them when a client is connected. This could be used to prevent missing mutant data in the browser.
5. When mutation testing is done, send a different event so that the report knows it won't recieve any new updates. 
6. Finally write the complete version to disk (as we currently do).

Also, we should rename `NotRun` to `Pending` (see stryker-mutator/mutation-testing-elements#2424)

## Question(s)

1. Should this be enabled by default or should this be behind the `-o` flag?

**Comment by rouke-broersma** [comment]
Imo this should only be enabled when the auto-open report feature is used.

**Comment by xandervedder** [comment]
@richardwerkman What do you think?

**Comment by richardwerkman** [comment]
I think it's fair to see this as an improvement to the `-o` feature. It doesn't make sense to introduce a new setting for this.
