### ISSUE TITLE
Refactor all files to use file-scoped namespaces

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-net#2470]
From:
```cs
namespace X.Y.Z 
{
    public class Foo 
    {
        // ...
    }
}
```

To:
```cs
namespace X.Y.Z;

public class Foo
{
    // ...
}
```

**Comment by ysbakker** [comment]
Will pick this up during the hacktoberfest event, so we can avoid merge conflicts with existing PRs.

**Comment by KonH** [comment]
Any updates about plans on that refactor? I also would like to make PR with that refactor, but there are still 9 open PRs which may leads to merge issues.

**Comment by rouke-broersma** [comment]
@KonH unfortunately PRs were being generated faster than we could review them 😅 I think the potential of this change does not necessitate the disruption it would cause at this time unfortunately.
