### ISSUE TITLE
enable access to complete test runner log

### ISSUE THREAD

**Issue by Dirk-Peters-BF** [stryker-mutator/stryker-net#2485]
Sometimes I want to run Stryker with integration tests working with an asp.netcore test server server. I accept the longer runtime in comparison to unit tests. 
The problem with these more complex tests are generic error messages when a test fails, especially 
`System.InvalidOperationException : The entry point exited without ever building an IHost.` 
when the server is not starting. In these cases I need console log output from the test runner to find the root cause, which unfortunately seem to get lost.

For this I'd like an option to output the complete test runner log in Stryker log by using an additional configuration switch or by including the logging into debug or trace verbosity level.

I already tried to use higher verbosity settings, but so far I was not able to see the test runner log.

**Comment by rouke-broersma** [comment]
Just to clarify, you want the application console output and not the testrunner logging right?

**Comment by Dirk-Peters-BF** [comment]
I.e. for NUnit: The content of the  'test-suite/test-case/output' node when written to an NUnit test result xml.

**Comment by rouke-broersma** [comment]
Looks like this is default enabled and is sent to vstest so we should be able to capture this somewhere: https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#consoleout

**Comment by Dirk-Peters-BF** [comment]
At least while debugging Stryker I can see the output in TestResult.Messages

This is btw. not a solution for my immediate problem, because I need this in the automated build.
