### ISSUE TITLE
Mark tests as killing if they fail during mutation test run.

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#2489]
**Is your feature request related to a problem? Please describe.**
Right now tests are never marked as killing, even if they fail.

**Describe the solution you'd like**
Mutants should track which tests failed, and display in the HTML report. To do this correctly we should run all covering tests for each mutant, and not stop when the first test fails. We already have an option for this `disable-bail`, should this be enabled by default when using the HTML reporter? Or should we explain clearly in the docs how to use this feature correctly.

**Comment by rouke-broersma** [comment]
Imo they're separate issues. We should log which tests killed a mutant, but we can do that without disable bail. Disable bail would just make it more accurate. Also we still need to expose disable bail in the cli.

I don't think we should enable disable bail by default until we are significantly faster.
