### ISSUE TITLE
Real time reporting can crash stryker when a client disconnects right before or during a crash

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#2517]
**Describe the bug**

https://github.com/stryker-mutator/stryker-net/blob/c116bd9bc4c3dc030dc5025873810f2341945fa0/src/Stryker.Core/Stryker.Core/Reporters/Html/Realtime/SseServer.cs#L68

Disconnected writes should be removed from the list of writers and some kinda exception handling should catch when a client disconnects in-flight.

**Comment by dupdob** [comment]
I am looking in to it because, I have several years of experience in this kind of code, but never played with tasks before.

I am having a hard time designing tests for this. The `EventSource` helpers is not helping much there 😉

**Comment by rouke-broersma** [comment]
@dupdob you can contact @xandervedder on slack for questions and discussions surrounding the design of realtime reporting. 

If significant changes are required to fix this I would ask that you give them as suggestions to xander so they can implement it themselves because their internship is still ongoing. If this bugfix does not require significant changes feel free to implement them directly.

**Comment by xandervedder** [comment]
I did look into this myself as well, but I could not reproduce the crash. One thing that could be done is checking whether the `BaseStream` is writeable:

```diff
        foreach (var writer in _writers)
        {
+           if (writer.BaseStream.CanWrite)
+           {
+               // remove writer
+           }
            writer.Write($"{serialized}{Environment.NewLine}{Environment.NewLine}");
            writer.Flush();
        }
```

This would be very difficult to reproduce in a testing scenario though (shame we can't mock the `HttpListener` class).
