### ISSUE TITLE
Fix sonarcloud issues

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-net#2519]
Would be nice to see the pipeline succeeding when PR's get merged 😄.

---

https://sonarcloud.io/project/issues?resolved=false&id=stryker-net

**Comment by dupdob** [comment]
why are those issues not raised/detected in PRs?

**Comment by rouke-broersma** [comment]
@dupdob they are raised for PRs made from branches in our repo, but due to security concerns (need to be able to upload to sonarcloud, leaking credentials) they are not raised for PRs from forks, that's how they usually slip in.
