### ISSUE TITLE
Wrong msbuild version used to build .net framework project

### ISSUE THREAD

**Issue by CzBuCHi** [stryker-mutator/stryker-net#2528]
**Describe the bug**
Stryker is building project using `dotnet build` (msbuild for .net core) command even when .net framework project is tested. -> build will fail, because resx are compiled differently in core than in framework.

**Expected behavior**
Build with `msbuild` command for .net framework project.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Type of project: class library
 - Framework Version net48
 - Stryker Version 3.9.0

**Additional context**
v 3.8.0 do not have this behavior

**Comment by dupdob** [comment]
Thanks for reporting that you have an issue. 
Could you specify which error(s) you have ?
And/or could you please provide some logs or a reproduction scenario?

 V3.9 indeed includes a massive refactoring of project management logic which could be the source of undetected regressions. 
That being said, the changes are more complex than switching between msbuild and dotent build. 

I did try the latest version with a simple Net framework project with a resx file and everything went fine.

**Comment by CzBuCHi** [comment]
im getting this log when running `dotnet build` in `c:\projects\dotnet\Zeus\5.0\` directory: [Log.txt](https://github.com/stryker-mutator/stryker-net/files/11494868/Log.txt)

probably useless, but msbuild log loogs like this: [msbuild.txt](https://github.com/stryker-mutator/stryker-net/files/11495036/msbuild.txt)

also i can show you (modified) affected project: [Zeus.Windows.Forms.YearGrid.csproj](https://github.com/stryker-mutator/stryker-net/files/11495004/Zeus.Windows.Forms.YearGrid.csproj.txt)

my guess is that dotnet core changed how `Page` is compiled ...

**Comment by rouke-broersma** [comment]
@CzBuCHi that is already what we do, there's just something going wrong in detecting since the solution run rework.

**Comment by dupdob** [comment]
@CzBuCHi : could you share the command line you are using? I am unable to see any defect in the code. Knowing the selected options would help me narrow my search.

**Comment by dupdob** [comment]
Thanks. I have tried these options on the net 4.8 integration test projects and Stryker ran as expected, using msbuild to build the project.
I am afraid I cannot do much more until you provide us Stryker's own log (using `--log-to-file` option) or a project reproducing the problem

**Comment by CzBuCHi** [comment]
ofcourse after pc restart & reinstall of stryker tool i cannot reproduce this error ... so sorry for wastling your time :/
