### ISSUE TITLE
Using AzureFileStorage for baseline results in RequestEntityToLarge error

### ISSUE THREAD

**Issue by ruben12321** [stryker-mutator/stryker-net#2548]
**Describe the bug**
I'm trying to test out the baseline feature with AzureFileStorage as the provider. The project I'm running is a rather large solution and the total report size amounts up to about 10 MB. At the end, I get a successful report but also get an error that the upload failed because the request entity is to large. I found that the maximum upload size for a file is 4 MB (https://learn.microsoft.com/en-us/troubleshoot/azure/general/request-body-large)  

**Logs**
```
[17:34:48 ERR] Azure File Storage upload failed with statuscode RequestEntityTooLarge and message: <?xml version="1.0" encoding="utf-8"?><Error><Code>RequestBodyTooLarge</Code><Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:5b68d54f-001a-0031-048c-8defc5000000
Time:2023-05-23T15:34:46.9474761Z</Message><MaxLimit>4194304</MaxLimit></Error>
```

**Expected behavior**
I expect the upload to azure file storage to also work with reports bigger then 4MB

**Desktop (please complete the following information):**
 - OS: Windows11
 - Type of project: Core
 -  core 6.0
 - Stryker Version 3.9.0

**Comment by rouke-broersma** [comment]
That's a big report :D
We need to implement chunking to support this. Maybe we should try to compress the json as well.

**Comment by psfinaki** [comment]
For reference, our reports are more than 100MiB :D but we are not using this feature.

**Comment by ruben12321** [comment]
Would you have any idea on when this would be available? Just so I can have an idea on when we can implement this into our pipeline.

**Comment by rouke-broersma** [comment]
I think we can work on this on Friday

**Comment by rouke-broersma** [comment]
@ruben12321 sorry it took a while!
