### ISSUE TITLE
Colorful.Console instead of static Chalk

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#255]
Right now we use a static Chalk class to write in colors to the console. We also use this for testing.

Using the library [ColorfulConsole](http://colorfulconsole.com/) we could create a cleaner code style. It also has some awesome features like printing in gradient. This could be an cool addition to the ascii logo.

My question is, would this be an improvement? Or does anyone have experience with the library?

**Comment by Mobrockers** [comment]
If someone really wants to add this, sure. Does not have any prio for me because who looks at the cmd output anyway? CI + json report is what is going to be used imo.

**Comment by richardwerkman** [comment]
True, of course a json report has more prio but I thought this would be a fun addition.

**Comment by mcliment** [comment]
I've been taking a look at this issue as it seemed kind of fun and I have some experience with Colorful.Console but the main problem is that `IChalk` is used in many tests for mocks that later check that the messages have been properly printed.

So wrapping `Colorful.Console` inside `IChalk` does not look interesting at all and capturing all things written to console with `Console.SetOut` and then checking stuff does not look very appealing either.

I ran out of ideas.

**Comment by eNeRGy164** [comment]
I'm investigating this, using Crayon.

![image](https://user-images.githubusercontent.com/10671831/96516599-c3275b80-1267-11eb-893c-f268c57773c6.png)

**Comment by Mobrockers** [comment]
Cool!

**Comment by eNeRGy164** [comment]
Chalk has been replaced now, should this issue be closed?

Maybe create a new one for a fancier banner?

**Comment by Mobrockers** [comment]
Yep! Thank you for your contributions!
