### ISSUE TITLE
Solution mode doesn't handle namesakes

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#2564]
**Describe the bug**
Found this bug while trying to reproduce another bug... :D 

But basically, imagine there is a solution with projects Library1 and Library2 and both have class MyClass, both classes are tested in respective test projects Library1.Tests and Library2.Tests. 

Judging by logs, Stryker knows what to do:
```
Version: 3.9.0

[14:38:45 INF] Analysis starting.
[14:38:45 INF] Identifying projects to mutate in C:\Users\xxx\Desktop\MySolution\MySolution.sln. This can take a while.
[14:38:48 INF] Found 2 source projects
[14:38:48 INF] Found 2 test projects
[14:38:48 INF] Found project C:\Users\xxx\Desktop\MySolution\Library2\Library2.csproj to mutate.
[14:38:48 INF] Found project C:\Users\xxx\Desktop\MySolution\Library1\Library1.csproj to mutate.
[14:38:48 INF] Analysis complete.
[14:38:48 INF] Building solution MySolution.sln
[14:38:53 INF] Number of tests found: 1 for project C:\Users\xxx\Desktop\MySolution\Library2\Library2.csproj. Initial test run started.
[14:38:57 INF] Number of tests found: 1 for project C:\Users\xxx\Desktop\MySolution\Library1\Library1.csproj. Initial test run started.
[14:38:59 INF] 3 mutants created
[14:38:59 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
Hint: by passing "--open-report or -o" the report will open automatically and update the report in realtime.
[14:39:02 INF] 1     mutants got status Ignored.      Reason: Removed by block already covered filter
[14:39:02 INF] 1     total mutants are skipped for the above mentioned reasons
[14:39:02 INF] 2     total mutants will be tested
████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████100,00% │ Testing mutant 2 / 2 │ K 2 │ S 0 │ T 0 │ ~0m 00s │                                                                                        00:00:02

Killed:   2
Survived: 0
Timeout:  0

Your html report has been generated at:
C:\Users\xxx\Desktop\MySolution\StrykerOutput\2023-06-08.14-38-45\reports\mutation-report.html
You can open it in your browser of choice.
[14:39:05 INF] Time Elapsed 00:00:19.9786253
[14:39:05 INF] The final mutation score is 100.00 %
```

But then the report...
![image](https://github.com/stryker-mutator/stryker-net/assets/5451366/8bbeaa93-c11e-4d4c-946a-62cdda096e2e)

If I do the renaming - that is, rename classes to Library1.MyClass1 and Library2.MyClass2, the results are reasonable.
![image](https://github.com/stryker-mutator/stryker-net/assets/5451366/6090b1e1-c3cf-4350-8ff7-c3b7b62317d0)

That said, this is still confusing in a way, I want some notion of the fact those classes are in different projects - but that's probably a separate discussion.

**Desktop (please complete the following information):**
 - OS: Windows
 - Stryker Version: 3.9.0

**Additional context**
To save you some time, here is the repro: 
[MySolution.zip](https://github.com/stryker-mutator/stryker-net/files/11688383/MySolution.zip)

**Comment by dupdob** [comment]
well, what are your expections here ?
also, is this the same file or just two different files with the same class(es) inside?

**Comment by psfinaki** [comment]
No, they are different classes, just called the same name.

As for my expectations - well, I am tunnel-visioned here in a way, we've been merging the reports manually for a long time, and the results look like this:
![image](https://github.com/stryker-mutator/stryker-net/assets/5451366/5d74648e-a4af-4138-92eb-4e5e21892257)
And then you can navigate back and forth...
![image](https://github.com/stryker-mutator/stryker-net/assets/5451366/acc26c92-a712-4323-a6b2-5fec8890dce7)

But we could probably at least start with full paths there.

**Comment by dupdob** [comment]
ok, this is a duplicate issue. I need to find the reference issue for this, but this is the problem that solution mode gobbles part of the path

**Comment by psfinaki** [comment]
Alright. What I originally wanted to confirm is that somewhere between versions 3.7.1 and 3.8.2 (that's the update I was testing) the `files` key in JSON reports started showing only the name of the file instead of the full path as it used to be.
![image](https://github.com/stryker-mutator/stryker-net/assets/5451366/24d3579c-70a1-434c-b3d2-441a159a0288)


Is this what you are talking about also? Or should I create some separate issue for this?

**Comment by rouke-broersma** [comment]
This isn't only in solutionmode. The filename is no longer the full path.

**Comment by psfinaki** [comment]
Yep, this is in all modes, it just regressed in 3.8.0. I can create a separate issue for this.

**Comment by rouke-broersma** [comment]
It's the same issue, because filenames are relative to the source project, if they have the same name they get discarded (filename is they key in the dictionary). Filenames should probably be relative to working directory or something instead. Not sure, it's a hard problem due to different modes.

**Comment by richardwerkman** [comment]
I encountered this problem before and fixed it (before we released solution mode officially). But it seems the fix was lost in a merge due to long living feature branches... Once again we see why this is not a good idea 🙈

**Comment by dupdob** [comment]
I am probably the guilty party here. I suspect this has been lost in the hellish merge between my work on solution mode and the work on test reporting. Two ambitious features that impacted deeply the design...
merging works great for incremental effort, but when one shift responsibilities to new classes, it gets really hard

**Comment by rouke-broersma** [comment]
Nope, it was me 🙄😁
