### ISSUE TITLE
DLL not found in solution mode

### ISSUE THREAD

**Issue by Stijn-Rutten** [stryker-mutator/stryker-net#2579]
**Describe the bug**
When running stryker in solution mode, the following exception is thrown during the mutation process:

[exception.txt](https://github.com/stryker-mutator/stryker-net/files/11800450/exception.txt)

**Logs**
[log-20230620.txt](https://github.com/stryker-mutator/stryker-net/files/11800644/log-20230620.txt)

**Expected behavior**
Would except Stryker to run a normal test run :) 

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project .net 6
 - Stryker Version 3.9.2

**Comment by dupdob** [comment]
It looks like a referenced assembly is missing. And it appears that Stryker does not handle this situation gracefully.
This issue will be fixed, but may I suggest you simply remove the useless reference from the project, assuming it is actually missing. If it is not missing, I have no idea why Stryker failed to load it.

**Comment by dupdob** [comment]
@Stijn-Rutten : any update on this issue?

**Comment by dupdob** [comment]
closing, no feedback since last year
