### ISSUE TITLE
Exception when using PackageReference aliases

### ISSUE THREAD

**Issue by SteveDunn** [stryker-mutator/stryker-net#2601]
The bug causes a runtime exception when a source project contains a PackageReference alias, such as:

`<PackageReference Include="Dapper" Version="2.0.143" Aliases="ORM" />`

**Logs**
[logs.zip](https://github.com/stryker-mutator/stryker-net/files/11998240/logs.zip)

**Expected behavior**
No runtime errors

**Desktop**
 - OS: Windows
 - Type of project: core
 - Framework Version: net6.0
 - Stryker Version 3.9.2

**Additional context**
Nothing in particular. It seems quite easy to reproduce by adding a nuget reference to any old package and adding an alias.

**Comment by SteveDunn** [comment]
Thanks for the quick response @dupdob . I took a (very) quick look at fixing it myself earlier, but I can't get it to build... https://github.com/stryker-mutator/stryker-net/discussions/2602

I'll try again later with the advice posted in that thread.

**Comment by SteveDunn** [comment]
Great news - thank you for the quick turnaround!

**Comment by rouke-broersma** [comment]
@SteveDunn I am looking into this due to an issue I am having with stryker itself, did this fix actually solve your problem when we released this? It seems to me like our references no longer contain aliases in the format that we try to parse.
