### ISSUE TITLE
Update NuGet link in readme and add badge

### ISSUE THREAD

**Issue by chris579** [stryker-mutator/stryker-net#270]
The NuGet link in the Readme is directing to the old package that has been archived. Plus, adding a NuGet badge makes it easier to get to the NuGet package page.

**Comment by Mobrockers** [comment]
Example of nuget badge:


[![Nuget](https://img.shields.io/nuget/v/StrykerMutator.DotNetCoreCli.svg)](https://www.nuget.org/api/v2/package/StrykerMutator.DotNetCoreCli)

**Comment by richardwerkman** [comment]
A bagde would be better yes! While we're on this we could also add a download count badge? 

https://shields.io/#/examples/downloads

**Comment by Mobrockers** [comment]
@richardwerkman 

[![Nuget](https://img.shields.io/nuget/d/StrykerMutator.DotNetCoreCli.svg)](https://www.nuget.org/api/v2/package/StrykerMutator.DotNetCoreCli)
[![Nuget](https://img.shields.io/nuget/dt/StrykerMutator.DotNetCoreCli.svg)](https://www.nuget.org/api/v2/package/StrykerMutator.DotNetCoreCli)

**Comment by richardwerkman** [comment]
Looks good, who creates the PR?

**Comment by chris579** [comment]
There you are 😛
