### ISSUE TITLE
A Mutation Score of the tests we run, not the source project

### ISSUE THREAD

**Issue by JackSteel97** [stryker-mutator/stryker-net#2700]
**Is your feature request related to a problem? Please describe.**
Mutation Scores can be misleading when not all tests can be run as mutants.

For example, API projects where large chunks of the code are covered by service tests rather than unit tests. In our scenario, these service tests spin up a testing database at the start of each test and delete it during test tear-down. This means that we have to exclude them from mutation tests because mutants can be created that enter infinite loops or otherwise cause the tear-down stage of database deletion to not be run - therefore creating hundreds of orphaned test databases that would require an external process to clean up regularly.

So we can have high code coverage and low mutation survival count but a high NoCoverage count that drags the overall mutation score down even though it is not representative of what we're trying to test with mutation tests (in this case at least)

**Describe the solution you'd like**
Some config toggle to exclude NoCoverage. 
Basically, a config option to say "I know about the uncovered mutations and I'm sure I want to ignore them as I'm using stryker to test the quality of a subset of my tests. I want a score for the quality of those tests, not the overall source project" (in the wordiest possible way 😆)

Whether that is just excluding them from the score calculation or actually not bothering to mutate uncovered code (although I realise this option may be significantly harder to implement)

**Describe alternatives you've considered**
As a workaround we could pull the survival and killed counts from the mutation report and calculate our own mutation score after stryker has run, however this relies on the mutation report format staying consistent enough to reliably work long term and just overall feels a bit hacky

**Additional context**
Open to suggestions or alternatives and if you want to go ahead with anything like this I'm happy to do the work to implement it.

**Comment by rouke-broersma** [comment]
How would we know which are covered by outside tests and which are insufficiently covered? We have no way of knowing. You can use `mutate` as well as `stryker comments` and `excludefromcodecoverage` to include/exclude certain files/lines from the result.

**Comment by JackSteel97** [comment]
Yeah I'm not suggesting stryker try to figure out what's covered or not any more than it does currently. I'm suggesting an option to just ignore NoCoverage when calculating the mutation score. I.e. the user takes responsibility that stryker will not provide any useful code coverage information, effectively only providing a score for mutants that are covered.

**Comment by dupdob** [comment]
> In our scenario, these service tests spin up a testing database at the start of each test and delete it during test tear-down. This means that we have to exclude them from mutation tests because mutants can be created that enter infinite loops or otherwise cause the tear-down stage of database deletion to not be run - therefore creating hundreds of orphaned test databases that would require an external process to clean up regularly.

I see the pain here; but may I suggest contemplating the usage of some in memory DB and/or mocks for such test ? if those are significant for coverage, they should be made as fast as possible.

> Whether that is just excluding them from the score calculation or actually not bothering to mutate uncovered code (although I realize this option may be significantly harder to implement)

Just for the laugh: we need to run the test on the mutated code to establish coverage, so this would be a nice chicken and egg situation.

> Basically, a config option to say "I know about the uncovered mutations and I'm sure I want to ignore them as I'm using stryker to test the quality of a subset of my tests. I want a score for the quality of those tests, not the overall source project" (in the wordiest possible way 😆)

The way we support this is via Stryker comments as those permits fine control about mutations. But this may not be practical if this means commenting a lot of lines scattered in the source files.

> as a workaround we could pull the survival and killed counts from the mutation report and calculate our own mutation score after stryker has run, however this relies on the mutation report format staying consistent enough to reliably work long term and just overall feels a bit hacky

This may be the best approach to what you want to achieve. I would suggest asking for a Reporter that would output the result statistics as a json/xml/yml file for simpke consumption/reuse

**Comment by JackSteel97** [comment]
Thanks for the feedback!
I do like the sound of the new reporter option, seems like a good balance of not mixing specific logic into stryker while also supporting easily passing statistic results to the next thing in the pipeline.

I know there's already a JSON reporter but I don't think it nicely reports the mutant number stats(?) What do you think about something like a `json-stats` reporter that reports the mutant numbers (totalled and maybe per-file?) So that the quantitative stats can be output in way easy to consume by other tools

**Comment by rouke-broersma** [comment]
That's exactly what the json reporter outputs.

**Comment by JackSteel97** [comment]
From what I can see getting meaningful numbers for stats from the current JSON report is somewhat non-trivial, I understand the current JSON report having everything like that in order to power the HTML report but I'm suggesting a more statistics-focused report that could just be piped through grep or something to pull out the relevant numbers to send off elsewhere. With the current JSON report, it would probably require writing a tool in the middle to do that transformation, which I'm not super opposed to but does it make more sense just to provide that built-in as a report?

Then again maybe this shouldn't be Stryker's responsibility, maybe I just need a python script to do some maths on the JSON report
