### ISSUE TITLE
System.UnauthorizedAccessException when running Stryker

### ISSUE THREAD

**Issue by royto** [stryker-mutator/stryker-net#272]
**Version**:  0.7.0 (beta)

On running dotnet stryker on my unit test project (.NET Core 2.0), I encountered the following issue 
```
[17:40:22 ERR] An error occurred during the mutation test run
System.UnauthorizedAccessException: Access to the path 'C:\Repos\MyProject\src\Tests\MyProject.UnitTests\bin\Debug\netcoreapp2.0\Services.dll' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.Abstractions.FileWrapper.Create(String path)
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)
[17:40:22 INF] Time Elapsed 00:00:39.8056808
```

I have multiple project reference (in .NET Standard 2.0) and I specify one of them with the `--project-file` option

`dotnet stryker --project-file=..\..\Services\Services.csproj`

**Comment by richardwerkman** [comment]
I haven't seen this error before. It looks like the file could be locked or your console doesn't have the correct rights to open the file. Could you try to run stryker from a console with administration rights? Or try to clean the solution and rerun? 

If the error keeps occuring we'll look further into this.

**Comment by royto** [comment]
I have tried on my colleague machine and he has the same issue ...

**Comment by richardwerkman** [comment]
Could it be that the file is somehow marked as readonly?

I found in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.create?view=netcore-2.1) for System.IO.File.Create that this exception can only come from:

```
The caller does not have the required permission.

-or-

path specified a file that is read-only.
```

**Comment by royto** [comment]
I found the issue. \o/

It was relative to a configuration in my csproj.

I had this line : 
 ```xml
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
``` 

When it is set to false, the dll are generated into `bin/debug` and the folder `netcoreapp2.0` was empty.

Stryker trying to generate in this folder, resulting to `access denied` error.

I set it to true and unit test dll was generated into `bin/Debug/netcoreapp2.0`. 
I do not have the error anymore and stryker working well ...

I think that stryker should look for this property and use `bin/Debug` or `bin/Debug/FrameworkVersion` depending of the AppendTargetFrameworkToOutputPath property value.

**Comment by richardwerkman** [comment]
Ah interesting! To be honest I was not aware of the `AppendTargetFrameworkToOutputPath` property for projects. We should indeed take this into account. 

Could you create a PR for this? Or should we create an issue for others to pick up.

**Comment by royto** [comment]
I'm working on it. PR will be created soon I hope ...

**Comment by richardwerkman** [comment]
Awesome! Looking forward to it 👍
