### ISSUE TITLE
Stryker does not enrich test project with test info for C#  .NET Framework unit tests

### ISSUE THREAD

**Issue by MischaVreeburg** [stryker-mutator/stryker-net#2750]
**Describe the bug**
Stryker is unable to correctly enrich test project data with test info data from VsTest for C# .NET Framework, in order to report to the user which test killed which mutant.

**Expected behavior**
Stryker correctly enriches test project data with test info data for C# .NET Framework, in order to report to the user which test killed which mutant.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Type of project [framework, core, xamarin]
 - Framework Version [e.g. core 2.2]
 - Stryker Version [e.g. beta 0.10.0]

**Additional context**

**Comment by dupdob** [comment]
this is a known issue with vstest, I am pretty sure there is already an issue for this but I can't find it right now.

**Comment by rouke-broersma** [comment]
Duplicate of #2458
