### ISSUE TITLE
Mutator not honouring `NoWarn`

### ISSUE THREAD

**Issue by RussKie** [stryker-mutator/stryker-net#2775]
**Describe the bug**

The mutator fails to compile the code that contains [experimental API](https://learn.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.experimentalattribute?view=net-8.0).

```cs
[Experimental(diagnosticId: "EXTEXP0002", UrlFormat = DiagnosticIds.UrlFormat)]
public class HmacRedactorOptions
{
    // ...
}

[OptionsValidator]
internal sealed partial class HmacRedactorOptionsValidator : IValidateOptions<HmacRedactorOptions>
{
}
```

This results in:
```
[19:05:56 WRN] Stryker.NET encountered a compile error in <file> (at 35:33) with message: 'Microsoft.Extensions.Compliance.Redaction.HmacRedactorOptions' is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed. (Source code: HmacRedactorOptions)
```

There are [suppressions in place](https://github.com/dotnet/extensions/blob/c8383902da237c8efd61a37808e444ac9b838f59/Directory.Build.targets#L29), and the project builds without any warnings or errors. The issue only happens under Stryker.

**Logs**
For us to best assist you in diagnosing the problem we would ask you to run stryker with the option `--log-to-file` or `-L` and to attach the resulting logs to the issue.
[stryker.zip](https://github.com/stryker-mutator/stryker-net/files/13448680/stryker.zip)

**Expected behavior**

The `NoWarn` must be honoured, and the build must succeed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Framework Version: .NET 8
 - Stryker Version: 3.12.0

**Additional context**

**Comment by rouke-broersma** [comment]
If you happen to have some information for us on how NoWarn msbuild config is transformed and passed to Roslyn it would make it easier for us to implement support for it.

**Comment by RussKie** [comment]
Use `/nowarn:x,y,z`: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings

```
D:\a\_work\1\s\.dotnet\dotnet.exe exec "D:\a\_work\1\s\.dotnet\sdk\8.0.100\Roslyn\bincore\csc.dll" /noconfig /nowarn:EXTEXP0002 ....
```

**Comment by rouke-broersma** [comment]
I think we want to use CSharpCompilationOptions.WithSpecificDiagnosticOptions

**Comment by RussKie** [comment]
This isn't the area I'm familiar with; browsing the Roslyn repo I came across of [this](https://github.com/dotnet/roslyn/blob/05b5b594a8abc7b9c7d6348d3df5406ace243101/src/Compilers/CSharp/Test/Symbol/Compilation/CSharpCompilationOptionsTests.cs#L86-L87):

```cs
CSharpCompilationOptions.WithSpecificDiagnosticOptions(new Dictionary<string, ReportDiagnostic> { { "EXTEXP0002", ReportDiagnostic.Suppress } }.ToImmutableDictionary()))
```

**Comment by rouke-broersma** [comment]
Sorry for the confusion, that was a note for myself, I expect that that is what we'll need to use yes.
