### ISSUE TITLE
Microsoft.Extensions.CommandLineUtils will no longer publicly be updated nor published

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#278]
This extension by the asp.net team will no longer be published to nuget as a lone package, because they never intended this to be a standalone product. No new releases for the package will be available. We should consider moving to a fork such as https://github.com/natemcmaster/CommandLineUtils

**Comment by Mobrockers** [comment]
See: https://github.com/aspnet/Extensions/commit/2230370a3985fd1bbeebbdd904a3dd348f612d35

**Comment by theunrepentantgeek** [comment]
The new [`System.CommandLine`](https://github.com/dotnet/command-line-api/wiki) library might be worth considering, even though it's very new and still experimental.

**Comment by Mobrockers** [comment]
Another candidate https://github.com/commandlineparser/commandline
