### ISSUE TITLE
InvalidOperationException: Cannot inject mutation because we cannot find the original code

### ISSUE THREAD

**Issue by Tr00d** [stryker-mutator/stryker-net#2837]
**Describe the bug**
At the beginning of the mutation process, an exception is suddenly thrown by Stryker.
This happened independently from a change on our side; the pipeline suddenly failed.
I conducted an investigation, and the problem appeared in v3.13.0. When running the mutation process with v3.12.0, the problem doesn't occur.

**Expected behavior**
No exception should be thrown in that case.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Type of project: SDK
 - Framework Version:  net6.0
 - Stryker Version: v3.13.1

**Additional context**
![Capture d’écran du 2024-01-24 09-02-30](https://github.com/stryker-mutator/stryker-net/assets/59444272/b0661f91-12d6-4857-8957-297a4c28620d)

Pipeline with v3.13.1 (fail): https://github.com/Vonage/vonage-dotnet-sdk/actions/runs/7636808253/job/20805094769
Pipeline with v3.12.0 (successful): https://github.com/Vonage/vonage-dotnet-sdk/actions/runs/7637218641

**Comment by dupdob** [comment]
Hi
I think this relates to a known issue. I can't be sure with so little information. I suggest you take a look at #2825 for a workaround that should resolve the problem immediately.
A complete fix will part of the next release.

**Comment by Tr00d** [comment]
@dupdob Thanks for that. On my side, the workaround was to downgrade to v3.12.0
Indeed, the issue looks similar to me. 

You can flag it as duplicate or close it.

**Comment by dupdob** [comment]
hi
the fix has been released, we expect this issue to be solved with V3.13.2
I close this issue, feel free to reopen it if your problem is still there.
