### ISSUE TITLE
 warning CS0618: VsTest Console Wrapper 'The async APIs don't work, use the sync API instead.'

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#2853]
**Describe the bug**
 warning CS0618: 'IVsTestConsoleWrapperAsync.RunTestsWithCustomTestHostAsync(IEnumerable<string>, string?, TestPlatformOptions?, ITestRunEventsHandler, ITestHostLauncher)' is obsolete: 'The async APIs don't work, use the sync API instead.'

warning CS0618: 'IVsTestConsoleWrapperAsync.DiscoverTestsAsync(IEnumerable<string>, string?, ITestDiscoveryEventsHandler)' is obsolete: 'The async APIs don't work, use the sync API instead.'

**Comment by dupdob** [comment]
PR #2845 fixes that properly: we need some form of async to recover from VsTest freezes

**Comment by dupdob** [comment]
note that this (obsolete) attribute has been added by an external contributor to the VsTest codebase and is not substantiated in any way 😄

**Comment by rouke-broersma** [comment]
[nohwnd](https://github.com/nohwnd) is not an external contributor, they work for microsoft on vstest. It was added here: https://github.com/microsoft/vstest/pull/4648 and substantiated here: https://github.com/microsoft/vstest/issues/4592

**Comment by dupdob** [comment]
thanks for the rectification.
And indeed, the fact is that they have little added value (except for somewhat better dealing with freezes)
