### ISSUE TITLE
Custom renovate config for parsing libman.json for mutation-testing-elements updates

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#2862]
**Is your feature request related to a problem? Please describe.**
We don't often update mutation-testing-elements because we don't notice there are changes. Renovate does not by default understand libman.json files, so it can't notify us of updates to the package.

**Describe the solution you'd like**
Implement a custom manager so renovate understands libman.json files as npm packages: https://docs.renovatebot.com/modules/manager/regex/

**Comment by hanahbaker1** [comment]
Hi there, I found this issue on GFI, and as you probably gather I'm new to opensource.
Would this be your solution and if so how can I push a PR to help with this? Thanks for your help and pointers 👍

``` "customManagers": [
    {
      "customType": "regex",
      "fileMatch": ["^libman\\.json$"],
      "matchStrings": [
        "\"library\": \"mutation-testing-elements\",\n\\s*\"version\": \"(?<currentValue>.*?)\""
      ],
      "depName": "mutation-testing-elements",
      "datasourceTemplate": "npm"
    }
  ] ```

**Comment by rouke-broersma** [comment]
Hi @hanahbaker1! And welcome to open source!

Without digging into it (I'm on leave at the moment) this seems like the solution I had in mind. You can contribute this change by editing the renovate.json located in the .github folder. Github should then suggest you create a fork of the repo and then submit a pull request. Once you've done that and once I'm back from leave I'll verify the change works as expected and if necessary request that you make some changes. Afterwards I'll approve the pull request and your change will be merged.

Does that help you to get on your way?

**Comment by hanahbaker1** [comment]
Thanks for the guidance and info @rouke-broersma 😄 I've created the [PR](https://github.com/stryker-mutator/stryker-net/pull/2902), but need to fix the build some time this week.

**Comment by rouke-broersma** [comment]
Don't worry about the build, that's my bad.
