### ISSUE TITLE
Cannot rollback mutated if with inline variable declaration

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#287]
The following code chokes Stryker: it generates a mutant on the if that leads to error on other lines (test not having a value defined) that it cannot rollback.
I think the best strategy would be not to try to mutate any _if_ embedding a variable declaration.
```csharp
public string UnsupportedSyntax(string a, string b)
{
    // mutating this statement triggers the error
    if (Demo(out var test))
    {
         return a + b;
    }
    return test;
}
private bool Demo(out string test)
{
     test = "dummy";
     return true;
}
```

**Comment by Mobrockers** [comment]
Applies to probably all out vars and perhaps also to the new c#7 pattern matching such as Type is var x
