### ISSUE TITLE
License of  RegexParser

### ISSUE THREAD

**Issue by Fieslix** [stryker-mutator/stryker-net#2900]
**Description**
Stryker (RegexMutators) uses the external library RegexParser¹, which apparently does not provide any license information and therefore may not be used in this project?!

¹https://www.nuget.org/packages/RegexParser/

**Comment by rouke-broersma** [comment]
This project was created by an internship student during an internship with our employer and as such we may use this but we should clear this up.

@richardwerkman

**Comment by richardwerkman** [comment]
They have a license located on their GitHub. But it seems it's not added to the nuget package itself.

https://github.com/PimRheiter/regex-parser

@PimRheiter could you try to add the license to the nuget package info? That would resolve this.
