### ISSUE TITLE
List pattern syntax mutation

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#2951]
**Is your feature request related to a problem? Please describe.**
The following code (in the switch expression) should be mutated but is not:

``` cs
    public void ListPatterns()
    {
        decimal balance = 0m;
        string[][] transactions = new[]
        {
            new[] { "1", "DEPOSIT", "100.00" },
        };
        foreach (string[] transaction in transactions)
        {
            balance += transaction switch
            {
            // "DEPOSIT" should be mutated here
            [_, "DEPOSIT", _, var amount] => decimal.Parse(amount),
            [_, "WITHDRAWAL", .., var amount] => -decimal.Parse(amount),
            [_, "INTEREST", var amount] => decimal.Parse(amount),
            [_, "FEE", var fee] => -decimal.Parse(fee),
                _ => throw new InvalidOperationException($"Record {string.Join(", ", transaction)} is not in the expected format!"),
            };
            Console.WriteLine($"Record: {string.Join(", ", transaction)}, New balance: {balance:C}");
        }
    }
```

**Describe the solution you'd like**
We should introduce a new orchestrator for the syntax type `ListPatternSyntax`.

**Comment by dupdob** [comment]
what kind of mutation you are thinking of?
with this example, I can see a switch mutation (shuffling conditions and values), but modifying list patterns looks difficult

**Comment by richardwerkman** [comment]
@dupdob  I wasn't thinking of new mutations. The issue is that existing mutations aren't placed. I expect string mutations in my example but no mutations are placed. This is a type of syntax that we don't support mutating yet

**Comment by dupdob** [comment]
Ah
Yes. Silly of me. You did mention needing an orchestrator.  Thanks

**Comment by dupdob** [comment]
I had a look: patterns are not mutated as of today as they are not 'expression' (and Stryker mutates expressions and statements). A new orchestrator hierarchy (maybe with only one class) has to be created to cover these.
But associated mutation switching logic remains TBD.

**Comment by dupdob** [comment]
so strings are not mutated because they are part of a ConstantPatternSyntax.
The fact is, we can mutate ConstantPatternSyntax, it's just that we need to control it at the right level (i.e. at the whole expression level)

**Comment by dupdob** [comment]
I have a working logic. It requires adding the possibility for an orchestrator to prevent any children from injecting mutations.
