### ISSUE TITLE
Crash/error log uploading and automatic reporting

### ISSUE THREAD

**Issue by perdignus** [stryker-mutator/stryker-net#296]
Something the stryker team noticed was that a couple releases didn't work, but they only found out after they wanted to use it themselves. After creating an issue for the problem, multiple other users also reported to have the same problem. 

Thus we can conclude that users won't always create issues on this repo when something goes wrong. It would be useful to give users the option to enable automatic error/crash reporting. This would be triggered when stryker crashes or has a breaking bug. The log/stacktrace/summary of the crash could be send to a shared location.

The log should at least include: the exception message, datetime of occurance, version of stryker.
If possible, the crashes should be grouped by similar issues/crashes so that it is clear how often it occurs. For example the exception + class and line where the crash occurred as a directory <exception>/<class>_<line>.

**Comment by perdignus** [comment]
@richardwerkman what's your opinion on this

**Comment by richardwerkman** [comment]
The logs could contain sensitive data that should not be uploaded to a shared server. Even when we ask users if they want to send us information about their crash I'm not sure why users would accept this. 

And of course we should strive to create a crash free application in the first place! So I think we should focus first on adding more integration tests for more use cases. In my opinion this is not the kind of functionallity we want to offer. Users can always collect the data by running with --log-console and give us the logs. 

So I'm closing this issue for now. Maybe we could think about this in the long run.
