### ISSUE TITLE
Suggestion: Execute initial tests mulptiple times before testing mutants

### ISSUE THREAD

**Issue by cs-util** [stryker-mutator/stryker-net#303]
I just realized that if I run Stryker on unit tests that randomly fail 1 out of 5 times stryker will think that 20% of the generated mutants are successfully killed but in reality, it's just the tests randomly failing. So my proposal would be to execute the tests initially not only once but multiple times to cover the case that the developer has tests that currently are failing but do not fail every time. 

In my case, the random failing was caused because of a global shared state of the code and the tests being executed in parallel randomly. 

Just a suggestion since it would not add much extra time to the total test time.

**Comment by richardwerkman** [comment]
That would be a great way to detect some sneaky false positives! 

We could indeed run the initial test in parallel just like the mutation testruns. So on a 4 core machine the initital testrun would be executed 4 times. If all are succesfull I guess it's safe to assume that the tests succeed all the time? And this would almost add no extra run time. This would mean however that on a 1 core machine the initial testrun is still executed only once. 

We could also pick a fixed number of initial testruns that should always run. What do you think?

**Comment by cs-util** [comment]
I think a fixed number would make the most sense and setting it to 5 or 10 should be nearly no additional overhead compared to the time it normally takes for the actual mutation tests to run afterward. 

In my case, the tests failed roughly 1 out of 5 or maybe even 1 out of 10 times so testing only 4 times because I have 4 cores on my machine might not have found these concurrency problems.

**Comment by cs-util** [comment]
Another idea that just came to my mind: 
How about executing an unmutated version of the tests for every x mutations. So e.g. after 50 mutated test executions, run 1 unmutated test execution, if the unmutated execution fails as well then stop Stryker

This would help with my initial problem detecting if the tests just sometimes fail randomly, but it would also solve the edge cases where an external state change of the system is caused by executing the tests multiple times.

**Comment by richardwerkman** [comment]
This was partially fixed by #481 

It tests against an empty mutant. If it fails that could mean that the unit tests are instable. We log a warning for now when this happens.

Closing this issue for now. If the dectection should get any better we can reopen again.
