### ISSUE TITLE
Allow skipping the version check

### ISSUE THREAD

**Issue by jafletch** [stryker-mutator/stryker-net#3044]
Today we use the stryker tool as part of our regular build flow. During this flow we would prefer to reduce or eliminate network touches during. On startup stryker reaches out to api.nuget.org (not configurable from what I see) to check for newer versions and print a message suggesting an update.

My preference would be to add support for a flag (--skip-version-check) to allow skipping this check flow completely as we already have access to things like Dependabot for suggesting version updates so there is less need for this kind of a check in automated flows.

**Comment by rouke-broersma** [comment]
Thanks, makes sense. Do note that the version check is optional so feel free to block the request in your firewall, this should not impact stryker.

**Comment by mobratil** [comment]
@rouke-broersma, I have created a PR for this issue, as I already had the work in progress. Feel free to review it.

**Comment by jafletch** [comment]
@mobratil, here is how I was thinking about this change re: the comment I previously left in your current PR

#3049
