### ISSUE TITLE
New mutations for LINQ in .Net 9 - CountBy

### ISSUE THREAD

**Issue by Myoxocephalus** [stryker-mutator/stryker-net#3052]
**Is your feature request related to a problem? Please describe.**
.Net 9 will soon be released and contains a few new LINQ methods that can be mutated.

**Describe the solution you'd like**
My suggestion is to add the following new mutation.
| Original    | Mutated |
| CountBy    | Count |

**Comment by dupdob** [comment]
Hi
Thanks for this idea. But `Count` and `CountBy` have very different return types, if I am not mistaken (`int/long` vs `Enumerable<int>`, so this more complex than replacing one with the other. If Stryker does that, this mutation would almost always result in a compilation error, which is of little added value.
What kind of mutation you had in mind?
