### ISSUE TITLE
Stryker disable comment not working for global statements

### ISSUE THREAD

**Issue by cfuehrmann** [stryker-mutator/stryker-net#3073]
**Describe the bug**

I have a .NET 8 Web API whose "Program.cs" contains the code below.

![image](https://github.com/user-attachments/assets/3a3f861c-ee42-4918-976e-a0cfe8e2b44f)

The variable `SWAGGER_MODULE` is set when the project compiles with the "DEBUG" configuration, and not set when it compiles with the "RELEASE" configuration. Eitherway, note how the `// Stryker disable all` is outside of the `#if`. Still, the code gets mutated. (This is also the case if I move the `// Stryker disable all` inside the `#if`.)

Why does `// Strykler disable all` not work?

**Logs**

Stryker takes several hours on this very big project. I can run it over night and deliver the logs if really required.

**Expected behavior**

I expect that the code between `// Stryker disable all` and `// Stryker restore all` is not mutated.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Type of project: .NET 8 Web API
 - Framework Version: .NET 8 Web API
 - Stryker Version: 4.3.0

**Comment by dupdob** [comment]
hi
thanks for reporting this. 
I added a unit test to try to reproduce this issue but it appears to be working. Disregarding the placement of the #`#if ... #endif` block, the mutations are not generated.
In other words, I do not reproduce your problem. The stryker comment is supposed to work and I have no explanation on why it fails in your case.

Could try using `// Stryker disable once all` on the `app.UseSwagerUI(...)` line and report the result ?

Are you using an incremental feature (via 'since') ? this may the cause (there may be a bug when ignoring mutants via stryker comments is not properly handled)

**Comment by cfuehrmann** [comment]
Hi, thanks for your quick reaction!

- About Question 1: `// Stryker disable once all` succeeded where `Stryker disable all` failed!
- About Question 2: As far as I can see, I don't use incremental features. Here is the `stryker.json` for the project:
```json
{
  "stryker-config": {
    "report-file-name": "WebApi.html",
    "project": "WebApi.csproj",
    "test-projects": [ 
      "../WebApiTests/WebApiTests.csproj",
      "../WebApiRoutesTests/WebApiRoutesTests.csproj"
    ],
    "thresholds": {
      "break": 77
    },
    "mutation-level": "Complete",
    "additional-timeout": 30000
  }
}
```
- About Question 3: I have one similar comment in the whole application, also in the "Program.cs", and it also fails:
![image](https://github.com/user-attachments/assets/483b62ed-a19b-42f2-a5b4-184c60b4be1c)
Besides that, I have multiple `// Stryker disable once Linq` in many files, and those all work. No other Stryker suppression anywhere.

**Comment by cfuehrmann** [comment]
I should maybe also mention that the `WebApi.csproj` contains this:

```xml
	<PropertyGroup Condition="$(Configuration.Equals('Debug'))">
		<DefineConstants>SWAGGER_MODULE;SERILOG_SINK_SEQ_MODULE</DefineConstants>
	</PropertyGroup>
```

**Comment by dupdob** [comment]
Thanks. Any occurrence where you use `disable all` outside `#if...'  constructs?
I am trying to figure out if there is a true correlation.

**Comment by cfuehrmann** [comment]
I check with an overnight run, and indeed `// Stryker disable all` seems to work in other places. Below you see another screenshot from our "Program.cs". The highlighted area is normall full with mutations.

![image](https://github.com/user-attachments/assets/c74ae719-d1bd-49f9-bd6b-8ecd0905e7d0)

**Comment by dupdob** [comment]
Many thanks, this helps me. 
I will try and reproduce this on a smaller project. If successful I can probably fix this straight away. 
I will revert to you if I am stuck and need extra information from your problem.

**Comment by dupdob** [comment]
Hummm
I am not able to test it, but I have a theory: it is possible that the Stryker comment is linked to the preprocessor command (#if). 
Those are ignored by Stryker parser, so any linked comments will be ignored as well. 

You could introduce an empty statement (´;´) between the command and the comment.

**Comment by dupdob** [comment]
Still unable to reproduce it, but at least, I know that Stryker tends to mess with #endif directives

**Comment by dupdob** [comment]
Since I cannot reproduce it, no promises there. 
BTW could you share the later statement before the #if ? My current theory is that both the Stryker comment and the directive were linked to the previous statement for some reason.

**Comment by cfuehrmann** [comment]
Here we go: 

![image](https://github.com/user-attachments/assets/d1a45df7-e69e-4241-9dbf-f19f59db7a31)

Mind you, the disabling statement also failed when it was inside the pragma.

**Comment by cfuehrmann** [comment]
Hi, here the results with semicolons: 
![image](https://github.com/user-attachments/assets/db4e00a0-cd8e-477f-a363-0f2a63fb4d9f)

**Comment by dupdob** [comment]
Well. They are still there. No idea why they appear in timeout.

**Comment by cfuehrmann** [comment]
If there is any other info I can provide, please let me know.

**Comment by dupdob** [comment]
Well. I was about to abandon all hopes, but I got a bunch of weird results doing integrated tests (vs unit): some mutators are disabled but not others. So there is something fishy here and I have a reproducing project. So, I can work now

**Comment by cfuehrmann** [comment]
Wow, thanks for the heroic stamina!

**Comment by dupdob** [comment]
I am afraid the log will not be able to help me, and I definitely need your help to move forward.
I assume this project is not publicly accessible (if yes, please share the link). 
But, parsing happens at the file level, so maybe you can share me the 'offending' source file privately with me.
Alternatively, devise a small project that reproduce the problem.

Finally, Yyou can also try and debug Stryker locally and see what happens. I can give you pointers where to look and hook 😄

**Comment by cfuehrmann** [comment]
I've just looked through the offending file ("Program.cs"). While the whole API is a commercial product, I can easily defend sharing the "Program.cs" with you, if you provide me with an upload pointer.

Be warned thought that the "Program.cs", being the "composition root" in the sense of dependency injection is full of dependencies that I cannot provide.

**Comment by dupdob** [comment]
Thanks. I think the best way is for you to go to the project slack: https://stryker-mutator.slack.com/join/shared_invite/enQtOTUyMTYyNTg1NDQ0LTU4ODNmZDlmN2I3MmEyMTVhYjZlYmJkOThlNTY3NTM1M2QxYmM5YTM3ODQxYmJjY2YyYzllM2RkMmM1NjNjZjM#/shared-invite/email

And DM me there with the file

**Comment by cfuehrmann** [comment]
Thanks, I just DMed you the file.

**Comment by dupdob** [comment]
Thanks for your help. I am now able to reproduce the issue. This is a problem with top level statements. It turns out we have no test for these (unit or otherwise).
For some reason, `// Stryker disable all` applies only to the next statement.

I am looking into how to fix this. I suppose you consider this problem as a minor until we provide a fix, but if you want to have a workaround, you can either use the legacy construct for the main method. If you can't or it does not suit you, you can use `// Stryker disable once all` end enclose this bit of code in curly braces for the same result.

Ultimately, you can also use multiple `// Stryker disable once`.

Sorry for the inconvenience and thank you for bearing with me with this.

**Comment by dupdob** [comment]
I just opened PR #3087 that will fix that.

**Comment by cfuehrmann** [comment]
This problem is indeed a minor to me. Thanks for your effort! Should I close this issue?
