### ISSUE TITLE
Exception on start for long session

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#312]
There is an exception If the total estimated test time is more than one hour (_' System.FormatException: Input string was not in a correct format.'_).
Reproduced and fixed locally. I will add relevant regression tests and open a PR.

**Comment by rouke-broersma** [comment]
> Created a simple consoleapp with an long add(int a, int b) function in it. Tested it with a simple unittest in a different project. This just to get to know Stryker. However, after 2 minutes stryker crashes with this same error: ' System.FormatException: Input string was not in a correct format.' I use dotnet-core 5.0. Update, dotnet-core 6.0 works just fine.

Hi @DriezL

I doubt your problem is related to a 3 year old closed issue. Could you create a new issue with the specific details of your problem and if possible a reproduction?
