### ISSUE TITLE
Technical references

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#32]
Where would we like to document our technical references? Things like:

- How the mutation algorithm works
- How Mutators can be added
- How the different packages work together

I see some options but would like to share thoughts.

1. GitHub wiki
2. Markdown files in a sub-folder 
3. External website

Especially diagrams are hard to maintain together. Maybe some sequence/activity diagrams could be useful. I've seen some tools that can generate diagrams from markdown. Which are best?

**Comment by Mobrockers** [comment]
Currently PlantUML is being investigated internally as a tool to generate such diagrams documentation and specification during build time.

**Comment by nicojs** [comment]
The Stryker handbook already has a script to generate sequence diagrams from clear text. Would be easy to add that for stryker-net as well.

In any case, the handbook could be a nice place for this.
