### ISSUE TITLE
Lambda assignment mutations break builds

### ISSUE THREAD

**Issue by maxcalvin** [stryker-mutator/stryker-net#339]
I've noticed that if we have a lambda which contains mutable components, stryker will mutate at the lambda assignment which does not compile and rolls back the mutation. With even a small amount of complexity it is easy to cause stryker to give up and abort the run.

I have created a minimal reproduction here:
```cs
    public class Class1
    {
        public void DoIt()
        {
            Action act = () => Console.WriteLine("A", "B", "C");
        }
    }
```
I have attached the output of `dotnet stryker --log-console debug` (ignoring the build output). Let me know if you need more of the log.

[stryker-debug.log](https://github.com/stryker-mutator/stryker-net/files/2850581/stryker-debug.log)

Thanks!

**Comment by richardwerkman** [comment]
I've tested this and it indeed breaks stryker. However, on version 0.7.0 it seemed to work. It seems a recent change caused this bug. I'll look into this in the near future 👍
