### ISSUE TITLE
Linq expressions with no replacements break builds

### ISSUE THREAD

**Issue by maxcalvin** [stryker-mutator/stryker-net#340]
I know the Linq mutator was only added recently but there appears to be issues with the mutations that go from something to 'none' (OrderBy, OrderByDescending, Reverse, etc), where the replacement is not able to build.

For example, the following line:
```cs
someList.OrderBy(i => i.ToString());
```
is mutated to:
```cs
someList.(i => i.ToString());
```

Perhaps the following options could be considered for fixes?
```cs
// Remove the call
someList;

// Find a valid anti-call (may not be always possible)
someList.OrderByDescending(i => i.ToString());

// Don't mutate (when no reasonable mutation exists)
someList.OrderBy(i => i.ToString());
```

I've put together a small reproduction:
```cs
    public class Class1
    {
        public void DoIt()
        {
            new List<object>().OrderBy(o => o.ToString());
        }
    }
```

And attached some logs: 
[stryker-debug.log](https://github.com/stryker-mutator/stryker-net/files/2861356/stryker-debug.log)

Thanks!

**Comment by richardwerkman** [comment]
Thanks for your notice. This mutation was meant to remove the call as you said. It seems nobody noticed this before since the mutations are just rollbacked and this is not shown (unless debugging is enabled). I'll look into this too!

**Comment by richardwerkman** [comment]
I'm not sure if this is even possible... To remove the statement we should place the mutation something like:

``` csharp
List<string> ordered = Stryker.ActiveMutationHelper.ActiveMutation == 8 ? list : list.OrderBy(x => x.Length);
```
But this produces an error since `list` and `list.OrderBy()` produce a different output type.
Also for `Reverse()` this is not possible since it produces no output and is thus used as a statement like:

``` csharp 
list.Reverse();
```
When mutated like:
``` csharp
if (Stryker.ActiveMutationHelper.ActiveMutation == 8)
{
    list;
} else {
    list.Reverse();
}
```
or
``` csharp
Stryker.ActiveMutationHelper.ActiveMutation == 8 ? list : list.Reverse();
```
Both produce compile errors...

Maybe it's best to just delete the "remove mutations". If we find a valid way of placing these mutations in the future they are not difficult to add again. @Mobrockers agreed?

**Comment by Mobrockers** [comment]
@richardwerkman Instead of removing the linq query, we could instead replace it with a ToList() or similar. This should work in most instances I think? If you see any issues with replacing it with a ToList then we can remove the mutation altogether yea.

**Comment by richardwerkman** [comment]
Putting a `ToList()` after the mutated node doesn't solve the problem. To fix this we should mutate the "original code" as wel. Something like this:

``` csharp
var ordered = Stryker.ActiveMutationHelper.ActiveMutation == 8 ? list : list.OrderBy(x => x.Length).ToList();
```
But now the original code is mutated and the return type of the whole expression was originally `IOrderedEnumerable` and is now `List`. This could cause even more trouble.

I think we are not ready for remove mutations alltogether... We might come up with a sollution later but for now we should remove these kind of mutations.

**Comment by Mobrockers** [comment]
I agree
