### ISSUE TITLE
Replace Linq OrderBy with OrderByDescending and vice versa

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#342]
Improvement found due to removal of linq mutations in #340 

When a list is explicitly ordered in some way, this should be tested. If the list ordered in the opposite manner still passes the test, then either the list does not need to be ordered, or the test should be amended.

Replace OrderBy statements with OrderByDescending and vice versa. This should not result in non-compilable code in most cases as the return type is the same.

Same for any ThenBy and ThenByDescending.

**Comment by richardwerkman** [comment]
Lets create an overview of what mutations should be added to the Linq mutator. Your suggestion (together with your other issue):

|      Original         |       Mutated         |
| --------------------- | --------------------- |
| `SingleOrDefault()`   | `Single()`    |
| `Single()`    | `SingleOrDefault()`   |
| `First()`    | `FirstOrDefault()`   |
| `FirstOrDefault()`   | `First()`    |
| `OrderBy()`   | `OrderByDescending()`    |
| `OrderByDescending()`   | `OrderBy()`    |
| `ThenBy()`   | `ThenByDescending()`    |
| `ThenByDescending()`   | `ThenBy()`    |

**Comment by Mobrockers** [comment]
Implemented by #424
