### ISSUE TITLE
Investigate possibility of replacing any linq query with a known return type with another

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#344]
There should be no issue replacing one linq query with another as long as the return type is the same. Currently we use a hardcoded list of query names to replace with other query names. If instead we group queries to replace by return type, we would make sure our mutation does not (most likely) result in a compile error, and it would be easier to manage which mutations to run.

The idea is:

query -> match return type with list of known queries + return types -> list of queries with same return type -> create mutation for each query in list.

@richardwerkman What do you think? Is this something we would like to have?

**Comment by richardwerkman** [comment]
So your idea is to resolve at runtime which methods do have the same return type? We currently don't have the return type of the method available.

**Comment by Mobrockers** [comment]
@richardwerkman No, my idea is we determine for every supported linq mutation what their return type is, and we add them to a list for their return type. Currently every linq mutation is in the same dictionary with <mutation, replacement>. I would propose changing that to <mutation, returntype> and/or <returntype, list<mutation>>
