### ISSUE TITLE
VsTest runner is stuck if test assembly is not found

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#390]
The VsTest runner remains stuck if the target testing assembly does not exist/is not found.

It should exit gratefully instead.

**Comment by richardwerkman** [comment]
In what case does the target assembly not exist? Stryker executes a build before calling the vstest runner. The assembly should always be in place by then. What is your specific case?

**Comment by dupdob** [comment]
the test assembly name is different from the project name, so the actual problem is that the assembly is not found

**Comment by dupdob** [comment]
will look in to this as part of the mutant coverage effort
