### ISSUE TITLE
VsTest runner assumes the test assembly name

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#391]
VsTest runner assumes the test assembly name is derived from the project name.
If the assembly name has been changed, the process fails.
related to #390

**Comment by Mobrockers** [comment]
We can improve this once we have #371 merged because buildalyzer will probably be able to provide us with the necessary information about assembly names so we don't have to make assumptions anymore. It would be wasted effort to try to improve this before then.

**Comment by dupdob** [comment]
good idea
