### ISSUE TITLE
Azure DevOps extension to integrate html report

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#394]
In Azure DevOps it is possible to add custom build report tabs through extensions. If we create a stryker extension we could load the whole html report into azure devops.

**Comment by Mobrockers** [comment]
We may want this to be a separate repo, as the html report is not stryker-net specific so any mutation report could be loaded by azure devops

**Comment by anhaehne** [comment]
As an intermediate solution to integrate with Azure Pipelines we could add a reporter that emits Errors in the form of: `##vso[task.LogIssue type=error;]This is the error`

See: [Azure Pipelines - Write an error](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#write-an-error)

That would allow fail a build when a mutant survives.

**Comment by Mobrockers** [comment]
A pipeline should already fail when Stryker is properly configured as we
exit Stryker with a non-zero status code if the amount of survived mutants
is over the threshold.

**Comment by anhaehne** [comment]
Yes but the user will see an error message like `dotnet.exe has exited with an non zero exit code` and would have to drill down into the logs to see which mutants have survived.

With a special reporter, the pipeline result would display each survived mutant as an error.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Mobrockers** [comment]
Mhm good point 👍

**Comment by Mobrockers** [comment]
It's live! https://marketplace.visualstudio.com/items?itemName=stryker-mutator.mutation-report-publisher
