### ISSUE TITLE
Calculate maximum possible testrun time over entire mutation run

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#399]
Currently we timeout of a testrun when we believe the test has reached it's maximum possible test time and is stuck in a loop. We should determine the maximum time for the entire testrun and timeout if it has been exceeded. Something as simple as initial testrun time * mutants + additional timeout should be plenty.

**Comment by richardwerkman** [comment]
Where do we need this? This issue is a bit unclear for me.

**Comment by Mobrockers** [comment]
If for some reason a part of the program hangs (vstest runner for example or other out of process processes) we might not detect this and end up in an infinite wait. We should terminate the entire program when the global timeout has been reached.

**Comment by richardwerkman** [comment]
I'm not sure if this would be useful. In your case, if the vstest runner hangs, that would be during the initial testrun. So that would be before your timeout has been calculated. So how do we know when the initital testrun times out? We can't. I think we should just treat that kind of cases as a bug. We don't have to build in a mechanism to handle bugs. Stryker should just always work :)

**Comment by Mobrockers** [comment]
I have actually seen vstest hang after a number of mutation runs, which is why I think we need this.

**Comment by richardwerkman** [comment]
Don't you think we should tackle that instead of creating a timeout? If we figure out why vstest hangs and we solve that we won't need the timeout. Have you created an issue for vstest hanging already?

**Comment by Mobrockers** [comment]
Yes, we should. But in the case a bug slips in it would not be a good user experience if stryker just keeps on running forever.

I have not created the issue yet because we need to redesign how we make vstest available on the system first.

**Comment by richardwerkman** [comment]
This is not needed anymore. Closing.
