### ISSUE TITLE
ExpressionStatement breaks stryker

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#411]
It seems that some ExpressionStatements containing a lot of mutations break stryker. Example:

``` cs
await SendRequest(url, HttpMethod.Get, (request) =>
{
     request.Headers.Add("Accept", "application/json; version=1");
     request.Headers.TryAddWithoutValidation("Date", datum);
}, ensureSuccessStatusCode: false);
```

4 mutations are made in this Expression, each rollback step 1 is removed unit this is left:

``` cs
Stryker.ActiveMutationHelper.ActiveMutation==16?await SendRequest(url, HttpMethod.Get, (request) =>
{
     request.Headers.Add("", "application/json; version=1");
     request.Headers.TryAddWithoutValidation("Date", datum);
}, ensureSuccessStatusCode: false):await SendRequest(url, HttpMethod.Get, (request) =>
{
    request.Headers.Add("Accept", "application/json; version=1");
    request.Headers.TryAddWithoutValidation("Date", datum);
}, ensureSuccessStatusCode: false);
```
This does not compile and stops with exit code 1.

These mutations should not be placed with the `conditional statements` but with `if statements`. Then the mutations would compile and Stryker will continue after mutating.

**Comment by dupdob** [comment]
Hum
Not sure an if is needed here, but ternary operator is ill placed.

Envoyé de mon iPhone
