### ISSUE TITLE
Feature request: Support for test filters

### ISSUE THREAD

**Issue by kwlin** [stryker-mutator/stryker-net#420]
It would be nice to provide a way which tests should be executed within stryker-mutator like: https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests 

Just to prevent (integration/long running)tests will be executed during a stryker run.

**Comment by richardwerkman** [comment]
This could potentially conflict with our new feature #388. We have to use the filter there too. If we have a way of combining the users filter with our own filters this would be a nice improvement!

**Comment by rubberduck203** [comment]
We heavily use test categories and filters to specify which tests can be run without external hardware connected.
Without a way to filter out tests that won't pass without that hardware, we can't really leverage this great tool.
Is there another option for filtering?

**Comment by richardwerkman** [comment]
@rubberduck203 I guess there is a way. When you enable coverage analyse `dotnet stryker --coverage-analysis perTest` stryker automatically filters out test cases that are not hit by any tests.

So if you enable test coverage you should be able to run stryker on your project! You might have to exclude some files to make sure that the hardware tests won't run.

**Comment by jnyrup** [comment]
It would be nice to have this filtering performed before coverage analysis.
Especially when  coverage analysis cannot filter out tests due to
```
WRN: Each mutant will be tested against XXX because we can't get coverage info for test case generated at run time
```

I assume this could both speed up the initial test run and the mutation test runs.

**Comment by Mobrockers** [comment]
We are open to pull requests to enable custom test case filtering as long as this works alongside coverage analysis.

**Comment by corentinaltepe** [comment]
I would be very interested in implementing such feature. I'm unfamiliar with the code base. Would anyone have pointers to how to get started, which classes the option is likely to be added, what implementation you think would work? Thanks.

**Comment by rouke-broersma** [comment]
> I would be very interested in implementing such feature. I'm unfamiliar with the code base. Would anyone have pointers to how to get started, which classes the option is likely to be added, what implementation you think would work? Thanks.

We execute the tests using vstest here: https://github.com/stryker-mutator/stryker-net/blob/v1.0/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs

This class also does test discovery. It's been a while since I touched this but I think the flow would generally be as follows:

1. user passes filter to stryker as an option according to new standard: https://github.com/stryker-mutator/stryker-net/pull/1273
2. filter gets used to filter the discovered tests in the initial testrun
3. filter gets to filter the executed tests during coverage analysis (all modes)
4. if coverage analysis is turned off, the filter needs to be applied still

I would suggest taking up 1 last, because we are reworking the complete option infrastructure.

**Comment by dupdob** [comment]
hello
@corentinaltepe : for information, I am a bout to open a PR with a redesign (and simplification) of tests and coverage management components. I still have some use case tests to add to my work, but I can open the PR in draft and then we can discuss how to implement this. Do you have access to Stryker's Slack?

**Comment by dupdob** [comment]
See PR: #1542

**Comment by corentinaltepe** [comment]
Hello. Thank you both for your guidance. 

@dupdob: Thank you. I'll base my work off #1542 if I manage to offer any solution. Sorry, I don't use Slack but I'll make sure to post updated/questions I might have here or on #1542.

**Comment by rouke-broersma** [comment]
That's no problem!

**Comment by jchesshir** [comment]
Can I get an update on the progress of this issue?  Being able to knock certain tests out of the running would be a HUGE improvement IMHO.

**Comment by rouke-broersma** [comment]
A wip pull request has been contributed that will probably be included in v1 which should implement this feature request. We don't have an eta for v1, sorry. The options rework is way more effort that we thought it would be.
