### ISSUE TITLE
Check for errors in mutant orchestrator tests

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#422]
## Why?
The unit tests for the mutant orchestrator are increasingly important for the stability of Stryker. We should add a test case to validate if all output is valid syntax. 

## Example
For example see #413. All tests were green but the syntax was incorrect. If this would have been merged a lot of mutations would have been rollbacked.

Note: we don't have to compile the output. We can just check for Syntax errors by calling the errors property on a syntaxtree.

**Comment by Mobrockers** [comment]
Fixed by #430
