### ISSUE TITLE
Feature request: support for signed assemblies

### ISSUE THREAD

**Issue by decipherer** [stryker-mutator/stryker-net#427]
We (VECOZO, used to) use a lot of signed assemblies here. Unfortunately stryker.net fails if the assembly to mutate is signed. I created a fix locally that works for our projects. It is based on the full-framework branch as we only use full framework for now.

Besides the added support for signed assemblies it contains a fix for certain projects that buildalyzer is not able to analyze well without passing the solution file to ProjectFileReader.AnalyzeProject. In our case the references of the project file were not found by buildalyzer without passing the solution file. With this fix, even though the references are found, buildalyzer still says analyzing fails, I've added a warning when that happens.

I'm not sure why the solution file wasn't passed in before. It seems to have been a conscious decision, as solutionFilePath was an optional parameter.

I will create a pull request in a minute, take what you like :)

-edit- pull request created: #428

**Comment by Mobrockers** [comment]
A solution file is used only for full framework projects, therefore a solution file should not be required.

**Comment by decipherer** [comment]
In the full framework branch, the solution path was always passed when analyzing the test project. In my change it is now also passed when analyzing the project under test. It seems the parameter should be optional for both cases then, based on full-framework or not.

I've not looked very deep into it, but it may also be a shortcoming in buildalyzer, as it's 'Succeeded' property is still 'false'.

**Comment by Mobrockers** [comment]
Merged with #428
Not sure when I'll be able to release a new RC or a full release

**Comment by decipherer** [comment]
Thanks for merging!
