### ISSUE TITLE
Stryker.net Report mutation score 100% is confusing when total mutants = 0

### ISSUE THREAD

**Issue by RinivR** [stryker-mutator/stryker-net#429]
Hi,

On the Stryker.NET Report the mutation score shows scores of 100% when the Total mutants = # Killed OR also when the Total mutants = 0 (so when in the file no code can be mutated). 
This is confusing. I expect when there is no code can be mutanted that the mutation score should be 0% because there is no test can be match against the mutants.

greetz.

**Comment by richardwerkman** [comment]
We are already working on this in #416! The new scenario will exit Stryker when no mutants have been made, before any reporter is called. This will mean that you won't see a 100% mutation score anymore. Is this a good solution for you?

**Comment by RinivR** [comment]
Richard, this sounds as a good solution!

**Comment by Mobrockers** [comment]
Implemented by #416 
Will release new RC when time permits
