### ISSUE TITLE
Add linenumbers to html report

### ISSUE THREAD

**Issue by SierraNL** [stryker-mutator/stryker-net#458]
It's seems there are no linenumbers in het html report (version 0.10.0).
It would be helpful to add them.

**Comment by richardwerkman** [comment]
As the html report comes from another open source project I've forwarded your request to an issue there:
https://github.com/stryker-mutator/mutation-testing-elements/issues/30

**Comment by Mobrockers** [comment]
A new stryker version with line numbers in the html report should be released shortly.
