### ISSUE TITLE
How do I exclude files with a pattern?

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-net#464]
**Source: https://github.com/stryker-mutator/stryker/issues/1515 by @Project4MobileDev**

### Summary

How do I exclude files with a pattern? I want to run stryker against a Xamarin .netstandard 2.0 library, I'm using stryker with in the console with the following command:
dotnet stryker -cp stryker-config.json

In the config file I'm specifying files to be excluded but it seems to only allow specific file names rather than using a pattern to exclude them. I've tried a few different ways of specifying a pattern, see the config file below. 

### Stryker config

```{
  "stryker-config": {
    "files-to-exclude": [
      "pattern": "/Views/*",
      "pattern": "**/*.xaml.cs",
      "pattern": "**/*.xaml",
      "/**.xaml.cs",
      "/**.xaml",
      { 
        pattern: "**/*.xaml.cs"
      }
      { 
        pattern: "**/*.xaml"
      }
    ]
  }
}
```

### Test runner

```
xUnit
```

### Environment

Windows 10
.NET Command Line Tools (2.2.203)

**Comment by Mobrockers** [comment]
@Project4MobileDev

We do not currently support patterns in exclusions. We support excluding whole folders or individual files. See our docs here :

https://github.com/stryker-mutator/stryker-net/blob/master/docs/Configuration.md#excluding-files

**Comment by richardwerkman** [comment]
Stryker.NET only reads and mutates `.cs` files. So you won't have to exclude `.xaml` files. That's why you don't have to pass any file extension.

As mobrockers said you can exclude folders, in your case I suggest something like:
```
"files-to-exclude": [
    "/Views/"
 ]
```

This will exlude all `.cs` files from mutation in you `Views` directory.

We are planning to implement pattern paths in the future. See #322

**Comment by Project4MobileDev** [comment]
Ah cool, thanks for your quick response, that answers my question :) Cheers!

**Comment by richardwerkman** [comment]
closing since question was answered
