### ISSUE TITLE
Decrease default additional timout

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#510]
**Is your feature request related to a problem? Please describe.**
Mutation testruns take longer than necessary due to very long default timeouts.

**Describe the solution you'd like**
Decreasing the default timeout from 30000 to 5000 greatly increases testrun speed.

**Describe alternatives you've considered**
Manually lowering the timeout for every project shows me that on most projects the default timeout can be much lower.

**Comment by dupdob** [comment]
With VsTestRunner you can monitor the time of each test in isolation; this can be used to identify timeout at the test level.

**Comment by Mobrockers** [comment]
@dupdob We don't decide timeouts on a per-test basis but on a mutant basis. I feel this is close enough without monitoring the per-test testtime. Simply lowering the default aditional test timeout value will decrease the overall runtime for most people as 30 seconds timeouts have proven to be way too much on our internal tests.

**Comment by dupdob** [comment]
Having a global felt sufficient for me too, but then I realised that having a unit test running for 2 seconds while it normally takes 20 ms was a strong hint.

Also, using coverage analysis, you should establish an estimated run time for each mutant (by summing the running time for each impacted tests), as not all tests are run.
this will also decrease the time issue
