### ISSUE TITLE
Progress bar appending instead of replacing values inline (Macos 10.14.5)

### ISSUE THREAD

**Issue by Kevintjeb** [stryker-mutator/stryker-net#519]
**Describe the bug**
Currently when running dotnet stryker, the reporter does not replace values inline in the terminal. It appends to it. This makes it look like the following:

**Logs**
[10:54:19 INF] Started initial build using dotnet build
[10:54:24 INF] Initial build successful
[10:54:24 INF] Using testrunner DotnetTest
[10:54:24 INF] Initial testrun started
[10:54:29 INF] Total number of tests found in initial test run: 56
[10:54:29 INF] Initial testrun successful in 4518 ms
[10:54:29 INF] Using 36777 ms as testrun timeout
[10:54:32 INF] 53 mutants ready for test

53 mutants have been created. Each mutant will now be tested, this could take a while.

Tests progress | ---------- | 0 / 53 | 0 % | NA |
Killed : 0
Survived: 0
Timeout : 0

Tests progress | ---------- | 1 / 53 | 1 % | ~5m 58s |

Killed : 1

Tests progress | ---------- | 2 / 53 | 3 % | ~2m 56s |

Killed : 2

Tests progress | ---------- | 3 / 53 | 5 % | ~1m 55s |

Survived: 1

Tests progress | ---------- | 4 / 53 | 7 % | ~1m 25s |

**Expected behavior**
I expect the output to be replaced, and thus having an animating progress bar.

**Desktop:**
 - OS: Macos
-  Terminal: Iterm2, and integrated terminal. Using the ZSH framework.
 - Type of project: core
 - Framework Version: core 2.2
 - Stryker Version:  beta 0.11.0

**Comment by Mobrockers** [comment]
When we cannot determine if we are dealing with an interactive console, we disable replacing the progress bar inline. See: 
https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Reporters/Progress/ConsoleOneLineLogger.cs#L27

And

https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Reporters/Progress/ConsoleOneLineLogger.cs#L62

Our check is pretty crude so it could very well be something else is crashing on MacOS which causes us to treat your terminal as non-interactive.

**Comment by richardwerkman** [comment]
We could look into https://www.nuget.org/packages/ShellProgressBar/# as an alternative for our own progress bar. ShellProgressBar claims to be .net core ready and to run on macos.

This could potenitally fix all errors we encountered with the progress bar like:
- Resizing issues
- #486 
- This issue

**Comment by nicojs** [comment]
Sounds great. Less code to maintain by us. Hopefully that dependency is actively maintained.

**Comment by Kevintjeb** [comment]
Regarding this issue on Macos, it seems that when instantiating the `ConsoleOneLineLogger` the following code misbehaves on macos:

```c#
public void StartLog(string text, params object[] args)
{
      if (_hasConsole)
      {
         _cursorTop = Console.CursorTop;
      }
      _logger.LogInformation(text, args);
}
```

`Console.CursorTop` is always the same and **not** incrementing as expected.

**Comment by richardwerkman** [comment]
Could that be the same issue as we saw on Linux in #486? There `Console.CursorTop` returned a negative value.

It looks like the .net core implementation of `Console.CursorTop` does not work as expected...

**Comment by Mobrockers** [comment]
@eNeRGy164 It usually does that when you've moved the powershell window any time after initialization. If you don't move the powershell window replacing should in my experience work.

**Comment by richardwerkman** [comment]
Powershell works fine for me (except resizing but that's an edge case I think)

**Comment by eNeRGy164** [comment]
No resizing, but I use PowerShell Core running in the Windows Console
Screen recoding:
![ps](https://user-images.githubusercontent.com/10671831/97079000-b781bf00-15f0-11eb-9606-c7e179da2659.gif)

**Comment by Mobrockers** [comment]
Powershell core probably has the same problem as dotnet core on linux with the `Console.CursorTop` as powershell core runs on dotnet core.

**Comment by eNeRGy164** [comment]
I gave it a stab:
![pgb](https://user-images.githubusercontent.com/10671831/97163910-a5835600-1781-11eb-9942-e78bc2580dd6.gif)

**Comment by Mobrockers** [comment]
That looks awesome!!
