### ISSUE TITLE
--project-file does not accept relative paths

### ISSUE THREAD

**Issue by hannahchan** [stryker-mutator/stryker-net#520]
I have the following file structure for my Application.
```
ExampleApp
├─ Sources
│  ├─ Project1
│  ├─ Project2
│  ├─ Project3
│  └─ Project4
├─ Tests
│  ├─ Project1.Tests
│  ├─ Project2.Tests
│  │  └─ stryker-config.json
│  ├─ Project3.Tests
│  └─ Project4.Tests
└─ ExampleApp.sln
```
When my current directory is *Project1.Tests* and I run `dotnet stryker --project-file="../../Sources/Project1/Project1.csproj"`, I get the error message *Project reference issue.*

Likewise I get the same error message when my current directory is *Project2.Tests* and I run `dotnet stryker` with a *stryker-config.json* containing the following;

```
{
    "stryker-config":
    {
        "project-file": "../../Sources/Project2/Project2.csproj"
    }
}
```

The error does not occur when using absolute paths. The version of `dotnet-stryker` I am using is `Version 0.11.0 (beta)`. The issue happens both in Windows 10 and macOS.

**Comment by Mobrockers** [comment]
Hey Hannah,

Apologies for the confusion but we don't actually match the project file with the file system, we match the project file name with your project references in the test project. This should be enough to get Stryker running:

`--project-file="Project1.csproj"`

Also if project1 is the only project reference in your project1.tests project then we can auto detect your project-file settings and you won't have to supply it yourself.

**Comment by hannahchan** [comment]
Thanks for getting back so quick. I just confirmed what you said and it works. I got confused because the error message I get back looks like this.
```
Project reference issue.

Test project contains more than one project references. Please add the --project-file=[projectname] argument to specify which project to mutate.
Choose one of the following references:
  C:\Users\Hannah.Chan\Code\Scaffold.WebApi\Scaffold\Sources\Scaffold.Application\Scaffold.Application.csproj
  C:\Users\Hannah.Chan\Code\Scaffold.WebApi\Scaffold\Sources\Scaffold.Data\Scaffold.Data.csproj

Example: --project-file=C:\Users\Hannah.Chan\Code\Scaffold.WebApi\Scaffold\Sources\Scaffold.Application\Scaffold.Application.csproj
```
So I assumed it needed a file path. Maybe absolute paths shouldn't work?

**Comment by Mobrockers** [comment]
We should probably improve the detecting and logging of the project under test settings, thank you for bringing it to our attention!

**Comment by jisperliu** [comment]
+1
the logging is confusing. It's probably better to let ppl know they can just use project name instead of giving a full path and this intuition that ppl can use relative path

**Comment by rouke-broersma** [comment]
I think this has been improved sufficiently
