### ISSUE TITLE
Nuget in path not found in Framework projects

### ISSUE THREAD

**Issue by leonverschuren** [stryker-mutator/stryker-net#533]
**Describe the bug**
When running Stryker on an .NET Framework 4.6.1 project stryker throws the following error:

`Nuget.exe should be installed to restore .net framework nuget packages. Install nuget.exe and make sure it's included in your path.`

However nuget is included in the path.

**Logs**
[logs.txt](https://github.com/stryker-mutator/stryker-net/files/3229244/logs.txt)

**Expected behavior**
Stryker to run and not throw an error

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Type of project: .NET Framework 
 - Framework Version: 4.6.1
 - Stryker Version: 0.11.0
 - NuGet Version: 4.8.1.5435

**Additional context**
Project is in SDk style, but error is also thrown in legacy csproj formats

**Comment by Mobrockers** [comment]
Hey leon,

We use where.exe (a default windows cmd app) to determine the nuget.exe location, see: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs#L151

Could you try running `where.exe nuget.exe` and show us the output?

**Comment by leonverschuren** [comment]
Hi Rouke,

This is the output:

`C:\choco\bin\NuGet.exe
C:\Users\LEON\bin\NuGet.exe`

**Comment by Mobrockers** [comment]
Aha, our nuget locator seems to not be case insensitive and also doesn't handle multiple results currently.

**Comment by leonverschuren** [comment]
Thanks for the update. Renaming the NuGet file fixed the issue for now.

**Comment by richardwerkman** [comment]
I'll pick this up now!
