### ISSUE TITLE
Stryker fails to resolve system assemblies on sdk style full framework project

### ISSUE THREAD

**Issue by AlwaysFollowTheCode** [stryker-mutator/stryker-net#537]
**Describe the bug**
Stryker throws a compile error 

**Logs**
[ConsoleOutput_Stryker_29-05-2019.txt](https://github.com/stryker-mutator/stryker-net/files/3232522/ConsoleOutput_Stryker_29-05-2019.txt)

More logs can be provided if necessary 

**Expected behavior**
Project compiles after mutation

**Desktop (please complete the following information):**
- OS: Windows Server 2012 R2
- Type of project: .NET Framework
- Framework Version: 4.6.1
- Stryker Version: 0.11.0
- NuGet Version: 4.8.1.5435

**Additional context**
Project is in SDK style, but error is also thrown in legacy csproj formats

**Comment by Mobrockers** [comment]
Hey! Would it be possible for you to provide us with a reproducible sample so we can investigate this?

**Comment by richardwerkman** [comment]
The sources code that does not compile is injected by Stryker into your source code. This is injected before all else so it's the first code that will compile.

My guess is that somehow the resolving of references assemblies and projects does not succeed on your project. We currently use buildalyzer for this, so this could be an issue with them...

**Comment by richardwerkman** [comment]
@AlwaysFollowTheCode did you run stryker on an open source project? If so we could debug this to see why stryker crashes on the project. If it's closed source, could try to debug for us? 

I don't think we can tackle the bug with current info.

**Comment by Mobrockers** [comment]
No longer possible to reproduce
