### ISSUE TITLE
Investigate per-test timeout strategy to replace per-mutation timeout

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#569]
Having a global felt sufficient for me too, but then I realised that having a unit test running for 2 seconds while it normally takes 20 ms was a strong hint.

Also, using coverage analysis, you should establish an estimated run time for each mutant (by summing the running time for each impacted tests), as not all tests are run.
this will also decrease the time issue

_Originally posted by @dupdob in https://github.com/stryker-mutator/stryker-net/issues/510#issuecomment-499933830_

**Comment by dupdob** [comment]
Alternative solution: use mutation hit count

**Comment by dupdob** [comment]
actually, it is not: we are still on a per mutation time out. The idea here was to detect when a single test ran for too long.
still could be closed as it probably requires long tuning and solve some tricky issues (how to arbitrarily abort a long test safely)

**Comment by richardwerkman** [comment]
We might want to look into that when we switched to the new MSTestRunner. Maybe it's easier to implement there.
