### ISSUE TITLE
Install Stryker .Net for .NET Framework Version=v4.7.1

### ISSUE THREAD

**Issue by alexbunardzic** [stryker-mutator/stryker-net#583]
Having problems trying to install Stryker for  .NET Framework Version=v4.7.1

The docs do mention installation for non-.Net Core projects, but the link seems to have expired.

Any pointers?

Thanks!

**Comment by Mobrockers** [comment]
Could you explain the problems you are having, and which links have expired? There is nothing different in installing Stryker for dotnet framework or dotnet core. Make sure you have at the minimum dotnet core 2.2 available and then run `dotnet tool install -g dotnet-stryker`.

**Comment by alexbunardzic** [comment]
I have no problems installing and running Stryker for dotnet core. I wasn't able to get it to work on .Net framework v4.7.1.

I'll try your instructions on Monday.

Thanks.

**Comment by Mobrockers** [comment]
There is no difference in installing between framework or core. Stryker runs on dotnet core only, even when testing a dotnet framework project. The only difference is in configuration and in that you need nuget.exe available in your path.

**Comment by alexbunardzic** [comment]
Everything works. Thanks for helping out :)
