### ISSUE TITLE
Installing stryker using toolpath option fails

### ISSUE THREAD

**Issue by vinnytheviking** [stryker-mutator/stryker-net#589]
**Describe the bug**
During my Azure Devops CI pipeline I need to install Stryker to run it against my project. 

When I do 

`dotnet tool install -g dotnet-stryker`

_Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed._

The recommended approach is to install the tool with --tool-path option.

`dotnet tool install dotnet-stryker --toolpath ~/artifacts`

However when I try and do that for Stryker it inject _dotnet-_ in front of the command which then fails for example

`dotnet ~/artifacts/stryker`

gets turned into

_No executable found matching command "dotnet-/home/artifacts/stryker"_

instead of /home/artifacts/dotnet-stryker

**Expected behavior**
When using the --toolpath option the dotnet- should not be prepended to the whole string but to the word stryker

**Desktop (please complete the following information):**
 - OS: Linux
 - core
 - core 2.2
 - Stryker 0.11.0

**Comment by Mobrockers** [comment]
Hey Vinny,

We use default dotnet tool behaviour, we do not define how dotnet should interpret the commands. I think you should ask the dotnet cli developers how this works.

Injecting dotnet- is how dotnet tools work.

**Comment by Mobrockers** [comment]
See microsoft explaination for how to run tools you installed in your own location:

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install

![image](https://user-images.githubusercontent.com/3595932/59849851-0ff3dd00-9369-11e9-8f2f-f8cb5334bf30.png)

**Comment by vinnytheviking** [comment]
I managed to get the resolution from the dotnet cli team and they raised an additional task for the ~/ folder approach.

[#11603](https://github.com/dotnet/cli/issues/11603) for anyone experiencing the same issue
