### ISSUE TITLE
Environment.GetEnvironmentVarible() does not exist in netstandard < 1.3

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#594]
**Describe the bug**
We inject Environment.GetEnvironmentVarible() into the source project to switch mutations in mutation testruns. This method is not available in netstandard > 1.3 so compiling fails.

Found in #593 
See: https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=netframework-4.8&viewFallbackFrom=netstandard-1.2

https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=netstandard-1.3

**Comment by richardwerkman** [comment]
I think it's best to say that we can't support `netstandard12` or lower. They are not used that much anyway and anybody still using it should upgrade to a newer version (IMO).

It also looks like there is no (simple) other way of getting Environment variables without using the actual GetEnvironmentVariable method.

**Comment by Mobrockers** [comment]
I agree, but that will be non-obvious for users with multiple targetframeworks. I think we should perhaps parse the targetframeworks and by default choose the higher version.

**Comment by dupdob** [comment]
PR #936 partially fixes it, as it no longer requires environment variables when using `VsTest`.
Full fix implies either dropping support for `dotnet test` or using symbol directives for compilation of mutant control
