### ISSUE TITLE
Build server

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#6]
We need to configure a online build server. Any thougths on which platform to use?

I know of [AppVeyor](https://www.appveyor.com/) and [Travis](https://travis-ci.org/)

**Comment by nicojs** [comment]
Generally, appveyer is for windows builds. Travis is for linux builds. I would suggest to use both. That way you can make sure that it works on both platforms

**Comment by simondel** [comment]
There's also of course CircleCI

**Comment by ptoonen** [comment]
And VSTS with its GitHub integration ;-)

**Comment by simondel** [comment]
In that case we will be limited by the free build minutes, right? (Unless we pay for an agent). I'd love to build on VSTS but I don't like the idea of having to pay for it as other offerings do offer free builds for open source projects.

**Comment by simondel** [comment]
We may want to move to Azure DevOps in the future. For now i'll close this issue.
