### ISSUE TITLE
The mutator uses `SyntaxKind.ExclusiveOrAssignmentExpression` which is `^=`.

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#618]
Either the documentation or the implementation is wrong. 

The mutator uses `SyntaxKind.ExclusiveOrAssignmentExpression` which is `^=`.
`|=` is `SyntaxKind.OrAssignmentExpression`.

_Originally posted by @jnyrup in https://github.com/stryker-mutator/stryker-net/pull/44_

**Comment by jnyrup** [comment]
As noted in #664 the direct negation of `^` depends on whether it's a boolean of integral type.
