### ISSUE TITLE
Add path param for nuget.exe

### ISSUE THREAD

**Issue by jisperliu** [stryker-mutator/stryker-net#626]
Add a parameter and a field in the configuration file to set path to nuget.exe as its required to restore NuGet packages for .net framework projects.

**Comment by richardwerkman** [comment]
@jisperliu we currently get the path using `where.exe`. It is able to find the `nuget.exe` path if it is present in your system path. 

If you follow the instructions as stated in their documentation stryker should run fine: https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#windows

**Comment by jisperliu** [comment]
@richardwerkman That's exactly the reason I think having a path param can be better. Instead of having one line of command now I have to get directory of nuget.exe, set environment variable in shell, then run stryker.

**Comment by Mobrockers** [comment]
But if you use a param you need to provide it every single time you run
Stryker instead of only set it once. I suppose in ci build scenarios it
might make sense to use a param, but as a user it does not make sense. We
will discuss it tomorrow and let you know.

**Comment by jisperliu** [comment]
@Mobrockers Yes and we can also use a config file. I'm having the CI mind here but I would think it enables the ability of people who wanna try this without putting their ```Download``` folder into ```PATH```

**Comment by Mobrockers** [comment]
I agree this makes sense for CI scenarios. Could you submit a PR for it? If not I'll get around to this eventually but it's not a top priority.

**Comment by jisperliu** [comment]
I'll make a PR later this week. My current workaround is add nuget path to powershell's ```$env``` variable.

**Comment by rouke-broersma** [comment]
Most CI tooling support making tools available in the path as part of the agent configuration. This is not really needed.
