### ISSUE TITLE
Stryker mutates Debug.Assert statements

### ISSUE THREAD

**Issue by apollux** [stryker-mutator/stryker-net#637]
**Describe the bug**
Stryker.Net mutates Debug.Assert expressions. It looks like Stryker.Net build the code in Release config, therefore the Debug.Assert statement won't be executed. Making Stryker believe that the mutation survived.

**Expected behavior**
I think Stryker.Net should not attempt to mutate Debug.Assert and Trace.Assert expressions. These are essentially tests as well, therefor it does not seem logical to change them. Alternatively Stryker.Net should define the Debug and Trace symbols while compiling, to have the assertions run.

**Comment by Mobrockers** [comment]
You're right, we don't compile in debug mode. Do you know if setting the DEBUG constant is all that is required to compile in debug mode? We don't use msbuild to compile so the concept of debug or release build doesn't really exist and we have to recreate it ourselves unfortunately.

**Comment by apollux** [comment]
I think defining the symbol is sufficient to enable Debug.Assert. https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Debug/ref/System.Diagnostics.Debug.cs#L16 seems to indicate the same.

I am not sure if Stryker should mutate Debug/Trace Asserts or ignore them.

**Comment by Mobrockers** [comment]
I don't think stryker should make assumptions about whether the user wants
code tested or not. Trace.Assert statements should be enabled in release
builds according to the docs so it could be used in production code to do
some kind of logging. If we assume they should always be ignored then we
are limiting users that do and it tested. Debug asserts could be ignored
perhaps but even then, it is code that exists in your project, and it's not
tested, that result is 100 percent valid whether it's by choice or not.

**Comment by richardwerkman** [comment]
@apollux  Using our new feature #646 you could exclude Debug.Assert from mutation. The feature will be released with the next version.

**Comment by apollux** [comment]
That will work, thanks for getting back to this!
