### ISSUE TITLE
Issues with non-standard output dlls directory

### ISSUE THREAD

**Issue by KirillFormado** [stryker-mutator/stryker-net#638]
**Describe the bug**
I cannot use stryker-net on a solution with the configuration like described below.
I've created the repo with the example of the solution [https://github.com/KirillFormado/Stryker-Net-Output-Issue](https://github.com/KirillFormado/Stryker-Net-Output-Issue)

The main difference with a regular solution configuration is that an output directory is changed from a standart /bin in the project folder to an output folder in the root of the repo.
csproj files don't contain <outputPath> element. Instead of that the <outputPath> is contained in the Common.props file. This file is imported into the csproj files.

The result of the stryker run on the unitTest project is that _analyzerResult.Properties["TargetDir"] throws the expection because Properties don't contain TargeDir.

I tried to fix it by just hardcoding the path to the bin directory. But the next issue was "Mono.Cecil couldn't resolve the one of assemblies but this dll lais in the same folder". I added DefaultAssemblyResolver with path to the output directory in the ModuleDefinition.ReadModule. It helped, but the last issue that I encountered was that the stryker didn't find any test.

**Expected behavior**
It will be good to have an opportunity to work with solutions like this

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: Library .net framework
 - Framework Version: .net framework 2.7.2
 - Stryker Version: Version 0.11.0 (beta)

**Comment by Mobrockers** [comment]
Thank you for the report, I'll take a look when I have time. In the mean time it looks like you're not using the newest version of Stryker! The new version won't fix this problem but it does include an update checker so next time you'll get a message if they is an update ;)

**Comment by KirillFormado** [comment]
Oh, yes I've just forgot to update codebase. But on my main project I've used the last pulled codebase of stryker. Ok, I can update and rechecking it for the test case project.

**Comment by AS25061988** [comment]
What is the fix for this issue.I am too facing the error The test project binaries could not be found at D:---\MutationTests\Build\bin\Debug\MyLib.UnitTests.dll, exiting...

**Comment by rouke-broersma** [comment]
Please let us know if this is still an issue. Closing for now.
