### ISSUE TITLE
Mutator should mutate string.Empty

### ISSUE THREAD

**Issue by anhaehne** [stryker-mutator/stryker-net#641]
**Is your feature request related to a problem? Please describe.**
It is common in C# to use the static field `string.Empty` instead of the empty string literal `""` but is not mutated at all.

**Describe the solution you'd like**
`string.Empty` should be mutated to `"Stryker was here!"`, the same as for the empty string literal.

**Comment by richardwerkman** [comment]
Nice catch! I think we forgot this as it is not a string literal but a SimpleMemberAccessExpression. This means that we have to create a new mutator in code just for this extra string mutation. The mutator should check if the SimpleMemberAccessExpression has an Expression with the value "String" or "string" and a Name with the value "Empty". If so it should return a new StringLiteralExpression with the value "Stryker was here!".

@anhaehne Would you like to try to create a PR yourself or should someone else pick this up?

**Comment by anhaehne** [comment]
I've already got some code working, just have to polish it. 

I encountered the problem that we can't decide whether `String` is the type `System.String` or a variable/member called `String` so i only implemented the mutation for the lowercase `string` since that is a reserved keyword in C#.

While implementing i also had the idea to not only replace string literals with different string literals (i.e. `"test" => ""`), but also to replace string literals with `null` (`"test" => (string)null`). 

Do you think that would be a worthwhile addition?

**Comment by richardwerkman** [comment]
No I don't think that would make much of a difference in many cases. We mainly mutate strings to see if there is a unit test to check for that specific value. By changing it to empty string we validate that. Also changing it to null would only mean extra run time as an extra Mutation has to be tested.

**Comment by anhaehne** [comment]
I created a PR, see: #653
