### ISSUE TITLE
Mutating while(true)

### ISSUE THREAD

**Issue by jnyrup** [stryker-mutator/stryker-net#642]
**Describe the bug**
I have some code which in reduced form looks like the snippet below.
```c#
public class UnitTest1
{
    [Fact]
    public void TestMethod()
    {
        Loop(true);
    }

    public static bool Loop(bool stop)
    {
        while (true)
        {
            if (stop)
            {
                return true;
            }
        }
    }
}
```

When running Stryker I see this warning:
```
Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
```

**Logs**
[log-20190731.txt](https://github.com/stryker-mutator/stryker-net/files/3453642/log-20190731.txt)

```
Stryker.NET encountered an compile error in C:\Users\jonas\source\repos\GenericTests\GenericClass\Class1.cs 
with message: 'Ext.Loop(bool)': not all code paths return a value (Source code: 
public static bool Loop(bool stop)
{
	while ((StrykerSnWrgPQwXU8BNiC.MutantControl.IsActive(0)?false:true))
	{
		if (stop)
		{
			return (StrykerSnWrgPQwXU8BNiC.MutantControl.IsActive(1)?false:true);
		}
	}
})
```

**Expected behavior**
No warning when running Stryker

**Desktop:**
 - OS: Windows 10 Version 1903 (OS build 18362.239)
 - Type of project core
 - Framework Version: 
	- library: `netstandard2.0`
	- test project: `netcoreapp2.2`
	- `dotnet --version`: `3.0.100-preview7-012821`
 - Stryker Version beta 0.12.0

**Additional context**

**Comment by dupdob** [comment]
Stryker raises this warning when a build error cannot be associated with a specific mutation; hence it removes all mutations from the current method to restore a working state.

The warning can be removed when there is a single mutation in the method, but this is an edge case.
 
Better fix can be considered, but they require development time as well as extra run time.

**Comment by richardwerkman** [comment]
In some cases stryker can change the code paths and this can reveal code path without a return statement that was unreachable at first. 

We could add a `return default` to the end of the method when this happens. But I don't like this solution as it requires compilation to C# 7.1 and until now we only inject C# 2 code. This would mean that we break for older versions.

We could also try to retrace which mutation caused the change of the code path. I think there are not much mutations that can cause this. Only mutations inside `If`, `While` and `For` expressions actually change the paths. Maybe we can try to remove them one by one and check if the code path changes .

The second solution is defenitely more work but is more clean in terms of not injecting extra code.

**Comment by dupdob** [comment]
the ```return default``` problem  may be resolved by using ```return default(T)``` where T is the return type for the method, thus getting rid of the constraint on C# version.

clearly
```csharp
int demo()
{
 ...
  while(true)
  {
    return 0;
  }
}
```

could be mutated to 
```csharp
int demo()
{
 ...
  return default(int);
}
```

**Comment by richardwerkman** [comment]
I've been thinking about this. And adding return default might cause un-killable mutants... For example:
``` cs
    public static bool Loop()
    {
        while (true)
        {
            return false;
        }
    }
```
Returns exactly the same as the mutated:
``` cs
    public static bool Loop()
    {
        while (false)
        {
            return false;
        }
        return default;
    }
```
So how could a unit test detect the change?

I think we should find another aproach instead of return default 👎

**Comment by dupdob** [comment]
I am not sure as I feel you abstracted to much in your example.
An actual _while(true)_ loop would have some side effect, the absence of which would/could be detected by some test. I.e.
```csharp
public static bool Loop()
{
  while(false)
  {
    ... do something <= this is what is tested
   return false;
  }
}
```
Alternatively, if the code does not have any (detectable) side effect, the original method still can refactored. I.e.
```csharp
public static bool Loop()
{
  while(true)
  {
  ...
    return true;
  }
}
```

Is strictly equivalent to :
```csharp
public static bool Loop()
{
  while(true)
  {
  ...
    break;
  }
  return true;
}
```
which is properly mutated.

**Comment by dupdob** [comment]
As a conclusion, I think the original proposal is still valid.

**Comment by richardwerkman** [comment]
We could try the return default solution, since we don't seem to have a better option at the moment.
