### ISSUE TITLE
Use coverage data to reduce number of test sessions

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#647]
**Is your feature request related to a problem? Please describe.**
Current version of Stryker tests a single mutant per test session to prevent any side effect due to having multiple mutants active.
But when mutants are decoupled and are covered by distinct tests, they can be simultaneously enabled and tested in a single test session, resulting in a shorter run time

**Describe the solution you'd like**
Analyse coverage data to identify mutants tested by distinct tests, modify the code to enable multiple mutants at once.

**Additional context**
Analysis of NFluent mutant coverage shows that number of test sessions can be divided sevenfold (1754 -> 249).
I am currently working on an implementation

**Comment by Mobrockers** [comment]
Cool!

**Comment by dupdob** [comment]
It remains to be seen if it brings a significant speed up. And there is a significant design shift and code effort to support simultaneous mutations:
- changing mutationtestprocess logic
- changing testrunners signature (even if it is only supported by VsTest
- changing mutant control logic (easy)
- changing test run result capture (need to map test result to the proper mutant)
....

**Comment by richardwerkman** [comment]
This would be awesome! And it sounds like a cool challenge. If you need help let us know.

**Comment by dupdob** [comment]
The thing that would help me the most right now is having PR #636 merged, as I my current work is based on this, for obvious reasons, and I spend time syncing my branch with master.
And anyone working on mutators and mutation logic will benefit from the refactoring done in this PR.

**Comment by dupdob** [comment]
Quick update: I ma still working on this. As described earlier, it implies a lot of significant re design effort. Everything is going well, but I have switched project as I am dealing with an issue in NFluent.

**Comment by dupdob** [comment]
I am back to Stryker. I implemented most of the needed changes. I have made a run against NFluent and run time is now around 25 minutes (roughly half what is needed when testing mutants in isolation.
I still have to implement abort on error, it is likely tile will be further reduce.
On the bad side, I get some undue survivors, indicating there is an issue in the coverage analysis step or test result analysis. Just a matter of fixing the bug.
Hope I will have a (draft) PR soon. Design changes will be significant in the test running part.

**Comment by richardwerkman** [comment]
Wow, 25 minutes is a bigger improvement than I expected! Looking forward to your PR 👍

**Comment by dupdob** [comment]
Let us wait for a fully working version before any celebration: after a second look at the run results, it looks like 10% of the mutants were not tested at all...

**Comment by dupdob** [comment]
Previous issue is fixed: it was related to timeouts that were not identified as such. I now have what appears to be consistent results between current Stryker version and my versions.
runtime is 34 minutes, still a significant improvement from the baseline. As stated before, there is room for improvement.
Quick explanation: when a test run timeouts while testing for multiple mutants simultaneously, I have to rerun the mutants in dedicated test runs to identify true timeout(s).

Next task: analyse test results in real time to re-enable abort on fail (when all mutants are identified as killed) and improve timeout handling

**Comment by dupdob** [comment]
November update: still working on it. 
Remarks: last release significantly increased the number of mutants (~1800 => ~2200) due to the negate condition mutator, it generates many duplicate mutants. As a result, total runtime has increased linearly.
Progress
- refactoring in progress
- supplemental work has been identified (see below)
Mutants may interact with each other despite using coverage to select them. This is because mutant alter the control flow of the tests (with regarded to the original version).
This result in false results (both false positive and negative).
This can be fixed by ensuring only one mutant is active for a given test. It can be done through the vstest extension. But this require extra work to transfer the needed data from Stryker down to the extension.

I focus on refactoring first and will implement this afterward.

**Comment by dupdob** [comment]
I am back to working on this. I have been busy with NFluent fixing a couple of issues and preparing a new release.
I am working on the updating the mechanism to control the active mutant. I have a working solution, I am busy designing tests for it.

**Comment by Mobrockers** [comment]
That's awesome :) 

We have an internship student in the coming months that is going to look into more ways to make stryker faster so it might be fun to have a chat with him if you have some more ideas he could investigate and work out.

**Comment by dupdob** [comment]
Good idea. I think the next strategy will require to write a custom test execution engine for VsTest, allowing hyper precise control of which test to run for which mutant.
By the way, my updated design get rid of the environment variables (between Stryker and VsTest) as all informations are transmitted through the VsTest config file.

Environment variables are still being used internally between VsTest and the test session for selecting the active mutant. It should be possible to remove them as well in the future.
