### ISSUE TITLE
Bitwise and shift mutators

### ISSUE THREAD

**Issue by jnyrup** [stryker-mutator/stryker-net#664]
[Bitwise and shift operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators) that can be mutated.

| Original | Mutated |
| -------- | ------- |
|   `<<`   |   `>>`  |
|   `>>`   |   `<<`  |
|   `&`   |   `\|`  |
|   `\|`   |   `&`  |

The mutant of `a^b` depends on whether `a` and `b` are integral types or booleans.

| Type | Original | Mutated |
| ---- | -------- | ------- |
| boolean |   `a^b`   |   `a==b`  |
| integral |   `a^b`   |   `~(a^b)`  |

**Comment by richardwerkman** [comment]
I like the idea of this mutator! We already place this mutation in assignment form. We seem to have forgotten the 'normal' bitwise operators.

> The mutant of a^b depends on whether a and b are integral types or booleans.
> 
> Type | Original | Mutated
> -- | -- | --
> boolean | a^b | a==b
> integral | a^b | ~(a^b)

We currently cannot know what type a variable has during mutation. So a different mutation dependent on the type could be tricky. We could place both mutations. The mutation that does not compile will be removed.

**Comment by Valdas3** [comment]
I have all operators more or less ready for a pull request using the above suggestion for XOR operator. But I am wondering if it is ok that when XOR operator gets mutated an info message like this is shown every time:

```1 mutants got status CompileError. Reason: Could not compile```

It does not seem ideal if it is known beforehand that one of the mutations will not compile.

**Comment by Mobrockers** [comment]
@valdas it is cleaner of course to never place the mutation in the first place, if you can figure out a cost effective way to recognize that. We remove all found compile errors in one recompile so the remove operation is sub milliseconds of work though. In this case I doubt finding a more clean solution is worth it.
