### ISSUE TITLE
Speed up pipeline with pipeline cache beta

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#667]
**Is your feature request related to a problem? Please describe.**
Our builds are fairly slow, using nuget caching will speed them up a bit

**Describe the solution you'd like**
https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#netnuget

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#enabling-lock-file

**Comment by lpraz** [comment]
Azure DevOps pipeline caching is in preview at the moment. Should this issue be held off until it comes out of preview, or is it still acceptable to implement now?

**Comment by Mobrockers** [comment]
I don't have any problem with trying this out while in preview.
