### ISSUE TITLE
Git diff check to skip mutations

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#692]
**Is your feature request related to a problem? Please describe.**
PR builds with Stryker.NET enabled take too long.

**Describe the solution you'd like**
Stryker should fetch the git diff between the PR branch and master and only mutate the files (and linespans) that were changed.

This could look like:
`dotnet stryker --diff`

Or if you would like the diff against another branch:
`dotnet stryker --diff develop`

Stryker should mark all mutations that are not inside the diff span as skipped. This will speed up stryker in PR builds as only the changed code will be mutated and tested.

We should see if this works fine together with the `mutate` option. What if I exclude a file in `mutate` and git diff sees a change in that file?

**Additional context**
This features depends on #322.

Edit: `dotnet stryker --gitdiff` --> `dotnet stryker --diff`

**Comment by anhaehne** [comment]
I think the most straight forward way to implement that right now would be to add a new MutantFilter that removes all mutants not affected by the by the git diff. That would also work nicely together with the mutate parameter, as it would allow the user to further filter which mutants will be evaluated.

**Comment by richardwerkman** [comment]
We could try [libgit2sharp](https://github.com/libgit2/libgit2sharp/wiki/git-diff) to get the git diff between two branches.

**Comment by richardwerkman** [comment]
I'm working on a solution for this. And I use the MutantFilters to filter out the unchanged files.
