### ISSUE TITLE
Ignore Methods option not working

### ISSUE THREAD

**Issue by sdcooper** [stryker-mutator/stryker-net#695]
**Describe the bug**
using both -im and --ignore-methods either from the command line or the config file does not work. The command line returns "Specify --help for a list of available options and commands."
Sure enough, ignore-methods is not listed in the help, but it is in the documentation?

**Logs**
None, it doesn't get that far!

**Expected behavior**
I want my logging methods to be ignore using the config:
"ignore-methods": [
            "Trace",
            "Debug",
            "Error",
            "Warn",
            "Fatal"
        ]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Type of project [core]
 - Framework Version [core 2.1]
 - Stryker Version [e.g. beta 0.12.0]

**Additional context**

**Comment by Mobrockers** [comment]
Sorry about that! We should from which version each option is available. The ignored methods feature has not yet been released to NuGet.org

**Comment by sdcooper** [comment]
Ah ok, that makes sense. Any idea when it is likely to be released?

**Comment by Mobrockers** [comment]
We were planning to release last friday but we are investigating a possible regression we discovered just before releasing. We should be releasing this week.

**Comment by Redocram** [comment]
Can't wait  to have this feature.
Which is the best channel to follow this project?

**Comment by Mobrockers** [comment]
What would you like to follow about this project? We sometimes post on [twitter](https://twitter.com/stryker_mutator), you can ask us questions on [gitter](https://gitter.im/stryker-mutator/stryker-net) and we sometimes post blog posts on our [website](https://stryker-mutator.io/blog), but currently we mostly just work on stryker on github :)

**Comment by Redocram** [comment]
Thanks for the reply.
Mainly I'd like to follow new releases and maybe some basic and advanced tutorial in order to get the best from this project

**Comment by Mobrockers** [comment]
Stryker will prompt you when new releases are available if you have an internet connection (from version 0.12.0)

**Comment by Mobrockers** [comment]
0.13.0 has just been released. It should be available within a couple hours depending on when your closest nuget.org edge servers receive the update.
