### ISSUE TITLE
Use the CSPROJ to build the mutated code

### ISSUE THREAD

**Issue by aarongomez1** [stryker-mutator/stryker-net#712]
**Is your feature request related to a problem? Please describe.**

I have a multi-targeted C# project that builds both .NetStandard and .NetFramework462 output.  To get this to work with my scenarios I was not able to opt-in to the MSTest v2 feature of having it automatically compile all files in the project folder.   I have it set to manually control the compiled files.  This project auto-generates CS files from its pre-build event using an XSLT and it optionally includes the CS files into compilation based on teh current build setting.  Its a bit complicated.

The issue I'm having is that after the mutator runs against my CS files, it doesn't seem to compile using my CSPROJ settings.  Its like it is just compiling thinking it can auto-compile with everything in the project folder which doesn't work for me.

**Describe the solution you'd like**
I'd like it if post-mutation it compiled using the CSPROJ settings, as it seems to ignore my setting and it tries to automatically include all CS files in the folder.  This causes redundant classes to show up and the compile fails.
[log-20190909.txt](https://github.com/stryker-mutator/stryker-net/files/3592986/log-20190909.txt)
[vstest-log.host.19-09-09_16-13-49_92662_6.txt](https://github.com/stryker-mutator/stryker-net/files/3592987/vstest-log.host.19-09-09_16-13-49_92662_6.txt)
[vstest-log.host.19-09-09_16-13-55_18559_6.txt](https://github.com/stryker-mutator/stryker-net/files/3592988/vstest-log.host.19-09-09_16-13-55_18559_6.txt)
[vstest-log.txt](https://github.com/stryker-mutator/stryker-net/files/3592989/vstest-log.txt)

**Comment by Mobrockers** [comment]
You're right, currently we find all cs files on disk and include them in the compilation. We would like to change this but have not managed to get msbuild to give us all relevant project files yet in a reasonable way.

**Comment by Mobrockers** [comment]
Fixed by #898
