### ISSUE TITLE
Stryker should not mutate classes with generated code

### ISSUE THREAD

**Issue by SierraNL** [stryker-mutator/stryker-net#752]
Stryker also mutates classes with generated code attributes

I would like Stryker to ignore these classes for mutations.
If this causes problems for other users, you could make this configurable using a CLI flag.

There are also classes like EF Migrations that I would like to see ignored, but since they don't have clear attributes, I'm not sure on how to fix that.

**Comment by Mobrockers** [comment]
Hey! Good suggestion! Are there any traits we can use to detect generated code? Keep in mind we can only check syntax elements or plain text comparison. We don't have easy context of namespaces etc.

**Comment by jnyrup** [comment]
Auto-generated is often annotated with [`[GeneratedCode]`](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute?view=netframework-4.8)

StyleCop.Analyzers seems to look for the comment `<auto-generated` or `<autogenerated` https://github.com/pdelvo/StyleCopAnalyzers/blob/1501workaround/StyleCop.Analyzers/StyleCop.Analyzers/GeneratedCodeAnalysisExtensions.cs
Apparently `[GeneratedCode]` had a negative impact for them: https://github.com/dotnet/roslyn/issues/20498

**Comment by richardwerkman** [comment]
@SierraNL To ignore your EF Migrations classes you could just exclude the whole migrations directory using our `mutate` option. This would look something like:

```
"file-patterns": [
   "!Migrations/**"
]
```

Or using the command line:
`dotnet stryker --mutate "['!Migrations/**']"`

**Comment by SierraNL** [comment]
> @SierraNL To ignore your EF Migrations classes you could just exclude the whole migrations directory using our `mutate` option. This would look something like:
> 
> ```
> "file-patterns": [
>    "!Migrations/**"
> ]
> ```
> 
> Or using the command line:
> `dotnet stryker --mutate "['!Migrations/**']"`

Thanks, this helps!
