### ISSUE TITLE
Mutated assembly is missing embedded resources

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#756]
**Describe the bug**
Mono.Cecil often fails to load the original assembly which means embedded resources rae missing from mutated assembly.

**Expected behavior**
Mono.Cecil loads the unmutated assembly in order to extract the embedded resources contained.

**Additional context**
Seems to sometimes be caused by file locks on the unmutated assemblies.

**Comment by Mobrockers** [comment]
I seem to be unable to reproduce this issue on my project. I know people are experiencing the problem though.
