### ISSUE TITLE
Add mutation for conditional (ternary) operator

### ISSUE THREAD

**Issue by Valdas3** [stryker-mutator/stryker-net#757]
I propose adding a mutation for conditional operator:

| Original | Mutated |
| ------------- | ------------- | 
| `a ? b : c` | `a ? c : b` |

Also, I am including a PR with implementation.

**Comment by richardwerkman** [comment]
What does this kind of mutation differ from mutating the condition? I think we have most conditions covered. In those cases this would result in identical mutations.

These identical mutations only add up to the runtime of stryker but do not add much value. 

Do you have some cases where this mutation is better than what conditions we currently mutate?

**Comment by Valdas3** [comment]
Often the condition is just a parameter or a member of some object which contains no boolean operators to mutate. For example:

```
public class CreditCard {
	private decimal Amount { get; set; }
	private bool IsExpired { get; set; }
	
	public decimal GetAmount() {
		return IsExpired ? 0 : Amount;	
	}
}
```

Correct me if I am wrong but as far as understand no current mutator can mutate these kind of expressions. It would be nice to avoid generating equivalent mutations but I am not sure how to achieve that right now.

**Comment by Mobrockers** [comment]
Your example should be mutated to return ! IsExpired  ? 0 : Amount;

Which results in more or less the same mutation.

**Comment by Valdas3** [comment]
@Mobrockers  Just to clarify, you mean that this already should work and my example code should be mutated to `!IsExpired ? 0 : Amount` or that you saying that this would be a preferred approach?

**Comment by Mobrockers** [comment]
It already should work, we have a negation mutator that should do this

**Comment by Valdas3** [comment]
It only works for expressions inside if and while statements if I understand correctly
https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Mutators/NegateConditionMutator.cs#L22-L27

**Comment by Mobrockers** [comment]
Mhm it seems you're right

**Comment by dupdob** [comment]
It should be a matter of adjusting this selection criteria to cover for ternary operators.

**Comment by Mobrockers** [comment]
> It should be a matter of adjusting this selection criteria to cover for ternary operators.

@Valdas3 I would prefer this solution because we don't need a separate class of mutators to achieve the same result, we can reuse the existing one.

**Comment by Mobrockers** [comment]
@Valdas3 Do you agree with implementing this feature by extending the negate condition mutator?
