### ISSUE TITLE
Question: What does Stryker need to run the mutations?

### ISSUE THREAD

**Issue by rajbos** [stryker-mutator/stryker-net#762]
I've been working on parallelizing running Stryker for multiple folders with mulitple projects for a larger .NET solution (115 projects and counting) in Azure DevOps. Stryker wants a recently build project otherwise it will fail with a message. You can read more about my setup [here](https://rajbos.github.io/blog/2019/10/11/Parallelizing-a-long-Stryker-Run-in-Azure-DevOps)

This adds some extra time to our setup, since we parallelize over multiple build agents that each have their own folder. 

### Question What does Stryker need to run the mutation on?
Is there a way that I can prep the solution **once** and then pass that (zipped?) folder around the different build agents? Our solution takes more than 5 minutes to build, so that would take us less time to run. 

I'm not sure what Stryker needs to run the mutation?

**Comment by richardwerkman** [comment]
Why we run a build every stryker run:

We need to have a baseline for detecting if a mutation causes a failing test. To do this we need to make sure that all tests are passing. We also need to know these tests have passed on the latests version of the code. So we run a build to make sure the project builds and run the tests on the newly build project.

I understand that in your situation you are already 100% sure your project is buildable and all tests are passing. We could add an option to stryker to skip the initial build and test. This would save you some time already and could be a easy fix.

> Is there a way that I can prep the solution once and then pass that (zipped?) folder around the different build agents?

This would prove a bit harder. We have chosen (for performance reasons) to keep a lot in memory during a run. We could try to add an option to run styrker on a already mutated assembly where you pass the full path to that mutated assembly. After you run stryker the first time the mutated assembly can be found in de obj folder. It already contains all mutations. However, stryker will have no context about those mutations. How many mutations are inside the mutated assembly? The only way I can think of would be:
- Re-analyse the project and re-create the mutants.
- Use Mono.Cecil to analyse the mutated assembly and get the mutations from there. 

This would both prove pretty hard and complex. 

For now I would say what you want is not possible (with the current stryker implementation). If you want to contribute by adding the option to skip the initial build we can give you some pointers on where to start!

Btw, cool blogs about how you are using Stryker on such a large project! It might be the biggest project Stryker.NET has ever run on 😎

**Comment by rajbos** [comment]
Thanks @richardwerkman for the clear explanation. Good to know, will leave it as is.
