### ISSUE TITLE
Add the mutation score to the json report

### ISSUE THREAD

**Issue by rajbos** [stryker-mutator/stryker-net#763]
**Is your feature request related to a problem? Please describe.**
I want to fail a build after running a mutation test on a large project where I only have the json results that I join myself (read more about my journey [here](https://rajbos.github.io/blog/2019/10/11/Parallelizing-a-long-Stryker-Run-in-Azure-DevOps). Currently the json files do not contain the mutation scores, so we cannot calculate the overall score at the end of a run.

**Describe the solution you'd like**
Add the mutation scores to the json file.

**Describe alternatives you've considered**
I could keep track of each score by parsing the output of the console reporter, but that seems less ideal and extra actions to create.

**Comment by richardwerkman** [comment]
You could look into: https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-metrics

It is an open source calculation tool that uses the json scheme that we too handle. You feed it the json and it returns a score. You could probably use Node to run it on the server and return a bad status code when the score is too low.

**Comment by nicojs** [comment]
C# implementation of mutation-testing-metrics is welcome in the mutation-testing-elements mono repo as well. 👍

**Comment by rajbos** [comment]
A .NET implementation would make running it easier in this context @nicojs 
I'll open up an issue there to discuss on where to start :-)
