### ISSUE TITLE
Merge interfaces and implementation

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-net#8]
Right now it seems like every interface in in a separate file. I personally find it easier to find an interface and the implementation if the interface is in the same file as the implementation (as long as there is one implementation).

**Comment by simondel** [comment]
Do you have interfaces for testing purposes or because the interfaces are (or will be) used in other projects/applications? If they are just used for testing purposes I would place them in the file where the implementation is.

**Comment by richardwerkman** [comment]
Mostly for testing perposes. Some will be used in other projects. But this architectural decision has not been made yet. For now it is best to place the interfaces in the implementations file.

**Comment by SeeSharpy** [comment]
Sorted (i think) in #126
