### ISSUE TITLE
System.Linq.Expressions.Expression mutations result in untestable mutations

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#814]
## Issue: Significant discrepancy in mutation testing result when disabling coverage analysis on [Unmockable](https://github.com/riezebosch/Unmockable)
All mutants (37 at time of testing) are killed when turning coverage analysis off whereas 6 are uncovered and 3 survived with coverage analysis on.

## Cause: Unexpected impact of mutant control logic
**[Unmockable](https://github.com/riezebosch/Unmockable)** extensively uses the [System.Linq.Expressions.Expression](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression?view=netframework-4.8) class in method signature. **StrykerMutator.Net** relies on an in-place mutation for expressions, using ternary operators to enable them when needed.
Therefore some mutated expressions are **not evaluated** at runtime, but simply passed as an expression tree to **Unmockable** code. 
As a result, mutant in **non evaluated expressions**:
- are invisible during coverage analysis  ⇒  flagged as not covered
- can't be selectively activated  ⇒  can't be tested 
- result mutated code that is active during every test sessions  ⇒ Stryker.Mutator results are wrong with or without coverage analysis.

To confirm that last statement, one simply has to manually introduce a mutant and run the code. For example, this mutant breaks no test and should be marked as survived 
```csharp
namespace Unmockable.Matchers
{
  internal static class ArgMatcherFactory
  {
    public static IArgumentMatcher? Create(Expression arg) => arg switch
      {
          MethodCallExpression call when call.Method.DeclaringType == typeof(Arg) => call.Method.Name switch
          {
              nameof(Arg.Ignore) => (IArgumentMatcher)new IgnoreArgument(),
              // here we have replaced Arguments.Single() with Arguments.SingleOrDefault()
              nameof(Arg.Where) => new LambdaArgument(call.Arguments.SingleOrDefault()),
              _ => throw new InvalidOperationException()
          },
          _ => null
      };
   }
}
```
But it is marked as *'not covered'* with coverage analysis and as *'killed'* when coverage analysis is off. Please note that having it marked as *'killed'* means it is very likely that other mutants are flagged as *'killed'* while they are actual survivors, invalidating the test session's results.

## Workaround
The only workaround is to use the ignore methods option (see #646) to disable mutation for each call to method expecting System.Linq.Expressions.Expression as parameter(s).

## Fix
At this time, there is no clear and fast approach to fix this issue. Leads are:
1. Identify offending method(s) and automatically disable related mutation. Can't be done as of now, as Stryker.Net does not implement the required call resolution logic to reliably identify those calls
2. Offer an option to only use if statements to control mutation logic. Difficult to do as it requires reliable identification of enclosing statements, it would result in bloated mutated assemblies due to the extra duplication and it is not universal (usage of expression body instead of statement)
3. A mixing **1** and **2** would limit the bloating (only use ifs when necessary) and handle the expression body problem by disabling mutation for those
4. Adjust mutant control logic to make it transparent for  System.Linq.Expressions.Expression. I have no idea how to achieve that, if it is possible.

_Originally posted by @dupdob in https://github.com/stryker-mutator/stryker-net/issues/781#issuecomment-549447726_

@dupdob please add any additional information if required

**Comment by dupdob** [comment]
From my point of view, this is not an important issue: I see point in using _LinqExpressions_ within a library, as the coders fully controls the expressions they use and can therefore find alternative design strategies.
_LinqExpressions_ type relies on a compiler hack which cannot be detected without adding symbol/type resolution to Stryker.
If the project goes down that road, then the fix will be easy. But, by itself, this issue is no compelling reason to engage in the immense work it requires.

Unless some OSS library provides this for us.

**Comment by Mobrockers** [comment]
I agree
