### ISSUE TITLE
Coverage analysis statistics (x out of y mutants will be skipped due to not being covered) are no longer reported

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#824]
**Describe the bug**
As seen in issue #821, Stryker outputs invalid optimisation statistics when the number of tests cannot be established.
This is a minor issue as the behaviour is not impacted.
**Logs**
> [15:26:34 INF] Coverage analysis eliminated 100.00% of tests (i.e. -132 tests out of -132).

**Expected behavior**
Either provide accurate statistics or remove the message altogether.

**Comment by dupdob** [comment]
Working on it, will be integrated with #633.

**Comment by Mobrockers** [comment]
I had a quick look at this before and to me it seems like we don't need the total number of tests to determine the total number of tests we eliminated. So perhaps we should just note the total removed if we could not determine the total amount of tests.

**Comment by dupdob** [comment]
In fact, with DotNetTest, the only think we can do is skip uncovered mutants, as we do not get access to the list of test and even less control which tests are run!
I took a look at my WIP and this statistics have been completely removed due to significant redesign of the coverage analysis logic (i.e. for dotnettest as well as VsTest).

Do you think I should restore it?

**Comment by Mobrockers** [comment]
@dupdob Yes I think it would be nice to restore the statistics

**Comment by dupdob** [comment]
working on it now, will push a PR soon
