### ISSUE TITLE
Stryker.Net does not properly capture coverage for some xUnit's theories

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#843]
**Describe the bug**
Stryker.Net VsTest plug-in (DataCollector) reports only coverage info for the first case of some/all xUnit theories, leading to false positive: mutants flagged as non covered or survivors.

**Workaround**
One can disable coverage analysis to get reliable results if the issue appears, using the following command line option:
```
-ca off
```

**Expected behavior**
Stryker should be able to properly capture coverage of any test.

**Additional context**
problem identified through issue #842

**Comment by dupdob** [comment]
Preliminary analysis hints that Stryker.DataCollector receives test event only one for the all theory. Not sure if it encompasses the whole theory or only the first test case.

**Comment by richardwerkman** [comment]
Do you think this can only occur in xUnit or in other test frameworks as well?

**Comment by dupdob** [comment]
I definitely need further analysis to reach a conclusion. As of now, I think this is very specific as:
- I am pretty sure NFluent uses some TestCase (NUnit feature similar to XUnit's Theory) and I do not have any coverage issue with NFluent
- many projects use XUnit Theory and it is the first time this issue is reported.

What raised suspicions regarding coverage with issue #842 is the fact that the test project provides TheoryData factories, which is pretty specific.

**Comment by dupdob** [comment]
Analysis update: turning on 'perTestInIsolation' coverage analysis mode, revealed that Stryker launch two test sessions, but 3 and 9 results instead of the expected one!.

**Comment by dupdob** [comment]
Btw, it looks a lot like it is related to this:
https://github.com/xunit/xunit/issues/1669

**Comment by dupdob** [comment]
Log analysis confirm first impression:
the xUnit visual studio runner treat (some?) theories as a single test (from vstest perspective).
It returns results for all test cases, but notifications to datacollector only happens on the first testcase.
This  kinda sucks, but should not come as no surprise when you see the comments on the xUnit issue I pointed to earlier.
I will look into workarounds/options to control that.

**Comment by dupdob** [comment]
# Analysis
I reviewed VsTest and xUnit code. I am afraid I was not able to fully reverse engineer xUnit behaviour (due to design complexity), but here is my understanding of the situation:
1. When xUnit (testrunner) **discovers** the tests, there is a special logic for **Theories**:
    1. If all Theory data can be discovered at analysis time, xUnit report one test per set of data
    1. if Theory data needs to be discovered at run time (e.g. MemberData), xUnit report only a single test for the theory
    1. it seems there is only one test also when mixing inline and runtime data
1. this is xUnit normal test execution workflow
    1. xUnit gather needed information
    1. Raises TestCase Starts (forwarded to datacollectors)
    1. xUnit executes the test and capture result
    1. Raises TestCase Ends (forwarded to datacollectors)
    1. Raises TestCase results (**not** forwarded to datacollectors)
1. But for theories with runtime data, this is the sequence of events
    1. xUnit gather needed information
    1. Raises TestCase Starts (forwarded to datacollectors)
    1. xUnit executes the test with the first set of data and capture result
    1. Raises TestCase Ends (forwarded to datacollectors)
    1. Raises TestCase results (**not** forwarded to datacollectors)
    1. xUnit executes the test with the second set of data and capture result
    1. Raises TestCase results (**not** forwarded to datacollectors)
    1. ... last steps are repeated until the last set of test datta

### Note:
- VsTest accepts more that one test result per test case
- these behaviour is also visible in the VisualStudio tests explorer window.
- it is possible that xUnit raises TestCase Ends events for each test runs, but only the first one is forwarded to collectors (for a given test case)

# Impact
1. we have is that tests are run without the datacollector being notified. So we cannot gather coverage data.
1. gap in coverage data leads to erroneously flagging some mutants as non covered
1. coverage data for non reported tests leaks into the next reported test

# Possible fix
1. Best: fix xUnit behaviour so that a test case is generated for **each** set of data, even for runtime data (**Unlikely** as it probably requires significant effort in xUnit)
1. Alternate: fix xUnit behaviour so that Testcase End is raised only when alll data set has been tested (sounds plausible but I have not been able to understand xUnit reporting logic)
1.  Other alternate: fix xUnit behaviour so that Testcase End is raised for each data set (**unlikely** as it requires a fix in xUnit and a large change in VsTest)
1. Workaround: capture coverage data in gap using the Testcase Start and TestSession end. Requires hacking existing data capture logic (**possible**)
1. Workaround: identify this situation and implement a defensive logic and assume those tests cover all mutants (**easy** but will slow things down)

**Comment by Mobrockers** [comment]
Nice analysis! Seems like the only good fixes require assistance from xunit and /or vstest which makes fixing this very difficult. We should probably start with workaround 5 and go from there.

**Comment by dupdob** [comment]
Yes, I will try to have a PR providing some mitigation logic.
