### ISSUE TITLE
Fail gracefully on incorrect targetframework in csproj

### ISSUE THREAD

**Issue by gregoks** [stryker-mutator/stryker-net#861]
**Describe the bug**
Im running stryker for netcore solution and the project under test target framework is:

<TargetFrameworks>netstandard2</TargetFrameworks>

dotnet stryker --solution-path C:\GIT\DefaultCollection\MyCompany\myService\MySln.sln --project-file Service.csproj --test-project-file UnitTests.csproj --reporters "['html', 'progress']" --excluded-mutations "['string', 'logical']" --coverage-analysis perTest --threshold-high 90 --threshold-low 75 --threshold-break 0 --log-level "debug"

**Logs**
```
[15:52:59 ERR] An error occurred during the mutation test run
System.ArgumentException: Version string portion was too short or too long.
Parameter name: input
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Stryker.Core.Initialisation.ProjectAnalyzerResult.get_TargetFrameworkAndVersion() in d:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\ProjectInfo.cs:line 260
   at Stryker.Core.Initialisation.ProjectAnalyzerResult.get_TargetFramework() in d:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\ProjectInfo.cs:line 106
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(StrykerOptions options) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\InitialisationProcess.cs:line 43
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in d:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 73
[15:52:59 INF] Time Elapsed 00:00:21.1318803
```

**Expected behavior**
To work?:)

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: core
 - Framework Version: 2.2
 - Stryker Version: 0.15.0

**Additional context**
I have debugged your solution and it seems like the issue is here:

![image](https://user-images.githubusercontent.com/15245808/71656640-afe0e900-2d44-11ea-8a74-1322e8491f3f.png)

It takes the "netstandard2" and pulls the "2" from it, then it tries to put it in the "new Version(version)" code.

Please advice.

Thanks,

Greg

**Comment by gregoks** [comment]
well I actually found the answer :) if I change my targetframework to netstandard2.0 then it works.
I changed it in my proj but actually you could add to your code if you see single number then just add ".0" suffix?

**Comment by dupdob** [comment]
Thanks for reporting this. 
But I am not sure what the fix should do: I failed to find any official/MS documentation regarding valid values for 'TargetFramework' in project files, therefore I am not sure how 'NetStandard2' is supposed to be resolved.
According to your issue, it seems like you expect the target framework to be NetStandard 2.2 and not NetStandard 2.0 that you specified as a workaround.
What I need to know is that NetStandard2 is supposed to resolve to NetStandard2.0 which is easy to do or the latest installed version of NetStandard2, (2.2 in your situation) which will be harder to implement.

**Comment by gregoks** [comment]
From what I saw, in my services netstandard2 is netstandard2.0 because when we want 2.2 we specifically write netstandard2.2, so Im changing it in my csproj but since both formats seems to work, I think you should just add “.0” if there is only one number in version.

**Comment by dupdob** [comment]
Thanks for the feedback.

**Comment by Mobrockers** [comment]
Imo I don't think netstandard2 is a valid targetframework and I've personally never seen it used, msbuild just seems to handle it gracefully. I would prefer if we handle it gracefully by crashing with an error indicating the targetframework is invalid instead of appending a 0.

**Comment by gregoks** [comment]
> Imo I don't think netstandard2 is a valid targetframework and I've personally never seen it used, msbuild just seems to handle it gracefully. I would prefer if we handle it gracefully by crashing with an error indicating the targetframework is invalid instead of appending a 0.

Thats also fine imho, just a clear error that will state what we should change in our scproj to make it work.
