### ISSUE TITLE
Feature request: Mutation strategy option

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#869]
**Is your feature request related to a problem? Please describe.**
People that are new to mutation testing can be overwhelmed by the number of mutations and type of mutations that are being placed. And more experienced testers might need more detailed mutations to further improve their testing.

**Describe the solution you'd like**
I'd like to introduce a mutation strategy option that has three possible values: Light, Medium and Heavy. 

- Light excludes some mutation types to keep the report simple and the mutating fast. 
- Medium uses current mutations, which are concidered good.
- Heavy uses extra mutations like regex mutations and removes code as well. This will drasticly increase runtime. But it gives even more insight than Medium.

**Additional context**
The default would be medium. 

We have to discuss what mutations will come with each strategy. @nicojs, @Mobrockers what are your thoughts on this?

**Comment by dupdob** [comment]
May I suggest you look into 'Extreme mutation testing'?
This is a mutation strategy where you simply replace full methods by empt blocks returning default value. I have a hard time reaching documentation on this, but there is a reference in [this post](https://pedrorijo.com/blog/intro-mutation/)!

In this case, extreme would be equivalent to _Light_ mode, but it has the benefit of being a referenced term.

While on the naming strategy, may I suggest **Deep** instead of **Heavy**. 
It is more evocative for me, and **Heavy** has a negative connotation.

**Comment by richardwerkman** [comment]
@dupdob Thanks for your suggestion! Extreme mutation testing looks promising indeed. It would be a quick way of checking global test quality. The name evoces to me that it is more thorough than normal. As it seems to me that when you do something extreme you do it very well, and not quick and dirty.

I chose the name Heavy as it makes clear it is a slow process. Just as i chose Light as it shows it is quick. However, I see why you want to name it Deep as it has a nice sound to it. 

We can also add Extreme as an extra option like:
- Extreme
- Light
- Medium
- Heavy/Deep

**Comment by richardwerkman** [comment]
I've started working on an implementation of this. Which got me thinking about the naming of the levels again. We could also go for:

`Beginner > Intermediate > Advanced > Expert`

With beginner being only block statements and expert every mutator.

**Comment by Mobrockers** [comment]
It seems weird to me to have levels depending on 'skill' of the user. 

I much prefer levels that indicate how thorough the test will be. 

For example:

Mode light/basic, 
Mode standard,
Mode advanced/thorough,
Mode full/complete/extreme/epic/ballers

I do not agree on mode Extreme being the same as light, to me that gives the wrong impression. Extreme being the least thorough mutation testing strategy is non obvious imo even if you've heard of the term before (and most will not have heard of it).
