### ISSUE TITLE
When using --diff, the mutation-report.html shows 100% mutation score on files that were not mutated

### ISSUE THREAD

**Issue by detrek77** [stryker-mutator/stryker-net#885]
**Describe the bug**
When running the command:
```dotnet-stryker --diff -gs "branch" -r "['html']"``` 

The mutation-report.html shows 100% mutation score on files that were not mutated.
![Stryker100diff](https://user-images.githubusercontent.com/35112219/72554628-1861b700-3869-11ea-8030-fd2ca4ebaa86.PNG)

**Expected behavior**
I would expect the report to show any files that were not tested as something like skipped, N/A, or 0.

**Desktop:**
 - OS: Windows
 - Type of project: .NET Core
 - Framework Version: Core 2.2
 - Stryker Version 0.15.0 beta

**Comment by Mobrockers** [comment]
We have a pull request open for this here: https://github.com/stryker-mutator/mutation-testing-elements/pull/52

I'll ping the people responsible to see if it can get merged and released. Thanks for the reminder!

**Comment by detrek77** [comment]
That's awesome news, thanks for the update!

**Comment by richardwerkman** [comment]
Update: Today I've updated the PR again so it can be merged soon 👍
