### ISSUE TITLE
Switch statement on string value causes mutated case labels

### ISSUE THREAD

**Issue by erwin-faceit** [stryker-mutator/stryker-net#892]
**Describe the bug**
In our project we have a few converters which convert from string to enumeration and back. For instance a GenderConverter as follows:

`
public Gender Convert(string sourceMember, ResolutionContext context)
{
  return sourceMember switch
  {
    "M" => Gender.Male,
    "F" => Gender.Female,
    _ => Gender.Unknown
  };
}
`

The case labels in this converter are also mutated, but that results in a compile error, because case labels should be constants.

**Logs**
The log shows the mutated method, and a compile error:

`
public Gender Convert(string sourceMember, ResolutionContext context)
{
  return sourceMember switch
  {
(StrykertJbFjO3MBeWZ3TJ.MutantControl.IsActive(50)?\"\":                \"M\" )=> Gender.Male,
(StrykertJbFjO3MBeWZ3TJ.MutantControl.IsActive(51)?\"\":                \"F\" )=> Gender.Female,
     _ => Gender.Unkown
   };
}
`

The compile error is:

`Stryker.NET encountered an compile error in "GenderConverter.cs" (at 21:0) with message: "A constant value is expected" (Source code: "(StrykertJbFjO3MBeWZ3TJ.MutantControl.IsActive(50)?\"\":                \"M\" )") (e3261dda)`

**Expected behavior**
At first, compilation should succeed. I'm not really sure a mutation is required on these statements. We also have the opposite conversion of this one (from Enum to string), and that method is mutated. I would say that for now it would be better if the string mutator leaves case labels alone.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: core 
 - Framework Version: 3.1.100
 - Stryker Version: 0.15.0 (compiled from git)

**Additional context**
There is workaround: change the switch labels to if-statements, or exclude these converter files.

**Comment by Mobrockers** [comment]
Does stryker actually crash with an error or did you just notice a compile error in the logs? Compile errors are not bad per se, we have a process to revert mutations that cause compile errors. If the revert process is failing, please show the part of the log with the crash.

**Comment by erwin-faceit** [comment]
Stryker handles it quite well. Rollback occurs, and the mutation is ignored. Low priority, and perhaps not a problem per se. Just wanting to let you know.

**Comment by Mobrockers** [comment]
Thanks for letting us know! This is by design. At this time we don't have enough context information to know that the string is a case label, and rollbacks are usually quite fast. We have some plans to improve this in the future but creating a higher level of context when placing mutations.

I am curious why you run Stryker compiled from source though.

**Comment by erwin-faceit** [comment]
I’m running this from source because I needed a patch to include files from outside the project directory using included files. I’ve created a (rather ugly) patch which worked for our project. I saw an open issue with he same requirement, and decided to test stryker in general for now. It’s quite amazing, but we’ll have to wait for official support for included files to include stryker in our CI/CD pipeline.
