### ISSUE TITLE
Linq FirstOrDefault()? to First()? -  Stryker.NET - 0.15 - unit test fails to kill it.

### ISSUE THREAD

**Issue by raviraj1976** [stryker-mutator/stryker-net#911]
**Describe the bug**
Linq FirstOrDefault() with ternary operator is replaced to First()? by  Stryker.NET  - 0.15 and suvives mutation. The assertion on unit test is Assert.Null(actual) and unit test is passing when the result is null (result.FirstOrDefault()?.Group return null).  Stryker.NET mutates it with result.First()?.Group and survives mutation, unit test fails to kill it, resulting a Mutation score of 0.00.  What's the best way to address this issue to kill the mutant?

![image](https://user-images.githubusercontent.com/17966882/73613763-cdfd6b80-45c6-11ea-8ea8-569b0645997e.png)

**Logs**

[Survived] Linq method mutation (FirstOrDefault() to First()) on line 91: 'result.FirstOrDefault()?.Group' ==> 'result.First()?.Group'

![image](https://user-images.githubusercontent.com/17966882/73613838-8cb98b80-45c7-11ea-9269-8b9c1bb19935.png)

**Expected behavior**
Mutation score of 100% and unit test must kill it.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Type of project - Infrastructure
 - Framework Version [e.g. core 2.2] - .NET Framework 4.7.2
 - Stryker Version [e.g. beta 0.10.0] - Stryker.NET - 0.15

**Additional context**

**Comment by raviraj1976** [comment]
Unit tests survived mutants eve though I have written 2 new unit tests 

![image](https://user-images.githubusercontent.com/17966882/73672439-ddd68780-467a-11ea-9c8b-9dbd2c20bfda.png)

Scenario 1
------------------------------------- -----------------------------------------------------
When  result is empty collection,  result.FirstOrDefault()?.Group returns null and assertions around Null.

Assert.Null(actual);

Scenario 2
------------------------------------------------------------------------------------------
When  result is null,  result.FirstOrDefault()?.Group throws ArgumentNullException

await Assert.ThrowsAsync<ArgumentNullException>(async () => await query.ExecuteAsync().ConfigureAwait(false));

**Mutants survive**

![image](https://user-images.githubusercontent.com/17966882/73672576-242be680-467b-11ea-8432-061a93f7c6d8.png)

**Comment by dupdob** [comment]
Can you share some code please ?
As I understand your issue, there is no issue with Stryker, but you are unable to kill this mutant.
As a general rule, when you have a difficult time to kill a mutant, the first thing you need to do is manually inject the mutant and devise a failing test for it (without using Stryker).
When you find one, you can revert the code to its original version and run Stryker again.

Regarding this specific mutant, it looks like you have to have a test where result turns out to be an empty collection, then _First_ will throw an exception.

**Comment by raviraj1976** [comment]
As you said I have manually injected the mutant  replacing result.FirstOrDefault()?.Group with  the mutant  result.First()?.Group and the test case is failing with an exception			
System.InvalidOperationException : Sequence contains no elements when result is null .

*Injected Mutant*

![image](https://user-images.githubusercontent.com/17966882/73754561-8eec2900-4732-11ea-88ee-4fa6051bcf6c.png)

* Failing test case*

![image](https://user-images.githubusercontent.com/17966882/73754872-15a10600-4733-11ea-94de-de144dc6e586.png)

*since I found the failed unit tests, revert the code to its original version to use result.FirstOrDefault()?.Group and run Stryker again. In this test where result turns out to be an empty collection, then First expected to throw an exception*

*revert the code to its original version*
![image](https://user-images.githubusercontent.com/17966882/73754944-3e290000-4733-11ea-912e-ed06dff3f9a6.png)

*mutant survived when run Stryker again resulting mutant scope of 0.00% *

![image](https://user-images.githubusercontent.com/17966882/73756126-163a9c00-4735-11ea-86ad-d4d15dae5346.png)

![image](https://user-images.githubusercontent.com/17966882/73756256-4124f000-4735-11ea-9bec-beaa4426911a.png)

I will attach an example shortly.

**Comment by dupdob** [comment]
Thanks for your detailed feed back. It may be an issue related to coverage analysis.
Can you try turning it off ? (see https://github.com/stryker-mutator/stryker-net/blob/master/docs/Configuration.md#coverage-analysis) and check the results.

I suspect the cause of this problem be somehow linked to async/await and coverage analysis.

**Comment by raviraj1976** [comment]
“Bingo!. work like a charm post setting "coverage-analysis": "off" in stryker-config.json.

Thank you for the suggestions. 

![image](https://user-images.githubusercontent.com/17966882/73848303-dd163080-47f5-11ea-89ac-c3f66ec08672.png)

**Comment by raviraj1976** [comment]
When I added the 3 unit tests class, the existing one shown above GetCommodityGroupNameByFreightCommodityQueryAsync.cs which killed the mutants survived.

![image](https://user-images.githubusercontent.com/17966882/73854247-31bea900-4800-11ea-905a-efcf0622746b.png)

**Comment by raviraj1976** [comment]
tried one more scenario by adding a ternary operator ? on result before calling FirstOrDefault i.e  result?.FirstOrDefault(). The unit test assert on null check is passing. But mutant survived. 

*ternary operator ? on result before calling FirstOrDefault*

![image](https://user-images.githubusercontent.com/17966882/73863808-a00a6800-480e-11ea-9773-77e1869b4744.png)

*Mutants survived*
![image](https://user-images.githubusercontent.com/17966882/73864185-350d6100-480f-11ea-8b8d-fff89c005111.png)

Am I doing something wrong here?

**Comment by Mobrockers** [comment]
Sorry for not replying, I had not noticed there was a new question.

Is this latest problem with coverage analysis still turned on or off?

**Comment by Mobrockers** [comment]
Please reply when you see this and I'll reopen the question.
