### ISSUE TITLE
Failed to retrieve coverage info when using internal classes

### ISSUE THREAD

**Issue by thijslimmen** [stryker-mutator/stryker-net#912]
I am getting the following error when running Stryker:

`Runner 1: Failed to retrieve coverage info for WhenInternalVisibleClassGetHello_ShouldReturnHello.`

Reproduction:

Create a project with a single class:

csproj name: **Project**

Add the following snippet to make internal classes visible to the unit test project

```
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>$(AssemblyName).Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
```

class: **TestingInternalVisible.cs**

```
internal class TestingInternalVisible
{
   public string GetHello(){
       return "Hello";
   }
}
```

Create a test project:

csproj name: **Project.Tests**

class: **TestingInternalVisibleTests.cs**: 
```
[TestClass]
public class TestingInternalVisibleTests
{
   [TestMethod]
   public string WhenInternalVisibleClassGetHello_ShouldReturnHello(){
       var sut = new TestingInternalVisible();
       
       var result = sut.GetHello();
      Assert.AreEqual("Hello", result);
   }
}
```

I would expect it to be able to kill all mutants, because I made all internals visible.

When making the class public it is able to kill all mutants.

**Comment by dupdob** [comment]
Could you please try using the _InternalsVisibleTo_ attribute at the source code level instead of the csproj file? as in:
```csharp
[assembly: InternalsVisibleTo("project.Tests")]
```
It should fix your problem. Stryker can not use the csproj to build the mutated project.
Can you please confirm it fixes your issue?

**Comment by thijslimmen** [comment]
This fixed my issue. Thank you very much :)

**Comment by Mobrockers** [comment]
This issue will be picked up in #917 so I'll close this issue
