### ISSUE TITLE
Pipeline execution fails repeatedly "System.InvalidOperationException: Could not find build environment"

### ISSUE THREAD

**Issue by edwardpmarin** [stryker-mutator/stryker-net#915]
**Describe the bug**
Repeatedly, an error occurs when running the mutation tests on the jenkins pipeline. 
The temporary solution is to re-execute the pipeline, because the cause of the error could not be identified
The error displayed on the console is as follows:

**Logs**
`Restore was successful.
/opt/dotnet-sdk-3.0.100-linux-x64/dotnet dotnet-stryker -cp ../stryker-config.json -tb 99 --project-file=Project.Application.csproj

   _____ _              _               _   _ ______ _______ 
  / ____| |            | |             | \ | |  ____|__   __|
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |   
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |   
  ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |   
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|   
                   __/ |                                   
                  |___/                                    

Version: 0.15.0 (beta)

[16:59:53 INF] The project /var/lib/jenkins/workspace/_chore_set-mutaiton-score_MM-723/Project.Application/Project.Application.csproj will be mutated
[16:59:54 ERR] An error occurred during the mutation test run 
System.InvalidOperationException: Could not find build environment
   at Buildalyzer.Environment.EnvironmentFactory.GetBuildEnvironment(String targetFramework, EnvironmentOptions options)
   at Buildalyzer.Environment.EnvironmentFactory.GetBuildEnvironment(String targetFramework)
   at Buildalyzer.ProjectAnalyzer.Build(String targetFramework)
   at Buildalyzer.ProjectAnalyzer.Build()
   at Stryker.Core.Initialisation.ProjectFileReader.AnalyzeProject(String projectFilePath, String solutionFilePath)
   at Stryker.Core.Initialisation.InputFileResolver.ResolveInput(StrykerOptions options)
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(StrykerOptions options)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages)
[16:59:54 INF] Time Elapsed 00:00:05.1448309
[Pipeline] sh
++ cd Project.Application.UnitTest
++ pwd
+ find /var/lib/jenkins/workspace/_chore_set-mutaiton-score_MM-723/Project.Application.UnitTest -type f -name mutation-report.html -exec dirname '{}' ';'
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] stage
[Pipeline] { (Notify)
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: https://channel-test.slack.com/services/hooks/jenkins-ci/, teamDomain: <empty>, channel: #media-management-alerts, color: danger, botUser: false, tokenCredentialId: SlackToken, notifyCommitters: false, iconEmoji: <empty>, username: test@test.com
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean Up)
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
ERROR: script returned exit code 1
Finished: FAILURE`

**Expected behavior**
The error is expected to be clearer for analysis. Additionally, it is a mistake that should not be presented sporadically as it happens at this time,

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project [framework, core, xamarin]
 - Framework Version [dotnet-sdk-3.0.100-linux-x64]
 - Stryker Version [0.15.0]

**Additional context**

**Comment by Mobrockers** [comment]
This looks like an error in a dependency we use called buildalyzer. We have not experienced this before so I do not know what went wrong. We'll look into it!

**Comment by Mobrockers** [comment]
Hey! We have not been able to find a cause for this problem, other than buildalyzer not being able to detect msbuild or dotnet core on your system. Are you always using the same jenkins slaves for these runs or could there be differences in the build environments?
