### ISSUE TITLE
Cannot convert from 'System.Exception' to 'System.Runtime.Serialization.StreamingContext'

### ISSUE THREAD

**Issue by matneyx** [stryker-mutator/stryker-net#916]
**Describe the bug**
I get the following compile error when I try to run Stryker for the first time:
Cannot convert from 'System.Exception' to 'System.Runtime.Serialization.StreamingContext'

**Logs**
For us to best assist you in diagnosing the problem we would ask you to run stryker with the option `--log-file` and to attach the resulting logs to the issue.

**Expected behavior**
I expect Stryker to run...

**Desktop (please complete the following information):**
 - OS: Win 10
 - Type of project: Core
 - Framework Version: Core 3.1
 - Stryker Version:  0.15.0 (beta)

**Comment by matneyx** [comment]
[log-20200204.txt](https://github.com/stryker-mutator/stryker-net/files/4156755/log-20200204.txt)

(Sorry, I had to restart before I could grab that...)

**Comment by dupdob** [comment]
Thanks for providing us the log. Is there any chance we could have access to the full project?
I recovered the mutated source file that is at the cause of this problem, but It seems that it should compile without any errors. I will attempt to compile it in isolation and see if any issue appears, but having access to your project would ease this task.

**Comment by dupdob** [comment]
I opened PR #930 that should fix this.
