### ISSUE TITLE
Stryker falls back to safe mode for this method

### ISSUE THREAD

**Issue by wischi-chr** [stryker-mutator/stryker-net#933]
**Describe the bug**
While running stryker the following warning was printed to the console, asking me to report this issue
```
[13:21:55 WRN] Stryker.NET encountered an compile error in D:\xxxx\VarUInt64.cs (at 56:22) with message: Verwendung der nicht zugewiesenen lokalen Variablen "b". (Source code: b)
[13:21:55 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
```

**Exception message in English: "Use of unassigned local variable"**

Luckily this class does not have any external dependencies, so my guess is that it should be reproducable.

Here is the code:

```csharp
using System.Diagnostics.CodeAnalysis;
using System.IO;

namespace XXXXX
{
	public static class VarUInt64
	{
		private const byte Msb0 = 0b0111_1111;
		private const byte Msb1 = 0b1000_0000;

		[SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "No null check for performance reasons")]
		public static int Write(Stream stream, ulong value)
		{
			ulong next;
			var cnt = 1;

			while ((next = value >> 7) != 0)
			{
				stream.WriteByte((byte)((value & Msb0) | Msb1));
				value = next;
				cnt++;
			}

			stream.WriteByte((byte)value);
			return cnt;
		}

		[SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "No null check for performance reasons")]
		public static int Read(Stream stream, out ulong value)
		{
			ulong b, result = 0;
			var shift = 0;
			var cnt = 0;

			while (true)
			{
				var x = stream.ReadByte();
				cnt++;

				if (x < 0)
				{
					throw new EndOfStreamException();
				}

				if (((b = (ulong)x) & Msb1) == 0)
				{
					break;
				}

				result |= (b & Msb0) << shift;
				shift += 7;
			}

			value = result | ((b & Msb0) << shift);

			return cnt;
		}
	}
}

```

**Expected behavior**
stryker cli asked my to report it, but I guess the expected behaviour would be that stryker is able to mutate the Read method without entering safe mode.

**Desktop:**
 - OS: Windows
 - Type of project: core3 / xunit tests
 - Framework Version: .net core 3.1
 - Stryker Version: 0.16.0 (beta)

**Comment by wischi-chr** [comment]
Looks like `ulong b, result = 0;` is causing the issue.
I tried to assign b on a separate line

```csharp
ulong b = 0;
ulong result = 0;
```

and stryker no longer reports that warning

**Comment by Mobrockers** [comment]
Thanks for reporting this issue!

**Comment by richardwerkman** [comment]
I've reduced this to a minimal reproduction scenario

It looks like this:

``` cs
ulong b;

while (true)
{
    if (1 == 1 ? (b = 1) == 3 : (b = 1) != 3)
    {
         break;
    }
}

var bla = b;
```

The while true is mutated to 

``` cs
while ((MutantControl.IsActive(21) ? false : true))
```

So the compiler sees a posibility that the code never enters the while loop. Thus `ulong b;` can be unassigned after the while loop.

After the while loop the variable b is used, which causes the message `Use of unassigned local variable 'b'`

I'm not sure yet how to tackle this...

**Comment by dupdob** [comment]
Thé fix in my PR should take care of that, by rollback if the mutation. 
Ultimately, this is ugly code and it could be ok not to support it

Envoyé de mon iPhone

**Comment by richardwerkman** [comment]
What fix are you talking about?

Yeah I agree on the ugly code part but it's still not nice of Stryker to crash on it

**Comment by wischi-chr** [comment]
> Ultimately, this is ugly code and it could be ok not to support it

Ok that would be a bit of a stretch IMHO unless it's very well defined what you mean by "ugly code". It's obviously "clear enough" that a compiler can process it ^^

IMO if the code compiles and stryker crashes while mutating it, it should be considered a bug (even if the code is "ugly")

**Comment by dupdob** [comment]
In PR #936, I added a marking logic for return default (T) so that it is properly rolled back in safe mode.

**Comment by dupdob** [comment]
I see, I failed to read the issue properly. 
Basically, we can’t do much for this: the while(true) is not mutable, period.

Trying to figure out which mutation triggered the use of un allocated error message is close to impossible.
 ⇒ triggering safe mode inevitable. 
One solution could be to have safe mode trying out every single mutation of the method till it removes the faulty one. 
 ⇒ painful, but doable


IMHO, we should avoid mutating `while(true)` altogether: there is a high chance it will end in some tricky error.

**Comment by dupdob** [comment]
My comment on the ugliness of the code was referring to minimal example, not the original code (which I failed to read). so sorry about that.
I  agree, Stryker should not crash, and it does not.
It just fails to manage the cascading effects of the mutation, which is difficult, because `while(true)`allows very specific constructions.

By the way, replacing `while(true)`by `for(;;)`will remove the message.

**Comment by richardwerkman** [comment]
Yeah we have been struggling with `while(true)` for a while now. The return default solution fixes most of it but now this... Maybe it is better to skip `while(true)` as a whole. In this case stryker should check if the body of the while loop is tested, not the expression inside the while. So skipping while true seems plausable.

@Mobrockers what's your opinion on this?

**Comment by dupdob** [comment]
@richardwerkman : sorry for suggesting you to open this can of worms (see #642). Of course, I failed to grasp those consequences then 😄

**Comment by Mobrockers** [comment]
@richardwerkman I think it would be a shame to ignore all while(true) mutations because it does not work in some cases. I would prefer if for example we don't ask users to create a new issue for known structures that we can't properly mutate and that will be rolled back. That would solve this issue because while mutating doesn't work, it doesn't crash stryker. The only reason an issue was created is because we ask the user to create an issue when we rollback the mutation.

**Comment by dupdob** [comment]
IMHO, I think most `while(true)` constructions will result in compilation issues.

Asking user to report safe mode was  there to prevent the persistence of mutation process bugs that would result in triggering safe mode.

**Comment by Mobrockers** [comment]
> IMHO, I think most `while(true)` constructions will result in compilation issues.
> 
> Asking user to report safe mode was there to prevent the persistence of mutation process bugs that would result in triggering safe mode.

I know, but if we acknowledge that some mutations have issues we can stop asking users to report on those specific issues (if it's possible to detect that of course).

**Comment by wischi-chr** [comment]
Is it confirmed, that `while(true)` is the problem (see my [second comment](https://github.com/stryker-mutator/stryker-net/issues/933#issuecomment-583842596))

**Comment by Mobrockers** [comment]
Created feature request #1400 to track implementing a way to ignore these mutations from asking users to report as we cannot prevent this compilation error.
