### ISSUE TITLE
Some mutants' coverage cannot be detected

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#949]
**Describe the bug**
Stryker coverage capture does not reflect actual coverage of some mutants which may lead to some random results for them. Randomness is related to the order of tests.

The problem was discovered when working on PR #936 with **NFluent**.
The tested project contains some lazy static cache initialisation logic. Therefore Stryker only captures the first test that triggers this logic. Further tests rely on the cached value.
Which means this test has be able to kill this mutant, otherwise, this test is flagged as _Survived_.

**Expected behaviour**
Ideally, Stryker should run all impacted tests. A realistic alternative would be that Stryker runs all tests.
As of now, if anyone encounters this issue, the possible workarounds are:

- Disable coverage: not acceptable in the long run, as it severely impacts performance
- Use 'PerTestInIsolation' coverage capture, which is **very slow** (as each test is run in a specific test session).

**Comment by dupdob** [comment]
I think coverage analysis based optimisations will probably be critical feature for most of the Stryker-Mutator.Net users, as they significantly reduce the test run time.

The best solution would be to improve _'PerTestInIsolation'_ performances, but it looks difficult at best.
Then, I think the second best solution is to use some form of source code annotation (comments or attributes) to guide Stryker-Mutator.Net logic.

**Comment by richardwerkman** [comment]
@dupdob do you think we can recognize situations like yours by using static code analysis?

**Comment by dupdob** [comment]
Maybe, I am not familiar with what can actually be achieved through static analysis, but I am pretty sure this would require hard work.
But, and this is an important but, it turns out that this problem comes from the violation of a very important unit testing rules: **tests must be isolated**, as in, the result of one test must not depend on some other tests.
Whenever static caching is involved, you are violating this rule.
For NFluent, I recognised this and ensure that cache were flushed before any tests designed to test them explicitely.
And then, everything works as expected

**Comment by richardwerkman** [comment]
Good point. So I checked the [vstest docs](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019) and found an option for running all tests in isolation. Have you tested with that as well? 

It might be a lot faster than spinning up a new vstest instance for each test.

**Comment by Mobrockers** [comment]
> Good point. So I checked the [vstest docs](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019) and found an option for running all tests in isolation. Have you tested with that as well?
> 
> It might be a lot faster than spinning up a new vstest instance for each test.

I don't think that runs the tests in isolation, it looks like it runs the testhost itself in isolation from the vstest.console so that a crash in the testhost does not crash the vstest.console.
