### ISSUE TITLE
Stryker version update check does not determine latest version correctly

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#968]
**Describe the bug**
```
Version: 0.16.0 (beta)

A new version of Stryker.NET (0.15.0) is available. Please consider upgrading using `dotnet tool update -g dotnet-stryker`

```

**Comment by dupdob** [comment]
I noticed it too. 
I had a look, the hard coded URL is wrong. My understanding of the Nuget API is that two calls are required to get this info, the first one giving the correct url root before asking for the list of versions. 
Manual testing proved it works. 

But only cursory reading of the doc, if it helps
