### ISSUE TITLE
Icons in mutation testing report are displayed as ðŸ™ˆ

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#972]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3595932/76394957-a0020880-6376-11ea-858e-fcfa8a026036.png)

**Comment by richardwerkman** [comment]
I've looked at the source of the html file we spit out and the emojis are correct in the file. Somehow the js messes the emojis up and shows that weird characters in the html.

**Comment by richardwerkman** [comment]
@nicojs @hugo-vrijswijk could one of you look into this for us? We can't figure out why the emoji's are broken for us but work for you.

**Comment by hugo-vrijswijk** [comment]
@richardwerkman can you add an example generated report where this happens?

**Comment by richardwerkman** [comment]
Sure!

[mutation-report.zip](https://github.com/stryker-mutator/stryker-net/files/4358985/mutation-report.zip)

**Comment by hugo-vrijswijk** [comment]
Got it! I noticed it did work in Firefox, just not in chrome. Adding a `meta` tag for the charset to utf-8 fixed it in Chrome as well. See https://github.com/stryker-mutator/stryker4s/blob/master/core/src/main/scala/stryker4s/report/HtmlReporter.scala#L16

Not sure why this is different between 1.3.0 and 1.2.3

**Comment by Mobrockers** [comment]
@hugo-vrijswijk Didn't we switch to a different library for some of the rendering stuff? Perhaps it messes with the default charset or something.

**Comment by Mobrockers** [comment]
@hugo-vrijswijk 👏

**Comment by hugo-vrijswijk** [comment]
We switched to a different code highlighting library, but that shouldn't make a difference for the status blocks.

There was a change from commonjs modules to es2015, that might have caused it 🤔

**Comment by richardwerkman** [comment]
Thanks Hugo! Issue closed :)
