### ISSUE TITLE
Mutation report html line numbers are wrong

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#974]
**Describe the bug**
New:

![image](https://user-images.githubusercontent.com/3595932/76596658-04e86a80-64ff-11ea-9bae-46af2005f43c.png)

Old:

![image](https://user-images.githubusercontent.com/3595932/76596670-0e71d280-64ff-11ea-9df1-0750cc5e45b6.png)

**Comment by richardwerkman** [comment]
Yeah this doens't look good... Do you think the problem is inside the mutationtesting elements or in stryker?

**Comment by Mobrockers** [comment]
It's in stryker, the json itself is wrong which suggests the parent nodes are broken somewhere resulting in wrong line spans.

**Comment by richardwerkman** [comment]
It could be due to #958. But we have unit tests for the line numbers so I wonder why the unit test didn't fail...
