### ISSUE TITLE
Update notification points to older version

### ISSUE THREAD

**Issue by wmeints** [stryker-mutator/stryker-net#981]
**Describe the bug**
When running `dotnet stryker`, you get a notification:

```
A new version of Stryker.NET (0.15.0) is available. Please consider upgrading using `dotnet tool update -g dotnet-stryker
```

While I'm running `Version: 0.16.1 (beta)`. Something's off.

**Expected behavior**
It should not send me an update notification if I'm running the latest version.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: .NET Core
 - Framework Version 3.1.2
 - Stryker Version beta 0.16.1

**Comment by Mobrockers** [comment]
Thank you for the report (you're actually the first to report this issue, after months of it not working correctly..), we have fixed this issue in #969 :) It should be released by the end of the week.
