### ISSUE TITLE
Coverage is reported rather strange in the console

### ISSUE THREAD

**Issue by wmeints** [stryker-mutator/stryker-net#982]
**Describe the bug**
When I run `dotnet stryker` in my terminal it runs fine, but the resulting coverage value is really strange:

```
[06:32:55 ERR] Final mutation score: 4473,6842105263157894736842110 under breaking threshold value 60.
```

It's well above the 60 percent mark, but it really isn't. When I check the HTML report it's 44.73 percent, which is indeed below 60. Something is off in the reporter.

**Expected behavior**
The reporter should report a value between 0 and 100. I guess the current value / 100.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: .NET Core
 - Framework Version: 3.1.2
 - Stryker Version: beta 0.16.1

**Comment by Mobrockers** [comment]
Mhm, the score should be rounded up to two digits as well. Thanks for reporting!
