### ISSUE TITLE
XOr mutators results in several unkillable mutants.

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#998]
**Describe the bug**
Introduction of Xor mutator resulted in having 5 unkillable mutants. 
They are unkillable because they do not alter the behaviour of the program. The only way (I can think of) to get read of them is to redesign this part not to use `|=' construction. 

**Logs**
![Capture d’écran 2020-03-22 à 14 44 22](https://user-images.githubusercontent.com/3131866/77250977-e34c5900-6c4b-11ea-8bdb-090457dbef17.png)

**Expected behavior**
Stryker must not create mutants that result in exactly the same behavior.
`xor` and `or` have very similar behaviour (same 75% of the time) and therefore the mutation often results in unkillable mutants. 
I suggest removing it altogether, or providing a way to disable this combination, while keeping other assignment mutators

**Comment by richardwerkman** [comment]
You are right that they are very hard to kill. Maybe they are too hard to kill to be turned on by default. We could add them to the "complete" level in #987?

I think removing them is unnecessary as they are killable. It's just really hard.

**Comment by dupdob** [comment]
There is now a workaround as one can disable them via Stryker Comments
